### ISSUE TITLE
[Bug] Support for .ss2 files within Foobar2000

### ISSUE THREAD

**Issue by FairyballYT** [vgmstream/vgmstream#1001]
Hi, I'm having trouble playing some of the music files from the Playstation 2 game Katamari Damacy, most of the music files are .bim files which play just fine with Foobar2K and ver. r1667 of the vgmstream component. The two .ss2 files that are also music files from Katamari Damacy aren't recognized by Foobar2K even though the vgmstream component has support for that file type. I'm not sure what's wrong so could someone help me fix this compatability issue?
![Screenshot 2021-10-31 004417](https://user-images.githubusercontent.com/81061935/139569839-fb4a72f8-07ee-4707-b071-ee35017233bd.png)
![Screenshot 2021-10-31 004508](https://user-images.githubusercontent.com/81061935/139569841-878c7248-db5e-4585-b139-5180d722417f.png)

**Comment by NicknineTheEagle** [comment]
We won't be able to do anything unless you post some samples

**Comment by bnnm** [comment]
Fixed (https://vgmstream.org/downloads), but next time upload samples

**Comment by FairyballYT** [comment]
oh woops thanks for the help. What file should I send the next time I encounter an error, Foobar2k log files, a .ss2 music file?

**Comment by FairyballYT** [comment]
Never mind, I realized that I need to send a copy of the music files that won't play properly. Will do that next time.
