### ISSUE TITLE
[Request] The IDOLM@STER: Starlit Season cue sheet

### ISSUE THREAD

**Issue by EclipsedVisions** [vgmstream/vgmstream#1003]
Hello, I was wondering if it was possible to make support for the newest UE4 idolmaster game? Upon inspection the files contain a metadata block in the beginning followed by the .awb AFS2 header and audio stream data immediately after, however extracting the stream or trying to play it back only results in noise. Here's a sample UE4 asset pair, the actual sound data is contained in the .uexp file: https://drive.google.com/file/d/1vQbwurlHGU3TvHIatV_-mTtERmTFjCkA/view?usp=sharing

**Comment by NicknineTheEagle** [comment]
vgmstream already has HCA keys for this game. Make sure you have the latest build: https://vgmstream.org/
Do not extract individual files from awb, open it directly in vgmstream.

**Comment by EclipsedVisions** [comment]
Ohh, sorry, I didn't check which version of vgmstream I have, thank you so much :D
