### ISSUE TITLE
[Bug] some odd "SCHl"-like files playing badly (or not at all)

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1004]
OK, so despite vgmstream supporting most of EA's sound formats, i found two unplayable formats that take advantage of this "SCHl" format. alongside one bnk file that is barely even "playable".

here are the samples.
[madden_nfl_2001[ps1][unplayable_schl_files].7z](https://www.sendspace.com/file/8y77qh)
[fifa_2001[ps1][messy_bnk_file].7z](https://www.sendspace.com/file/mslbbh)

**Comment by modusc896d352** [comment]
correction - these are all PS2 files not PS1.
i'll post up the real PS1 files whenever i can,

**Comment by modusc896d352** [comment]
here are the actual PS1 files.
[fifa_2001[real_ps1_files][fully_playable_bnk_files].7z](https://www.sendspace.com/file/fva3ec)
[madden_nfl_2001[real_ps1_files][fully_playable_bnk_files].7z](https://www.sendspace.com/file/khi33a)
they all play fine compared to the above.

**Comment by bnnm** [comment]
Not seeying anything off in offsets or codec for FIFA2001 PS2. Does it really play correctly in game?

**Comment by modusc896d352** [comment]
i'm not sure. i would need to check if TRAFF.BNK plays OK in that PS2 game myself.

**Comment by modusc896d352** [comment]
i've found another non-functional "SCHl" file.
[med4[triple_play_2002][ps2].7z](https://www.sendspace.com/file/cupw4t)
as the filename says, this is med4.asf, coming from the PS2 version of Triple Play 2002.

i'll check in on the TRAFF.BNK situation whenever possible. TRAFF.BNK on FIFA 2001 PS1 plays rather well but it uses PS1 ADPCM codec which is true for most EA PS1 games.

**Comment by modusc896d352** [comment]
i checked in on FIFA 2001 PS2 just to see if TRAFF.BNK plays correctly in game. it doesn't seem to be (in fact, actually isn't) used anywhere at all as i haven't heard even a single sound from that file. everything else is OK though.

**Comment by bnnm** [comment]
med4 plays here, maybe try latest, renaming to .lasf or updating foobar (also see [here](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#related-issues)).

**Comment by modusc896d352** [comment]
tried all of them, in the end only renaming med4.asf to med4.lasf did the trick.

**Comment by Caesar0007** [comment]
https://drive.google.com/file/d/15MhApngKwngUCoYKTceyYgsHdp5urzUI/view?usp=sharing
unplayable file form PS1 NFSHS

**Comment by Caesar0007** [comment]
> tried all three suggestions, in the end only renaming med4.asf to med4.lasf did the trick.

worked for me

**Comment by modusc896d352** [comment]
issue closed to avoid clutter
