### ISSUE TITLE
[Request] Please, add support for Halo 2's .Sound files

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#1005]
Could you please add support for .Sound audio files from Halo 2 on the Master Chief Colletion?
Halo 2's .sound files look to be a Microsoft game studios' proprietary format.

https://drive.google.com/file/d/1A64ee4QGoKURwZM-GQbEdfZCAGwWfKtx/view

I sincerely thank you!

**Comment by bnnm** [comment]
Unzip this file in the sound dir to make them playable: [txth.zip](https://github.com/vgmstream/vgmstream/files/7490596/txth.zip)


You may need to set "enable unknown exts" in vgmstream's options, or change extension to .vgmstream first

**Comment by Simo311** [comment]
I do really apologize for my lack of knowledge, but i can't figure out how to make it work, how do i change vgmstream options? the only thing i have is a 'test.exe' file and prompt command line interface to perfom the conversion.
thanks a lot!

**Comment by Simo311** [comment]
It now works! 
But only for English localized voices, can you please add support for others languages voices as well, please?

https://drive.google.com/file/d/1HonQgcd4Dc_TTz5sSrzf0TZk4sGwuGmS/view?usp=sharing

Thanks a lot!

**Comment by bnnm** [comment]
For localiced voices try this [txth.zip](https://github.com/vgmstream/vgmstream/files/7490678/txth.zip)

For other dialogs I'll check later.

**Comment by Simo311** [comment]
> For localiced voices try this [txth.zip](https://github.com/vgmstream/vgmstream/files/7490678/txth.zip)
> 
> For other dialogs I'll check later.

Great! it works!
Thanks a lot for your help!
i'll wait further update!

**Comment by Simo311** [comment]
> For localiced voices try this [txth.zip](https://github.com/vgmstream/vgmstream/files/7490678/txth.zip)
> 
> For other dialogs I'll check later.

Any news?

**Comment by bnnm** [comment]
None yet

**Comment by Simo311** [comment]
:(

**Comment by Simo311** [comment]
> None yet

So this ends here? :(

**Comment by bnnm** [comment]
Nothing to report yet.

**Comment by AlexisJonsson** [comment]
@bnnm This works great except for .sound files that contain several sounds and tracks. Any idea how to go about separating the output of files like that?

The vast majority of sounds in Halo have several permutations and tracks to them so it's preventing a lot to get extracted. Here's the file in question I'm having issues with:
[loop.zip](https://github.com/user-attachments/files/16618992/loop.zip)

Thanks!
