### ISSUE TITLE
[Bug] Bad audio quality issue

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#1007]
Whenever i convert this .sps audio files from Battlefield 4, the audio quality seems to be very nasty. 

Can you please improve the audio quality of the following audio format please?

https://drive.google.com/file/d/1PR1DAxmkpM8sbEdgl9RUqce8uWmv2rI5/view?usp=sharing

Thanks a ton!

**Comment by NicknineTheEagle** [comment]
The audio sounds bad because it's a low bitrate (20 kbps) Speex. vgmstream is not a magic "enhance" button, it cannot create quality that's not there.
