### ISSUE TITLE
Add PRG Maker MV Encrypted RIFF WAVE-like header

### ISSUE THREAD

**Issue by termorizadr3d** [vgmstream/vgmstream#1011]
so i was looking at the OMORI rip and i found that some files were unplayable, opened on HxD and found some RIFF WAVE familiar tags (like data tag or the list tag) 
i think its just a standard wav file but the chunk size is encrypted via the rpgmvo format which is similar to rpgmvo vorbis

most of these files don´t have sample loops (according to this rip, it might be different on another RPG MV game rip)

samples
https://drive.google.com/drive/folders/1uOTjUWkzDNNzoCuIpyFTP0e5FjJglp_5?usp=sharing

also sorry for issuing on a newer account (I don´t have github) and my bad english

**Comment by bnnm** [comment]
Added, see: https://vgmstream.org/downloads
