### ISSUE TITLE
[Request] Shin Megami Tensei V ADX support

### ISSUE THREAD

**Issue by The-Gaben** [vgmstream/vgmstream#1016]
I've managed to extract the files of Shin Megami Tensei V, however all the ADX files i've seen in Stream_en seem to be encrypted with type 9 encryption. 

Here's all the sample ADX files from one AWB bank if it helps. 
https://mega.nz/file/3UsCEZLT#s-KmKPIUhB2RGFEJZRRikv7r691y9pv1ZPkQwaqPTcQ

**Comment by kode54** [comment]
The file keys are in the bank, don't extract them from it.

**Comment by The-Gaben** [comment]
> 
> 
> The file keys are in the bank, don't extract them from it.

If that's the case, how do I decrypt it? Cause it sounds distorted when I import it into foobar

**Comment by bnnm** [comment]
Post the original .awb (or some .acb) and the main executable.

**Comment by The-Gaben** [comment]
Dunno if this is any good, but here's the AWB I extracted from aswell as all the stuff within the exefs.
https://mega.nz/file/mNtyXQTT#r5ZONh3KI5ENPSMcmml2anqJN19NBQ3JjsPUxi_x1S8

**Comment by bnnm** [comment]
Added: https://vgmstream.org/downloads
