### ISSUE TITLE
[Request] WiiU xws files (Ninja Gaiden 3: Razor's Edge [Wii U])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1020]
OK, turns out that this "xws" format was also used in at least one Koei Tecmo wiiU game.
i'm talking about the WiiU version of **Ninja Gaiden 3: Razor's Edge**. despite vgmstream code supporting the format, these things are all but playable.

here are the samples.
[ninja_gaiden_3_razors_edge_wiiu_xws](https://1drv.ms/u/s!Asofkpy7aqyKxU_OhQ4mlSHl9DG5?e=G4zhib)
i had to include a few of them because i'm kinda running out of space on my onedrive account and had to delete a couple of files to make space for them.

**Comment by bnnm** [comment]
Fixed.

**Comment by modusc896d352** [comment]
thanks.
