### ISSUE TITLE
[Bug] some DSP sounds are garbled (We Dare [Wii])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1023]
hey.

so, i did a pull request that highlighted an Wii game called **We Dare** made by Ubisoft that used their precious BAO engine. becaused i tried to play some sounds from that game. then i was in a "bug testing" mood and played like more than half the pk files (i tried to play all of them until foobar2000 crashed on me) through vgmstream to see which subsong is glitchy and which one plays "correctly". there were a surprisingly amount of the former, actually. ogg vorbis subsongs play fine, some DSP ADPCM subsongs play fine while others don't.

here are the samples.
[we_dare_wii_bao_files.7z](https://1drv.ms/u/s!Asofkpy7aqyKxVM3vV2VR-GUE4cB?e=nK26dQ)

and there's the PS3 version of that same game where it uses the same BAO engine, only vgmstream can't play the PS3 files. i can post them here if requested.

**Comment by bnnm** [comment]
Checked some files and seems to play ok, you'll need to be more specific.

**Comment by modusc896d352** [comment]
OK. i'll try to describe exactly which sounds are troublesome. starting with...
0x0010B03F.pk, subsong 13 (package/n-mem/01-0000148a/00001486)
0x0010B1A9.pk, subsong 26 (package/n-mem/01-00000c0f/00000c0e)
0x0017B211.pk, subsong 19 (package/n-mem/01-00000c0f/00000c0e)

**Comment by bnnm** [comment]
Fixed

**Comment by modusc896d352** [comment]
thanks.
