### ISSUE TITLE
[Bug] EA .mpf/.mus files don't play correctly

### ISSUE THREAD

**Issue by AstroSnail** [vgmstream/vgmstream#1024]
Using latest commit, f45715da.

I found .mpf and .mus files in my copy of Shox (SLES 511.44), and i tried to play them with vgstream123.

When I try to play the .mpf files, I only hear a small (0.89 to 7.55 seconds) part of the music.
When I try to play the .mus files, they play for a seemingly appropriate amount of time (4-6 minutes) but in complete silence, or don't play at all.

They play correctly on console, where the intended effect is for the music to adapt to the game state.

Some of the music: [music.zip](https://github.com/vgmstream/vgmstream/files/7621585/music.zip)

**Comment by NicknineTheEagle** [comment]
The music in MPF/MUS is split into segments by game developer because that's how dynamic music system works. MPF file is parsed correctly. Do not open MUS file.
The reason you're only hearing the first segment is because vgmstream123 only plays the first subsong by default.
You're also not using the latest version as the hack where EA SCHl bigfiles were combined into single audio was removed several weeks ago.

**Comment by AstroSnail** [comment]
>  You're also not using the latest version as the hack where EA SCHl bigfiles were combined into single audio was removed several weeks ago.

I don't understand what you mean, but I did find the commit where the SCHl merge hack was removed 27cf174.
For curiosity, I checked their behaviors.

When I build commit 27cf174, vgmstream123 behaves as I described earlier:
Playing .mpf files results in a too short audio. I understand that this is just the first segment of the music.
Playing .mus files results in either:
- If it's SCHl, silence.
- If it's BNK, fails.

When I build a commit before that one, then playing a .mus file either:
- If it's SCHl, produces the full music, but jumbled. I assume this is the hack at work.
- If it's BNK, produces some music, but less than playing the .mpf file.

That's all for curiosity.

I had a look at [TXTP](https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md), and it's exactly what I'm looking for, thank you!

I'll see if I can use Audacious. (I haven't yet because of a packaging bug in my distro)

**Comment by NicknineTheEagle** [comment]
> Playing .mpf files results in a too short audio. I understand that this is just the first segment of the music.

It's not "too short", it's playing the first subsong returned by the parser.
For .mus, it could be that ffmpeg parser is hackily opening the file if it's MP2. Regardless, this is not the intended behavior.

**Comment by bnnm** [comment]
I've updated vgmstream123 to show current/total subsongs if the format has them, so it's clearer you are only playing first one.

Also you can now use `-s 1 -S 10` to play songs 1 to 10 (or such) one after other.

But yeah you probably want TXTP to fine tune playable [subsongs ranges](https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md#play-segmented-subsong-ranges-as-one).

**Comment by AstroSnail** [comment]
I have discovered that the `.mpf` files contain the correct order of the subsongs.

![top: a txtp file with segments manually written in order; bottom: a hexdump of the mpf file](https://user-images.githubusercontent.com/15970994/218430700-d3b4b515-9dd2-457b-b89f-e88a52207c43.png)

See: At the top is a TXTP file i manually created with the correct subsong order. At the bottom is a hexdump of the corresponding `.mpf` file. Starting at file offset 0xec (it's not always 0xec, only for this file. i don't understand the format yet) and after every 0x10 bytes, there is the segment index that should be played.

Is it possible to configure vgmstream to read the segment order from the `.mpf` file? (i have not found such a feature in the docs for TXTH)

**Comment by NicknineTheEagle** [comment]
mpf format is much more convoluted than that, it's a dynamic music container that can and does define multiple branches and transitions for its nodes. There's no single "right" order that can be read by vgmstream.

**Comment by AstroSnail** [comment]
I see. Then i change my question: Is it possible to program/configure vgmstream to understand these branches and transitions, and then let me pick what branches and transitions to take, instead of writing the order for each and every segment?
