### ISSUE TITLE
NFS MOST WANTED 2012 (GAMEPLAY.BNDL)

### ISSUE THREAD

**Issue by srzstark** [vgmstream/vgmstream#1027]
Hi everyone, I have a small project to modify a file for Xbox 360... For that I need to use a script that is only available for computer, but not available for X360. I need help in the script to be able to extract and join the files again, I'm using plugins (DGlorio Noesis Plugins) for that. Could someone help me with this issue? I'm using the noesis program to modify.

Script:

[unpacker.txt](https://github.com/vgmstream/vgmstream/files/7661016/unpacker.txt)
[packer.txt](https://github.com/vgmstream/vgmstream/files/7661017/packer.txt)

BNDL file (Xbox):

https://www.mediafire.com/file/8q8pk5di328gcog/GAMEPLAY.BNDL/file

**Comment by NicknineTheEagle** [comment]
vgmstream is a decoder only. It does not encode audio into game formats.

**Comment by srzstark** [comment]
> vgmstream is a decoder only. It does not encode audio into game formats.

I'm using it but can't access the bndl files, even so I'll see other ways to extract, thanks.
