### ISSUE TITLE
[Request] THE IDOLM@STER STARLIT SEASON v1.21 updates

### ISSUE THREAD

**Issue by SNRI-Formula91** [vgmstream/vgmstream#1030]
Since the release of the game, the latest update v1.21 has added 2 new songs (Song024 and 025) which likely need their own HCA keys for proper playback. 

The corresponding CueSheet_SWAV uasset and uexp files for these songs are on my google drive URL:
https://drive.google.com/drive/folders/1tE41svLK9p_PU5-FCNCcDWNImBoFNHQd?usp=sharing

**Comment by bnnm** [comment]
You need to post the updated executable.

**Comment by SNRI-Formula91** [comment]
I am assuming you are referring to the "StarlitSeason-Win64-Shipping.exe" file. I went ahead and uploaded it to the google drive.

**Comment by bnnm** [comment]
Added.

**Comment by Kredacriz** [comment]
I'm sorry I'm bumping old thread, but could you please update keys for more dlc songs? All files in drive as in OP's share. 
https://drive.google.com/drive/folders/1Gw_gTJW1iTGLFsftyDPiYm9RQW0LxhlX

**Comment by bnnm** [comment]
Added. Interestingly keys are in the base exe too, so much for being DLC.
