### ISSUE TITLE
[Request] ZombiU (WiiU) - (unsupported) son files

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1032]
apparently, there are some sound files used by the ZombiU game that aren't compatible with vgmstream. 
[zombiu_incompatible_son_files.7z](https://www.sendspace.com/file/kwyz6z)
if you look at some of them using an hex editor, there seem to be some kind of signature thing that either says "libfaac 1.28" or "zobi 1.xx" depending on the file. i don't know what to make of the rest of the data after that.

**Comment by bnnm** [comment]
Added.

**Comment by modusc896d352** [comment]
thanks.
