### ISSUE TITLE
Incorrect loop points in Switch HCA?

### ISSUE THREAD

**Issue by Xehanort88** [vgmstream/vgmstream#1034]
So, I'm trying to convert this file into a OGG file while preserving the loop points

[BGM_BATTLE_JOBBOSS_0.zip](https://github.com/vgmstream/vgmstream/files/7697558/BGM_BATTLE_JOBBOSS_0.zip)

however, doesn't matter which format the HCA is converted in, the HCA loop points do not lead to the same result heard during the tune itself in foobar. What am I doing wrong?

**Comment by NicknineTheEagle** [comment]
foobar converter does not copy over loop points. The most you can do is bake in one or multiple loops with fade.

**Comment by Xehanort88** [comment]
I know it doesn't copy them. But the ones visualised appear to be wrong.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 11 Dic 2021, 6:54 PM NicknineTheEagle ***@***.***> ha
scritto:

**Comment by NicknineTheEagle** [comment]
What do you mean by "visualized"?

**Comment by Xehanort88** [comment]
When you look at file info in foobar.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 11 Dic 2021, 7:18 PM NicknineTheEagle ***@***.***> ha
scritto:

**Comment by NicknineTheEagle** [comment]
What file info? How can actually see loop points in OGG produced by converter if foobar doesn't actually copy loop points?

**Comment by Xehanort88** [comment]
I never said that. My problem is whether loop points are displayed
incorrectly in the original HCA, so when trying to look for them in a
converted WAV or OGG for replication the final result is incorrect.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 11 Dic 2021, 7:24 PM NicknineTheEagle ***@***.***> ha
scritto:

**Comment by NicknineTheEagle** [comment]
How do you know they're displayed incorrectly? Note that loop points are displayed in *samples* not time. Time = samples / sample_rate, and, of course, if you resample the sound, it all flies out the window.

**Comment by Xehanort88** [comment]
Normally when resampling the file I rarely have issues with loop points,
with this game I do. Hence the question whether loop points for this HCA
are displayed incorrectly or if there is a specific technique to follow.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 11 Dic 2021, 7:30 PM NicknineTheEagle ***@***.***> ha
scritto:

**Comment by NicknineTheEagle** [comment]
Loop points displayed are the actual points used by vgmstream for looping during playback so if looping sounds correct when the sound played by vgmstream, it's physically impossible for the displayed numbers to be wrong. Are you sure you're interpreting the loop points correctly?

**Comment by Xehanort88** [comment]
I'm fairly certain I am looking for samples in Sound Forge. And they don't
work. So maybe as you said it's a re-sampling issue, but then how could I
work around it?

Il giorno sab 11 dic 2021 alle ore 19:36 NicknineTheEagle <
***@***.***> ha scritto:

**Comment by NicknineTheEagle** [comment]
foobar does not resample sounds by default. Do you have any DSPs active in your converter preset?

**Comment by Xehanort88** [comment]
None that I see, only thing I have active for WAV is "Dither from lossy
sources only".

Il giorno sab 11 dic 2021 alle ore 19:41 NicknineTheEagle <
***@***.***> ha scritto:

**Comment by NicknineTheEagle** [comment]
"Dither from lossy sources only"? That sounds rather suspicious. Then again, you mentioned that you're having problems with OGG, too. I'm out of ideas then. Lining up loop points with converted files should work, I've done that in the past. I also don't get why such an issue would only affect HCA.

**Comment by Xehanort88** [comment]
Would Foobar re-sample when converting?

Il giorno sab 11 dic 2021 alle ore 20:01 NicknineTheEagle <
***@***.***> ha scritto:

**Comment by NicknineTheEagle** [comment]
I literally just stated that foobar does not resample sounds by default.

**Comment by Xehanort88** [comment]
Apologies, and thanks for your help. *Repetita iuvant *after all. Any
suggestions on how to convert or alternative tools?

Il giorno sab 11 dic 2021 alle ore 20:31 NicknineTheEagle <
***@***.***> ha scritto:

**Comment by bnnm** [comment]
It's hard to understand what you want but foobar should make a .wav based on vgmstream's config in options and foobar's plugins. Or you can get vgmstream command line tools [here](https://vgmstream.org/downloads) and drag/drop your file into test.exe and get a plain .wav with default options.
