### ISSUE TITLE
[Request] King Kong (PC Gamer's Edition) Unsupported .wa* format

### ISSUE THREAD

**Issue by icup321** [vgmstream/vgmstream#1035]
The PC Gamer's Edition (which is a port of the X360 version) uses a different sound format from the regular PC version and the X360 version. I checked with MPV and it seems to use some sort of ADPCM format with RIFF WAVE headers, here's a few samples:
[05 Audio Bank.zip](https://github.com/vgmstream/vgmstream/files/7697744/05.Audio.Bank.zip)

**Comment by NicknineTheEagle** [comment]
These are just MS ADPCM with RIFF header, it plays if you rename to .wav.
.waa and .wam extensions could be added to parser although I suspect these files are intended to be opened indirectly via some sound bank format.

**Comment by icup321** [comment]
If what you mean by some sound bank format is what type of Ubisoft audio format this is, it's definitely Jade: https://github.com/vgmstream/vgmstream/blob/master/src/meta/ubi_jade.c

**Comment by NicknineTheEagle** [comment]
Ah, I see now, .waa and .wam are standard Jade extensions. It looks like Jade parser needs MS ADPCM codec added.

**Comment by bnnm** [comment]
Fixed.
