### ISSUE TITLE
[Request] Rabbids Go Home (Windows) - unsupported sns files

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1036]
me again.
though vgmstream does have [some code](https://github.com/vgmstream/vgmstream/blob/master/src/meta/ubi_lyn.c) for supporting those sns files, i came across some more unplayable ones.

here are the samples.
[rabbids_go_home_windows_sns.7z](https://www.sendspace.com/file/0kh0cp)

**Comment by bnnm** [comment]
Fixed.
