### ISSUE TITLE
.ue4opus - Darksiders III

### ISSUE THREAD

**Issue by fignyafsyakaya** [vgmstream/vgmstream#1037]
Something bizarre happens to the .ue4opus files in Darksiders 3.

I extracted them after I used this bms-script on .uexp files:
[ue4opus_standard.txt](https://github.com/vgmstream/vgmstream/files/7722956/ue4opus_standard.txt)
But **vgmstream** persistently refuses to convert them for some reason.

Here are the examples of the .ue4opus files plus the original ones, just in case.
[Darksiders 3 - ue4opus + uasset+uexp.zip](https://github.com/vgmstream/vgmstream/files/7722944/Darksiders.3.-.ue4opus.%2B.uasset%2Buexp.zip)

**Comment by bnnm** [comment]
That .bms only works for simple cases, use umodel instead as it creates proper .ue4opus: https://www.gildor.org/en/projects/umodel#files

(select folder and check "sound" in export types, select files, press export + ok, select Unreal Engine 4.27)

**Comment by fignyafsyakaya** [comment]
Hmm, strange: I actually tried umodel couple of months ago, but it couldn't export anything then.
And now it worked... Maybe I lost some .dlls, I guess I'll never find it out.

Thank you for your time. :)
