### ISSUE TITLE
[Bug] Ape Escape Pumped & Primed (PS2) - unsupported .INT files 

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1040]
As the title says so seeing as there's the INT audio format that vgmstream supports i thought i rip the music from Ape Escape Pumped & Primed 

As for the **unsupported** part vgmstream could not play the .INT files as i said, the music uses compressed .INT format

I have wrote a simple .txth file for the format and the tracks play but there's no looping 

here's one from the game's music files and a txth file to fix.

https://drive.google.com/file/d/1Vp4vMZ28xMnIdB2lnEx1gX2uOaRS4vl2/view?usp=sharing

**Comment by bnnm** [comment]
That game should use [.sts + .int](https://github.com/vgmstream/vgmstream/blob/master/src/meta/exst.c), so you need to find the .sts that do have loop info.

**Comment by Sukotto-1999** [comment]
unfortunately KARI_01B (which is Kakeru's Theme) is the only track that uses .sts and .int (both) how about you make changes to the included txth file so the tracks loop properly

**Comment by bnnm** [comment]
Loop info is in the .sts

**Comment by Sukotto-1999** [comment]
Oh, so they are inside the BIN file in the root of the disc itself.

**Comment by Sukotto-1999** [comment]
Hi @bnnm. I figured out inside the BIN/INF file it does not store loop info inside. So it turns out loop info would be hardcoded in the executable. I will make a rip of this game if those loop points are extracted.

**Comment by Sukotto-1999** [comment]
Hello. I found the loop points in the executable. These loop points are extracted from the US version, I cannot get the loops to work with them. So, @bnnm, here you go. Try to calculate the following offsets of the header itself.

`00 76 BB 00 00 01 00 04 00 30 07 02 7F 00 00 7F 00 10 05 58 00 79 BB 00 00 01 00 0A 00 D8 06 02 7F 00 00 7F 00 20 05 58 00 4E BB 00 00 01 00 50 00 02 07 02 7F 00 00 7F 00 30 05 58 00 66 BB 00 00 01 00 0E 00 66 06 02 7F 00 00 7F 00 40 05 58 00 80 BB 00 00 00 00 00 00 38 01 02 7F 00 00 7F 00 50 05 58 00 80 BB 00 00 00 00 00 00 B8 01 02 7F 00 00 7F 00 60 05 58 00 80 BB 00 00 00 00 00 00 44 01 02 7F 00 00 7F 00 70 05 58 00 80 BB 00 00 00 00 00 00 F0 01 02 7F 00 00 7F 00 80 05 58 00 80 BB 00 00 00 00 00 00 2A 02 02 7F 00 00 7F 00 90 05 58 00 80 BB 00 00 00 00 00 00 92 02 02 7F 00 00 7F 00 A0 05 58 00 80 BB 00 00 00 00 00 00 8C 02 02 7F 00 00 7F 00 B0 05 58 00 80 BB 00 00 00 00 00 00 80 00 02 7F 00 00 7F 00 C0 05 58 00 80 BB 00 00 00 00 00 00 A6 00 02 7F 00 00 7F 00 D0 05 58 00 80 BB 00 00 00 00 00 00 9E 00 02 7F 00 00 7F 00 E0 05 58 00 80 BB 00 00 00 00 00 00 92 00 02 7F 00 00 7F 00 F8 05 58 00 80 BB 00 00 00 00 00 00 66 00 02 7F 00 00 7F 00 10 06 58 00 80 BB 00 00 00 00 00 00 A2 00 02 7F 00 00 7F 00 28 06 58 00 80 BB 00 00 00 00 00 00 7A 00 02 7F 00 00 7F 00 40 06 58 00 80 BB 00 00 00 00 00 00 CE 00 02 7F 00 00 7F 00 58 06 58 00 80 BB 00 00 00 00 00 00 92 00 02 7F 00 00 7F 00 68 06 58 00 80 BB 00 00 00 00 00 00 DE 00 02 7F 00 00 7F 00 78 06 58 00 80 BB 00 00 00 00 00 00 DE 00 02 7F 00 00 7F 00 90 06 58 00 80 BB 00 00 00 00 00 00 DE 00 02 7F 00 00 7F 00 A8 06 58 00 80 BB 00 00 00 00 00 00 6C 00 02 7F 00 00 7F 00 C0 06 58 00 6B BA 00 00 01 00 1A 00 EC 00 02 7F 00 00 7F 00 D8 06 58 00 26 BA 00 00 01 00 1A 00 EC 00 02 7F 00 00 7F 00 F0 06 58 00 53 BB 00 00 01 00 0C 00 5A 07 02 7F 00 00 7F 00 08 07 58 00 60 BB 00 00 01 00 1E 00 34 07 02 7F 00 00 7F 00 18 07 58 00 60 BB 00 00 01 00 06 00 02 07 02 7F 00 00 7F 00 28 07 58 00 6B BB 00 00 01 00 0A 00 0A 06 02 7F 00 00 7F 00 38 07 58 00 47 BB 00 00 01 00 0A 00 62 06 02 7F 00 00 7F 00 48 07 58 00 6D BB 00 00 01 00 28 00 54 07 02 7F 00 00 7F 00 58 07 58 00 78 BB 00 00 01 00 0C 00 52 07 02 7F 00 00 7F 00 68 07 58 00 6A BB 00 00 01 00 04 00 1A 07 02 7F 00 00 7F 00 78 07 58 00 70 BB 00 00 01 00 14 00 40 07 02 7F 00 00 7F 00 88 07 58 00 80 BB 00 00 01 00 00 00 35 08 02 7F 00 00 7F 00 98 07 58 00 0D BA 00 00 01 00 06 00 9A 00 02 7F 00 00 7F 00 A8 07 58 00 38 BB 00 00 01 00 06 00 EC 02 02 7F 00 00 7F 00 B8 07 58 00 7B BB 00 00 01 00 52 00 16 07 02 7F 00 00 7F 00 C8 07 58 00 60 BB 00 00 01 00 5A 02 5A 08 02 7F 00 00 7F 00 D8 07 58 00 C0 5D 00 00 00 00 00 00 10 00 01 7F 00 7F 00 00 10 4A 5B 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 E8 07 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 00 08 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 18 08 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 30 08 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 48 08 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 60 08 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 78 08 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 90 08 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 A8 08 58 00 80 3E 00 00 00 00 00 00 0E 00 01 7F 00 7F 00 00 C0 08 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 D8 08 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 F0 08 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 08 09 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 20 09 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 38 09 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 50 09 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 68 09 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 80 09 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 98 09 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 B0 09 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 C8 09 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 E0 09 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 F8 09 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 10 0A 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 28 0A 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 40 0A 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 58 0A 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 70 0A 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 88 0A 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 A0 0A 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 B8 0A 58 00 80 3E 00 00 00 00 00 00 0F 00 01 7F 00 7F 00 00 D0 0A 58 00 80 3E 00 00 00 00 00 00 13 00 01 7F 00 7F 00 00 E8 0A 58 00 80 3E 00 00 00 00 00 00 0E 00 01 7F 00 7F 00 00 00 0B 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 18 0B 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 30 0B 58 00 80 3E 00 00 00 00 00 00 0E 00 01 7F 00 7F 00 00 48 0B 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 60 0B 58 00 80 3E 00 00 00 00 00 00 0C 00 01 7F 00 7F 00 00 78 0B 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 90 0B 58 00 80 3E 00 00 00 00 00 00 0D 00 01 7F 00 7F 00 00 A8 0B 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 C0 0B 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 D8 0B 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 F0 0B 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 08 0C 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 20 0C 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 38 0C 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 50 0C 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 68 0C 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 80 0C 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 98 0C 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 B0 0C 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 C8 0C 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 E0 0C 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 F8 0C 58 00 80 3E 00 00 00 00 00 00 0E 00 01 7F 00 7F 00 00 10 0D 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 28 0D 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 40 0D 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 58 0D 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 70 0D 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 88 0D 58 00 80 3E 00 00 00 00 00 00 0C 00 01 7F 00 7F 00 00 A0 0D 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 B8 0D 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 D0 0D 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 E8 0D 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 00 0E 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 18 0E 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 30 0E 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 48 0E 58 00 80 3E 00 00 00 00 00 00 0C 00 01 7F 00 7F 00 00 60 0E 58 00 80 3E 00 00 00 00 00 00 10 00 01 7F 00 7F 00 00 78 0E 58 00 80 3E 00 00 00 00 00 00 12 00 01 7F 00 7F 00 00 90 0E 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 A8 0E 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 C0 0E 58 00 80 3E 00 00 00 00 00 00 11 00 01 7F 00 7F 00 00 D8 0E 58 00 80 3E 00 00 00 00 00 00 11 00 01 7F 00 7F 00 00 F0 0E 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 08 0F 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 20 0F 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 38 0F 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 50 0F 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 68 0F 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 80 0F 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 98 0F 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 B0 0F 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 C8 0F 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 E0 0F 58 00 80 3E 00 00 00 00 00 00 17 00 01 7F 00 7F 00 00 F8 0F 58 00 80 3E 00 00 00 00 00 00 16 00 01 7F 00 7F 00 00 10 10 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 28 10 58 00 80 3E 00 00 00 00 00 00 18 00 01 7F 00 7F 00 00 40 10 58 00 80 3E 00 00 00 00 00 00 14 00 01 7F 00 7F 00 00 58 10 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 70 10 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 88 10 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 A0 10 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 B8 10 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 D0 10 58 00 80 3E 00 00 00 00 00 00 0C 00 01 7F 00 7F 00 00 E8 10 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 00 11 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 18 11 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 30 11 58 00 80 3E 00 00 00 00 00 00 0C 00 01 7F 00 7F 00 00 48 11 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 60 11 58 00 80 3E 00 00 00 00 00 00 13 00 01 7F 00 7F 00 00 78 11 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 90 11 58 00 80 3E 00 00 00 00 00 00 14 00 01 7F 00 7F 00 00 A8 11 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 C0 11 58 00 80 3E 00 00 00 00 00 00 0B 00 01 7F 00 7F 00 00 D8 11 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 F0 11 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 08 12 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 20 12 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 38 12 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 50 12 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 68 12 58 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 80 12 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 98 12 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 B8 12 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 D0 12 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 E8 12 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 08 13 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 28 13 58 00 80 3E 00 00 00 00 00 00 0E 00 01 7F 00 7F 00 00 48 13 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 60 13 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 78 13 58 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 90 13 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 A8 13 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 C0 13 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 D8 13 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 F0 13 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 08 14 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 20 14 58 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 38 14 58 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 50 14 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 68 14 58 00 80 3E 00 00 00 00 00 00 0A 00 01 7F 00 7F 00 00 80 14 58 00 80 3E 00 00 00 00 00 00 07 00 01 7F 00 7F 00 00 98 14 58 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 B0 14 58 00 59 BB 00 00 01 00 36 01 68 07 02 7F 00 00 7F 00 20 4A 5B 00 7D BB 00 00 01 00 1E 00 8E 07 02 7F 00 00 7F 00 28 4A 5B 00 61 BB 00 00 01 00 0A 00 74 06 02 7F 00 00 7F 00 30 4A 5B 00 7D BB 00 00 01 00 0A 00 DA 06 02 7F 00 00 7F 00 38 4A 5B 00 62 BB 00 00 01 00 0C 00 5A 07 02 7F 00 00 7F 00 40 4A 5B 00 7A BB 00 00 01 00 EA 00 38 07 02 7F 00 00 7F 00 48 4A 5B 00 56 BB 00 00 01 00 1E 00 26 07 02 7F 00 00 7F 00 50 4A 5B 00 5D BB 00 00 01 00 0A 00 5C 07 02 7F 00 00 7F 00 58 4A 5B 00 5B BB 00 00 01 00 0E 00 3C 06 02 7F 00 00 7F 00 60 4A 5B 00 57 BB 00 00 01 00 34 00 98 07 02 7F 00 00 7F 00 68 4A 5B 00 7B BB 00 00 01 00 88 00 EE 07 02 7F 00 00 7F 00 70 4A 5B 00 47 BB 00 00 01 00 12 00 26 01 02 7F 00 00 7F 00 78 4A 5B 00 6F BB 00 00 01 00 1A 00 42 02 02 7F 00 00 7F 00 80 4A 5B 00 35 AC 00 00 01 00 24 00 22 01 02 7F 00 00 7F 00 88 4A 5B 00 80 3E 00 00 00 00 00 00 02 00 01 7F 00 7F 00 00 90 4A 5B 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 98 4A 5B 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 A0 4A 5B 00 80 3E 00 00 00 00 00 00 08 00 01 7F 00 7F 00 00 A8 4A 5B 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 B0 4A 5B 00 80 3E 00 00 00 00 00 00 02 00 01 7F 00 7F 00 00 B8 4A 5B 00 80 3E 00 00 00 00 00 00 05 00 01 7F 00 7F 00 00 C0 4A 5B 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 C8 4A 5B 00 80 3E 00 00 00 00 00 00 04 00 01 7F 00 7F 00 00 D0 4A 5B 00 80 3E 00 00 00 00 00 00 02 00 01 7F 00 7F 00 00 D8 4A 5B 00 80 3E 00 00 00 00 00 00 06 00 01 7F 00 7F 00 00 E0 4A 5B 00 80 3E 00 00 00 00 00 00 03 00 01 7F 00 7F 00 00 E8 4A 5B 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 F0 4A 5B 00 80 3E 00 00 00 00 00 00 09 00 01 7F 00 7F 00 00 F8 4A 5B 00 00 00 00 00`

**Comment by Sukotto-1999** [comment]
> I think you should use txth with a name table like this example: https://github.com/vgmstream/vgmstream/blob/master/doc/TXTH.md#simple-2000-series-vol-120---the-saigo-no-nihonhei-ps2-xagtxth
> 
> You can tell vgmstream where are the loop points by file, which I would be what the game also does.

Um . . . i think i can't convert the loop points to samples. Are the loop table partially the same as the EXST header data, if not. Try calculating the specification and matching the table to the .INT files.
