### ISSUE TITLE
[Request] Rayman Origins - 3DS and Vita wav files

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1042]
so, i managed to datamine the 3DS and Vita versions of Rayman Origins and took at look at some of the sound files through an hex editor. here's what i managed.

3DS wav files have what's either an "dsph" or "cwav" chunk followed by what is basically an entire bcwav file. their file extension is just ".wav" and nothing else.

Vita wav files are just the usual RIFF AT9 header with the only caveat being that they somehow bear the ".wav.ckd" extension. like every other version of the game except the 3DS one. i can change the extension of all of them to just ".at9" but i'm not going out of my way to do just that. so i'll just leave it as-is.

here are the samples.
[rayman_origins_3ds.7z](https://www.sendspace.com/file/8sv9yl) - "dsph" files
[rayman_origins_3ds_2.7z](https://www.sendspace.com/file/575upj) - "cwav" files
[rayman_origins_vita.7z](https://www.sendspace.com/file/7oo3o9) - usual RIFF AT9 files

**Comment by bnnm** [comment]
Added.
