### ISSUE TITLE
Multiply converting   -o ".ogg" ".wem" doesn't work!

### ISSUE THREAD

**Issue by W1nKille3r** [vgmstream/vgmstream#1043]
I try to use ww2ogg, but new FNAF 9 have other wwise format audio. So many audio haven't convert yet.
Find a this software - but i can't convert all unknown audio files by one batch script. Like.. I have many wem's and convert it all manualy by cmd is extra unnafective & boring.

How what i can do to make it convert by .bat file? Or that impossible?

**Comment by bnnm** [comment]
You can drag-and-drop multiple files into test.exe from the command line tools, to convert `.wem` to `.wav` 

Or in a .bat: `for %%x in (*.*) do test.exe "%%x"`. Or install a music player like foobar2000 and convert from there.
