### ISSUE TITLE
Something I noticed about SGD/SGH files

### ISSUE THREAD

**Issue by Nezogoku** [vgmstream/vgmstream#1047]
The four bytes at offset 0x04 (immediately after "SGXD") seem to point to the name of the file. This was the case for every sgd and sgh file I've looked at thus far (I haven't gotten the opportunity to try this with any sgx files).

I've only tried several files so I don't want to say this is definitive. I just thought it would be good to bring up this trend as one of the comments in the sgxd.c file stated the bytes represented an "unknown header_size".

**Comment by bnnm** [comment]
Thanks, that looks correct, I'll update it later
 .sgx don't have names so it's just the header size (or data offset).
