### ISSUE TITLE
[Request] Minecraft .mus files

### ISSUE THREAD

**Issue by KatieFrogs** [vgmstream/vgmstream#1048]
Minecraft versions before 1.6.1 used .mus files for its music disc audio. There is already [a project that can convert mus to ogg](https://github.com/ata4/muscode) (prebuilt release on that page is broken, needs to be rebuilt), I suggest adding support in vgmstream.

Samples:
[minecraft-streaming.zip](https://github.com/vgmstream/vgmstream/files/7829185/minecraft-streaming.zip)

muscode binary:
[muscode.zip](https://github.com/vgmstream/vgmstream/files/7829186/muscode.zip)

**Comment by NicknineTheEagle** [comment]
Are these encrypted? Data looks like garbage.

**Comment by KatieFrogs** [comment]
muscode calls the files "XOR-encrypted" and the decode function does [this](https://github.com/ata4/muscode/blob/master/src/info/ata4/minecraft/muscode/io/MusInputStream.java#L30-L34) to the files
```java
private byte decode(byte b) {
	b = (byte) (b ^ hash >> 8);
	hash = hash * 498729871 + 85731 * b;
	return b;
}
```

**Comment by bnnm** [comment]
Added.
