### ISSUE TITLE
Fahrenheit - .partitio, language files

### ISSUE THREAD

**Issue by fignyafsyakaya** [vgmstream/vgmstream#1049]
Recently I tried to interact with _.partitio_ audio files in Fahrenheit and got stuck with ones of this kind:
 
[0Fahrenheit - language files.zip](https://github.com/vgmstream/vgmstream/files/7833677/0Fahrenheit.-.language.files.zip)

The best possible result I managed to get with commands below in **.txth**-file still has lots of noises.

**codec = IMA**

**channels = 1**
**sample_rate = 22050**
**start_offset = 0x808**
**num_samples = data_size**

Also, they seem to have some kind of data among audio - maybe lypsinc-kind, I actually don't know yet.

So, I wonder if it's possible to get playable files without noises, whether or not they will have unnecessary data.

**Comment by bnnm** [comment]
Should work with:
```
codec = XBOX
channels = 1

data_size = @0x814
start_offset = 0x820
num_samples = data_size

id_value = 0x50415254 #PART
id_offset = @0x00:BE

base_offset = 0x10 + @0x0c
id_value = 0x53545245 #STREAMAB
id_offset = @0x20:BE

sample_rate = @0x5d
```

**Comment by fignyafsyakaya** [comment]
It works, but only with first segments of audio.

E.g., while using it on **459e.partitio**, I've been changing _start_offset_ to **0x45820**, **0x87820**, **0xCC820**, **0x110820** and **0x150020** - each offset resulted in getting playable corresponding audio data.

And, of course, different partitio-files have different offsets for audio, but I cannot understand the pattern they use.

**Comment by fignyafsyakaya** [comment]
I actually tried my "newbie skills" to find some kind of pattern of getting from one part of audio data to another one. Maybe it won't reveal anything new, but at least it's been worth trying, I think.

**459e.partitio** as example: at 0x808 the file has "52 13 C0 40" entry.
Next place it appears at is 0x45804 - with "52 13 40 41" next to it.
Which in turn appears at 0x87804.
"7E 0E 90 41" from 0x87808 can also be seen at 0xCC804.
"52 13 C0 41" from 0xCC808 - at 0x110804.
"26 18 F0 41" from 0x110808 - at 0x150004.
"93 E7 0B 42" is the final one.

So, the last (here it's "93 E7 0B 42") and the first (here - "52 13 C0 40") series are usually found right under the "STREAMAB" twice in a column - at the moment I haven't met any exceptions.

**Comment by fignyafsyakaya** [comment]
After some exploration I stumbled upon files with some differences.
**4613-4615** don't have _data_size_ value at 0x814 (as well as near other chunks) - just "30 30 30 30".
And **470b** turned out to have 2 channels instead of 1 - I don't know if that's the only case.

[other situations.zip](https://github.com/vgmstream/vgmstream/files/7877424/other.situations.zip)

**Comment by bnnm** [comment]
Channels probably would work with `channels = @0x5c + 1` after sample_rate

I don't see offsets or sizes for other segments so probably the game reads and handles size per segment one after other automatically. Because this engine is very complex (and seemingly depends on other files), I don't think much else can be done. See here too for some more info: https://github.com/vgmstream/vgmstream/issues/483

Maybe once it's fully figured out (outside vgmstream), with all info it's possible to make more complete .txth

Numbers like "52 13 C0 40" are float timestamps btw (0x40C01352 = ~6.0023, 0x41900E7E = ~18.0070 and so on), probably to sync with game scenes.
