### ISSUE TITLE
[Bug]  this file wont work

### ISSUE THREAD

**Issue by MarcelloBlinxyblinx** [vgmstream/vgmstream#1051]
Hi I'm new here. i tried ripping a wad file but didn't work thought(
here's the wad file: https://cdn.discordapp.com/attachments/761195154728026122/929477050463551490/sfx_com.wad)
the file comes from smashing drive prototype for GameCube

**Comment by bnnm** [comment]
That .wad is just a mix of .dsp files, you'd need to find another file that contains offsets and sizes.
