### ISSUE TITLE
[Bug] some adp files from GameCube games don't play.

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1052]
so, i came across two GameCube games (Wave Race Blue Storm, 1080 Silver Storm) where more than a few adp files don't play at all with vgmstream. the rest of the adp files that these games have fare OK in that they do play fine, so to speak.

here are the samples.
[unplayable_adp_files.tar](https://www.sendspace.com/file/3evo2x)

**Comment by bnnm** [comment]
Fixed.
