### ISSUE TITLE
[Request] Support more Heavy Iron .SNDS audio formats

### ISSUE THREAD

**Issue by icup321** [vgmstream/vgmstream#1054]
I've recently been re-ripping the audio files from SpongeBob: Battle for Bikini Bottom, I noticed that vgmstream has a little bit of code for reading Heavy Iron audio formats: https://github.com/vgmstream/vgmstream/blob/master/src/meta/raw_snds.c

However, it only seems to support the PC version of The Incredibles, perhaps this could be expanded upon to support more variations of the SNDS format?

**Comment by NicknineTheEagle** [comment]
SNDS files are raw audio and this is legacy parser that will be eventually removed. Use TXTH.
