### ISSUE TITLE
[Bug, PS3] Sly 2/3 BNK Files: "Unsupported or Corrupted" Subtracks

### ISSUE THREAD

**Issue by Quasi-Detective** [vgmstream/vgmstream#1056]
When I open BNK files containing sound effects from The Sly Collection's remastered versions of Sly 2 and Sly 3, most of the subtracks within load fine, but often about 20 or so output "unsupported format or corrupted file" when using the latest foobar component release (r1702).

Here's a sample BNK file from each game, both for the main menus, which show the issue.
[MEGA](https://mega.nz/file/OOpz0KhB#aprrY5fZzpYEimCf-282O3Hx7uw6B3Pm-6muENpibyA)

**Comment by bnnm** [comment]
Should work now: https://vgmstream.org/downloads
