### ISSUE TITLE
[Error] test.exe won't open

### ISSUE THREAD

**Issue by mamm26** [vgmstream/vgmstream#1057]
---------------------------
test.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
---------------------------
OK   
---------------------------

Windows Server 2019 Standard.

**Comment by NicknineTheEagle** [comment]
Do you have the latest 32-bit Visual C++ Redistributable installed? https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by mamm26** [comment]
I thought I had it installed, I had only installed x64. Fixed.
