### ISSUE TITLE
[Bug] I'm having issues with converting some files

### ISSUE THREAD

**Issue by Orangespark24** [vgmstream/vgmstream#1058]
Ok, i have tried to convert a .wav file using the -o command (it's a file from a Wii game, so i can't just open it up with a media player). Whenever i try to convert it though, it just tells me the file does not exist, even after i put it in the same directory as test.exe! What do i do to get past this? Can anybody help me? I'm rather new in using vgmstream, so yeah if you guys could help me, i would be very glad.

This is one of the files i have tried to open.

https://cdn.discordapp.com/attachments/700031950467104818/934434611927339120/CallMe.wav

**Comment by NicknineTheEagle** [comment]
Post the full command you're entering.

**Comment by bnnm** [comment]
File is not a wav, but a link. Open with notepad or so to see the text.

**Comment by Orangespark24** [comment]
> Post the full command you're entering.

C:\Users\Orangespark24\Downloads\vgmstream-win\text.exe - o CallMe.wav CallMe.wav

**Comment by kode54** [comment]
Also, you can't convert a file over top of itself. The output will overwrite it before it is opened for reading.
