### ISSUE TITLE
[Request] Michael Jackson: The Experience (Xbox 360) - "Dare" "package" sounds (pk, spk)

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1060]
so, about that Michael Jackson game made by Ubisoft...
there was a Xbox 360 version made by one of their subsidiaries that use an entirely different game engine from the other versions (themselves made by other subsidiaries as well) including an in-house sound engine of theirs as well.

anyhow, since none of the files there play with vgmstream i'd thought i'd post this here.
[michael_jackson_the_experience_xbox360_audio.7z](https://krakenfiles.com/view/m3ztuCygnr/file.html)

**Comment by bnnm** [comment]
Added.

**Comment by modusc896d352** [comment]
thanks. for real.
