### ISSUE TITLE
[Bug] Input accepts PSF files, and forwards them to FFmpeg

### ISSUE THREAD

**Issue by kode54** [vgmstream/vgmstream#1062]
This is a problem with a partial build of FFmpeg 5.0, which accepts the PSF files, then proceeds to lock up, reading them forever and ever. This causes PSF files to lock up my player, because the Container parser has the default VGMStream extension set, which for some reason includes "PSF" as an extension.

**Comment by bnnm** [comment]
Was this fixed with your recent commit or do we need to reject PSFs in ffmpeg.c or such?

**Comment by kode54** [comment]
This was fixed by my recent commit. No need to reject anything. The issue was that either current or newest FFmpeg always needs AVERROR_EOF to be returned by the read callback when it reaches EOF. It will treat 0 just like 1+, and simply "increment" the read pointer and count by the zero and keep reading forever.

**Comment by kode54** [comment]
Fixed by 2db8e56ef2d11bed8b8f40e7fb9bce4d4fbc5c52
