### ISSUE TITLE
[Bug] the idolm@ster one for all

### ISSUE THREAD

**Issue by 5redtrees** [vgmstream/vgmstream#1063]
https://drive.google.com/drive/folders/1bADans6QkljDDDGbn-KLoX3ae2pR7ZCr?usp=sharing

I attempted, but there are some files having noise like the above

**Comment by bnnm** [comment]
Should work now: https://vgmstream.org/downloads

**Comment by 5redtrees** [comment]
https://drive.google.com/file/d/1xJQy6pZdzLILm3-qNuQLs-gtHYdujqPs/view?usp=sharing

I think this audio have same problem

**Comment by bnnm** [comment]
Try latest version again.
