### ISSUE TITLE
[Bug] Emergency Heroes (Wii) - XA/XAM files

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1064]
Like the title says, Emergency Heroes XA/XAM files do not play properly on vgmstream. here are some sample files:

https://drive.google.com/file/d/1apDgftDedrv9tFl-q8J68OIchPJE79vF/view?usp=sharing

**Comment by bnnm** [comment]
How where those ripped? XA files have unexpected 0x10000 blank bytes of padding.

**Comment by Sukotto-1999** [comment]
Really? So i have open up a single .XA file in a hex editor, and i just saw some kind of Developer text, but still unreadable on vgmstream. Could you just make a .txth file?

**Comment by bnnm** [comment]
I meant if files were found as-is on the disc, or it was an extraction problem from some bigfile.

Anyway, should work now: https://vgmstream.org/downloads

.xam is not audio but a playlist of other files (use .txtp to simulate).

**Comment by Sukotto-1999** [comment]
Alright. so, i updated vgmstream on foobar2000, and. . it works! Hope this helps!
