### ISSUE TITLE
[Bug] EAAudioCore EAOPUSM not playing

### ISSUE THREAD

**Issue by bep713** [vgmstream/vgmstream#1067]
Hey guys, first of all thanks so much for the tool. This is awesome. I'm looking at Madden 22's sound files. I ran into an issue with the OPUSM codec that they use for QB cadences.

- SPS file
- OPUSM codec
- 1 channel

I was able to get it working by uncommenting line 1423 in ea_eaac.c: `case 1:  cfg.coupled_count = 0; break;   /* 1ch, 1 stream */`
Not sure if there was a reason this was commented out, but figured I'd let you guys know. It works fine after doing that.

Link to file: https://drive.google.com/file/d/1c-8-GCiJrKTgRVtzVtvtlM-SC3QZVlTE/view?usp=sharing

Thanks,
Matt

**Comment by bep713** [comment]
Upon looking at it further, there are multiple SPS files in the file that I linked. Interesting...I don't see a .sbr file anywhere for it. I'll keep digging. Unless I have the wrong extension? I just assumed it was an SPS because the other stuff I looked at was too.

**Comment by NicknineTheEagle** [comment]
You're mixing up formats. SPS is standalone. SBR is for SBS.

**Comment by bep713** [comment]
Gotcha. The other files were Harmony Sample Banks, SBR + SBS.

There must be some accompanying file which has all the offsets to the file that I linked. Back to the depths of Frostbite I go, lol.

**Comment by bep713** [comment]
Okay, I think I found the corresponding SBR file: https://drive.google.com/file/d/19KB-5uOPkRfQWJaunL8bTB9EJMzHRa-M/view?usp=sharing

It was located in a RES chunk. The RES chunk GUID matches the GUID of the original file that I linked. Unfortunately, the DSET blocks seem to be in a different format. I'll keep looking at it to see if I find something.

I would expect to see 7 offsets from the original file:
- 0x0
- 0xB93C
- 0x13038
- 0x17208
- 0x1B240
- 0x20DD0
- 0x26768

**Comment by NicknineTheEagle** [comment]
I've made a parser for NewWaveResource SBR files here some time ago here: https://github.com/NicknineTheEagle/Frostbite-Scripts/blob/master/frostbite3/sbr.py, it's integrated into my ebxtoasset script. ebxtoasset is probably not going to work with your dump, though, unless the directory structure and chunk naming matches.

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/downloads
Several `coupled_count` lines  are commented out simply because I didn't test them, though probably are correct.
