### ISSUE TITLE
[Bug] unplayable SPS file (Madden NFL 13 Demo [PSVita])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1068]
apparently there is a sps file i found (from the Vita version of the Madden NFL 13 Demo) that doesn't seem to do well with vgmstream. other sps files play fine.

here are the samples.
[[madden_nfl_13_demo]vita_sps.tar](https://www.sendspace.com/file/jc1quk)

**Comment by modusc896d352** [comment]
i also found an unsupported sps file in the full Vita version of the game (Madden NFL 13). again, other files play fine.

again, the samples are here.
[[madden_nfl_13]vita_sps.tar](https://www.sendspace.com/file/amywl7)

**Comment by bnnm** [comment]
Fixed.
