### ISSUE TITLE
[Bug] Rayman 2 (iOS) music tracks play incorrectly

### ISSUE THREAD

**Issue by icup321** [vgmstream/vgmstream#1077]
Attempting to play any music tracks (sound effects work properly) inside the BNM archives will result in incorrect playback, or maybe just nothing. Interestingly, the iOS port seems to split the music tracks into BGM files for whatever reason, which can actually be played back on vgmstream, but without looping info.

https://www.mediafire.com/file/y96ys6gby5fu71k/R2_iOS_Sounds.7z/file

**Comment by NicknineTheEagle** [comment]
Curious, BNM banks themselves look normal but APM files are dummies and the actual music is stored in BGM files which look like standard M4A audio files.

**Comment by icup321** [comment]
Oh, that's interesting, I was expecting it to be missing some sort of missing codec for playing M4A audio files. In that case, I might just have to create a playlist file instead of manually sorting through the BNM files, which is easier said than done. I'll close this now unless something comes up later.
