### ISSUE TITLE
[Request] Sphinx & the Cursed Mummy (PC) Unsupported Eurocom MUSX format

### ISSUE THREAD

**Issue by icup321** [vgmstream/vgmstream#1080]
The remastered PC (and probably Nintendo Switch) version uses a different variation of the Eurocom MUSX/SFX format that is currently unsupported by vgmstream. There's plenty of documentation on the SFX format here which should help: https://sphinxandthecursedmummy.fandom.com/wiki/SFX

Music files: https://www.mediafire.com/file/glda1mzaqyo5ibe/sphinx_pc_music.7z/file

**Comment by bnnm** [comment]
Should work now.

**Comment by icup321** [comment]
Yep, all seems good now. Found no regressions so far so I'll go ahead and close this.
