### ISSUE TITLE
[Bug] some sbr don't really play [FIFA 15 (Vita)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1083]
just something i need to report before i go insane.

so, the gist of it is - sbr+sbs combo files, works with vgmstream latest update. they play fine.
individual sbr files, doesn't work with vgmstream latest update. they're all unplayable for some reason.

below is a tar file containing individual sbr files.
[[fifa15_vita]unplayable_sbr.tar](https://www.sendspace.com/file/1chl80)

**Comment by NicknineTheEagle** [comment]
Aw, great, these are SBR files with SPS inside them. I thought SPS can only inside SBS for these banks.

**Comment by modusc896d352** [comment]
yeah, i never really came across them until now.
