### ISSUE TITLE
Certain .fsb Files Crash Winamp

### ISSUE THREAD

**Issue by XaikuTheMaverickHunter** [vgmstream/vgmstream#1090]
The music files from Mortal Kombat 9 (Komplete Edition) seem to cause Winamp to crash when attempting to play them.

**Comment by NicknineTheEagle** [comment]
Post samples.

**Comment by bnnm** [comment]
Closing since no samples were posted and existing rips play fine.

Those files seem multichannel so your sound card may not support them, try Preferences > Plugins > input > vgmstream >"Configure" button, then set "downmix" to 2.
