### ISSUE TITLE
Kirby and the Forgotten Land .opus format doesn't read.

### ISSUE THREAD

**Issue by LoneEevee** [vgmstream/vgmstream#1096]
I'm not too versed in the technical knowledge of how all of this works, but Kirby in the Forgotten Land doesn't seem to work with the vgmstream component. It gives an error saying the file may be corrupted. Attached are some samples based on what they seem to be named. Some have a ".marker.opus" extension and some just have ".opus" but I'm not too sure if they have any differences.
[Marker Samples.zip](https://github.com/vgmstream/vgmstream/files/8357179/Marker.Samples.zip)
[Non-Marker Samples.zip](https://github.com/vgmstream/vgmstream/files/8357181/Non-Marker.Samples.zip)

**Comment by punk7890** [comment]
Rename them to ".lopus".

**Comment by LoneEevee** [comment]
Okay, that was a really dumb mistake on my part, then. I'd assumed "opus" was the name of the format and was creating errors due to a custom compression of sorts. Thanks!

**Comment by bnnm** [comment]
.opus is the name of the format, but plugins have issues with that extension (there is a setting to allow loading .opus too).

See here for mode info: https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#common-and-unknown-extensions

**Comment by LoneEevee** [comment]
I know I've closed this issue, but now I realize that looping doesn't seem to work when I do load the files. They just either end abruptly or fade out, depending on the song. I'm not sure if that's an issue with this game in particular or not, and if the loops are embedded in the opus files themselves or if they're in a separate file in the rom. If anyone has the time to check that out, I'd appreciate it.

**Comment by milesthecreator** [comment]
The loops are stored in BgmLoop.bfsar

**Comment by bxaimc** [comment]
Loop points are stored externally in that bfsar. You would need to locate where they are stored within and create txtps to force each looping opus to loop using those loop points. See TXTP document, more specifically this, 
https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md#install-loops
on how to use the loop feature with this scenario.

**Comment by bnnm** [comment]
Closing since using .txtp to handle external loops is the only way (you can probably find pre-made .txtp with extracted loops if you look around)
