### ISSUE TITLE
[Request] Support for .m4/.og audio files

### ISSUE THREAD

**Issue by SecureFootage** [vgmstream/vgmstream#1098]
The files are from a game called Yokai Watch Wibble Wobble, from level 5 games. They have no header, and have no information online. Maybe you guys could examine them and add support for them?

Sample files: [Here](https://mega.nz/folder/SpRTyaiS#L4X62Wy0vLupcjUvzZELCw)

**Comment by NicknineTheEagle** [comment]
If the contents of bgmmaster.mst are any indication, these are encrypted .m4a and .ogg files. You need to decrypt them first.

**Comment by SecureFootage** [comment]
Oh, well that gives me a start at least. I'll see what I can do.
