### ISSUE TITLE
Some CAF files cause foobar2000 to crash

### ISSUE THREAD

**Issue by Mohamed00** [vgmstream/vgmstream#1100]
Hi, I noticed that some CAF files that previously worked when played in vgmstream now cause crashes in foobar2000.
[Some broken files](https://github.com/vgmstream/vgmstream/files/8377205/broken.files.zip)
[foobar2000 crash dump](https://github.com/vgmstream/vgmstream/files/8377207/crash.dump.zip)

**Comment by kode54** [comment]
Your crash log shows that your input load order is preferring to load these in a plugin called `foo_input_caf` which I've never heard of, and it's crashing.

**Comment by Mohamed00** [comment]
Indeed that was the issue, removing it fixed that. I used foo_input_caf 
because I had some files that vgmstream was rejecting.
