### ISSUE TITLE
[Bug] unplayable mpf+mus combo [NFL Street 2 (PS2)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1102]
so, i came across an mpf+mus combo from **NFL Street 2** (PS2 ver though). without saying much, i tried to play them myself, and i thought vgmstream could handle this combo quite well until they turned out to be literally unplayable.

tried to make up a txtm file so i could play them at all, like this:
`1.mpf: 2.mus`
but even that didn't work.
i placed said file alongside the combo.

anyhow, here are the files that doesn't work with vgmstream as of this writing.
[[nfl_street_2][ps2]mpf.7z](https://krakenfiles.com/view/3nCas6Bszn/file.html)

---

found another mpf+mus combo from **NFL Street 2: Unleashed** (PSP game). same thing here; the combo doesn't play even when an txtm file is present alongside it.
[[nfl_street_2_unleashed][psp]mpf.7z](https://krakenfiles.com/view/jtlMZu7L53/file.html)

**Comment by NicknineTheEagle** [comment]
MPF/MUS v5 without track checksum at the start at the start. Weird.

**Comment by NicknineTheEagle** [comment]
Try the build from PR once it compiles.

**Comment by modusc896d352** [comment]
i'll test the PR build right away.
