### ISSUE TITLE
[Request] Metal Gear Solid 4 - .ssp and .spc formats

### ISSUE THREAD

**Issue by Zoft123** [vgmstream/vgmstream#1108]
Hey there, 

Apologies for bringing my own requests to this Github page but I've tried personally to get an idea of how I could go about doing this and learning the first couple steps and I can confidently say I absolutely do not understand how I can go about reversing these two formats. I never made a request like this before and because of that I may be providing more information that what is needed.

With that being said -

Game: Metal Gear Solid 4 (+ Metal Gear Online - multiplayer aspect)
Formats: .SSP and .SPC
Codec: MTA2
Endianness: Big Endian 

Most of the formats for this game's audio files have been reversed but it's been a long time since then and these two formats remain as still needing reversed. I tried to gather as much information as possible on these files (so far as to reverse and early-build of the game's engine to see how the game calls the files). I will be linking below a few different things.

Pastebin of various functions seen in the game's .self file on what these files include/require to be used: 
https://pastebin.com/Li8A4fR7

IMGUR link to 4 pictures (2 from each format) displaying the top & bottom halves of each type's raw data:
https://imgur.com/a/kw5kaYH

Finally, a Google Drive link to 2 examples (each) of the files in question for any sort of examination that may be requested:
https://drive.google.com/file/d/1PSvQiijJF5evDT8eeeL9OiHIxnX_URwY/view?usp=sharing

I hope this is something that could be potentially done by VGStream?

**Comment by bnnm** [comment]
I think it's possible to add support but you need to upload a lot more samples than that.

.spc looks like a bunch of .ssp pasted together so doesn't look like a real format that needs to be added, should be easy enough to split.

**Comment by Zoft123** [comment]
Sure thing I can upload you all of them.

**Comment by Zoft123** [comment]
Here you go, all of the SSP & SPC files in-game (archive is 900 MBs):
https://drive.google.com/file/d/1ZVJWtdqLOwFJE4WzN0gbhPQu2yrywG30

**Comment by Zoft123** [comment]
Also, if there is any additional info you would use that would aid in this being possible let me know and I can try to find any entries referencing it in the game's source. Not sure if what you see when looking at these files is something you already understand and can do or if additional details would help.

**Comment by bnnm** [comment]
Added .ssp, as for .spc since it's just a bunch of .ssp don't think it's worth adding, should be easy enough to split with some custom bms (there is an offset/size in sectors table at the end).

Some .ssp subsongs (ex. wpn913_mgo_common.ssp#129) use a SSWF variation but I don't recognize the codec (simplified MTA2?), I'll try again later.

Also voices seem to play at a wrong sample rate but according to your pastebin decomp "freq" field is correct, so maybe this is modified later via pitch cues? Or this "freq" has another pitch-like meaning?

**Comment by Zoft123** [comment]
> 

Anyway for me to get in touch with you and I can provide you everything there is on these formats? The ones I listed are the broad functions listed in the game in regards to the audio but some of them do branch off to 1-2 more options. If not I can try to post them here, will post in about 15-20 minutes.

**Comment by Zoft123** [comment]
[More_Audio_Info.txt](https://github.com/vgmstream/vgmstream/files/8457725/More_Audio_Info.txt)

When you open that be sure to turn of Text Wrapping if you use it or the formatting for you will be terrible.

Also about MTA2: https://www.mgsdevwiki.com/wiki/index.php/MTA2_(Container)

**Comment by Zoft123** [comment]
If ever after that you'd still come to the end result of the pitch/sound not coming out right and this is the only avenue for us to communicate please just give me an idea of what kind of information you'd need in reference to the data I have (I don't know much if anything about audio formats and codecs) for instance:

Give me data on pitch, gain, volume etc. 


Ty very much for checking into this and I'm sure the community will really appreciate your hard work.

**Comment by bnnm** [comment]
Could you post this .self? probably easier this way

**Comment by bnnm** [comment]
Roughly fixed the sample rate (not exact for all sfx but best I could manage, voices are probably ok) and fixed unplayable subsongs:
https://nightly.link/vgmstream/vgmstream/workflows/vs-win/master
