### ISSUE TITLE
[Bug] "silent" PCM files [NBA Live 95 (MS-DOS)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1109]
OK, i need to make this brief and get that off my chest before i go insane.

so, there are some sound files (already supported on vgmstream by the way) that *do* play but let out a big chunk of nothing instead.
i'm talking about the ASF files from the MS-DOS version of NBA Live 95.
these files contain a lot of data that vgmstream "jumps over" for some reason? they do play but they're all playing silence here.

anyway, here are the files i guess.
[[nba_live_95][ms-dos]silent_asf_files.7z](https://www.sendspace.com/file/26svj5)

**Comment by bnnm** [comment]
Fixed.
