### ISSUE TITLE
[Request] Rayman 3 (PC) Demo Versions Support

### ISSUE THREAD

**Issue by icup321** [vgmstream/vgmstream#1113]
VGMStream lacks support for reading some of the audio tracks in the early PC demo versions, I think it's specifically the music tracks, because I wasn't able to find any of them that were playable. Only demo 4 (AKA the January 29, 2003 demo) is fully compatible.
https://www.mediafire.com/file/vrrfdz33tcqkpuu/Rayman_3_Demo_Sounds.7z/file

Also, I found out that the PS2 demo version of Rayman M has some unplayable .hxd files, the ones in the TribeBin folder work, but all others fail to playback.
https://www.mediafire.com/file/tw2p52rkdl6icc9/Rayman_M_%2528PS2%2529_%2528Demo%2529.7z/file

**Comment by bnnm** [comment]
Should work now.

site is out so: https://nightly.link/vgmstream/vgmstream/workflows/vs-win/master

**Comment by icup321** [comment]
It looks like there are still some issues with audio playback on Rayman 3 PC Demos 3 and 5, some sound effects have noticeable popping on either the beginning or end, and I think the vast majority of the music tracks corrupt halfway through the track length, maybe they're supposed to be split?

**Comment by bnnm** [comment]
Should work now.

**Comment by icup321** [comment]
All seems to be working well now, thank you.
