### ISSUE TITLE
[Request]WWise WEM not playable - ADM3 Header

### ISSUE THREAD

**Issue by ManuJDT** [vgmstream/vgmstream#1115]
[WEM_ADM3.zip](https://github.com/vgmstream/vgmstream/files/8473081/WEM_ADM3.zip)
[more_samples.zip](https://github.com/vgmstream/vgmstream/files/8475809/more_samples.zip)

Hello. I have unpacked these .wem files with ADM3 header which cannot be played. Any ideas?

Additional note: If I import raw data (.wem with ADM3 header) into audacity I can hear the sounds I'm looking for, with a lot of background noise but the sounds are there.

**Comment by NicknineTheEagle** [comment]
What game?

**Comment by ManuJDT** [comment]
MotoGP21

**Comment by bnnm** [comment]
Post more of those .wem and a few .bnk too (including init.bnk), and if the game has it SoundbankInfo.xml or related wwise text/.h files. If this is PC also post any .dll that may be related to wwise and the main exe (motogp21-Win64-Shipping.exe I guess).

**Comment by ManuJDT** [comment]
> Post more of those .wem and a few .bnk too (including init.bnk), and if the game has it SoundbankInfo.xml or related wwise text/.h files. If this is PC also post any .dll that may be related to wwise and the main exe (motogp21-Win64-Shipping.exe I guess).

Ok, I have included more files and executable in the first post (more_samples.zip)

Thanks

**Comment by ManuJDT** [comment]
> I have a general idea of what's this about thanks to the .xml, but if you could post related dll/exe and init.bnk + init.xml/txt etc too.

I don't know where to find .dll related to those files.
The ADM3 .wem files are the bikes engine sounds created with crankaseaudio rev, but I can't find anything related to crankaseaudio inside the pak.

I attach another zip with the executable and the init files. 
https://www.mediafire.com/file/4ogj5hsqk8dlwhj/Init+exe.zip/file

Thank you very much for your work. You are a genius.

**Comment by bnnm** [comment]
Works now

https://github.com/vgmstream/vgmstream/actions/runs/2254478427
