### ISSUE TITLE
[Bug] awb/acb files not playing properly in Foobar w/plugin

### ISSUE THREAD

**Issue by 64BTX** [vgmstream/vgmstream#1119]
I'm trying to get the music from an Android/iOS game, and they're in awb/acb format. When trying to play them in foobar with the vgmstream plugin, all that the streams in them play are a garbled mess of noise. Other people I've talked to have done the same thing as I have (from the same game) and have had no problem listening to them properly. Therefore I don't think it's a problem with the game format itself, but something on my end related to vgmstream.
I've uploaded some sample files from the game: https://mega.nz/file/KAQk0BpI#2Ym5s_eYHEo2gUpYs8BVkd1EXTWc8o8dbBpnRG5VGDg
And the game itself I'm looking at if needed: https://mega.nz/file/DUgWyZBK#h-4M7LAC-mH3HAO9I95tUkRoaVc_-fANsoXtkHUXXLg
[for clarity's sake, I'll mention that the game itself has been free throughout its lifespan]
I've also used just the vgmstream commandline tools to see the info about the audio files, and it comes through fine with reasonable song length, bitrate, channel numbers, etc.

**Comment by bnnm** [comment]
You need a recent (april) version:

https://nightly.link/vgmstream/vgmstream/workflows/vs-win/master
