### ISSUE TITLE
Prototype 2 - (p3d) RADP, Dialogues 

### ISSUE THREAD

**Issue by fignyafsyakaya** [vgmstream/vgmstream#1122]
[Prototype 2 - speech.zip](https://github.com/vgmstream/vgmstream/files/8527225/Prototype.2.-.speech.zip)

Tried to convert speech audio files from "**Prototype 2**" - failed right at opening.
After examining "_p3d.c_" I think that the source of the problem is in "info_count":
![image](https://user-images.githubusercontent.com/96207944/164376116-c2481570-23d3-470e-b965-48da723bcf5a.png)

In the files I examined (some of them are uploaded) this value is always "0" so the program immediately goes to "fail".

But some of those files include "**AudioDialogueSubtitle**" section with its own description rules, which makes getting to audio part more difficult for current settings.
As far as I can see, both **AudioDialogueSubtitle**-header and **AudioFile**-header begin with 0xA.
But the components of "Subtitle" are not fully comprehensible for me.

At first, there is a 0x1 value (number of names, maybe?),
then - length of the name of subtitle, with the name itself with 00 delimiter after that,
then - some 0x4-long value,
then - 8 zero values,
then - a 0x1 value (number of...smth?) with 5 zero values,
then - 0x9-long value (in the files I looked it was always the same; maybe other languages are different),
then - length of the language of subtitle, with the language itself with 00 delimiter after that,
then - length of the subtitle text, with the text itself...
and after that it's only 0x1B length left to get to **AudioFile**-header.

I'm not fluent enough in "C"-language to contribute this without breaking the code, but at least, I hope that the stuff I tried to describe will make somebody's life easier.

**Comment by fignyafsyakaya** [comment]
[Prototype 2 - missed_out.zip](https://github.com/vgmstream/vgmstream/files/8549070/Prototype.2.-.missed_out.zip)

Of course, I had to miss out on something.

It turned out that sometimes instead of the **"8 zero values"** there might me some 0x8-long value.
And when it happens, it is followed by the same **0x1** byte-value - not with 5 zero values but with length of some kind of name (maybe, NPC-kind) and the kind ifself. Surely, with 00-delimiter, as in other cases.

So, as I think, when the length of "NPC-name" is zero, the only thing left is the 00-delimiter - that's why there were **5 zero values** (0x4-long value + 00-delimiter).

**Comment by bnnm** [comment]
Should work now.

**Comment by fignyafsyakaya** [comment]
Hmm, the size of the first file section is written at the beginning, how could I not see it...

Yep, it does work. Thank you for your trouble.
