### ISSUE TITLE
Vgmstream Have raw audio quality loss compared to other extractor ?

### ISSUE THREAD

**Issue by DarkFrost89** [vgmstream/vgmstream#1123]
Hi I have Question for today
Vgmstream Have raw audio quality loss compared to other extractor ?
Because sample rate doesnt change Vgmstream and ı didnt extract like another xa extractor
This is Compare image
![Ekran Görüntüsü (3)](https://user-images.githubusercontent.com/39680092/164497770-31aea120-fb5f-4c7a-a930-1d1eb81a9745.png)
based on this image vgstream loss qualty then another extractor. Becase avarage bitrate lower then another extractor and sample rate cuttof dropped then another.
how can ı change default sample rate vgstream ?
and how can ı fix this ?

Best Regards
Dark Frost

**Comment by bnnm** [comment]
XA files have an internal sample rate of 37800hz or 18900hz only, never 44100hz.

vgmstream outputs the raw audio as-is, this is not an error.

A real PS1 however, takes this raw 37800hz audio and upsamples it to 44100hz. This isn't simulated in vgmstream.

I don't know if XA Audio Converter simulates the PS1 upsampling, or does a generic upsampling. Either way, 37800 is the original audio quality, and 44100 versions will be the same but filtered.

You could simulate this yourself by using upsampling manually from 37800 to 44100.

**Comment by DarkFrost89** [comment]
@bnnm 
Today I wrote my commandline Batch ffmpeg XA extractor and ı see someting interesting things
if I use raw pcm_s16le codec 44100 sample is not Upsampled and No Loss Quality (and bitrate is good)
but if ı use raw pcm_s16le 48000 is Upsampled And Loss Quality, (bitrate is good but Upsampled)
![Ekran Görüntüsü (2)](https://user-images.githubusercontent.com/39680092/164874312-e5eed270-4ee5-423f-a8a4-1fba4e89a9f3.png)
Possibly  Xa format supported the 44100 Upsampling but only limited is 44100 not upper,if you use ffmpeg library for extracting possibly vgstream is supported  Xa 44100 sample rate mybe future you added Upsample function in your software
Best Regards
Dark Frost

**Comment by bnnm** [comment]
Even if you think ffmpeg output at 44100 has "no quality loss", it's just upsampling + filtering with a another algorithm. PS1 XA only has data for 37800 or 18900, it's just how it works.

Maybe upsampling can be added in vgmstream later, but XA will still sound as good as upsampling it yourself.
