### ISSUE TITLE
[Bug] Build fails if FFMpeg disabled on Linux x86_64

### ISSUE THREAD

**Issue by andrewathalye** [vgmstream/vgmstream#1124]
Using VGMStream r1721, ktac.c references mp4_custom_t even if FFMpeg is disabled. The result is that the build fails. This can be replicated by building using the following command:
cmake .. -D BUILD_AUDACIOUS=OFF -D BUILD_CLI=OFF -D BUILD_V123=OFF -D USE_ATRAC9=OFF  -D USE_CELT=OFF -D USE_FFMPEG=OFF -D USE_G719=OFF -D USE_G7221=OFF -D USE_JANSS
ON=OFF -D USE_MAIATRAC3PLUS=OFF -D USE_MPEG=OFF -D USE_SPEEX=OFF -G Ninja 

A quick workaround is to replace mp4_custom_t with something else, since ktac is effectively not useful without FFMpeg in any case.

**Comment by bnnm** [comment]
Should be fixed already, always try latest commits:
https://github.com/vgmstream/vgmstream/blob/master/src/meta/ktac.c

**Comment by andrewathalye** [comment]
My bad, sorry for the erroneous bug report.
