### ISSUE TITLE
[Bug] Some acb files not playing properly

### ISSUE THREAD

**Issue by dewrfe53535** [vgmstream/vgmstream#1125]
Some acb files from the game "iris mysteria" not playing properly.I have used the latest version.Here are some samples:
[samples.zip](https://github.com/vgmstream/vgmstream/files/8546248/samples.zip)

**Comment by bnnm** [comment]
Fixed

**Comment by dewrfe53535** [comment]
It seems that there are still problems for these files.I noticed that you added the hcakey of this game [again](https://github.com/vgmstream/vgmstream/blob/e9292a1f5fe57e67265275004de2a3f186d72e23/src/meta/hca_keys.h#L271).The key should be correct because it works well with [acbDecrypter](https://github.com/Rieksee/acbDecrypter) for these files.Most of the other acb files for this game play fine.

**Comment by bnnm** [comment]
Try again now.

**Comment by dewrfe53535** [comment]
Working fine now.Thank you!
