### ISSUE TITLE
[Bug] Issue with specific song from Metroid: Other M (AIX)

### ISSUE THREAD

**Issue by Miepee** [vgmstream/vgmstream#1133]
VGMStream has issues playing `bgm_m_stage_06_02` from Metroid: Other M.
All other songs it can play fine. VLC(/ffmpeg?) supports playing that file, albeit with stuttering issues which it has for all AIX files.
I've provided a sample of `bgm_m_stage_06` which plays fine for comparison, and `bgm_m_stage_06_02` which errors.
[bgm_m_stage_06_02.zip](https://github.com/vgmstream/vgmstream/files/8611111/bgm_m_stage_06_02.zip)
[bgm_m_stage_06.zip](https://github.com/vgmstream/vgmstream/files/8611113/bgm_m_stage_06.zip)

**Comment by bnnm** [comment]
The file looks truncated, which is why vgmstream rejects it. Bad rip?

**Comment by Miepee** [comment]
Nope, it's a correct rip.

**Comment by bnnm** [comment]
I've tweaked the parser to allow this, but due to missing data some parts of the song will be silent. 

Since bgm_m_stage_06_02 is just bgm_m_stage_06 with an intro this seems correct as both are aligned this way, not sure how the game would actually play it.

**Comment by Miepee** [comment]
Took out all the songs, except for `bgm_m_stage_06_02` and put that into the game. Here's a recording of it, does that help?

https://user-images.githubusercontent.com/38186597/167297345-e2a16234-0dfa-4be8-8933-2f4158a1e792.mp4

I don't know if the "noise" which starts to play near the end is because if it's playing another song on top of it (which'd be weird considering I took all of them out), or a weird loop point.

**Comment by bnnm** [comment]
The noise you hear at ~2:36 is when the missing data starts. Notice that (comparing vgmstream with your recording) that noise is all over the track too (after the intro), maybe a layered enviromental sfx (sounds like white noise so maybe generated by the engine?).

So when the missing data starts and assuming that's just external noise, it's also silent (then it loops), so I think vgmstream behaves like the game.

**Comment by Miepee** [comment]
Checking b1d6e689ddb3c549199bba6cee00d66169fddf3e, loop behaviour seems different. VGMStream starts looping after around ~2:40, while the game actually ignores the loop. I thought at first this was because I initially put `bgm_m_stage_06_02` over a song that never loops, but when putting it over other songs that do loop, the game still ignores the loop point from the file.

**Comment by bnnm** [comment]
I guess the engine just stops the song once missing data is reached, I'll tweak it later.

**Comment by bnnm** [comment]
Fixed
