### ISSUE TITLE
[Request] unplayable ktsl2 (and g1l) files [Nioh (PS4)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1138]
so, uhhhhhhhhhh, i came across some unplayable ktsl2 files from the PS4 version of Nioh. vgmstream doesn't seem to support these particular files. i remember looking at the code and seeing some support for ktsl2 files so maybe this is one variant that isn't covered there or something?

anyhow, here are a few select files.
[[nioh][ps4]unplayable_files.7z](https://krakenfiles.com/view/Ex98OevOcH/file.html)

i don't really know what to do with g1l though...
extracting it using some script/tool *is* viable, though not necessarily something i have in mind when i want to play whatever sound comes across my ear.

**Comment by bnnm** [comment]
Fixed, but .g1l is a pseudo-container format that is too simple and also a container of containers, so I think it's better to extract first (there is some support for one game but may be dropped in the future).

See this .py if you need it: https://github.com/bnnm/vgm-tools/blob/master/py/etc/koei-G1LExtract.py

**Comment by modusc896d352** [comment]
alright. i'll see what i can do.
thanks for the fix.
