### ISSUE TITLE
[Bug] unplayable atsl files [Nioh (PS4)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1140]
ok, it's about time i reported this.

i've been testing some atsl files extracted from g1l archives using a python script that can be found here.
https://github.com/bnnm/vgm-tools/blob/master/py/etc/koei-G1LExtract.py

i tested all of them and they play quite well. that said, there are like two atsl files that vgmstream refuse to work with. here they are.
[[nioh][ps4]unplayable_atsl_files.7z](https://www.sendspace.com/file/0n6p9d)

thanks in advance!

**Comment by bnnm** [comment]
Fixed.
