### ISSUE TITLE
[Bug] unplayable sb0 files [Myst IV: Revelation (Windows XP)]

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1141]
guess vgmstream isn't done with ubisoft yet.

so, as i was datamining Myst IV (with help from [myst4tools](https://github.com/coderjo/myst4tools)) i came across all the sound files using "the usual" Ubisoft sound format stuff (with four weird extensions at that). while i could get something playable out of them, i don't think the rest can be said with the "non-music", "non-SFX" sound files. as in, the files that have actual spoken sounds in them. anything that has to do with dialogue really since the game was filmed with live-action footage containing actors, prop sets, among other things.

anyhow, here are the files.
[[myst_iv_revelation][windows_xp]unplayable_files[sb0+ls0].7z](https://www.sendspace.com/file/xsvo2g)

only one file (**video_w6_stream.sb0**) works well at all with vgmstream. the rest of the files just doesn't work.

**Comment by NicknineTheEagle** [comment]
The parser relies on the presence of Ubi project file (.SPx) to detect this game. Make sure gamesnd_myst4.sp0 is in the same directory or the level above which it should be if you do not separate the banks.

**Comment by modusc896d352** [comment]
managed to place gamesnd_myst4.sp0 in the same folder. and the dialogue sounds do work this time around.
seems like listening to most of the dialogue isn't completely hopeless. yet.

**Comment by bnnm** [comment]
I've updated detection a bit so it may work without gamesnd_myst4.sp0.
