### ISSUE TITLE
[Request] Support the rest of the .STD files in Harry Potter and the Prisoner of Azkaban GameCube 

### ISSUE THREAD

**Issue by SkyrimFan64** [vgmstream/vgmstream#1143]
Hi. I would like to request to add support for the rest of the .SDT files for Harry Potter and the Prisoner of Azkaban for GameCube for Foobar2000 as the ones that contain dialog aren't supported but the emotes are supported.

**Comment by bnnm** [comment]
Post multiple samples of those files.

**Comment by SkyrimFan64** [comment]
> 
[Samples.zip](https://github.com/vgmstream/vgmstream/files/8703815/Samples.zip)

**Comment by bnnm** [comment]
This seems to be a container of EA's SCHl files with a table.

Seems a bit too simple to be be added, but if you unzip this file in the folder they should be playable:

[txth.zip](https://github.com/vgmstream/vgmstream/files/8711399/txth.zip)

**Comment by SkyrimFan64** [comment]
> This seems to be a container of EA's SCHl files with a table.
> 
> Seems a bit too simple to be be added, but if you unzip this file in the folder they should be playable:
> 
> [txth.zip](https://github.com/vgmstream/vgmstream/files/8711399/txth.zip)

So what exactly am I supposed to do with the file after unzipping it? Clicking the .sdt file and dragging it to the file you sent me doesn't do anything. Is it supposed to be a command line prompt thing?

**Comment by bnnm** [comment]
Unzip the file in the folder then try to play the .sdt

**Comment by SkyrimFan64** [comment]
> Unzip the file in the folder then try to play the .sdt

That worked. Thanks. But for some reason, it doesn't work for two of my friends. They have the latest version of Foobar2000 and VGMStream but the file doesn't work for them.

**Comment by kode54** [comment]
Assuming that last comment about "latest version" was deleted, I'll still reply to it. I removed the component from the official repository, because we could no longer automate uploading new versions, and it was otherwise serving potentially obsolete builds unless I manually updated it. So you need to check manually if you're running the latest.
