### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PeperonChill** [vgmstream/vgmstream#1144]
The vgmstreamplugin doesn't seem to be working on fb2k.  i'm trying to extract the audio files from scp unity, and it doesn't play any of them. thanks in advice

**Comment by bxaimc** [comment]
Provide samples please.

**Comment by PeperonChill** [comment]
Dont worry bud, problem solved. For some reason firewall was blocking fb2k.
Thanks anyways, the plugin works great.
