### ISSUE TITLE
[Bug] These s14 files have some noise[The Idolmaster Dearly Stars]

### ISSUE THREAD

**Issue by 5redtrees** [vgmstream/vgmstream#1145]
https://drive.google.com/file/d/1y96pP8XHZdMZXuLfjFxOpCrUYJL7bVth/view

**Comment by bnnm** [comment]
These files have some kind of variable padding. For example, first file has 0x924 data, 0x2c padding/garbage, 0x834 data, more padding (smaller?), etc. Each file works differently and padding doesn't match a proper frame so decoding fails mid-way.

Not seeing any patterns or anything in the data that would signal padding. Not sure how the game would handle that, maybe it's part of the original container (idx+bin) and has to be removed during extraction, so don't think this can be fixed here.
