### ISSUE TITLE
[Request] Azurik - Rise of Perathia

### ISSUE THREAD

**Issue by CameoDaManeo** [vgmstream/vgmstream#1146]
Would you be able to have a look at Azurik .wave files for me? I have included a zip file containing a bunch of samples of what I believe to be audio files. I can send more information at your request

Thank you very much :)
[fx.zip](https://github.com/vgmstream/vgmstream/files/8751127/fx.zip)
.

**Comment by bnnm** [comment]
The files are a bit too simple to make them playable directly, but if you unzip this file in a dir with .wave files, then play the .waves they should work (you need a not-too-old vgmstream: vgmstream.org/downloads).

[wave.txth.zip](https://github.com/vgmstream/vgmstream/files/8794305/wave.txth.zip)

A few 1kb files don't play but they don't have any audio.

**Comment by CameoDaManeo** [comment]
Works like a charm! Thank you very much.

I've checked the rest of the files, and unfortunately, I cannot find any music anywhere. But that'll be a mission for another day. (It's probably in the .xbe file, which I cannot figure out how to decompress)

Again, thank you very much for you help!
