### ISSUE TITLE
Frostbite 2 sound file Unsupported format

### ISSUE THREAD

**Issue by antoniu200** [vgmstream/vgmstream#1147]
Hi!

The following two Frostbite 2 (NFS The Run) files are not recognized by the latest version of vgmstream. "clown_music.awc" might be a dummy, but the other one I have some doubts.

Please investigate, if possible.
Thank you!
[NFS_DRA2_9a_loop_bpm_145_wave.zip](https://github.com/vgmstream/vgmstream/files/8794366/NFS_DRA2_9a_loop_bpm_145_wave.zip)

**Comment by bnnm** [comment]
clown_music.awc is a file from the PC version of GTA5, which isn't encrypted thus not playable at the moment.

NFS_DRA2_9a_loop_bpm_145_wave.sps has 4 extra garbage bytes at the end, so it may be an issue with the extractor (it's playable if you remove them)

**Comment by antoniu200** [comment]
> clown_music.awc is a file from the PC version of GTA5, which isn't encrypted thus not playable at the moment.

Sorry about that, must 
> 
> NFS_DRA2_9a_loop_bpm_145_wave.sps has 4 extra garbage bytes at the end, so it may be an issue with the extractor (it's playable if you remove them)

**Comment by antoniu200** [comment]
I re-extracted the files, the extraction process for The Run is a bit more complicated than the usual BMS script.
It seems now the file's ending bytes are quite different. In any case, before the new extraction, there were some other files that were not openable by vgmstream. Those seem to have been fixed, but if any other issue comes up again in this game, I'll just reopen this thread.

For now, I'll close it.
Thank you for your time and sorry for a possible false alarm.
