### ISSUE TITLE
[Bug] .tak (Tom's lossless Audio Kompressor) files don't play

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1148]
Although Tom's lossless Audio Kompressor is supported on vgmstream, .tak files won't play, unless file extension is renamed to any other.

**Comment by kode54** [comment]
Can't reproduce. Please forward me a non-playing TAK file to takfile@kode54.net.

**Comment by Sukotto-1999** [comment]
Turns out, there is a plugin for foobar2000 that can decode .tak files.

**Comment by kode54** [comment]
Sorry, I didn't realize this was posted to the VGMStream tracker.
