### ISSUE TITLE
[Request] PS2 Jak and Daxter, Jak II dynamic music

### ISSUE THREAD

**Issue by PookaMustard** [vgmstream/vgmstream#1150]
Hi. Thanks for the development of vgmstream. Playing game audio straight from their files and not from third party MP3s have been a boon.

Before @Ziemas [wrote the audio player code for the OpenGoal project](https://github.com/open-goal/jak-project/tree/master/game/sound/989snd) (big thanks for that!), there was no audio player that could play the original PS2 music files for Jak and Daxter: The Precursor Legacy (TPL) and Jak II, due to being the only games in the series to use dynamic audio. For example:

- in Sandover Village in TPL, more instruments join in and some leave simply by virtue of whether you're in Samos's hut, the Mayor's house, etc.
- in Haven City in Jak II, the base instrumentation is played on foot and more are added if you're in vehicle, holding your gun, or on the hoverboard.

From what I've heard, only one variant is played at a time, the game doesn't stack two variants on top of the base track. The music code is mostly in mostly in ame_handler and midi_handler in the above link.

Samples are not available on joshw but I can provide them on request (as long as I don't jeopardize the project by introducing copyright shenanigans to it).

**Comment by bnnm** [comment]
vgmstream can only play, well, "streams" (prerecorded audio). Jak 1/2 use "sequences" for music afaik (basically MIDI with instruments).

That is to say, it's not possible for vgmstream to support these games unless massive changes were done, basically becoming another program entirely. A more likely approach would be porting the above sound code as an standalone plugin, with some kind of dynamic track selection.

Thus unfortunately nothing can be done here.

**Comment by PookaMustard** [comment]
> That is to say, it's not possible for vgmstream to support these games unless massive changes were done, basically becoming another program entirely. A more likely approach would be porting the above sound code as an standalone plugin, with some kind of dynamic track selection.

Probably not related to this problem, but is it possible to treat each set of "sequences" as separate streams? So let's say the sequences for Sandover + any one of its dynamic variants is a separate stream. If I'm imagining this right, it won't be dynamic anymore, just static tracks with the dynamic instrumentation built in.

I think it can be done via plugin, but I thought I'd request it on vgmstream first so it may be available in other software using vgmstream.

**Comment by bnnm** [comment]
I don't know what Jak exactly does, but usually, sequences are a list commands ("play piano note at pitch C4", "play horn note at pitch D6") all together playing and joined on real time. When you have a dynamic variation there is some command like "keep playing/stop playing this set of notes that make a variation", still within the same sequence. But I guess it's possible to have 2 separate sequences going at the same time and crossfade them.

Either way, vgmstream can't simulate these whole sequences of "play piano note X" due to its internals being too different, though it could play single, separate instruments or voices at default pitch, that themselves are tiny "streams".

**Comment by PookaMustard** [comment]
Hmmm, so Jak won't be possible with vgmstream at the moment. That's alright, thanks for letting me know! I'll admit I'm not too knowledgeable about game music.

Should I close this issue?

**Comment by bnnm** [comment]
Closing since there isn't much we can do.
