### ISSUE TITLE
? naming without old file extension at the end of the name

### ISSUE THREAD

**Issue by biast12** [vgmstream/vgmstream#1160]
Hey i was wondering if we could get a way to name the converted files as the name only and not the old file extension

an example is with using `?f`, that games <Name of the file>.<old file extension>.<new file extension> / `59283765.wem.wav` (converting from .wem to .wav), so what i am suggestion is a ? to name the files as `59283765.wav` instead of `59283765.wem.wav`

**Comment by bnnm** [comment]
Some files that vgmstream supports use .wav as extension (not just regular .wav), so using a double extension ensures they won't be overwritten by mistake.

Plus, vgmstream wants to encourage people using original files, so this double extension also makes easier to identify CLI conversions. Besides, if one knows how to convert with CLI, they probably can manage to batch rename extensions too.

**Comment by biast12** [comment]
see i'm not asking to change the already `?f`, i'm just asking for a new one, i don't see why there would be any reason to not allow another way of naming them when the `?f` is still there and people still can use it if they need it for something

**Comment by bnnm** [comment]
Yes, I understand you are asking for a new one. You "don't see any reason to not allow", but I literally posted various reasons. Adding new behaviors does take time and effort, so why not try to explain why you need this option, why would it be useful? What about the points I raised?

**Comment by biast12** [comment]
what i say saying in my second comment was that all those "reasons" you gave was actually 0 reasons since it doesn't matter if it's a new way of naming the files

also why i need it is because i got an archive with all the files from Apex Mobile and the sounds are a part of that and since people are really dumb are they getting confused of what file type it actually is (guess they got file showing extensions off in explore but idk) i have already from the day i made this request / enhancement gotten a few people DMing me about the confusion of the file names, so it would honestly just solve a lot of confection on other people part who use my archive and a lot of stress off me for constantly gotta explain why it's like that, here's a link to the archive if you wanna have a look btw https://bit.ly/3ArgvxY

**Comment by bnnm** [comment]
I still don't see how a having a new flag that potentially deletes original files if used by mistake is a good idea.

You don't seem to care about addressing those potential issues so no point in discussing any further.

I recommend making some script that removes the double extension.

**Comment by biast12** [comment]
....... but that "potential" is both low and can still be combatted with just using the flag already made (`?f`)... that's why it's not a so called "issue" because it's not really an issue at all when you still can do it in a way that works, honestly not even giving it a chance is just kinda weird, why not even think about having something useful for a lot of people that only may be a problem for a few and those few can still just use the `?f` flag...
