### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by VanHoevenTR** [vgmstream/vgmstream#1162]
I just noticed test.exe got deleted by Windows Defender as soon as I execute it. I have whitelisted it now

But why should anti-virus detect it as trojan even it's build from source code? it's so strange. Just curious why. I downloaded it from automated build

This is automated build. 19/66
https://www.virustotal.com/gui/file/02d641e2eaca9da7b609a8802942ebff127440471440c993d6c68bab364115f5

This is release build. Just only 1/68
https://www.virustotal.com/gui/file/1f2b988b6a0e1ae26a56b6f2a57017cefde71e9fe484cc9b874be86238db3a9c

**Comment by kode54** [comment]
As I've said numerous times, antivirus scanners are a scam to make people feel safe. Report it to Microsoft as a false positive, report it to your vendor if that's the case, then move on until the next time they flag us.

**Comment by bnnm** [comment]
Updating the VS version used to compile seems to have fixed it for a number of AVs and prev version was also reported to MS and excluded.

**Comment by Pysis868** [comment]
> As I've said numerous times, antivirus scanners are a scam to make people feel safe. Report it to Microsoft as a false positive, report it to your vendor if that's the case, then move on until the next time they flag us.

r1951: https://www.virustotal.com/gui/file/c28d08de245ff805d15770e635d5a37cf6235185a9eca95cf7011a620af07bd6
> 2/72
> 
> Bkav Pro: W32.AIDetectMalware
> Rising: Trojan.Kryptik@AI.88 (RDML:nm1j0hZY9isbowrvH
