### ISSUE TITLE
[Request] Get WAV/WEM internal name

### ISSUE THREAD

**Issue by VanHoevenTR** [vgmstream/vgmstream#1164]
I extracted WAV a.k.a WEM audio files from The Crew 2. Some of them contains internal name in the header but vgmstream cmd/foobar2000 plugin doesn't seems to read it.

![image](https://user-images.githubusercontent.com/70694330/178782023-3bb93834-78f5-4c3b-a61f-659fd2f9feb5.png)

This is what i found in hex editor
![image](https://user-images.githubusercontent.com/70694330/178781165-25939b9a-c9c8-4d44-aef6-e26912fabf15.png)

Possible to add support for getting internal name of WAV/WEM?

Sample
[000598.zip](https://github.com/vgmstream/vgmstream/files/9104069/000598.zip)

**Comment by bnnm** [comment]
Those are metadata/cue labels rather than names (devs can and will write useless stuff like multiple "1-T112/4/4" labels that refers to some point in the song).

I think it's better handled like comments (see here: #844), but currently there is no way to print them.

**Comment by bnnm** [comment]
Closing this since it'd be handled in #844
