### ISSUE TITLE
[Bug] .wem vorbis conversion

### ISSUE THREAD

**Issue by MagicalShion** [vgmstream/vgmstream#1165]
When decoding .wems with vorbis codec the last ~200-300 samples fail to decode and contain only silence. When dealing with Elden Ring's files, where loose wems come padded with 0 bytes to align with the next multiple of 16, I saw this was not the case. Doing some further testing I found that having any amount of data after the end of the vorbis data chunk will cause the last samples to decode correctly. I tried both adding 0 bytes myself, as well as appending a smpl chunk, in the end it didn't matter what data or how much was added (a single byte was enough), but this fixed the issue. Verified this behaviour on vorbis wems from multiple games (Code Vein, Nier Replicant + Automata, Elden Ring).

**Comment by bnnm** [comment]
Thanks, should be fixed now.

**Comment by MagicalShion** [comment]
Yep, it's fixed. Thank you^^
