### ISSUE TITLE
Another observation on the SEQD section in SGD files

### ISSUE THREAD

**Issue by Nezogoku** [vgmstream/vgmstream#1168]
Just tested it out. The sequences seem to just be MIDI sequences without the header. There's a byte before each sequence that might indicate what type of sequence each one is: 0 might be SFX whereas 1 might be actual musical composition. SFX sequences seem to end each one with the Sequence Number MIDI Event (0xFF 0x00 0x00). Each sequence might have a default tick resolution of 960 pulses per quarter note.

That's all for now.

**Comment by bnnm** [comment]
Added.
