### ISSUE TITLE
Pachislot Gyakuten Saiban (パチスロ逆転裁判 encrypted HCA files

### ISSUE THREAD

**Issue by TypeBrince** [vgmstream/vgmstream#1170]
I've come across these encrypted HCA files (version 2.0 I believe) from an android pachislot game. Looking at the .so file the key seems to be the default CF222F1FE0748978 key however testing in a number of HCA decryption programs lends me only painful noise. 0x80 xored headers but the actual info seems to be correct, I'm lost as to how to get any sound out of them. Larger files have loop info and a header size of C1 and the tiny smaller ones have a header size of 60. 

Below I have provided the acb/awb and some of the extracted hcas. 

[ExampleHCAs.zip](https://github.com/vgmstream/vgmstream/files/9127011/ExampleHCAs.zip)

**Comment by bnnm** [comment]
You need to post data files (where actual key would be) and .awb/acb (you posted .hca).

**Comment by TypeBrince** [comment]
Ah apologies I thought I did, here's the .awb/acb and the .so file, I hope that's what you meant

https://drive.google.com/file/d/1L50UHpew2xDAEqTcoZ3G4sCXOXFb_qJ_/view?usp=sharing

**Comment by bnnm** [comment]
Added key: https://vgmstream.org/downloads
