### ISSUE TITLE
[Request] 64-bit build?

### ISSUE THREAD

**Issue by MainMemory** [vgmstream/vgmstream#1173]
For many years now, I have been utilizing the [bass-vgmstream](https://github.com/X-Hax/bass-vgmstream) library, which uses the BASS audio library to play audio from the vgmstream library, to incorporate robust music support for mods of various Sonic games. However, my latest project seems to have hit a snag: the game is 64-bit, while vgmstream is (seemingly) only available in 32-bit. Is there any way to get a version of the library for 64-bit Windows (x86-64 to be exact)?

**Comment by kode54** [comment]
Rebuild VGMStream and all of its dependencies as 64 bit. Building FFmpeg is a bit of a pain, because you have to find some sort of build environment. Or you can just replace it with a full version of the official FFmpeg, and carry like 50MB of overhead.

**Comment by bnnm** [comment]
Compiling 64-bit vgmstream should work, just that the DLLs are pre-compiled 32-bit since typical players are 32-bit only, Would need to recompile and tweak build files to account 32/64 modes (kinda involved), or just compile disabling those libs.

**Comment by stevefan1999-personal** [comment]
Also needed this for my internal VGMStream.Net project as well

**Comment by bnnm** [comment]
Added CLI/foobar 64: https://vgmstream.org/

Minimally tested so feel free to report any oddities.
