### ISSUE TITLE
[Help] Resident Evil 4 PS3 sound

### ISSUE THREAD

**Issue by wolfysdl** [vgmstream/vgmstream#1174]
i have tried some time extracting bio4evt4.dat.crc of resident evil 4 for ps3 and i was unable to do it, so i removed the extension .crc and .dat and i replaced the extension to .at3(Sony ps3 codec) however when it plays it´s sounds broken(plays in 0:00 and stops in 0:06 or something) and shows only one audio bank inside. i know there is more because i used some program to scan the file, i don´t remember his name right now but it show some of these waves banks stored inside of the bio4evt.dat.crc, well i extracted one to test and same thing.
PS: The header inside of the file sounds like a wave format or some kind.
sample: https://drive.google.com/file/d/13J4LWT39yHRu36wdJr1EoS6W3hO_EgfF/view?usp=sharing

**Comment by bnnm** [comment]
That bigfile is just a collection of .at3 pasted together, all should work once extracted.

Better ask in xentax/zenhax for some script to split it, or use VGMToolBox's "advanced cutter" option with the "RIFF Style Header" preset.

**Comment by wolfysdl** [comment]
> That bigfile is just a collection of .at3 pasted together, all should work once extracted.
> 
> Better ask in xentax/zenhax for some script to split it, or use VGMToolBox's "advanced cutter" option with the "RIFF Style Header" preset.

ok i will try it soon
