### ISSUE TITLE
[Bug] Most of the .ubulk music files in Live a Live (Switch) cut off way too soon

### ISSUE THREAD

**Issue by FabPhntm** [vgmstream/vgmstream#1178]
While trying to extract the audio files from Live a Live (Switch), i ran into an issue where the files containing music almost always cut off really early on, some lose a bit of the music from the cut-off, and very few work perfectly. This issue does not occur with the game's ambience and SFX audio files. Perhaps the game uses a complex looping system that prevents vgmstream from reading it correctly?

For the purposes of reading the files with foobar2000 + vgmstream, i renamed all .ubulk music files to .wem
[Sample.rar](https://mega.nz/file/lItwTQCB#ns8lPjex-0MtGlLkPqJp_z3y0oPk-EmEkqx7ClTuydI)
(WARNING: A huge chunk of the cut-offs have ear-piercing glitchy sounds... at least on my end. You probably may want to lower your volume.)

**Comment by FabPhntm** [comment]
If it helps, Live a Live remake was made in Unreal Engine v4.27

**Comment by NicknineTheEagle** [comment]
Do not simply rename .ubulk files .wem as they often contain prefetch data + main sound together (which is why vgmstream doesn't handle them properly). I'm preparing a pull request with Wwise class exporting to push to UE Viewer, in the meantime, what you can do is find the second RIFF header and cut off everything before it if one is found.

**Comment by FabPhntm** [comment]
> Do not simply rename .ubulk files .wem as they often contain prefetch data + main sound together (which is why vgmstream doesn't handle them properly). I'm preparing a pull request with Wwise class exporting to push to UE Viewer, in the meantime, what you can do is find the second RIFF header and cut off everything before it if one is found.

OOH so it was that simple!! i cut everything before 2nd RIFF header and it really worked.
thank you so very much i heavily appreciate it so much ♥♥♥
