### ISSUE TITLE
[Request] Add PSV codec / PSX HEVAG codec variant to TXTH 

### ISSUE THREAD

**Issue by swosho** [vgmstream/vgmstream#1179]
Use case: playing back raw audio ripped from sound banks.

**Comment by bnnm** [comment]
Post original sound bank and which games.

TXTH codecs should only be added *if* actually needed, so would need to see original bank to decide if  it's worth being added directly or handling with TXTH.

**Comment by swosho** [comment]
Here's a pair from Valhalla Knights 3: 
[Valhalla Knights 3 GED.zip](https://github.com/vgmstream/vgmstream/files/9229557/Valhalla.Knights.3.GED.zip)
and here's another pair from Shinobido 2:
[Shinobido 2 NSP.zip](https://github.com/vgmstream/vgmstream/files/9229558/Shinobido.2.NSP.zip)

This kind of audio is used fairly often for sound effects on Vita.

**Comment by bnnm** [comment]
Added: https://vgmstream.org/downloads/
