### ISSUE TITLE
[Bug] M2 .psb files cause Foobar2000 to crash immediately

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1180]
Like the title says, M2 PSB files cause foobar2000 to immediately crash upon loading. 

Affected version:
VGMStream (foobar2000 plugin)

Sample files are in:

1. [Sega Vintage Collection - ToeJam & Earl (2012-11-07)(M2)(Sega)[PS3].7z](http://psf3.joshw.info/s/Sega%20Vintage%20Collection%20-%20ToeJam%20&%20Earl%20(2012-11-07)(M2)(Sega)[PS3].7z)
2. [Capcom Arcade Cabinet (2013-02-19)(M2)(Capcom)[PS3].7z](http://psf3.joshw.info/c/Capcom%20Arcade%20Cabinet%20(2013-02-19)(M2)(Capcom)[PS3].7z)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/downloads

**Comment by Sukotto-1999** [comment]
So, i just updated vgmstream in foobar2000 and . . No more crashes! This bug appears when loading PSB files with .at3 files in it. Now i can play them now.
