### ISSUE TITLE
[Request] - SEGA Dreamcast .SPC Files & Other File Types

### ISSUE THREAD

**Issue by MrCurious00** [vgmstream/vgmstream#1183]
I saw a loads of .SPC files when looking around in Illbleed's game data and with the way the files are all together and next to some .ADX files, I suspect that they contain some audio, maybe related to cutscenes or something. If it is audio related, how could I go about listening to them or extracting them?

I am also wondering if anyone could help identify the other included file types as I am trying to learn more but online research has only led me so far. I'm mostly looking for audio related data and ways to play/extract them.

[Odd File Types Found (Illbleed).zip](https://github.com/vgmstream/vgmstream/files/9258357/Odd.File.Types.Found.Illbleed.zip)
.

**Comment by bnnm** [comment]
.spc looks more like some pack of graphic files to me (maybe .cgm and .pvr too are graphics)
.afs is a container of .adx (use vgmtoolbox or .bms scripts)
.sfd is a video file (try VLC)
No idea other about other files, no audio I could recognize.

**Comment by MrCurious00** [comment]
I have read that some Resident Evil games used .spc as a sound container file. I couldn't find anything at all online regarding .spc files to do with Sega Dreamcast games.

I do think that there is some kind of audio data in all of those FORM.spc files (I only submitted 1 of atleast 20 found .spc files) as the few .adx files that were also named FORM, happen to be linked to in-game audio too. I'm assuming it is cutscene related.

Come to think of it, what does .spc stand for when it comes to Sega Dreamcast?

**Comment by MrCurious00** [comment]
I accidentally clicked the wrong thing when I went to post my comment. Sorry about that.

**Comment by MrCurious00** [comment]
From what I could figure out, there was nothing audio related with the .spc files in this case. I found cutscene audio etc within the .asf files.
