### ISSUE TITLE
vgmstream.so with Audacious fails to read headers => txth issues?

### ISSUE THREAD

**Issue by nPHYN1T3** [vgmstream/vgmstream#1185]
I built vgmstream.so and added it to Audacious. It says it's playing for a moment then quickly stops or advances with no sound. I tried running Audacious with -V to get some possible errors or debug but it says nothing about failing to decode or anything...just silently faux plays the file for a few seconds then stops.

Checking in the options to configure it while it doesn't explicitly say v3 only v3 and v3.6 are the two Audacious versions mentioned in the info. I however am on Audacious v4.2 and it's not working.

***Addendum I found some files are working (sometimes/randomly) so I've revised the title and premise of the issue.

**Comment by bnnm** [comment]
Should work with any +3.6 version as long as they don't change the API. I don't see recent changes in other plugins so don't think it's that.

Make sure vgmstream and not other plugin is actually playing the file (should write "vgmstream" somewhere in the info dialog or logs) and post the file you are trying to open.

**Comment by nPHYN1T3** [comment]
I disabled the GME plugin just to make sure, loaded a few vgm files and...Error playing (path-file) The file could not be decoded. It may be invalid, corrupt or in an unsupported format. Files play fine in foobar2000 (wine)

**Comment by bnnm** [comment]
You didn't post samples like requested. I'm guessing you are trying to open a .vgm file. Those are sequenced formats that vgmstream doesn't play. Just in case I added rejection of unplayable format cleaner in audacious, can't do much more.

**Comment by nPHYN1T3** [comment]
There is a degree of trepidation around posting such files due to legalities. I posted the only debug I could gleen and I've tried several vgm files from different arcade cabinets and consoles and they play one time, then if I restart audacious they won't anymore, restart again and a few will. If they were flat out unsupported they shouldn't "randomly" play here and there.

**Comment by bnnm** [comment]
If you can't post a file then please say it so when first requested, otherwise looks like you are ignoring the efforts to help with your issue.

As said before, I improved the rejection of unplayable files. You need to update vgmstream. This would improve vgmstream hijacking .vgm in certain cases, maybe why they randomly play. `.txth` in the log is not relevant and just a type of supported file that vgmstream looks for when validating.

You comment info says "CP System, Stereo, 48kHz, 4kbit/s.". As pointed out before, info should write "vgmstream codec" somewhere. vgmstream never writes "CP System", so can't be vgmstream playing your file.

**Comment by nPHYN1T3** [comment]
Well I can post a file but that doesn't mean I won't be banned after for distributing copywritten works or something.

If vgmstream will never output the platform type then what might? I explicitly disable the gme plugin while testing so it doesn't conflict or muddy the water. Adding the file with vgmstream disabled it immediately says incompatible format so that would seem nothing else was/is feigning that it can or is playing the file.

**Comment by bxaimc** [comment]
What game is said file from?

**Comment by nPHYN1T3** [comment]
I have NG games but these are not them, the two main I have been trying are as I said, Forgotten Worlds (CP/Capcom (system1 I believe)) and Revenge of Shinobi (Genesis)

This is from the rebuild.

```
INFO adder.cc:142 [add_file]: Adding file: file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO probe.cc:89 [aud_file_find_decoder]: Probing file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm.
INFO probe-buffer.cc:30 [ProbeBuffer]: <0x7fdf7800f240> buffering enabled for file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO vfs.cc:105 [VFSFile]: <0x7fdf7800f240> open (mode r) file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO probe.cc:157 [aud_file_find_decoder]: Trying vgmstream Decoder.
INFO probe-buffer.cc:30 [ProbeBuffer]: <0x7fdf780a7ae0> buffering enabled for file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO vfs.cc:105 [VFSFile]: <0x7fdf780a7ae0> open (mode rb) file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
ERROR vfs_local.cc:120 [fopen]: pathtofile/GENESIS/12 - China Town.vgm.txth: No such file or directory
ERROR vfs_local.cc:120 [fopen]: pathtofile/GENESIS/.vgm.txth: No such file or directory
ERROR vfs_local.cc:120 [fopen]: pathtofile/GENESIS/.txth: No such file or directory
INFO probe-buffer.cc:30 [ProbeBuffer]: <0x7fdf7804fc40> buffering enabled for file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO vfs.cc:105 [VFSFile]: <0x7fdf7804fc40> open (mode rb) file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO probe-buffer.cc:50 [release_buffer]: <0x7fdf7804fc40> buffering disabled for file:///pathtofile/GENESIS/12%20-%20China%20Town.vgm
INFO probe.cc:157 [aud_file_find_decoder]: Trying AAC (Raw) Decoder.
INFO probe.cc:157 [aud_file_find_decoder]: Trying AMIDI-Plug (MIDI Player).
INFO probe.cc:157 [aud_file_find_decoder]: Trying MPG123 Plugin.
INFO probe.cc:157 [aud_file_find_decoder]: Trying OpenMPT (Module Player).
INFO probe.cc:157 [aud_file_find_decoder]: Trying WavPack Decoder.
INFO probe.cc:157 [aud_file_find_decoder]: Trying FLAC Decoder.
INFO probe.cc:157 [aud_file_find_decoder]: Trying Ogg Vorbis Decoder.
INFO probe.cc:157 [aud_file_find_decoder]: Trying FFmpeg Plugin.
INFO ffaudio-core.cc:277 [get_format_by_extension]: No format matched by extension.
INFO ffaudio-core.cc:318 [get_format_by_content]: Probe did not match any known formats.
INFO probe.cc:185 [aud_file_find_decoder]: No plugins matched.
```

**Comment by bxaimc** [comment]
Yeah dude, none of those can be played with vgmstream.

**Comment by nPHYN1T3** [comment]
I'm not trying to force it to do anything. This is more an issue of streamed and non-streamed files both using vgm as an extension and just trying to get things to play with a single application rather than needing a thousand players for each type. Sadly I guess I'll just have to stick with foobar in wine as it's the only thing that seems to have a well rounded game plugin.

**Comment by kode54** [comment]
Foobar2000 does not have one plugin that covers everything, unless you're using that kitchen sink known as zxtune.

**Comment by kode54** [comment]
I'll go ahead and refer to vgmrips.net since they're the largest collection of arcade and sometimes PC game vgm sets, which are logged from emulators. Those should be played with libvgm or vgmplay based plugins. This plugin should be rejecting such files and letting another plugin handle them.

foobar2000 is one of the only pc players that lets the user reorder input priorities. Cog for macOS has input priorities, but I hand tuned them and they're hard coded.

**Comment by nPHYN1T3** [comment]
vgrips.net is where almost all my vgm / vgz files are from. Back in the day all my Genesis files were gym (iirc) but a hard drive failure and unreadable CD/DVD backups ended that saga.

I don't use zxtune, don't need it. In fact I've never installed any format components in foobar to play all my files. All the extras were for some OS integrations and UI functions. I don't have some huge -every console- collection, just stuff I grew up with. I was the nut with the Neo-Geo and the T.G.-16 was my fav platform. Basically NES, Master System, T.G.-16, Genesis and Neo-Geo.

**Comment by kode54** [comment]
And you're likely using at least foo_input_vgm and foo_gep for those formats. Possibly some of the xSF formats as well, which would be more plugins.

**Comment by nPHYN1T3** [comment]
I never said I didn't use plugins, just that I never explicitly added them...outside the base installer. ;p That said I've been dragging the foobar install along (begrudgingly) for easily 20 years. The only things I've added outside the base installer as I said were UI stuff. foo always just played whatever I threw at it, from the nsf, to the hes and the vgm that are some times streams, some times not.

**Comment by kode54** [comment]
Except that the base installer doesn't bundle any of my plugins.
