### ISSUE TITLE
 [Bug] Incompatibility with features of PSF Decoder 2.3.1

### ISSUE THREAD

**Issue by aarontiger1** [vgmstream/vgmstream#1191]
The edit length of a psf file is removed or not available with both PSF Decoder and  vgmstream installed.

**Comment by bnnm** [comment]
Unsure what you mean but PSF works here, with and without vgmstream. Make sure you have the latest vgmstream (https://vgmstream.org/downloads/) and try changing plugin priority in *preferences > playback > decoding*.

**Comment by aarontiger1** [comment]
When you have both installed, you cant edit the length of any psf. When you right click the file in foobar and go to tagging, there is where the edit length should show up. The edit length allows to edit length of the psf shorter or longer. This command is what I am talking about not actually playing the file itself.

**Comment by kode54** [comment]
What they're saying is that when the VGMStream component is installed, the context menu command handler for PSF files does not function. And I have no idea why that would be, other than an arbitrary service limit in foobar2000 itself.

**Comment by bnnm** [comment]
Seems the psf decoder's context menu disappears when vgmstream is installed *and* declares ".psf" in the extension list. Commenting "psf" out restores the edit context menu.

On a quick glance not seeing anything off [here](https://github.com/vgmstream/vgmstream/blob/master/fb2k/foo_filetypes.h) nor in foo_psf's [code](https://gitlab.com/kode54/foo_psf/-/blob/main/psf.cpp#L1922). I guess foobar sees 2 plugins with the same extension and gives up on the context menu, or something.

Probably if you had any other plugin that declares ".psf" as the extension you'd get the same thing. I'd think context menu would be allowed if plugin is higher in the priority list, so maybe this is a foobar issue, or the context menu API in foo_psf needs to be updated?

**Comment by aarontiger1** [comment]
The issue did not exist with an old version of the psf decoder. version v2.0.38. Foobar is up to date.

**Comment by kode54** [comment]
Convenient since I don't update my foobar plugins any more. Just use the old version, nothing has changed in the emulator core in years.

**Comment by kode54** [comment]
Yeah, it's entirely my fault. I implemented crap in foo_psf and foo_input_upse to catch if multiple components claim to support "PSF" file extensions, and if so, disable most of their own functionality. Oops, that was a dumb idea. Maybe I can be motivated to actually work on Windows crap again some day and fix it.

**Comment by kode54** [comment]
Incidentally, that was a pre- foobar2000 v1.4 change, because prior versions didn't support input reordering, so you were down to the luck of the PRNG that reorders services on app startup.
