### ISSUE TITLE
Uma Musume Pretty Derby "Hca key not found"

### ISSUE THREAD

**Issue by CornalEc** [vgmstream/vgmstream#1195]
Hi, i tried to convert hca audio files from Uma musume, both version DMM (PC) and Android, but with both get the message "hca key not found" and get a big file with noises: 

https://drive.google.com/drive/folders/1CNgtIZIadUy1V3l-4qpWaFZIFmYjRrzS?usp=sharing

**Comment by bnnm** [comment]
Works correctly here. You need to play the .awb directly and not extract the .hca, and use new-ish version of vgmstream: https://vgmstream.org/downloads/

**Comment by CornalEc** [comment]
I tried to open with foobar, but get unsupported file format message :(

**Comment by bnnm** [comment]
You need to add .awb extension to the bigger files, and preferably .acb to the smaller files then rename both to the same name (to show song names), then play the .awb with foobar.

Surely the actual name of the files is saved in some helper file, so there may be a tool that renames those awb/acb, but that's beyond vgmstream's scope (try xentax/zenhax).

**Comment by CornalEc** [comment]
Thank you so much, is working now, I really appreciate your help :)
