### ISSUE TITLE
[Bug] Extensionless files no longer plays in foobar

### ISSUE THREAD

**Issue by BloodRaynare** [vgmstream/vgmstream#1196]
After updating the vgmstream's foobar plugin to 8bf07f12adb5ac133c610e8e34f2088fef188f3e yesterday, I've just noticed it today that it no longer play most of my extensionless files that I've extracted from games like Tony Hawk's series on the PS2 (This one requires TXTH file in place since it doesn't have any header, but even the TXTH file is not detected by foobar) or PS1 version of Need for Speed High Stakes (The files are basically ASF/MUS file) (The test.exe program still works fine with them though). Already checked the "Enable unknown exts" or "Enable common exts" or both in the plugin's preferences and still not working, I even tried updating the plugin and even updated the foobar itself.

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/downloads/
