### ISSUE TITLE
[Bug] .DXH loop detection is wrong, mainly in the gallop racer 2004 & 2006[PS2]

### ISSUE THREAD

**Issue by oumasanhasoushoku** [vgmstream/vgmstream#1197]
Late gallop racer (2004 and later) dxh does not work correctly.
None of the dxh in the game are consistent, and loop points appear suddenly.
Since there are many different cases, we will send all dxh's for now.

Some dxhs had audio data at the end, but the majority of the data was irrelevant, so some was removed to save weight.
But at the end there seems to be audio data.

**Comment by bnnm** [comment]
I get an 'unsupported compression' when trying to decompress it with latest 7z.

**Comment by oumasanhasoushoku** [comment]
It looks like Zstandard was the cause. Fixed.

**Comment by oumasanhasoushoku** [comment]
https://drive.google.com/file/d/1qA5vAAUAC8VDW_BMeijKIYv7-kr0LmnB/view?usp=sharing

**Comment by bnnm** [comment]
Those files weren't extracted correctly. In the bigfile, data (.str) goes first then header (.hxd), and both are separate files, so just cutting audio won't play correctly. 

I've updated vgmstream to support this and removed old hacked .dxh, here is an script to properly extract files for the US versions of Gallop Race 2004/2006, needs the executable near the bigfile:
https://github.com/bnnm/vgm-tools/blob/master/bms/tecmo_img_bd.bms
