### ISSUE TITLE
[Request] Support for .sag/.sig format [Hot Wheels Stunt Track Driver/Hot Wheels Stunt Track Driver 2: Gettin' Dirty]

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1200]
As the title says, vgmstream could not play the .sag/.sig files from HWSTD/HWSTD2GD]. At the beginning of which .sag/.sig, the first 4 letters in the header are "SLAG". DVI_IMA is for .sag, while IMA is for .sig. (open which .sag or .sig file in a hex editor for proof)

Sample files are in:

- [Hot Wheels Stunt Track Driver (1998-10-15)(Semi Logic Entertainments)(Mattel Media)[PC].7z](http://pc.joshw.info/h/Hot%20Wheels%20Stunt%20Track%20Driver%20(1998-10-15)(Semi%20Logic%20Entertainments)(Mattel%20Media)[PC].7z)
- [Hot Wheels Stunt Track Driver 2 - Gettin' Dirty (2000-09-30)(Semi Logic Entertainments)(Mattel Media)[PC].7z](http://pc.joshw.info/h/Hot%20Wheels%20Stunt%20Track%20Driver%202%20-%20Gettin'%20Dirty%20(2000-09-30)(Semi%20Logic%20Entertainments)(Mattel%20Media)[PC].7z)

(The sample files have a .txth file crafted. but the files still won't play with the .txth file)

**Comment by bnnm** [comment]
Should work now with the .txth: https://vgmstream.org/downloads/
