### ISSUE TITLE
Another Observation on SGD sequences

### ISSUE THREAD

**Issue by Nezogoku** [vgmstream/vgmstream#1203]
The sequences in SGD files use Midi Time Code. So far, I've noticed that they are in 30fps with around 196 ticks per frame. They also use the same controller event for looping as SEQ files (CC 99).

Additionally (I'm not sure if I mentioned this in any of my previous observations), in the RGND section, the byte after the one that signifies the root key of a sample is used for fine tuning.

**Comment by bnnm** [comment]
Added but best reusing this issue for further comments as doc isn't really an vgmstream issue.
