### ISSUE TITLE
EA SPORTS UEFA Champions League 06-07 xbox360 sound format .hdr/.dat

### ISSUE THREAD

**Issue by faruk1407** [vgmstream/vgmstream#1204]
Hello! First of all, Thank you for this amazing plugin which made .sbr/.sbs files readable and playable.
Looks like the xbox 360 version of Uefa Champions League 06-07 sound files cant be listened to by using vgmstream.
Ealayer3 also doesn't work. So the commentary cant be extracted at all. It looks like the game uses a codec from fifa 06-07 era but i'm not sure (adpcm_ea_r3)
The thing is, this game has some unique commentary lines and player names, which were never used on any game after this one.
On this game, .hdr and .dat files are stored seperately
Here are some sample player commentary files to explore/observe
Some of them have 1, some of them have 2 or 3 sound files inside the .dat file
https://www.mediafire.com/file/oevgchi59onlfoc/UEFA+CL+06-07+XBOX+360+SOUND+SAMPLES.rar/file

Thank you!

**Comment by NicknineTheEagle** [comment]
This is EAAC hdr/dat format, it actually consists of hdr, sth and dat. You need all 3 of those in the same folder, look for sth files, they should be in a nearby archive.

**Comment by faruk1407** [comment]
Thanks for the instant feedback.
It worked! Thank you so much
