### ISSUE TITLE
[Bug] ps2 MIB and MIH files are reconhized as Ps4 ADPCM 

### ISSUE THREAD

**Issue by wolfysdl** [vgmstream/vgmstream#1205]
Hi, my friend @OAleex have found some a weirdo bug on vgmstream that .MIB and .MIH only reconhizes As ps4 adpcm 4bit. I will send soon the samples

**Comment by wolfysdl** [comment]
[MIBMIH_Samples.zip](https://github.com/vgmstream/vgmstream/files/9365250/MIBMIH_Samples.zip)

**Comment by modusc896d352** [comment]
did some testing with these files on foobar2000 v1.6.11 (with latest version of vgmstream component installed) and it always showed as "PlayStation 4-bit ADPCM" to me.

vgmstream does not report MIH/MIB pairs as having "ps4 adpcm 4bit" or whatever, it reports them as "PlayStation 4-bit ADPCM" and only that.
