### ISSUE TITLE
[Request] Taiko no Tatsujin: Rhythm Festival (Demo) Audio

### ISSUE THREAD

**Issue by swigz27** [vgmstream/vgmstream#1206]
A demo recently released for the next Nintendo Switch Taiko no Tatsujin game, this game runs on Unity and appears to be using HCA audio encryption (as opposed to previous Unity-based instalments in the series which encrypted the entire file instead (PTB and TDMX))

Me and some people have been digging around to try and find the game's HCA key but to no avail - from what I can gather it appears to be hidden somewhere and not in `CriWareInitializer`? 

Below are some audio samples from the Demo
https://drive.google.com/file/d/1FYc64YctCu1s2H32NW79Jyr7k2paP44V/view?usp=sharing
ns2.zip contains some audio samples from the game (`jingle_map.acb` and `jingle_title.acb`) as well as `global-metadata.dat` and the game's `main` file/executable

If any more sample files are needed, please let me know

**Comment by bnnm** [comment]
Added: https://vgmstream.org/downloads/
