### ISSUE TITLE
[Bug] Decoding .hca BGM princess connect re:dive 

### ISSUE THREAD

**Issue by Kyouka79** [vgmstream/vgmstream#1209]
Please fix issue playing bgm Priconne PC/Android,  I'm only heard noise during playing

hca file: https://drive.google.com/drive/folders/1UJYnzrIhmmlEv7ZLCA2Qmwo7HOUKicO4

**Comment by kode54** [comment]
Please do not extract the HCA from the ACB/AWB files.

**Comment by Kyouka79** [comment]
Uh oke, I'll try it
