### ISSUE TITLE
[Request] Extracting Star Fox Assault / Donkey Konga .cbd .c3d .chd

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1211]
Games with this format : Star Fox Assault / Donkey Konga (I would guess Donkey Konga 2 and 3 too)

On games developed by Namco for the Gamecube, the voices and sfx are stored in a directory named "se". In this directory, there are different files with the same pattern : "label.cbd" "label.c3d" "label.chd". Opening these in an hex editor didn't help : my guess is .chd is a header and .cbd actually contains the audio.

Games in the archive : Star Fox Assault (Japanese version) / Donkey Konga (USA version)
I've included the whole directory for both games.
Download link : https://drive.google.com/file/d/1K_P0-C_v05WYplWaxP6vZgIEMdbaNIZ2/view?usp=sharing

Is it possible to extract the audio from these?

**Comment by bnnm** [comment]
Should work if you unzip this file in the folders and open the .chd: [chd-txth.zip](https://github.com/vgmstream/vgmstream/files/9410807/chd-txth.zip)


You may need to set "Enable unknown exts" option if you use foobar/winamp.

**Comment by MrShiruba** [comment]
It indeed works, thanks!
If somebody wants to know where the "Enable unknown exts" is, in foobar2000 it's in  File > Preferences > Playback > Decoding > vgmstream.
