### ISSUE TITLE
[Request] Subinterleaved .GCub format

### ISSUE THREAD

**Issue by Hexagon123** [vgmstream/vgmstream#1219]
Seen in games like Shrek Superslam (GC), Shrek the Third (Wii), and SEGA Soccer Slam (GC)

Interleave is 0x1, subinterleaved format. Soccer Slam is 0x8000 interleaved format. If mono, then it is flat.

Not a SEGA game, although being a similar format from Black Box/Shaba devs.

[samples.zip](https://github.com/vgmstream/vgmstream/files/9537183/samples.zip)

**Comment by bnnm** [comment]
Please post multiple samples.
