### ISSUE TITLE
Sonic & Sega All-Stars Racing Wii .abc file

### ISSUE THREAD

**Issue by VoviTekk** [vgmstream/vgmstream#1226]
This .abc file is a bank file, the sound files are simple Mono .dsp files, but with many sounds in it, https://drive.google.com/drive/folders/1Fs8IaKK0Of-EScEWYd-qVech_ES1wS_x?usp=sharing

**Comment by bnnm** [comment]
This format can't quite be added to with vgmstream. 
The .abc is just dsp pasted together and there are no proper ways to handle xml/text in vgmstream (too uncommon). I suggest asking in xentax/zenhax for some script, should be easy enough to split the dsp with the info in the .xml (location/length).
