### ISSUE TITLE
[Bug] LAFI Files Don't Loop

### ISSUE THREAD

**Issue by MInecrafterPictures** [vgmstream/vgmstream#1236]
I was trying using the LAFI files used by the pc version of Wall-E and no file I tried loops at all.
I use the latest Foobar2000's version of vgmstream and the plugin is set to highest priority using the latest beta of Foobar2000, I used to have a looping problem with BRSTM or BFSTM files (filenames are a bit confusing I think) until I cranked the priority all the way up.
JOE files used by the PS2 version of Wall-E also suffer from the same issue, but somehow the AT3 files used by the PSP version loop perfectly.

**Comment by NicknineTheEagle** [comment]
They don't loop because this format doesn't have loop points, the game simply loops them from start to end. You can use TXTP to apply looping if you want.
