### ISSUE TITLE
[Request] Hca key desired to be added

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1241]
OBB_Files:[グリパチ]パチスロ戦国乙女 暁の関ヶ原-DARKNESS-
　　　　　/Pachi-slot sengokuotome akatukinosekigahahara-darkness-
https://apkpure.com/%E3%82%B0%E3%83%AA%E3%83%91%E3%83%81-%E3%83%91%E3%83%81%E3%82%B9%E3%83%AD%E6%88%A6%E5%9B%BD%E4%B9%99%E5%A5%B3-%E6%9A%81%E3%81%AE%E9%96%A2%E3%83%B6%E5%8E%9F-darkness/net.commseed.gp.he145001
-------------------
OBB_Files:P戦国乙女6～暁の関ヶ原～/Pachinko sengokuotome6 akatukinosekigahahara
https://m.apkpure.com/jp/%E3%82%B0%E3%83%AA%E3%83%91%E3%83%81-p%E6%88%A6%E5%9B%BD%E4%B9%99%E5%A5%B36%EF%BD%9E%E6%9A%81%E3%81%AE%E9%96%A2%E3%83%B6%E5%8E%9F%EF%BD%9E/net.commseed.gp.he142001
It would be helpful if you could add the two hcakey points above.
Also, if possible, it would be great if you could add usmkey as well.

**Comment by bnnm** [comment]
Added key for the second game. usm key is 00000000021FF2B3

First one doesn't seem to use any CRI format (nor libraries, internally), but some kind of custom Cocos2d archive, outside of vgmstream's realm so better ask in xentax/zenhax.
