### ISSUE TITLE
[Bug] Puyo Puyo 20th Anniversary 3DS version corrupted .awb file

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1245]
Game affected : Puyo Puyo 20th Anniversary 3DS
File affected : 3DS_manzai_voice.acb and 3DS_manzai_voice.awb

Upon extracting the game there is a "sound" directory with every sound in it. The sounds are in .acb .awb pairs. Every file with the r1776 version of vgmstream for foobar2000 get the audio except for one file "3DS_manzai_voice". I don't know why it is like this because the other files work fine so it doesn't make sense to get only one file not working.
The other versions of the game don't use this .acb .awb format so I couldn't compare with these.

The contents of the "sound" directory found in the 3DS version : [link](https://drive.google.com/file/d/1Ity8b9J_-GgWwEpUxrb4hrqxI4V28xvw/view?usp=sharing)

**Comment by bnnm** [comment]
Fixed.
