### ISSUE TITLE
[Bug] .cads files still do not work directly with the latest version of vgmstream

### ISSUE THREAD

**Issue by Surihix** [vgmstream/vgmstream#1249]
The newer version of vgmstream refuses to convert the .cads files natively with the drag n drop method onto the test.exe as well as playback the audio file in foobar2000 with the component. I saw the changelog and it mentioned that cads support is added.

I tried the latest version marked with -win and with foobar2000 with the latest version vgmstream component installed to it it still shows up as unsupported file and the converter doesn't convert it at all.

Here is a sample .cads file
[file0.zip](https://github.com/vgmstream/vgmstream/files/9844728/file0.zip)

**Comment by bnnm** [comment]
Fixed.
