### ISSUE TITLE
[Request]:Android mobile game Hca key decoding

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1255]
[Request]OBB_Files:[グリパチ]パチスロ戦国乙女 暁の関ヶ原-DARKNESS- 　　　　　/Pachi-slot sengokuotome akatukinosekigahahara-darkness- https://apkpure.com/%E3%82%B0%E3%83%AA%E3%83%91%E3%83%81-%E3%83%91%E3%83%81%E3%82%B9%E3%83%AD%E6%88%A6%E5%9B%BD%E4%B9%99%E5%A5%B3-%E6%9A%81%E3%81%AE%E9%96%A2%E3%83%B6%E5%8E%9F-darkness/net.commseed.gp.he145001  OBB_Files:P戦国乙女6～暁の関ヶ原～/Pachinko sengokuotome6 akatukinosekigahahara https://m.apkpure.com/jp/%E3%82%B0%E3%83%AA%E3%83%91%E3%83%81-p%E6%88%A6%E5%9B%BD%E4%B9%99%E5%A5%B36%EF%BD%9E%E6%9A%81%E3%81%AE%E9%96%A2%E3%83%B6%E5%8E%9F%EF%BD%9E/net.commseed.gp.he142001 
It would be helpful if you could add the two hcakey only points above.

**Comment by bnnm** [comment]
https://github.com/vgmstream/vgmstream/issues/1241

**Comment by parasaite** [comment]
I'm sorry, I actually sent you an email, but you didn't respond, so I took the liberty of making an additional request here.

**Comment by parasaite** [comment]
> #1241

I'm sorry, I actually sent you an email, but you didn't respond, so I took the liberty of making an additional request here.
