### ISSUE TITLE
[Request]Extraction and decryption of files stored in encrypted archive folders

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1257]
Hello.
There is an ogg file inside, but the header is ? It seems to be encrypted.
●CRリング2-呪いの7日間-
/CR_RING2_NOROINO7NITIKAN
https://mega.nz/file/XcZhlT4T#eOi4o_GnionSxvVy5w7frtvgzGqwhKDUHU8P9YAT78o
The header seems to be encrypted here as well.
-------
Best regards

**Comment by bnnm** [comment]
That .obb is a generic file archive (like .tar or a .zip) and not something audio related.

Please don't submit those kind of requests here. vgmstream can only handle audio formats, so we can't help you extract non-audio archives (even if they may have audio somewhere inside).

Try other forums like xentax/zenhax, somebody may help you extract those generic archives.

There are also generic .OGG extractors such as VGMToolbox (misc tools > extraction tools > streams > xiph ogg extractor) that can find .ogg inside your file, if you don't mind not having filenames.
