### ISSUE TITLE
[Request] Puyo Puyo 20th Anniversary PSP - a3c file

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1258]
Games affected : Puyo Puyo 20th Anniversary PSP version but given the name other games would use it.

On this game the contents are in an archive GAME.DAT. After extracting it, the music is in .at3 format and the character voices + sfx are in .acx format. So they are all playable with vgmstream.

The problem are the story voices which are in .a3c format. They can be found [here](https://drive.google.com/file/d/13nW85dviHjYVqlA0LWlMC8tyCW6eur11/view?usp=share_link). After looking on an hex editor, it just seems to be a collection of riff audio and after using [RiffExt](https://github.com/PKBeam/RiffExt) to extract riff audio I managed to extract the audio.

So I guess implementing this format for vgmstream wouldn't be too hard. I guess implementing .a3c would be useful if anyone doesn't know how CLI works so they can use foobar2000 to extract the files.

**Comment by bnnm** [comment]
Those files are a very simple container of AT3, and seemingly only used in one game in some complex archive. Cases like this are generally handled via TXTH, unless it's clearer this format is useful elsewhere.

So, update, unzip this file in the .a3c folder and play the .a3c: [a3c.txth.zip](https://github.com/vgmstream/vgmstream/files/9964738/a3c.txth.zip)
