### ISSUE TITLE
[Request]PSP game_Tales_of_VS_JPN_PSP-Caravan game audio file playback

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1264]
PSP game_Tales_of_VS_JPN_PSP-Caravan game audio file playback
I have never seen this extension with a CHAIN file, so if anyone knows how to deal with it, please let me know.
https://mega.nz/file/SZ5lVA7b#ygOgfwRlgK7F5ouNznAoxMlDSWpCHc5B5jEybtKQkwQ

**Comment by bnnm** [comment]
Looks like a collection of at3, try some tool that extract RIFFs (like VGMToolbox > advanced cutter > RIFF style header preset, use .at3)
