### ISSUE TITLE
[Request]PSP game_Initital_D_Street_Stage_JAP_PSP-DMU game audio file playback

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1265]
PSP　game_Initital_D_Street_Stage_JAP_PSP-DMU game audio file playback
I have never seen this extension with a bin file, so if anyone knows how to deal with it, please let me know.
https://mega.nz/file/aEhzRCIZ#_UYrM9Y22QJEXuf7ZiLVCZXea8nshuMmYfFb-JrWWdE

**Comment by bnnm** [comment]
Looks like a collection of at3, try some tool that extract RIFFs (like VGMToolbox > advanced cutter > RIFF style header preset, use .at3)
