### ISSUE TITLE
[Request]PSP game_Kazoku Keikaku (Japan) (v1.01) game audio file playback

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1266]
PSP　game_Kazoku Keikaku (Japan) (v1.01) game audio file playback
I have never seen this extension with a pgd file, so if anyone knows how to deal with it, please let me know.
https://mega.nz/file/3BpEhB5S#R1CLaPRsJFScT7gHdio5hZgblcLWVWAa-TTmBhMGEJk

**Comment by bnnm** [comment]
pdg is some kind of generic PSP encrypted file, better ask in zenhax/xentax.
