### ISSUE TITLE
PSPGAME:Decrypt encrypted audio files and add keys /ahx keys

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1268]
PSPGAME:Decrypt encrypted audio files and add keys /ahx keys
PSP game_Baka_to_Test_to_Shoukanjuu_Portable_JPN game audio file playback
If you can decrypt it or add a decryption key, it would be appreciated.
-------
https://mega.nz/file/TRQzSYrI#kOnCMBHy8SeUJ8fu0jl_4Xa0cwm-_bi35tqYqOWttus

**Comment by bnnm** [comment]
Fixed.
