### ISSUE TITLE
BRSTM fixes + improvements

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1273]
this is more of a "discussion" thing than an outright bug report or feature/meta request, but as of right now i'm trying to do some "updating" around the BRSTM meta and i'm starting to think of a plan. here's what i aim to do.

- modernize brstm.c so it can keep up with recent meta additions/updates. meaning, more checks and replacing old-ish code with new, more flexible code if you will. work is already under way on this matter.
- related to the above, i've found out that BRSTM has two header modes, both of which are already supported - the "borked header" mode which was only seen on stereo BRSTM files from about two games from around the Wii's launch, and the "extended header" mode which is used in just about every Wii game imaginable. with this in mind, i decided to rewrite how vgmstream read the first bytes of an BRSTM file so it actually knows what to do with them. meaning, _atlus_shrunken_head_ is gone.
- the _spm_flag_ thing remains intact however, though almost half the code around it had been rewritten.
- the whole "read extension based on filename" and "read the file per channel" thing had also been rewritten.
- exclusive to the "extended header" mode and to the DSP ADPCM codec in particular, there's this "ADPC" chunk that was never taken advantage of. seems like it stores about two "hists" per channel, per block. one way i thought about handling this chunk would be by writing a new layout that would handle not just interleave stuff but other existing metadata from BRSTM as well, including said chunk. i haven't done anything useful with it beyond having the meta check its existence though.

thoughts?

**Comment by bnnm** [comment]
What you propose sounds ok, though note this format is widely used and changes must be carefully tested not to break anything.

**Comment by modusc896d352** [comment]
yeah, that was the plan. refresh BRSTM meta code to better support such files.
careful testing is my number one priority. i only have mono and stereo BRSTM files at the moment though, but nothing i can't handle.

**Comment by modusc896d352** [comment]
good news!

just recently i managed to make just about all the "borked header" files (that i know of) compatible with my BRSTM meta code.
as for the few "extended header" files i have, i took good care of them. they work with said code now.

bad news!

as i was writing out (and re-writing) the code for all that meta, i ended up having to make out a header file containing nothing but like two structs (one which is a typedef struct, the other which is just the struct that's used by the former) so as to make my life easier.

while doing so, i was trying to think of a layout code that took inspiration from layout interleave code while also being the "middleman" of sorts for dealing with BRSTM format stuff. i thought about making a blocked layout for BRSTM instead, but i realized that wasn't actually necessary as that format stores all its metadata from the start so i had to find another way.

except i didn't and i kinda-sorta gave up half-way through. still not done though, but i'll give this whole work a pause for the time being.

**Comment by bnnm** [comment]
It'd be strange a Nintento format (that is typically rather simple as needs to play fast in hardware) needs a custom layout.
From the info [here](http://wiibrew.org/wiki/BRSTM_file) looks like a ADPC looks like a seek table of sorts and for playback. Take a look at similar ones like bfwav.c/bfstm.c/bcstm.c too.

From your comments your code may be getting a bit too complex, keep in mind metas should be as simple and linear as possible.

**Comment by modusc896d352** [comment]
oh, similar ones. i used those as a base of reference for my BRSTM code. looking at bcstm.c, bfstm.c and bwav.c in particular helped me get a grasp of where i should go from there.

as for how complex my code currently is, well... i can't really comment on it at the moment. getting the format right is just too personal for me so i can't really show much of anything. i will try to keep the meta from being too complex though.

sorry about the late reply, i tried to find a lot of words to put this into text. took me about 1 hour and 20 minutes to do so though.

**Comment by bnnm** [comment]
Did a quick cleanup in brstm.c as to "complete" this issue, feel free to reopen if there are further developments.
