### ISSUE TITLE
[Request] Nancy Drew: Ghost Dogs of Moon Lake - .HIS, headerless .wav

### ISSUE THREAD

**Issue by fignyafsyakaya** [vgmstream/vgmstream#1275]
VGMstream seems to handle only .ogg from this game, though some of the files are in headerless .wav - they are "failed to open".

[ND - Ghost Dogs - headerless WAV.zip](https://github.com/vgmstream/vgmstream/files/10173465/ND.-.Ghost.Dogs.-.headerless.WAV.zip)

**Comment by bnnm** [comment]
Fixed: https://www.vgmstream.org/downloads/

**Comment by fignyafsyakaya** [comment]
Wow, it was resolved really quickly - way too impressive, thanks a lot. )
