### ISSUE TITLE
[Request] Takatis .sfx .trk .spc files

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1281]
Takatis is a fan-game shoot'em up inspired by Katatis which can be found [here](https://www.winterworks.de/project/takatis/) if needed.
After installing the game the sound are found in 2 directories : `Sfx` and `Speech` which are in the link below.
`Sfx` contains the sound effects in .sfx format and the music in .trk format while `Speech` contains the voices in .spc format.

The whole soundtrack is available on the website so it doesn't matter if the format isn't decrypted but for the sfx and voices seem like a sort of RIFF variant but I didn't manage to extract it.

The files can be downloaded [here](https://drive.google.com/file/d/1U16UbP_-t0Unw61VCrvU3LDvzIHdw6uU/view?usp=share_link).

**Comment by bnnm** [comment]
Those are basically obfuscated wavs. Being just a handful of samples in a single game, here are .txth for now:
[Sfx.zip](https://github.com/vgmstream/vgmstream/files/10475881/Sfx.zip)
[Speech.zip](https://github.com/vgmstream/vgmstream/files/10475882/Speech.zip)

.trk looks to me like midi + sound samples, so it's not something that vgmstream could handle.
