### ISSUE TITLE
[Request]Please add support for .fsb sound files of Ash Echos

### ISSUE THREAD

**Issue by SageU** [vgmstream/vgmstream#1282]
Games affected : 白荆回廊/ Ash Echos
Device : Android&PC game(developed by UE4 and fmod)
When I try to use vgmstream to open .bank files of Ash Echos,it didn't work,so I think it may not supported by vgmstream,and I would appreciate it so much if you can add it to your support list.
[samples of Ash Echos sound files.zip](https://github.com/vgmstream/vgmstream/files/10373492/samples.of.Ash.Echos.sound.files.zip)

**Comment by bnnm** [comment]
Added key.

**Comment by SageU** [comment]
Problem has been solved，Thankyou so much！

**Comment by tuanqf-cyber** [comment]
> Problem has been solved，Thankyou so much！

Hello, sorry for reaching out this way, but did you success in extracting all the albums from the game files?  I think the fmod>Desktop folder doesn't include all the music files in the game (global version) ? plus all the extracted data with quickbms script only made up 40+GB compare to the game data of 60+GB? I found it pretty strange.

**Comment by SageU** [comment]
> > Problem has been solved，Thankyou so much！
> 
> Hello, sorry for reaching out this way, but did you success in extracting all the albums from the game files? I think the fmod>Desktop folder doesn't include all the music files in the game (global version) ? plus all the extracted extract only made up 40+GB compare to the game data of 60+GB? I found it pretty strange.

It’s normal to only get around 40GB of files after exporting with QuickBMS. As for the music files, they can all be fully processed with vgmstream-win. You can refer to the command I used:
.\vgmstream-cli.exe -o ?n.wav -S 0 ...\Content\fmod\Desktop\bgm.assets.bank

**Comment by tuanqf-cyber** [comment]
> It’s normal to only get around 40GB of files after exporting with QuickBMS. As for the music files, they can all be fully processed with vgmstream-win. You can refer to the command I used: .\vgmstream-cli.exe -o ?n.wav -S 0 ...\Content\fmod\Desktop\bgm.assets.bank

Thank you, everything seems to be fine now.
