### ISSUE TITLE
[Request]Please add support for .acb sound files of 陰の実力者になりたくて！マスターオブガーデン

### ISSUE THREAD

**Issue by kofing1** [vgmstream/vgmstream#1283]
Games affected :  陰の実力者になりたくて！マスターオブガーデン
Device : by Unity
it not to work
[iris_adv.zip](https://github.com/vgmstream/vgmstream/files/10383774/iris_adv.zip)

**Comment by bnnm** [comment]
Added key (needs .acb extension).
