### ISSUE TITLE
[Request] DeaDBeeF plugin Support

### ISSUE THREAD

**Issue by TroubledPerson** [vgmstream/vgmstream#1284]
a very good alternative to Audacious and especially Foobar2000. Support for deadbeef would be nice.

i personally like deadbeef better as it more closely resembles Foobar2000

**Comment by bnnm** [comment]
I think it's technically doable ([ref](https://github.com/DeaDBeeF-Player/deadbeef/wiki/Developing-your-own-plugin)) and API could support vgmstream's oddities (external files, subsongs, etc). But adding a new plugin is a bunch of extra work, would be helpful telling us which OS are you using, and see if more people would be interested.

I think kode54 already did one [here](https://bitbucket.org/losnoco/deadbeef_plugins/src/master/plugins/vgm/), not sure if that's usable as is for recent versions.

**Comment by TroubledPerson** [comment]
Linux. Linux mint is my OS

**Comment by bnnm** [comment]
The original? author has been updating the plugin lately so it's probably best to let them handle this:

https://github.com/jchv/deadbeef-vgmstream
