### ISSUE TITLE
[Request] EA SWVR/RVWS - Add looping support

### ISSUE THREAD

**Issue by BloodRaynare** [vgmstream/vgmstream#1286]
At offset 0x0c there's a 4 byte value which is the starting loop of the MGAV chunk should the RWVS/SWVR audio stream already reaches it's end.

![image](https://user-images.githubusercontent.com/46045141/213628772-5424c0d6-d236-437b-a2d9-8b133f209b7e.png)

BB.STR is from NASCAR Rumble, while FE.STR is from Rumble Racing.

[SWVR_example.zip](https://github.com/vgmstream/vgmstream/files/10463543/SWVR_example.zip)

**Comment by bnnm** [comment]
Fixed: https://github.com/vgmstream/vgmstream-releases/releases/tag/nightly
