### ISSUE TITLE
[Bug] certain FMOD FSB bank files not looping correctly [Onore no Shinzuru Michi wo Yuke (PSP)]

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1287]
Like the title says, certain .fsb files (with XBOX IMA-ADPCM audio) do not loop properly when playing one of the bgm in the .fsb file with loop flag enabled.

Sample files are in:
[Onore no Shinzuru Michi wo Yuke (2009-06-11)(Silicon Studio)(From Software)[PSP].](https://psp.joshw.info/o/Onore%20no%20Shinzuru%20Michi%20wo%20Yuke%20(2009-06-11)(Silicon%20Studio)(From%20Software)[PSP].7z)

comparison:

Actual game (audio recorded on emulator):
https://drive.google.com/file/d/1iGFDZc88FvMnaAshmYlXmfGwkvsRt5mn/view?usp=share_link
Ripped data:
https://drive.google.com/file/d/1iODtL29XUCW4Di20ZGPNIQSQu0c0YSVa/view?usp=share_link

**Comment by bnnm** [comment]
This game doesn't use loop points from .fsb (that just repeat from 0 to end), and hardcodes them in the exe instead, get updated rip that uses txtp to simulate this.

**Comment by Sukotto-1999** [comment]
Okay, the loop points are entirely hardcoded in EBOOT.BIN of the game.
