### ISSUE TITLE
[Bug] VGS files from Karaoke Revolution 2 & 3 (PS2) failed

### ISSUE THREAD

**Issue by kpcenti** [vgmstream/vgmstream#1296]
I keep getting failed 
"Could not convert file: failed opening babyone.vgs" from Karaoke Revolution 2 and 3 (PS2) files

**Comment by kpcenti** [comment]
I didn't realize I could upload actual files. Here's a sample
[babyone.zip](https://github.com/vgmstream/vgmstream/files/10528466/babyone.zip)

**Comment by bnnm** [comment]
This format is a bit too simple to be detected and added in vgmstream.

In those cases we use a TXTH file to tell vgmstream how to play the format. Unzip this file in the .vgs folder, open .vgs and files should play: [txth.zip](https://github.com/vgmstream/vgmstream/files/10530916/txth.zip)

**Comment by kpcenti** [comment]
> This format is a bit too simple to be detected and added in vgmstream.
> 
> In those cases we use a TXTH file to tell vgmstream how to play the format. Unzip this file in the .vgs folder, open .vgs and files should play: [txth.zip](https://github.com/vgmstream/vgmstream/files/10530916/txth.zip)

Thanks so much! This worked perfectly. How did you come up with the info in that txth file? I'd like to know for future reference.

**Comment by bnnm** [comment]
For simple things like this basically you open file(s) with a hex editor and try to figure out. Channels is a small number so easy to pinpoint, sample rate is usually 24000/44100/48000 so plain too. PSX codec has a particular look (byte + fixed-ish byte) that is easy to see and find out interleave.
