### ISSUE TITLE
[Bug] Karaoke Revolution Presents_ American Idol Encore .PS3 file multi channel as one long track

### ISSUE THREAD

**Issue by kpcenti** [vgmstream/vgmstream#1298]
The extracted .PS3 audio files from Karaoke Revolution Presents American Idol Encore on PS3 is being treated as one long stereo track instead of 2 Stereo tracks (4 channels)

**Comment by bnnm** [comment]
You need to post samples of files that play wrong so we can take a look.

**Comment by kpcenti** [comment]
> You need to post samples of files that play wrong so we can take a look.

My mistake. I wasn't sure if that was allowed. Here's 
[w_song_glamorous_music.zip](https://github.com/vgmstream/vgmstream/files/10528464/w_song_glamorous_music.zip)
one of the files.

**Comment by bnnm** [comment]
Looks like 2 mp3 pasted together with some header, but it's nigh impossible to figure out anything non-trivial with a single file, so post a bunch of samples of various sizes preferably.

**Comment by kpcenti** [comment]
> Looks like 2 mp3 pasted together with some header, but it's nigh impossible to figure out anything non-trivial with a single file, so post a bunch of samples of various sizes preferably.

I couldn't upload the files because of size. I hope google drive is ok https://drive.google.com/file/d/1QeApnrput4-xGa0aO9vaaujw-8bBmz68/view?usp=share_link

**Comment by bnnm** [comment]
Afraid I'm not getting how the header works, may take a while.

**Comment by stknec** [comment]
You may have problems with the header because Karaoke Revolution uses four files per song, so the header may be in a separate file.
[La Bamba.zip](https://github.com/vgmstream/vgmstream/files/11066903/La.Bamba.zip)
[1000 Miles.zip](https://github.com/vgmstream/vgmstream/files/11066904/1000.Miles.zip)
[Benorig.zip](https://github.com/vgmstream/vgmstream/files/11066906/Benorig.zip)
Here are three examples. Maybe this helps a little.

**Comment by stknec** [comment]
Ok, the files I've uploaded are from the Wii Version, looks like they are different to the PS3 Version.

**Comment by bnnm** [comment]
Header in wii files looks more or less the same. If you can post same songs in different versions, that'd make it easier to compare.

**Comment by stknec** [comment]
As I said, my PS3 files look very much different than the ones from kpcenti. But here they are:
[La Bamba (PS3).zip](https://github.com/vgmstream/vgmstream/files/11072879/La.Bamba.PS3.zip)
[1000 Miles (PS3).zip](https://github.com/vgmstream/vgmstream/files/11072880/1000.Miles.PS3.zip)
[Benorig (PS3).zip](https://github.com/vgmstream/vgmstream/files/11072881/Benorig.PS3.zip)

**Comment by bnnm** [comment]
Those files look encrypted (like extracted directly from edats) and can't be used, maybe post wii versions of songs that kpcenti posted?

**Comment by stknec** [comment]
I would post wii versions but I don't have American Idol Encore for wii.

**Comment by bnnm** [comment]
Added.

First extract .ps3 or .rev files using one of included scripts for [quickbms](http://aluigi.altervista.org/quickbms.htm): [bms.zip](https://github.com/vgmstream/vgmstream/files/12907454/bms.zip) (if bratz_rev.bms fails try rev.bms). That should output `(file).wav` and `(file).wav.str` that are now playable: https://vgmstream.org. Small .ps3/rev archives seem to be metadata and don't have audio tho.
