### ISSUE TITLE
[Bug] PSP Baka_to_Test_to_Shoukanjuu_Portable

### ISSUE THREAD

**Issue by parasaite** [vgmstream/vgmstream#1305]
I have a request. I have added a key for ahx files, but when I play the audio files, I have files that don't play and have errors.
-----
https://mega.nz/file/vAh2DRyR#oO4Rs_i9F1q27WquIwyDdR1A0fym6QPcPMilTSYkihs
https://mega.nz/file/qQRiWJyJ#7muFTQMC9GpWCIIW8qPX1QhnSdWrnrmrcXhkDBSqiVg
https://mega.nz/file/PMRwEYzb#A2uqlPH-VY_CK5JrhOidhMtTTZy5nyYbubt286uM4H4

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/

**Comment by parasaite** [comment]
With the new update, ahx files that were previously playable and some files that were originally unplayable will no longer play properly as they are.

**Comment by bnnm** [comment]
Should work now.
