### ISSUE TITLE
[Req.] NINJA GAIDEN Master Collection (Sigma 2, Razor's Edge) KWB2 .XWSFILE Support 

### ISSUE THREAD

**Issue by real-guilty** [vgmstream/vgmstream#1308]
NGS2 and Razor's Edge on PC use .XWSFILE containers for audio. For both games, there is a KWB2 header at 0x50. For the Sigma 2 files, there are HB headers that I suspect could be the individual tracks, considering they are 224 bytes long and their quantities are not astronomical, (21 HBs here, 35 there, etc.). Razor's Edge is a different monster without any discernible pattern of headers. Requesting someone smarter than me to put eyes on this, solve if they can, and add to the plugin. Thank you all.

[xwsfiles.zip](https://github.com/vgmstream/vgmstream/files/10714852/xwsfiles.zip)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/

You needs to use .XWS extension though.

**Comment by real-guilty** [comment]
Thank you. Can only seem to use the CLI at the moment and it doesn't appear to pull past the first KWB2 header. The attached 31MB file has 4 KWB2 headers; and if the HB headers are any indication, there are a couple hundred files therein.

[07145.zip](https://github.com/vgmstream/vgmstream/files/10715193/07145.zip)

**Comment by bnnm** [comment]
You need to use `-s` / `-S`: https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#vgmstream-cli-command-line-decoder
