### ISSUE TITLE
[Bug] Shin'en Opus looping misaligned

### ISSUE THREAD

**Issue by PhoenixClank** [vgmstream/vgmstream#1309]
This is audibly noticeable in multiple songs, I picked Fast RMX's `alpha centauri.opus` as an example.

I have visualized the phenomenon in Audacity.
![screenshot](https://user-images.githubusercontent.com/30195074/218319668-27ed0f03-a929-43b0-929d-0d574e740648.png)
The top track is the original song (the output of `vgmstream-cli -i`), with the last 524 samples sectioned off because they aren't part of the loop ('loop end' is 524 lower than 'stream total samples').
The middle track is the looping section ('loop start' to 'loop end') copied and pasted to where it would appear in-game.
The bottom track is how vgmstream decides to loop this song (the output of `vgmstream-cli`).

AS you can see, the audio after the loop point is slightly delayed, but not by a full 524 samples.

**Comment by bnnm** [comment]
I get output like 1st+2nd track and not like the 3rd, that looks delayed (lacking encoder delay maybe?). What CLI are you using? (from vgmstream.org or self-compiled, which OS, ffmpeg version is compiled on linux, etc).

**Comment by PhoenixClank** [comment]
Interesting.

- I compiled vgmstream myself.
- I don't compile ffmpeg myself, I use my distro's package manager. When I run `ffmpeg` without arguments, it dumps the following configuration:

```
ffmpeg version n5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
```

- I'm using Arch.

**Comment by bnnm** [comment]
In theory that ffmpeg version is ok, including libopus. Check that vgmstream says `encoding: libopus Opus`. Since that's the program's (`ffmpeg`) output there could be a small chance that links to a different ffmpeg?

Also try `vgmstream-cli -i -r (file)`. That will output another file, check if there are differences. Not sure if works for Arch but if possible compare with `vgmstream-cli` from vgmstream.org (correct output here).

**Comment by PhoenixClank** [comment]
The self-compiled vgmstream says `encoding: Opus` without mentioning libopus. The two outputted files differ in that the reset one is delayed when viewed in Audacity (and zoomed pretty far in).

The downloaded vgmstream says `encoding: libopus Opus` and outputs two identical files.

Here's the beginning of the two files the self-compiled vgmstream outputs:
![screenshot](https://user-images.githubusercontent.com/30195074/219203333-3b35f878-4290-404b-8e9b-0b33cb60301d.png)

**Comment by bnnm** [comment]
Added a fix for regular opus though note libopus decoding is more accurate.

**Comment by PhoenixClank** [comment]
How do I get vgmstream (or ffmpeg, if that's where the issue lies) to use libopus?

**Comment by bnnm** [comment]
If you build via cmake ([info here](https://github.com/vgmstream/vgmstream/blob/master/doc/BUILD.md#linux)) and set BUILD_STATIC it should download and compile FFmpeg with libopus. This would result in the same file that you get from vgmstream.org though.

If you use system's installed ffmpeg libs (libav*-dev etc), it's likely just regular ffmpeg opus (probably same in arch's vgmstream [package](https://aur.archlinux.org/packages/vgmstream-git) but not familiar with that) and you'd need to fiddle a bit too much to recompile+install ffmpeg+libopus libs I think.

FFmpeg's opus was audibly buggy in lower bitrate vgm in the past so we switched to libopus, but seems good enough these days. Though PCM output +- diffs look rather big so we still use libopus just in case. Anyway the loop issue should be fixed for FFmpeg's opus with the latest commits, closing this.

**Comment by PhoenixClank** [comment]
Trying to compile with `BUILD_STATIC` fails in the very beginning because pkg-config can't find opus even though it's installed. But I think that's a ffmpeg problem, not a vgmstream problem.

Trying to compile without `BUILD_STATIC` now fails after building `vgmstream-cli` but before `vgmstream123` with the following error:

```
/bin/sh: line 1: ./autogen.sh: No such file or directory
make[2]: *** [CMakeFiles/LIBAO_AUTORECONF.dir/build.make:70: CMakeFiles/LIBAO_AUTORECONF] Error 127
make[1]: *** [CMakeFiles/Makefile2:155: CMakeFiles/LIBAO_AUTORECONF.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by bnnm** [comment]
Afraid I don't use Linux nor CMake so can't tell at a glance what could be off. If you check github's [workflow](https://github.com/vgmstream/vgmstream/blob/master/.github/workflows/cmake-lx.yml#L97) (that makes those releases) you can see commands used, maybe it's some Arch diff vs Ubuntu that makes pkg-config to fail. Also see [CMake doc ](https://github.com/vgmstream/vgmstream/blob/master/doc/CMAKE.md).

**Comment by hackyourlife** [comment]
> Trying to compile with `BUILD_STATIC` fails in the very beginning because pkg-config can't find opus even though it's installed. But I think that's a ffmpeg problem, not a vgmstream problem.

That's most likely an Archlinux problem. Aparrently `BUILD_STATIC` tries to use a system wide installation of libopus in case it finds one. On Archlinux you don't get static libraries installed, this is the reason why the config check of ffmpeg fails when it tries to compile with `-lopus -static` because there is no `libopus.a` although there is a libopus installation. If the build process would download libopus if it's not installed, you could probably try to temporarily uninstall libopus if that's possible in your situation. Otherwise you could also build the static library of libopus yourself and (temporarily?) install it in /lib, but be careful with this.

**Comment by PhoenixClank** [comment]
I pulled again and deleted the build folder and re-built everything again, and this time it worked.

I'm not sure where the error lied but now that it's gone I'd close this issue if it weren't already :)
