### ISSUE TITLE
[Bug] Trying to extract the whole audio files but instead only got one | PS2 - HX2

### ISSUE THREAD

**Issue by uzublecker** [vgmstream/vgmstream#1311]
I don't know how to explain it correctly since I'm really new with this program so perhaps I am doing something wrong. It is a file from a level of the 2003 game XIII. I just got one file instead of all in a single wav file. How can I do it? Thanks a lot.

CMD log:

```
C:\Users\Sebastian\Desktop\vgmstream-win>test -o PRock04a_hx2.wav PRock04a_hx2.hx2
decoding PRock04a_hx2.hx2
sample rate: 11025 Hz
channels: 1
stream total samples: 13804 (0:01.252 seconds)
encoding: Playstation 4-bit ADPCM
layout: interleave
metadata from: Ubisoft HXx header
bitrate: 50 kbps
stream count: 401
stream index: 1
stream name: hx/2/28a08021-83bd6136/.\Data.hos/SnipFire1
play duration: 13804 samples (0:01.252 seconds)
```

**Comment by bnnm** [comment]
Use `-S 0` and remove `-o`, also check this:
https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#subsongs
