### ISSUE TITLE
vgmstream rip everything but the music, XIII (2003) -Xbox

### ISSUE THREAD

**Issue by Gelbun** [vgmstream/vgmstream#1314]
I realized that the 'XIII' beta has unique beta music, I try to extract them with the vgmstream, the file where this is an Xbox .hxx. I used the instructions on how to use the program, which is the -S command, but it only extracts the SFX, voices, but less the music. for some strange reason try with audicity and it is possible to hear a little but static. Any solution?

As an extra piece of information, when extracting ''Todo'' the vgmstream throws this last err
![Captura de pantalla (17)](https://user-images.githubusercontent.com/125937914/220232016-bd1b757f-8bb0-438f-b2d7-578236f7b2c2.png)
or when finished; failed 121 subsongs

**Comment by bnnm** [comment]
It may be missing a resource file, that would write an error like `UBI HX: external file '[name]' not found (put together)`. Otherwise post samples.

**Comment by Gelbun** [comment]
> Es posible que falte un archivo de recursos, que escribiría un error como . De lo contrario, publique muestras.`UBI HX: external file '[name]' not found (put together)`

-----------------------------------------------------------------

I tried it with the ps2 version and it throws me the 'not found (put together)' which is a .hx2 and the Xbox version which is .hxx throws me an error that I had never gotten until now for trying it again.
![Error PS2](https://user-images.githubusercontent.com/125937914/220456218-a6b4c803-bf7c-4be3-8049-a45b20b039fe.png)
![Error Xbox](https://user-images.githubusercontent.com/125937914/220456225-0040ff12-03f4-4351-be0e-98e675a15cba.png)

**Comment by bnnm** [comment]
You need to upload files that do not work and post a link here.  We cannot help you without them.

Those files are *.hxx and (probably) *.hos

**Comment by Gelbun** [comment]
> Debe cargar archivos que no funcionen y publicar un enlace aquí. No podemos ayudarte sin ellos.
> 
> Esos archivos son *.hxx y (probablemente) *.hos

--------------------------------------------------------------------------------------------------------------------------------------------

I managed to solve the PS2 ones, but not the Xbox one, so I'll pass it on to you

https://www.mediafire.com/file/4o4bkvjyadedydf/usa02.hxx/file

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/

**Comment by Gelbun** [comment]
> Corregido: https://vgmstream.org/

--------------------------------------------------------------------------------------------------------------------------------------------

Re-download the components again? Why?

**Comment by Gelbun** [comment]
> Corregido: https://vgmstream.org/

--------------------------------------------------------------------------------------------------------------------------------------------

Thank!!!!
