### ISSUE TITLE
[Bug] Foobar2000 importing fails with NUS3AUDIO

### ISSUE THREAD

**Issue by zrksyd** [vgmstream/vgmstream#1318]
Foobar2000 importing fails when at least one entry in the NUS3AUDIO does not contain audio. Attached is a vanilla example.
[vc_kirby_copy_brave+jp_ja.zip](https://github.com/vgmstream/vgmstream/files/10832557/vc_kirby_copy_brave%2Bjp_ja.zip)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org
