### ISSUE TITLE
[Bug] - Error when trying to extract the audios of an older prototype of the XIII beta (December 16, 2002 prototype)

### ISSUE THREAD

**Issue by Gelbun** [vgmstream/vgmstream#1319]
When trying to extract the sound of a .hxx of even older Build (2002) gives this error.
![Captura de pantalla (25)](https://user-images.githubusercontent.com/125937914/222010649-cbc269d3-a882-4080-a588-2c5f346b0e38.png)

Link the files: https://www.mediafire.com/file/uzez6ueoe89bkmu/hual02.hxx/file

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org
