### ISSUE TITLE
[Request] CSB archives with AHX files inside

### ISSUE THREAD

**Issue by Quasi-Detective** [vgmstream/vgmstream#1323]
Hi. CSB archives load with the plugin if Unknown file exts is on, but files that contain AHX files rather than ADX/etc. fail to load. Here are three sample files from Yakuza: Dead Souls. BTL_AKIYAMA fails to load entirely, BTL_AMON partially loads with only certain indexes failing, and BTL_HIEN loads fine. Is it possible to get the other two files to load?
[BTL_samples.zip](https://github.com/vgmstream/vgmstream/files/10950127/BTL_samples.zip)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/

**Comment by Quasi-Detective** [comment]
Thank you!
