### ISSUE TITLE
[Request] CLI parameter for converting a complete folder

### ISSUE THREAD

**Issue by testusersample1** [vgmstream/vgmstream#1325]
I've a folder with 80k+ soundfiles which I would need to convert. What parameter should I use, I would use a batch file for everything however I'm pretty unfamiliar with windows cli.
The input and output name should be then the same, best would be if the converted files are in a different folder

**Comment by bnnm** [comment]
You'd probably have an easier time using foobar2000 + [vgmstream plugin](https://github.com/vgmstream/vgmstream#getting-vgmstream) and using the "convert" option there.

If you really want CLI you can drag and drop several files into it, but Windows has a limit (probably around 1000 files at once). You could also make a .bat file, edit and write `for %%x in (*.*) do  vgmstream-cli "%%x"`
