### ISSUE TITLE
[Bug] - Extracting the Audio content ''.uax'' from game XIII gives an error in its extraction.

### ISSUE THREAD

**Issue by Gelbun** [vgmstream/vgmstream#1332]
![Captura de pantalla (28)](https://user-images.githubusercontent.com/125937914/228437691-5745dc0c-6d93-432a-bbb8-d5ece6b00c38.png)

uax files: https://www.mediafire.com/file/5b2bsizpz4p1uk7/XIII.uax.zip/file

**Comment by bnnm** [comment]
.uax is a generic Unreal Engine 2 package that can contain any file, vgmstream can't do anything with it.

You need a .uax extractor, try umodel or asking in xentax/zenhax. Files you posted look like some list of sound files with no audio.
