### ISSUE TITLE
[Bug] Build fails with following error on Ubuntu for Audacious

### ISSUE THREAD

**Issue by Bonboon229** [vgmstream/vgmstream#1333]
coding/ffmpeg_decoder.c:742:36: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  742 |     int channels = data->codecCtx->ch_layout.nb_channels; //data->codecCtx->channels;
      |                                    ^~~~~~~~~
      |                                    channel_layout
coding/ffmpeg_decoder.c: In function ‘ffmpeg_get_channel_layout’:
coding/ffmpeg_decoder.c:984:25: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  984 |     if (data->codecCtx->ch_layout.order == AV_CHANNEL_ORDER_UNSPEC)
      |                         ^~~~~~~~~
      |                         channel_layout
coding/ffmpeg_decoder.c:984:44: error: ‘AV_CHANNEL_ORDER_UNSPEC’ undeclared (first use in this function)
  984 |     if (data->codecCtx->ch_layout.order == AV_CHANNEL_ORDER_UNSPEC)
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
coding/ffmpeg_decoder.c:984:44: note: each undeclared identifier is reported only once for each function it appears in
coding/ffmpeg_decoder.c:986:25: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  986 |     if (data->codecCtx->ch_layout.order == AV_CHANNEL_ORDER_NATIVE) {
      |                         ^~~~~~~~~
      |                         channel_layout
coding/ffmpeg_decoder.c:986:44: error: ‘AV_CHANNEL_ORDER_NATIVE’ undeclared (first use in this function)
  986 |     if (data->codecCtx->ch_layout.order == AV_CHANNEL_ORDER_NATIVE) {
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~
coding/ffmpeg_decoder.c:987:42: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
  987 |         return (uint32_t)data->codecCtx->ch_layout.u.mask;
      |                                          ^~~~~~~~~
      |                                          channel_layout
coding/ffmpeg_decoder.c: In function ‘ffmpeg_set_channel_remapping’:
coding/ffmpeg_decoder.c:1001:25: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
 1001 |     if (data->codecCtx->ch_layout.nb_channels > 32)
      |                         ^~~~~~~~~
      |                         channel_layout
coding/ffmpeg_decoder.c:1004:37: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
 1004 |     for (i = 0; i < data->codecCtx->ch_layout.nb_channels; i++) {
      |                                     ^~~~~~~~~
      |                                     channel_layout
coding/ffmpeg_decoder.c: In function ‘ffmpeg_get_channels’:
coding/ffmpeg_decoder.c:1072:28: error: ‘AVCodecContext’ has no member named ‘ch_layout’; did you mean ‘channel_layout’?
 1072 |     return data->codecCtx->ch_layout.nb_channels; //data->codecCtx->channels;
      |                            ^~~~~~~~~
      |                            channel_layout
coding/ffmpeg_decoder.c: In function ‘copy_samples’:
coding/ffmpeg_decoder.c:755:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  755 |         case AV_SAMPLE_FMT_U8P:  if (is_planar) { samples_u8p_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break; }
      |                                     ^
coding/ffmpeg_decoder.c:756:9: note: here
  756 |         case AV_SAMPLE_FMT_U8:   samples_u8_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break;
      |         ^~~~
coding/ffmpeg_decoder.c:758:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  758 |         case AV_SAMPLE_FMT_S16P: if (is_planar) { samples_s16p_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break; }
      |                                     ^
coding/ffmpeg_decoder.c:759:9: note: here
  759 |         case AV_SAMPLE_FMT_S16:  samples_s16_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break;
      |         ^~~~
coding/ffmpeg_decoder.c:761:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  761 |         case AV_SAMPLE_FMT_S32P: if (is_planar) { samples_s32p_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break; }
      |                                     ^
coding/ffmpeg_decoder.c:762:9: note: here
  762 |         case AV_SAMPLE_FMT_S32:  samples_s32_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break;
      |         ^~~~
coding/ffmpeg_decoder.c:764:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  764 |         case AV_SAMPLE_FMT_FLTP: if (is_planar) { samples_fltp_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed, data->invert_floats_set); break; }
      |                                     ^
coding/ffmpeg_decoder.c:765:9: note: here
  765 |         case AV_SAMPLE_FMT_FLT:  samples_flt_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed, data->invert_floats_set); break;
      |         ^~~~
coding/ffmpeg_decoder.c:767:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  767 |         case AV_SAMPLE_FMT_DBLP: if (is_planar) { samples_dblp_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break; }
      |                                     ^
coding/ffmpeg_decoder.c:768:9: note: here
  768 |         case AV_SAMPLE_FMT_DBL:  samples_dbl_to_s16(outbuf, ibuf, channels, samples_to_do, data->samples_consumed); break;
      |         ^~~~
coding/ffmpeg_decoder.c: In function ‘ffmpeg_get_channels’:
coding/ffmpeg_decoder.c:1073:1: warning: control reaches end of non-void function [-Wreturn-type]
 1073 | }
      | ^
make[2]: *** [Makefile.autotools:2567: coding/ffmpeg_decoder.lo] Error 1
make[2]: Leaving directory '/home/gojigoodra/vgmstream/src'
make[1]: *** [Makefile.autotools:2591: all-recursive] Error 1
make[1]: Leaving directory '/home/gojigoodra/vgmstream/src'
make: *** [Makefile.autotools:412: all-recursive] Error 1

**Comment by bnnm** [comment]
Added some tweaks but can't test it since it depends on system's installed FFmpeg version, try and see.

**Comment by Bonboon229** [comment]
Will do, and will report back with results
