### ISSUE TITLE
stereo channel bcwav files fail to open

### ISSUE THREAD

**Issue by Algorithmus** [vgmstream/vgmstream#1335]
This has been happening since this commit: https://github.com/vgmstream/vgmstream/commit/55307d393f0bb291e50295cf4ce3b59e70273e5b

I have valid bcwav files that will play correctly on the 3DS, but vgmstream still fails to load them or even recognize them.

```
vgmstream-cli -m cursor.bcwav
```

output is

```
failed opening cursor.bcwav
```

expected

```
metadata for cursor.bcwav
sample rate: 48000 Hz
channels: 2
stream total samples: 16846 (0:00.351 seconds)
encoding: Nintendo DSP 4-bit ADPCM
layout: flat
metadata from: Nintendo CWAV header
bitrate: 445 kbps
play duration: 16846 samples (0:00.351 seconds)
```

https://www.mediafire.com/file/5mrxosvl96hp7e8/cursor.bcwav/file

**Comment by Algorithmus** [comment]
We are using a fork of rstmcpp to convert wavs to bcwav files. I'm not an audio programmer, so I don't actually know what the values should look like, but I think the culprit is this line:
https://gitlab.com/beelzy/rstmcpp/-/blob/master/cwav.h#L105

It was like that in the original as well, but I don't know why. I can try to ask the original developer though.
As for the table order, it seems to be correct according to this: https://www.3dbrew.org/wiki/BCWAV.

But I found it works with vgmstream after fixing the stereo channel marker anyways. Do we require the tables to be in a specific order if it just works?

**Comment by bnnm** [comment]
I've allowed those files since real 3DS plays them (https://vgmstream.org/). Table order doesn't matter, just that real files store it differently so those custom files look a bit odd.
