### ISSUE TITLE
[Bug] Ubisoft CKD - DSP coef artifacts [Rayman Origins (Wii)

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1336]
When some CKD files are played (with a bigger byte interleave than 8 bytes), there are coef artifacts on the right channel, left channel is fine.

Sample files are in:
[Rayman Origins (2011-11-15)(Ubisoft Montpellier)(Ubisoft)[Wii].7z](https://wii.joshw.info/r/Rayman%20Origins%20(2011-11-15)(Ubisoft%20Montpellier)(Ubisoft)[Wii].7z)

How to reproduce:
Play some CKD file like 420_hud~sfx_endofmap_discoloop.wav.ckd

**Comment by bnnm** [comment]
Fixed.
