### ISSUE TITLE
[Request] Torus Games - SqueakStream audio data (RAWI/IWAR)/SqueakSample audio data

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1339]
Format Specifications:

SqueakStream .raw files are played, though needs to have a header specified. Header data for each .raw file start in a 4-letter string. RAWI is Little Endian (PC/3DS/DS), IWAR is Big Endian (X360/PS2/PS3/Wii/Wii U).
The header itself for each .raw file comes from .hnk file archives, sometimes in packfile.dat (packfile.dat filenames are all encrypted)

I don't know if this is possible without a .txth file

Codec:

PC: Little Endian 16-bit PCM/Ogg Vorbis
Xbox 360: Big Endian 16-bit PCM
PS2/PS3: Playstation 4-bit ADPCM
Nintendo Wii/3DS/Wii U: Nintendo DSP 4-bit ADPCM/Big Endian 16-bit PCM
Nintendo DS: Microsoft 4-bit IMA ADPCM/8-bit signed PCM

I unfortuanently don't know the offset anyway.

Interleave:
SqueakStream audio data is interleaved for stereo output, mono audio uses a flat layout. Interleave offset is 0x38

Sample rate:
Located at offset 0xC.

Channel:
Located at the following offsets:
0x05 (for Wii)
0x06 (for others)

Loop Offsets and Num of samples:
Loop start sample offset is: 0x10
Loop end sample offset is: 0x14
Number of samples is located at offset: 0x8

Coef offsets (for DSPADPCM):

Coef offset value is: 0x40
Coef spacing value is 0x30
Coef endianess is: LE (for 3DS)/BE (for Wii/Wii U)

Stream Name:
The header ends with a stream name which links to the correct .raw file. for IWAR, it sometimes apply as well.

Info:

Header file extension needs to have a fake extension (.hdr) which i assigned in my rips. or empty. I do not know the real header extension.

For SqueakSample audio data, Interleave is in half size. it needs to have an extension of .vgmstream as a fake extension. and a .txth file needs to be assigned to play.

Examples:

- [Rise of the Guardians (2012-11-20)(Torus)(D3 Publisher)[Wii]](https://wii.joshw.info/r/Rise%20of%20the%20Guardians%20(2012-11-20)(Torus)(D3%20Publisher)[Wii].7z)
- [Turbo - Super Stunt Squad (2013-07-16)(Torus)(D3 Publisher)[3DS]](https://3sf.joshw.info/t/Turbo%20-%20Super%20Stunt%20Squad%20(2013-07-16)(Torus)(D3%20Publisher)[3DS].7z)
- [Turbo - Super Stunt Squad (2013-07-16)(Torus)(D3 Publisher)[NDS]](https://2sf.joshw.info/t/Turbo%20-%20Super%20Stunt%20Squad%20(2013-07-16)(Torus)(D3%20Publisher)[NDS].7z)
- [Mike the Knight and the Great Gallop (2016-06-17)(Torus)(GSP)[3DS]](https://3sf.joshw.info/m/Mike%20the%20Knight%20and%20the%20Great%20Gallop%20(2016-06-17)(Torus)(GSP)[3DS].7z)
- [How to Train Your Dragon 2 (2014-06-10)(Torus)(Little Orbit)[PS3]](https://psf3.joshw.info/h/How%20to%20Train%20Your%20Dragon%202%20(2014-06-10)(Torus)(Little%20Orbit)[PS3].7z)
- [Penguins of Madagascar (2014-11-18)(Torus)(Little Orbit)[3DS].](https://3sf.joshw.info/p/Penguins%20of%20Madagascar%20(2014-11-18)(Torus)(Little%20Orbit)[3DS].7z)

**Comment by bnnm** [comment]
How are those hnk/dat files extracted? Headers seems cut, should have the string name pointing to a raw I think. It'd make more sense to read this reader and use that string to load the correct .raw, like other formats does.

As for the extension using the header ID (rawi) is preferable if extension isn't known, rather tan using a fake extension.

**Comment by Sukotto-1999** [comment]
To extract those files, use quickbms script croods_party_dat.bms or scooby_doo_swamp.bms to extract the packfile.dat, then use falling_skies.bms to extract the .dat files as .hnk data. (packfile.dat filenames are all encrypted though). Some PS2 games using the SqueakSample engine have all files stored inside packfile.dat, which was a HUGE pain to extract them.

For those files to play correctly, the header needs to be matched with the .raw file, the string should be the stream name.

the metadata name is: Torus Games SqueakStream header

**Comment by Hexagon123** [comment]
0x5 likely could be codec?

**Comment by Sukotto-1999** [comment]
Looks like i can describe the hexidecimal numbers for each codec. I can describe it now. Not needed for PC, as .raw files are same as Ogg Vorbis. Here you go.

00: Nintendo DSP ADPCM
02: Big Endian PCM
03: PlayStation ADPCM
05: Signed 8-bit PCM
09: IMA-ADPCM

**Comment by Sukotto-1999** [comment]
Okay then. Though i can find .raw strings using just a hex editor. Let's wait!

**Comment by Sukotto-1999** [comment]
And it actually turned out there was an earlier version of Squeak engine for Scooby-Doo First Frights.

**Comment by bnnm** [comment]
> Looks like i can describe the hexidecimal numbers for each codec. I can describe it now. Not needed for PC, as .raw files are same as Ogg Vorbis. Here you go.
> 
> 00: Nintendo DSP ADPCM 02: Big Endian PCM 03: PlayStation ADPCM 05: Signed 8-bit PCM 09: IMA-ADPCM

Example games using these codecs? (and ogg vorbis)

**Comment by Sukotto-1999** [comment]
Okay then, here you go.

Example game:
Rise of the Guardians (Wii/3DS): GCDSP ADPCM
Turbo Super Stunt Squad (Wii/3DS): GCDSP ADPCM
Turbo Super Stunt Squad (DS): MS_IMA
Scooby Doo and the Spooky Swamp (Wii): GCDSP ADPCM
Scooby Doo First Frights (DS): PCM8 (game uses an earlier build of Squeak engine)
Scooby Doo and the Spooky Swamp (DS): signed 8-bit PCM
Scooby Doo and the Spooky Swamp (PS2): PlayStation ADPCM
Scooby Doo First Frights (Wii): GCDSP ADPCM? (coef offsets are all different)
How to Train Your Dragon 2 (PS3): PlayStation ADPCM
Falling Skies The Game (PS3): PlayStation ADPCM
Falling Skies The Game (Xbox 360): Big Endian 16-bit PCM
Falling Skies The Game (PC): Ogg Vorbis

**Comment by bnnm** [comment]
Added regular SqueakStream (RAWI/IWAR) for all known codecs, but try a bit.

To extract pakfiles use this (same as old bms, but also identifies all .hnk):
https://github.com/bnnm/vgm-tools/blob/master/bms/torus_pak.bms

And to extract .hnk use this (by default only extracts audio, edit bms for other files):
https://github.com/bnnm/vgm-tools/blob/master/bms/torus_hnk.bms

Then put the SqueakStream headers with the .raw in one the allowed forms, for example: 
- `MUS_title_01` + `sound/4d6c7df1.raw` (typical .raw subdir)
- `MUS_title_01` + `4d6c7df1.raw`
- `MUS_title_01` + `MUS_title_01.raw` (best not to rename and use the ones above, though)

Wii titles also need the .asset files (ex. `MUS_title_01` + `MUS_title_01.asset` + `sound/4d6c7df1.raw`)

Note that older versions (Scooby Doo First Frights) and SqueakSamples don't work but probably could add later.

**Comment by Sukotto-1999** [comment]
Should be done now. I will still use .txth for old versions of vgmstream.

**Comment by bnnm** [comment]
Added SqueakSamples and old SqueakStreams since they weren't very different.

**Comment by Sukotto-1999** [comment]
Woah there, @bnnm, i have some questions: i was trying to retouch my rips of games using Squeak engine. But for Barbie games, i can't rip it easily without just sorting and looking at hex editors. Sorry. can you make a script to sort raw files with headers easily?

But wait, i forgot, Hexagon123 revealed more specification, to be worth adding. Thanks.

**Comment by bnnm** [comment]
For missing codecs/etc posted by hexagon123 better post samples.

**Comment by DaLLuZZ** [comment]
Hello, I'm not sure, but maybe this will help you
https://github.com/desuex/hunkfile/

**Comment by Sukotto-1999** [comment]
No need to, i used my existing rip to re-rip the BGM of Barbie Dreamhouse Party.

**Comment by Sukotto-1999** [comment]
Hi there @bnnm. Can you come up with a tool to make sorting easier without bothering to look at any hex editors?

**Comment by bnnm** [comment]
You could try using this: 
<https://github.com/bnnm/wwiser-utils/blob/master/scripts/vgmstream-filter.py>

If you try to open a file without .raw the log tells you which file is missing: 
<https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#logged-errors-and-unplayable-supported-files>

**Comment by Sukotto-1999** [comment]
@bnnm, i tried to use vgmstream-filter, but i can't automatically move .raw files that are besides the header outside the sound folder. any suggestions?

**Comment by bnnm** [comment]
sorry don't have anything for that. but if you move header files (you could use vgmstream-filter with >=2ch or > 5secs) and open them without sound/, the log tells you the exact .raw files missing, there shouldn't be that many for bgm.

**Comment by Sukotto-1999** [comment]
Okay. I got an idea. For easier ripping. How about making a Python script that takes the .raw files only linked to header files into a folder named "sound_moved" based on strings straight from RAWI/IWAR header files, so it'll be possible to rip without the need of looking into .raw filenames. How does that sound, @bnnm?

**Comment by TROguz** [comment]
> packfile.dat

Hi. Would you share again scripts? I can't download it. Link removed.

**Comment by TROguz** [comment]
> To extract those files, use quickbms script croods_party_dat.bms or scooby_doo_swamp.bms to extract the packfile.dat, then use falling_skies.bms to extract the .dat files as .hnk data, though some .dat files may have unusual information (packfile.dat filenames are all encrypted though). Some PS2 games using the SqueakSample engine have all files stored inside packfile.dat, which was a HUGE pain to extract them.
> 
> Besides the point, some Wii games using the SqueakSample engine (especially How to Train Your Dragon 2) do not have internal stream name at the end of some SqueakStream header files when those files are all extracted from .hnk files, that's why in my Rise of the Guardians gamerip, i cut the stream name out of the files since the header data is big endian, and then put the stream name at the start and then the external file name at the end.
> 
> Though unfortuanently, while i covered the basic structure of SqueakStream header information, i cannot find the codec offset. So i guess it's not possible without a .txth file
> 
> For those files to play correctly, the header needs to be matched with the .raw file, the string should be the stream name.
> 
> Example: MU_menu_01.hdr MU_menu_01.raw
> 
> The metadata name is: Torus Games SqueakStream header

Do you know extract packfile.dat file? I want to translate this game.

**Comment by Sukotto-1999** [comment]
Understand this repo is not for fan translation discussion.
