### ISSUE TITLE
[Bug] Atomic Heart sound banks wem files sometimes truncated

### ISSUE THREAD

**Issue by RealCosmicD** [vgmstream/vgmstream#1342]
I'm not entirely sure if this issue has to do with vgmstream itself, 

when I use the component plugin for foo and drop a .BNK to play sounds from directly directly, you sometimes see the (sound file) stream numbers with a (pre) suffix listed Those files always cut off during playback. They also don't properly extract (they throw an error). , I have to look for the unpacked .wem files (by unrealpak) via the stream number to hear them completely. What might cause this ? Am I overlooking something ?

**Comment by NicknineTheEagle** [comment]
These are "prefetch" files - truncated mirror of the real wem file that Wwise plays while the real streamed wem is loaded from disk. The actual full wem is stored outside of bnk as you have already noticed.
