### ISSUE TITLE
[Request] [New CRI HCA Key] - Love Live! School Idol Festival 2 MIRACLE LIVE

### ISSUE THREAD

**Issue by CharlieFuu69** [vgmstream/vgmstream#1343]
Guys, I don't know if I'm being annoying, but I have found the CRI HCA key for the recently released game "Love Live! SIF 2 MIRACLE LIVE".

![image](https://user-images.githubusercontent.com/77955772/232287808-054c2512-f7d7-47b6-a8c9-c3b8c218685c.png)

The key present in the MonoBehaviour `CriWareInitializer` is as follows:
```
Raw: 5067530812966687744
Hex: 0x46537c6ceb39d400
```
With VGMToolbox it went wrong, so I had to do the process manually. I'll leave it there in case you want to add it to vgmstream's list of known keys.

Thank you for your time =D

PS: Consider this key only for the Japanese version, since the global version (not released yet) might have another key.

**Comment by bnnm** [comment]
Thanks, added,
