### ISSUE TITLE
[Bug] foobar2000 x64 dlls do not get installed properly due to extraneous files

### ISSUE THREAD

**Issue by SCOTT0852** [vgmstream/vgmstream#1345]
If the component is simply installed with no further intervention, it isn't even detected in 64-bit versions of foobar2000. The DLLs must be manually moved from "user-components\foo_input_vgmstream\x64" to "user-components\foo_input_vgmstream" before it's detected and loaded. I'm not too familiar with foobar2000 component packaging, but this seems to be because of the README.md and USAGE.md being packaged into the plugin, if those are removed from the foo_input_vgmstream.fb2k-component package the 64-bit DLLs will properly copy into "user-components\foo_input_vgmstream". I believe this issue affects every version of the vgmstream foobar2000 component with 64-bit support, but I've only tested r1831 (the latest as of right now).

edit: can't seem to reproduce this fix behavior on downloads from the vgmstream.org page, only on the Github release of 1831. The automated builds will still install to the "x64" subfolder even with the README.md and USAGE.md removed, causing them to not be loaded. Not sure what the difference is.

**Comment by bnnm** [comment]
When removing the plugin data first, latest foobar 2.0 beta 34 and r1831 works for me (github or [here](https://www.foobar2000.org/components/view/foo_input_vgmstream)) and gets copied to user-components-x64/foo_input_vgmstream/* (including readmes), while nightly doesn't and copies into user-components-x64/foo_input_vgmstream/x64/* (works if manually moved to user-components-x64/foo_input_vgmstream)

However [prev nightly](https://github.com/vgmstream/vgmstream/actions/runs/4652269771) also works, and current nightly works if I unzip and rezip with no compression (.fb2k-component are just renamed zips), so I think it's just a 2.0 beta bug in that certain zips trip the plugin parser or something, and may be needed to be reported to the beta devs.

**Comment by bnnm** [comment]
No response from devs so added a workaround.
