### ISSUE TITLE
Phantasy Star Collection [Saturn] XA audio playback

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [vgmstream/vgmstream#1346]
The TXTH documentation seems to suggest that decoding audio for Phantasy Star Collection for the Sega Saturn is supported, but I can't seem to get the CLI tool or Foobar2000 plugin to playback the .ADP files included under the PS4 subdirectory of the Phantasy Star Collection CD.

Are there a particular combination of TXTH settings required to play them back? If so, does anyone know what they are?

**Comment by bnnm** [comment]
This should work [adp.zip](https://github.com/vgmstream/vgmstream/files/11326835/adp.zip) (also make sure your vgmstream version isn't really old)

**Comment by dread-pirate-johnny-spaceboots** [comment]
That did the trick, thanks for the prompt reply!
