### ISSUE TITLE
[Bug] Nintendo .THP - mono .THP artifacts

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1347]
There are still artifacts when playing mono .thp files. Could be stuttering, specifically to mono .thp in Wii games.

Sample files are in:
[Ben 10 Alien Force Vilgax Attacks (2009-10-27)(Papaya)(D3 Publisher)[Wii]](https://wii.joshw.info/b/Ben%2010%20Alien%20Force%20Vilgax%20Attacks%20(2009-10-27)(Papaya)(D3%20Publisher)[Wii].7z)

How to reproduce:
Play some mono .thp file like (mov)[unplayable] papaya.thp, which can be found in JackTheRipper's rip of Ben 10 Alien Force Vilgax Attacks

**Comment by bnnm** [comment]
Fixed.

**Comment by Sukotto-1999** [comment]
Done.
