### ISSUE TITLE
[Bug] ? New ACB/AWB files for Uma Musume files showing as "not supported or corrupted" with current VGMStream (ACBs using a newer version?)

### ISSUE THREAD

**Issue by xanek** [vgmstream/vgmstream#1348]
acb/awb files in question: https://mega.nz/folder/ewxUzB6b#xwDBYwQWMb9rPRsd0DZ_PA

Seems like in today's update for the game there are some awb files that are not playing with vgmstream via foobar and saying it is unsupported or corrupted.

There are other acb/awb files in the update that work perfectly fine, but seems like the files that are specifically BGM related are not opening anymore.

The previous update on the 18th for the game is able to play the files that have bgm perfectly fine, it's just not working for new files from today.

Edit:
Someone seems to have noticed that the ACBs are built on version 1.30 while the new ones are 1.40, if that helps at all?
https://github.com/hozuki/libcgss/issues/13

**Comment by bnnm** [comment]
All playing here. Make sure you have a recent version (https://vgmstream.org/) and other plugins aren't affecting vgmstream (see [this](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#plugin-conflicts)).

**Comment by xanek** [comment]
> All playing here. Make sure you have a recent version (https://vgmstream.org/) and other plugins aren't affecting vgmstream (see [this](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#plugin-conflicts)).

Ah I guess that was it, I was tryign to see if there was an update via foobar itself and it didn't show anything, I didn't know that I needed to goto the actual website to get an updated version.

**Comment by bnnm** [comment]
I think foobar updater will work now if you get it again from https://www.foobar2000.org/components/view/foo_input_vgmstream (there were some changes in that front) though the vgmstream.org will always have the most up to date version.
