### ISSUE TITLE
[Request] CRI HCA Key is displayed in the vgmstream output

### ISSUE THREAD

**Issue by sonicdemo** [vgmstream/vgmstream#1349]
So, CRI HCA files are encrypted in a key. Making the key displayed in the vgmstream output would make discovering some keys easier.

**Comment by bnnm** [comment]
Why do you need this? Doesn't seem very useful. 

All keys are listed [here](https://github.com/vgmstream/vgmstream/blob/master/src/meta/hca_keys.h) with example games. People that would normally use those keys would be programmers, they can print keys by changing [here](https://github.com/vgmstream/vgmstream/blob/master/src/meta/hca.c#L163) to  `vgm_asserti(hk.best_score >= 1, ...)` (for example) and recompiling.
