### ISSUE TITLE
[Request] .sli+wav support (Touhou Youyoumu: Perfect Cherry Blossom TrialPlus)

### ISSUE THREAD

**Issue by Dobby233Liu** [vgmstream/vgmstream#1350]
As noted in (the 2020-12-18 16:58 version of) [`Touhou 07 Youyoumu ~ Perfect Cherry Blossom Trial+ (2002-12-30)(Team Shanghai Alice)[PC]`](https://pc.joshw.info/t/Touhou%2007%20Youyoumu%20~%20Perfect%20Cherry%20Blossom%20Trial+%20(2002-12-30)(Team%20Shanghai%20Alice)[PC].7z) on `pc.joshw.info`, the game comes with `.sli` loop metadata files for its wav-based tracks.

```shell
$ thdat -l 7 th07md.dat
Name                Size   Stored
th07_01.mid        23291    11047
th07_02.mid        58889    16329
th07_03.mid        45995    21779
th07_04.mid        49727    18448
th07_05.mid        20695    11026
th07_06.mid       413110   122832
th07_07.mid       200654    46971
th07_01.wav.sli       38       42
th07_02.wav.sli       38       43
th07_03.wav.sli       38       43
th07_04.wav.sli       39       43
th07_05.wav.sli       38       43
th07_06.wav.sli       38       43
th07_07.wav.sli       39       42
musiccmt.txt        2678     1795
th07_0001.dat         63      546
```
[th07md.dat sli files.zip](https://github.com/vgmstream/vgmstream/files/11358671/th07md.dat.sli.files.zip)

The format of these `.sli` files corresponds with "version 1", which vgmstream already supports. However, vgmstream only looks for `.ogg.sli` and `.opus.sli` files.

**Comment by bnnm** [comment]
Works now, see https://vgmstream.org (may take some minutes to update)
