### ISSUE TITLE
[Bug]  - XIII (GameCube) - Error extracting .hxg audio files.

### ISSUE THREAD

**Issue by Gelbun** [vgmstream/vgmstream#1352]
![Captura de pantalla (34)](https://user-images.githubusercontent.com/125937914/235803639-4247ed0b-8de7-456f-a137-eb3110eb9a45.png)

Link: https://www.mediafire.com/file/nnpurfkdr5y01ws/fix.hxg/file

**Comment by Gelbun** [comment]
PS: How do I make the files have their original name instead of having the name of where they came from?

**Comment by bnnm** [comment]
Fixed. Original name is printed in the "stream name", after "internal" or external file.
(like `hx/id/guid/internal or file/name`).

**Comment by Gelbun** [comment]
> Fijo. El nombre original se imprime en el "nombre de la secuencia", después del archivo "interno" o externo. (como ).`hx/id/guid/internal or file/name`

---------------------------------------------------------------------------------------------------
Look at the screenshot, the extracted audios have the name of the file they come from, but it's a hassle to rename them manually (which would take 4 hours to give them their original names and the possibility of giving a name to an SFX that doesn't belong to it). Isn't there a command in Test.exe that can extract them with their original name?
![Captura de pantalla (35)](https://user-images.githubusercontent.com/125937914/236883181-e318fc9a-dcb1-4aa0-aabd-090ab1eb33a9.png)

**Comment by bnnm** [comment]
There is how you use the CLI: https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#vgmstream-cli-command-line-decoder

Try -o ?n.wav
