### ISSUE TITLE
[Request] Donkey Kong Barrel Blast (Wii) .WVD

### ISSUE THREAD

**Issue by Mysticus92** [vgmstream/vgmstream#1355]
Please add the .wvd file extension.
[se_grp_dnk.zip](https://github.com/vgmstream/vgmstream/files/11444100/se_grp_dnk.zip)

**Comment by bnnm** [comment]
Post multiple samples.

**Comment by Mysticus92** [comment]
[wvd files.zip](https://github.com/vgmstream/vgmstream/files/11472506/wvd.files.zip)

**Comment by bnnm** [comment]
Download the [latest vgmstream](https://vgmstream.org/), unzip this [txth.zip](https://github.com/vgmstream/vgmstream/files/11586062/txth.zip) file in the folder with all the .wvd, and play the .wvd.
