### ISSUE TITLE
[Bug] [Unsupported Format] .bars AMTA v5 is NOT supported!

### ISSUE THREAD

**Issue by PlatinumLucario** [vgmstream/vgmstream#1356]
Games that use the AMTA v5 format in .bars files (such as in The Legend of Zelda: Tears of the Kingdom), are not supported in VGMStream. Attempting to open its corresponding .bwav file will result in the following error and will refuse to open:
foobar2000
```
Unable to open item for playback (Unsupported format or corrupted file)
```
CLI
```
Unable to read
```

Some findings of the file format have been posted [here](https://github.com/TotkMods/Research/issues/2). Which myself included, have found that the .bwav is missing coefficients, compared to their previous version counterparts, because in AMTA v4, they had coefs in their DSP-ADPCM table. But this new version doesn't. So there may be some XOR-ing calculations going on in there, maybe, just a theory.

Furthermore, the .bars files are encrypted, but can be decrypted with [this tool](https://github.com/TotkMods/Totk.ZStdTool)

Steps to reproduce:
1. Unpack the romfs
2. Navigate to romfs/Sound/Resource/Stream directory
3. Open ``Dm_ED_0005.bwav`` in vgmstream.

Are there any games other than TotK that use AMTA v5? I haven't found any so far. If anyone does, please post it here!

**Comment by bnnm** [comment]
Make sure you have the lastest vgmstream from here: https://vgmstream.org/

If still doesn't work post multiple samples of bwav files that fail.

**Comment by PlatinumLucario** [comment]
Okay, it seems like it was just an outdated version of the cli, because it works on the newest version! Awesome! I can now close this.
