### ISSUE TITLE
[Bug] Zelda: Tears of the Kingdom - Unplayable BWAVs

### ISSUE THREAD

**Issue by Zen64** [vgmstream/vgmstream#1358]
Some bwavs in TotK seem to be unplayable. Trying to convert always results in `failed opening *.bwav`.

From what I understand, this seems to primarily impact memory cutscenes, at least based on filenames. This also impacts voice clips for said cutscenes, however only some of them seem to be unplayable.

I've pulled out 2 folders of samples:

- DM_ZN_0033_Stream (Voice\Resource\USen\EventFlowMsg)
This folder contains every voice clip used for memory 14. Some are playable, some not.

- Stream (Sound\Resource\Stream)
I believe all of the files here are also cutscene related. None of them convert with vgmstream.

[TotK Samples.zip](https://github.com/vgmstream/vgmstream/files/11521648/TotK.Samples.zip)

**Comment by bxaimc** [comment]
Have you tried updating [vgmstream](http://vgmstream.org)?

**Comment by Zen64** [comment]
I apologize, I guess I screwed something up on my end. I could've sworn I had just downloaded it a few days after TotK released, but I guess not.
