### ISSUE TITLE
[Request] Automatically split tracks with loop information into multiple files

### ISSUE THREAD

**Issue by SamusAranX** [vgmstream/vgmstream#1359]
I'm dealing with a directory of hundreds of converted files, some of which have loop points and some of which don't. I'm using some of them for further work in Logic Pro, which doesn't seem to make use of the smpl chunk embedded in said files.

It'd be super helpful if there was an option to automatically write the pre-loop and loop parts to two separate .wav files. I can split files after the fact using tools like sox and probably even automate it, but there's no substitute for something built-in.

**Comment by bnnm** [comment]
You can achieve it with some creativity:
```
# 0 .. loop start
vgmstream-cli.exe -l 0.0 -f 0.0 -o ?f_intro.wav Boss_ANG.adx
# loop start .. loop end
vgmstream-cli.exe -l 1.0 -f 0.0 -k -2 -o ?f_main.wav Boss_ANG.adx
```

The later is ignored it file doesn't loop, could maybe give an error instead if needed.
