### ISSUE TITLE
[Request] Nintendo DTK 4-bit ADPCM in .trk files

### ISSUE THREAD

**Issue by iGom** [vgmstream/vgmstream#1363]
Some GC games, e.g. Bloody Roar: Primal Fury store GC DTK ADPCM in .trk files, so they are playable after renaming the extension to ADP, could .trk be added to supported fil extensions?
[bgm.zip](https://github.com/vgmstream/vgmstream/files/11595322/bgm.zip)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/
