### ISSUE TITLE
[Bug] .Binka audio file from UE5 game Garten of Banban does not play

### ISSUE THREAD

**Issue by Ratiminator** [vgmstream/vgmstream#1364]
I'm not 100% sure if i should submit this as a bug report or as a feature request, but since it seems like vgmstream has support for the .binka file forma, I'm submitting as a bug report.

It seems like the BINKA audio files from Garten of Banban 1-3 does not work with vgmstream, I'm not sure if that's a problem with all of the UE5 games that use this format or if this is a specific problem with this game, as i could not find another game that used this file format.

I'm attaching a sample from the third game, if you need more, you should be extract them from the first game with no problem (It's free on steam and itch.io), or you can just @ me, though it might take me a little while to respond.

[Jumbo_Josh_1.zip](https://github.com/vgmstream/vgmstream/files/11607386/Jumbo_Josh_1.zip)

**Comment by bnnm** [comment]
Closing since this is the same as #1261, see there.
