### ISSUE TITLE
[Bug] Shift 2 Unleashed Audio Files is not now working with the latest build of the plugin

### ISSUE THREAD

**Issue by TBNRassault0030** [vgmstream/vgmstream#1365]
When I play the Shift 2 Unleashed .fsb audio files on foobar2000 with this with plugin ver. r1810, it works and plays totally fine, but when I update the plugin to the latest version (ver. r1843), foobar doesn't recognize and decode the Shift 2 Unleashed .fsb audio files.

Here is one example of those audio files:
[musicset_bravery.zip](https://github.com/vgmstream/vgmstream/files/11611874/musicset_bravery.zip)

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org

**Comment by TBNRassault0030** [comment]
It isn't fixed yet.
