### ISSUE TITLE
[Bug] Need for Speed Nitro missing part in every music file?

### ISSUE THREAD

**Issue by antoniu200** [vgmstream/vgmstream#1375]
Hello,

I am trying to extract Need for Speed Nitro's soundtrack, but I noticed that at least one song has a missing part.

Here is a sample: https://drive.google.com/drive/folders/1J2ZyPZ93a0jxIvfeTogK-AasIQfJcKPS
Hold The Line.wav is how the game plays the song, the rest are the in-game files.

Is there some part that vgmstream is not decoding or could it be that the part I am looking for is someplace else in the game filesystem? At a glance, there is no other file that should contain that part, but I may be wrong, so here is the full game filesystem: https://drive.google.com/drive/folders/1jHW8RyzKVdJvvFZv6f1WATJ96p6uwC06

Thank you!

**Comment by bnnm** [comment]
What part would be missing? (which seconds more or less)

I get 51 subsongs with the .mpf, when playing them one after (or with txtp: `nsf_sing.mpf #1~51`) sounds mostly the same vs your .wav.

**Comment by antoniu200** [comment]
Yes, that's the same thing I get. Problem is with the song's end: the game gets a slice that is not present in the 51 vgmstream decodes (have a listen at minute 2:55).

**Comment by antoniu200** [comment]
Oh my god.
I just identified the file the version of the song that I heard was stored in.
Sorry for this, it's my bad, there is most likely no bug.
