### ISSUE TITLE
[Request] TLOU BNK/STR files not playing

### ISSUE THREAD

**Issue by Xehanort88** [vgmstream/vgmstream#1378]
PC TLOU displays bnk files which can be extracted, but which don't work with vgmstream. Is this something that can be implemented or an extraction error? Please find two examples below.

[giraffe.zip](https://github.com/vgmstream/vgmstream/files/11856387/giraffe.zip)

[doors-anims-wood-aggr.zip](https://github.com/vgmstream/vgmstream/files/11856386/doors-anims-wood-aggr.zip)

Audio files are XVAG and they work out of the box (renamed).

**Comment by bnnm** [comment]
This is Sony's .bnk, but a version much higher than the ones vgmstream supports. This format is very complex so I'd need many (many) files to figure out.

**Comment by Xehanort88** [comment]
As in more bnk files? Because I can provide those. And the files referenced
in the str as well.

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Sab 24 Giu 2023, 3:02 PM bnnm ***@***.***> ha scritto:

**Comment by bnnm** [comment]
Yes more bnk files like you posted.

**Comment by Xehanort88** [comment]
Thank you. Please find more.

[foli-grass-tall.zip](https://github.com/vgmstream/vgmstream/files/11857619/foli-grass-tall.zip)
[vox-inf-bloater
[vox-inf-runner-female-b.zip](https://github.com/vgmstream/vgmstream/files/11857621/vox-inf-runner-female-b.zip)
-male-a.zip](https://github.com/vgmstream/vgmstream/files/11857620/vox-inf-bloater-male-a.zip)
[vox-inf-stalker-fema
[vox-slaver-male-c.zip](https://github.com/vgmstream/vgmstream/files/11857624/vox-slaver-male-c.zip)
le-c.zip](https://github.com/vgmstream/vgmstream/files/11857622/vox-inf-stalker-female-c.zip)

**Comment by bnnm** [comment]
Most .bnk should work now, except those named vox-* that work differently. .str are just text info.

**Comment by EdnessP** [comment]
The vox-prefixed files should now also work.
