### ISSUE TITLE
[Bug] Eragon x360 Audio Files broken

### ISSUE THREAD

**Issue by Conko** [vgmstream/vgmstream#1383]
The music files from Eragon (2006) from the PS2, PC, and xbox Versions work well with vgmstream. I can convert them to wav and foobar can play them with vgmstream.
However, the files from the xbox 360 Version do not work, I can play them but they are very broken. They are interesting because the xbox 360 Version does contain a few unique version specific songs.

Interestingly, I can easily drag the x360 audio files into audacity, where they can be played correctly, it tells me its "Stereo, 44100Hz, 32-bit float". The PS2 files dont easily work with audacity on the other hand.
The PS2 songs are "Playstation 4-bit ADPCM | 404 kbps | 44100 Hz | stereo" according to foobar.

I attached a zip file with 4 files. Its 2 different songs from the x360 and ps2 versions.

[eragon samples.zip](https://github.com/vgmstream/vgmstream/files/11887471/eragon.samples.zip)

**Comment by bnnm** [comment]
Should work now.

**Comment by Conko** [comment]
Works perfectly with the nightly build, thank you so much @bnnm ! 😀
