### ISSUE TITLE
[Request] Colors (Gizmondo) ISA support

### ISSUE THREAD

**Issue by childishbeat** [vgmstream/vgmstream#1384]
This is a container for multiple WAV files. The game uses multiple ISA files to sort them into different categories, including one for most of the soundtrack.

It starts with a header consisting of 01 00 00 00 in hex, followed by a list of internal categories, consisting of xx xx xx 00 (I can't discern xx xx xx, but I initially thought the third byte was the number of files in the category), a name and 3A. The rest of the file consists of WAV files, as well as some extra characters I also can't discern.

Here is a variety of ISA files from the game:
- [sound_door.isa](https://github.com/vgmstream/vgmstream/files/11888161/sound_door.zip) - Consists of single-file categories.
- [sound_foot.isa](https://github.com/vgmstream/vgmstream/files/11888162/sound_foot.zip) - Consists of multi-file categories.
- [sound_music.isa](https://github.com/vgmstream/vgmstream/files/11888163/sound_music.zip) - Added in case there's flags for looping.
- [sound_voice.isa](https://github.com/vgmstream/vgmstream/files/11888164/sound_voice.zip) - Consists of both single-file and multi-file categories.

**Comment by bnnm** [comment]
It looks more like a generic container than a sound bank, not very suited to vgmstream and too complex for TXTH. I made a quick .py to extract those wavs instead: [isa.zip](https://github.com/vgmstream/vgmstream/files/11900032/isa.zip)

**Comment by childishbeat** [comment]
Thanks for the script! I had used Mediaextract, which didn't extract names (unlike your script), and only renamed a few small clusters of sound_voice.isa because it was a real pain to get through. Other than that, everything else was alright.
