### ISSUE TITLE
[Request] [New CRI HCA Key] Tower of Sky

### ISSUE THREAD

**Issue by justincys** [vgmstream/vgmstream#1389]
I found the HCA key for a Japanese Android game called [Tower of Sky](https://play.google.com/store/apps/details?id=com.mixi.tower&hl=en_US). Note that I tested this with version 1.2.0 of the game.
```
Raw: 5893902754391672
Hex: 0014F0792C042678
```
[.hcakey.zip](https://github.com/vgmstream/vgmstream/files/11990928/default.hcakey.zip)

**Comment by bnnm** [comment]
Added, thanks.
