### ISSUE TITLE
[Request] GameCube High Voltage .GMD

### ISSUE THREAD

**Issue by Hexagon123** [vgmstream/vgmstream#1395]
Looks like a audio file container that might be extracted or to be played format?

Structure:
0x20 and 0x24 have number of songs
0x30-0xE4 - Total song header?
0x44 - First of left song file header
0xA4 - First of left song file offset
0xA8 - First of right song file header
0x108 - First of right song file offset
0x10c - Data size of first song file

Only a few games that had seen in
- Zathura (2005, PS2/Xbox, as unused mspacelp.GMD)
- Codename - Kids Next Door - Operation V.I.D.E.O.G.A.M.E. (2005, GC)
- Grim Adventures of Billy & Mandy, The (2006, GC)
- Charlie and the Chocolate Factory (2005, GC)
[highvoltage_gc_samples.zip](https://github.com/vgmstream/vgmstream/files/12008687/highvoltage_gc_samples.zip)

**Comment by bnnm** [comment]
Use this TXTH (unzip in the same folder, open .GMD files): [GMD.txth.zip](https://github.com/vgmstream/vgmstream/files/12445824/GMD.txth.zip)
