### ISSUE TITLE
[Request] Failed opening .bank files in netease nshm. New version of FMOD bank?

### ISSUE THREAD

**Issue by happyme531** [vgmstream/vgmstream#1403]
When I am trying to use the latest vgmstream to extract the .bank file from the game  "Netease NiShuiHan Mobile(逆水寒手游,nshm)" it just fails:

```log
.\vgmstream-cli.exe -m D:\Downloads\common_instrument_baidicheng.assets.bank
failed opening D:\Downloads\common_instrument_baidicheng.assets.bank

.\vgmstream-cli.exe -o e.wav D:\Downloads\common_instrument_baidicheng.assets.bank
failed opening D:\Downloads\common_instrument_baidicheng.assets.bank
```

These files all have .bank extension and a "RIFF FEV FMT" header, so it could be a new version of some FMOD format currently not supported by vgmstream.

Tried python-fsb5 and https://github.com/Vextil/Wwise-Unpacker, also not working.

Some samples: 
[samples.zip](https://github.com/vgmstream/vgmstream/files/12334535/samples.zip)
If not enough, just ask me for more. 

(These assets is obtained by installing the android version of the game from https://h.163.com, after the asset is downloaded go to 
Android/data/com.netease.nshm/files/patch/rawfiles/High/AssetsExtra/FMODAssets/mobile to see them. For PC version they bundled all assets into some huge files so don't use this.)

**Comment by bnnm** [comment]
Added missing decryption key (and a log mentioning that when it fails): https://vgmstream.org

**Comment by happyme531** [comment]
Works perfectly, huge thanks!
