### ISSUE TITLE
[Request] .pck for Genshin & Star Rail format support.

### ISSUE THREAD

**Issue by Devyatyi9** [vgmstream/vgmstream#1416]
The first 4 bytes always have the `AKPK` signature, the .pck container contains `RIFF WAVEfmt` files. 

Games affected:
- Genshin Impact
- Honkai: Star Rail
- Honkai Impact 3rd

Screenshots from hex editor
https://github.com/vgmstream/vgmstream/assets/5161472/82594e1c-c8d8-43e4-9198-434a20a30c0d
https://github.com/vgmstream/vgmstream/assets/5161472/ba2a424f-d9c0-4a4a-b7d7-b831696944e4
quickbms script:
[wavescan.zip](https://github.com/vgmstream/vgmstream/files/12570523/wavescan.zip)

Files for example:
https://drive.google.com/drive/folders/16_Ss4-MM1Rd2ZBfBjf-72Ui3XRhRYfoy
[Minimum.zip](https://github.com/vgmstream/vgmstream/files/12570106/Minimum.zip)
[External0.zip](https://github.com/vgmstream/vgmstream/files/12570171/External0.zip)
[Banks25.zip](https://github.com/vgmstream/vgmstream/files/12570176/Banks25.zip)

Programs that read and convert this format:
https://github.com/dvingerh/genshin-audio-exporter
https://github.com/paimoooon/HoYo-New-Music-Extractor
https://github.com/alexpado/hoyoverse-music-unpacker

**Comment by NicknineTheEagle** [comment]
Wwise PCK is not a sound bank format. Use this QuickBMS script to extract it: https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms

**Comment by bnnm** [comment]
.pck is basically a virtual filesystem so it's not really a good case to add to vgmstream, so best use the above BMS script.

You can also use this tool with the extracted bnk/wem: [wwiser](https://github.com/bnnm/wwiser).

**Comment by Devyatyi9** [comment]
So there is no way to add support for foobar2000 or other players?

**Comment by NicknineTheEagle** [comment]
Why do you insist on adding support to foobar2000 for this format? You were told twice that pck is a VFS format not a sound bank. You're not supposed to toss such formats into audio players, you want to extract them to get the audio files inside.
