### ISSUE TITLE
[Request] XMPlay plugin extension list size limit removal

### ISSUE THREAD

**Issue by KelticDanor** [vgmstream/vgmstream#1418]
I'm unsure if it has been reported but there was a recent change to XMPlay which removes the 1000 character limitation on the list of extensions supported by the plugin.

The issue was reported on this thread on the Un4seen forum: https://www.un4seen.com/forum/?topic=20202.msg141285
A new version which supports the larger extension list is available here: https://www.un4seen.com/stuff/xmplay.exe

As per the forum post it makes reference that the limit to the extension list in the following file is no longer applicable so it can be opened up again. It is only with the recent XMPlay versions however so perhaps it will need a version check change if that is available.
https://github.com/vgmstream/vgmstream/blob/883d796d4b63c42810586e9f1ffbdcdd28c73ef5/xmplay/xmp_vgmstream.c#L33

Cheers! 👍

**Comment by bnnm** [comment]
Thanks, fixed.
