### ISSUE TITLE
[Request] HCA Keys Rune Factory 3 Special (Nintendo Switch & PC Steam)

### ISSUE THREAD

**Issue by RenBou10** [vgmstream/vgmstream#1422]
Please Update hca_keys.h With Rune Factory 3 Special (Nintendo Switch & PC Steam), Thanks..

**Comment by bnnm** [comment]
You need to post the exe/main and some acb/awb samples.

**Comment by RenBou10** [comment]
> You need to post the exe/main and some acb/awb samples.

Like This? https://drive.google.com/file/d/1PzQmBjkFkKoYhVuJejPCeXxQo8QY9fbd/view?usp=sharing

**Comment by bnnm** [comment]
Those are acb/awb samples. Also needs exe/main.

For unity games, this generally means GameAssembly.dll, global-metada.dat and files like level0/level1

**Comment by RenBou10** [comment]
> Those are acb/awb samples. Also needs exe/main.
> 
> For unity games, this generally means GameAssembly.dll, global-metada.dat and files like level0/level1

Ah, So Other Files Needed is This ? : https://drive.google.com/file/d/1SUqjwGd2dsEwFW5YuNpIBIFMd41EjMip/view?usp=sharing

**Comment by bnnm** [comment]
The files aren't actually encrypted and don't need any key.

You need to rename them to `.acb(text)` to `.acb` and `.awb(text)` to `.awb`.

(you can do that from the command line, or making a `rename.bat` file and writting this text inside, then opening it)
```
ren *.awb* *.awb
ren *.acb* *.acb
```

**Comment by RenBou10** [comment]
> The files aren't actually encrypted and don't need any key.
> 
> You need to rename them to `.acb(text)` to `.acb` and `.awb(text)` to `.awb`.
> 
> (you can do that from the command line, or making a `rename.bat` file and writting this text inside, then opening it)
> 
> ```
> ren *.awb* *.awb
> ren *.acb* *.acb
> ```

So the Game Are not Encrypted, I Think The Keys Needed For This Game Because Actually I Just Want To Repack .usm, but Always Failed, The Game Always Skiping into Main Menu.. Anyway Thanks!
