### ISSUE TITLE
[Bug] Taz: Wanted PC Music (.str+.wav) distortion (Blitz Games 4-bit IMA ADPCM)

### ISSUE THREAD

**Issue by MilkGames** [vgmstream/vgmstream#1423]
Here is what happens after decrypting .str+.wav files:
- If .str file contains 3 tracks, it's labeled as 3-channel, although it should be 6-channel. Also, the sound is horribly distorted after decryption.
- If there is only 1 track in .str file, it's labeled as 1-channel, although it should be 2-channel.
Link to examples and output: https://drive.google.com/file/d/109kDJg2gez0dFQZVM4iXpQK1Yi-GwesQ/view?usp=sharing

I also need a little help with these things:
- After decrypting (this thing happens even for Taz: Wanted PS2/Xbox/GCN music) via foobar rather than vgmstream web/win I get multiple loops at the same time, how can I avoid this?
- Is it possible to split these 3 tracks directly in vgmstream or foobar without using third party programs like Audacity or Vegas Pro?

**Comment by bnnm** [comment]
Fixed multitracks. I only see data for 1 channel though, so can't play as 2ch/6ch.

Not sure what you mean 'multiple loop at the same time' but you can disable looping in foobar's vgmstream config, and setting flags in vgmstream-cli

You can tell vgmstream which channels you want by making a `(name).txtp` file with these commands: https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md#channel-removingmasking-for-channel-subsongslayers (example: `ninja normal loop.wav.str #C2`)

Also note that converting a compressed music file to wav is called "decoding", while "decrypting" is for other data transformations.
