### ISSUE TITLE
[Request]“GIRLS' FRONTLINE 2:EXILIUM” audio files

### ISSUE THREAD

**Issue by lingmiao1** [vgmstream/vgmstream#1426]
the audio file is in "GW_Build_1364\assets\AssetBundles_Android\Assets\ArtsResource\Audio\CriWare"
pc is in "GF2Exilium\GF2 Game\GF2_Exilium_Data\LocalCache\Data\AssetBundles_Windows\Assets\ArtsResource\Audio\CriWare"
The correct hca key may be required. Please update hca_keys.h. thanks
game pc :[GIRLS' FRONTLINE 2:EXILIUM](https://gf2-cn.cdn.sunborngame.com/download/launcher/GF2Exilium_Setup.exe)
apk : [Android](https://gf2-cn.cdn.sunborngame.com/download/apk/GW_Build_1364.apk)

**Comment by broli95** [comment]
Check this repo: https://github.com/66hh/GF2Decrypter

Tested and can confirm that it works

**Comment by lingmiao1** [comment]
> Check this repo: https://github.com/66hh/GF2Decrypter
> 
> Tested and can confirm that it works
> 
> This is the key btw: "8930254087621254"

how to use it?

**Comment by bnnm** [comment]
Added.
