### ISSUE TITLE
[Request] Rubik's World Wiive files

### ISSUE THREAD

**Issue by BLiNXthetimesweeperGOD** [vgmstream/vgmstream#1427]
Rubik's World on the Wii uses a seemingly custom (yet uncompressed) audio format. The channels appear to be stored in 0.5-1 second chunks instead of being every other sample like a WAV file.
[wiive.zip](https://github.com/vgmstream/vgmstream/files/12765530/wiive.zip)

**Comment by bnnm** [comment]
Get [latest](vgmstream.org/), unzip this txth in the folder and files should be playable: [txth.zip](https://github.com/vgmstream/vgmstream/files/12775447/txth.zip)

`.wiive.txth`
```
codec = PCM16BE
channels = @0x00
sample_rate = @0x04
#08: bps
#0c: ?
interleave = @0x10  * channels
num_samples = @0x14
start_offset = 0x18
```
