### ISSUE TITLE
[Request] Fate/Samurai Remnant SRSA/Koei .ktsl2stbin KTSR update needed

### ISSUE THREAD

**Issue by MaxAkito** [vgmstream/vgmstream#1430]
Format for Koei's KTSR format has seemingly changed with Fate/Samurai Remnant, as vgmstream is no longer able to read the files with the .srsa wrapper removed.

I have provided a few samples converted to .ktsl2stbin along with their untouched .srsa wrapper version.
https://drive.google.com/drive/folders/1z4qunQabn_4XSmvmyMnp4XL3CTMgcENZ?usp=sharing

Seeing as how Koei keeps their formats rather consistent this will also most likely apply to their future games too, it may already apply to the game "Wild Hearts", but I do not own it to check it's files.

**Comment by bnnm** [comment]
Fixed, also added .srsa
