### ISSUE TITLE
[Request] adding VGM/vgmstream support to Mixxx

### ISSUE THREAD

**Issue by ghost** [vgmstream/vgmstream#1436]
HI

Are you interested in adding VGM/vgmstream support to Mixxx?

https://github.com/mixxxdj/mixxx/issues/12122

**Comment by bxaimc** [comment]
Hi, adding any type of support to another project would be the responsibility of the maintainers of said project. It's up to them if they'd want to incorporate whatever code or functionality that would make whatever you're seeking for possible. Our scope is only maintaining the vgmstream repo with adding/modifying support and addressing issues for said repo.
