### ISSUE TITLE
[Request] Valve .vsnd_c format

### ISSUE THREAD

**Issue by makefilex** [vgmstream/vgmstream#1437]
games that use this format:
Half-Life Alyx (?)
Counter-Strike 2
Aperture Desk Job
and probably every game made with Source 2 (like s&box)

codecs i found:
PCM (Little Endian 16-bit)
MP3

header info:

- first 16 bytes
0x00 header size (includes the filetype header)
0x04 version?
0x06 file type
0x08 8?
0x0c total chunks?

- RED2 header
idk, compiler info or sort of?

- audio (or filetype) header (skipping via the offset next to DATA)
0x00 sample rate
0x02 codec
0x03 channels
0x04 unknown (loop points goes here?)
0x08 total samples
0x0c crc32?
0x10 to 0x1c (nothing, something goes here?)
0x1c data size
0x20 to 0x30 (nothing)

Notes:
- the examples are from Counter-Strike 2 (i currently don't own a VR headset for HL Alyx, but i figure it out)
- since each _c file starts the same (16 bytes, RED2), i added some stuff
- although, i doubt Valve uses the same formats that supports the Miles Sound Engine from the Source engine, i have thoughts that Valve adds other codecs (like vorbis or opus) to this format
- i made a working TXTH for this format, PCM plays correctly, and also MP3 (broken but FFmpeg can parse well)

https://drive.google.com/drive/folders/1qu2ywX1m8hKvvhaCW5utk-UzqVrVcLNa?usp=share_link

**Comment by bnnm** [comment]
How were those files extracted? They look like some engine serialization rather than actual formats (like Unity bundles or Unreal Engine objects nodes). If it's like the later, would make more sense to extract the actual sound/etc data inside.

**Comment by makefilex** [comment]
extracted with GCFscape, CS2 uses .vpk

**Comment by makefilex** [comment]
I decided to close this issue, because i found out that there's a decompiler for .*_c files "https://valveresourceformat.github.io/" , and that is exactly how did you say it.

It looks like Valve decided to use the same vpk format used in Source for Source 2, with the main difference being that includes compiled serialization or nodes.
apologies if it bothers you that. and also my awful english
Thanks
