### ISSUE TITLE
[Bug] unsupported psb file (METAL GEAR SOLID: MASTER COLLECTION Vol. 1 [Switch])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1438]
vgmstream, as of the latest update, does not support this one particular **se.psb** file despite said file having nothing but sounds in it.
[alldata_201_sound_se-psb.zip](https://files.catbox.moe/6c93g1.zip) <-- weighs in at 27.2MB

compare that to the *other* **se.psb** file which is this one.
[alldata_system_sound_se-psb.zip](https://files.catbox.moe/hugcoa.zip) <-- weighs in at *just* 1.08MB

the latter can be played back no problems through foobar2000 if vgmstream component is already installed.
this is as far as i can manage on the *multiple samples* part.

**Comment by bnnm** [comment]
Fixed.
