### ISSUE TITLE
[Bug] unsupported nub2 file (Noby Noby Boy [iOS])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1439]
vgmstream, as of the latest version, cannot support this one nub2 file.
[SE_BANK-nub2.zip](https://files.catbox.moe/vzi3s4.zip) <-- weighs in at 2.51MB

please note that this is the *only* nub2 file in the entire game. yes. i mean the iOS version of Noby Noby Boy.
meaning i could not corroborate multiple nub2 files for this one because there were no such files to be found beyond the above. sorry.

**Comment by bnnm** [comment]
Fixed.
