### ISSUE TITLE
[Request] 2sf/mini2sf Format (Nintendo DS)

### ISSUE THREAD

**Issue by Clozent** [vgmstream/vgmstream#1441]
This is a format used by some Nintendo DS titles. There seem to be at least two versions:

1. `.mini2sf` - seems to use a library file.
2. `.2sf` - much less used, might be self-contained.

### Some games using `.mini2sf`:

- Pokemon Heart Gold & Soul Silver
- Pokemon Diamond
- Plants vs. Zombies
- Mario Kart DS
- Animal Crossing - Wild World

While each track has it's own `.mini2sf` file, it seems like these files only contain metadata, such as tags, while the actual music seems to be located in one or multiple `.2sflib` file.

### Some games using `2sf`:

Note: I found that some games have `.2sflib` files despite others not having them. Perhaps the `2sf` format is not self contained, and my source for the music lacks some files...

- Sonic Rush Adventure (Also uses `.strm` and `.2sflib` files)
- Englisch Buddy (only has one `.2sf` file, with the rest being `.strm`)

**Comment by citrusui** [comment]
2SF is a sequenced format, not streamed. I don't see this ever being added to vgmstream.

You are probably looking for the [2SF Decoder](https://www.foobar2000.org/components/view/foo_input_vio2sf) plugin for foobar2000. This lets you play and export .mini2sf tracks into WAV or FLAC.
