### ISSUE TITLE
[Request]AutoNavi (.dyaudio)

### ISSUE THREAD

**Issue by WM86** [vgmstream/vgmstream#1445]
After looking at the file I found that it should be opu encoded wav audio, but the usual way to read it directly is not possible, this is the file I grabbed.
[skit.zip](https://github.com/vgmstream/vgmstream/files/13202944/skit.zip)
[weilandangan_ds.zip](https://github.com/vgmstream/vgmstream/files/13202946/weilandangan_ds.zip)

**Comment by bnnm** [comment]
Please elaborate on what this is from and how were those files are extracted. Doesn't seem related to VGM?

**Comment by WM86** [comment]
The file was extracted from APP:AutoNavi and is the navigation voice file (this is the navigation voice with the game company).
I got the original audio file using fiddler (couldn't find where this file was unpacked in the APP folder)
