### ISSUE TITLE
[Request] Dead Space 1, 2 and 3 (Legacy) Audio Formats

### ISSUE THREAD

**Issue by MaZT3Rz** [vgmstream/vgmstream#1446]
I doubt the support exists yet, so I was wondering if the audio formats from the 2008 Dead Space, 2011 Dead Space 2 and 2013 Dead Space 3 could be added here. I have all of the audio tools on my computer which I got years back from the now-dead Xentax if it helps with reverse-engineering. I'm making a thread to ResHax forum about this too.

Edit: Here are all of the audio format tools:
https://reshax.com/topic/149-dead-space-legacy-2008-2013-audio-tools/

**Comment by bnnm** [comment]
All EA formats should be supported if properly extracted (snu/spr/sps/etc), otherwise post samples that don't work.
