### ISSUE TITLE
[Request] Scan unknown files for headers?

### ISSUE THREAD

**Issue by Feathered-Serpent** [vgmstream/vgmstream#1449]
Hi everyone,

I have a thought and would like to know, how useful you think it could be.

Could VgmStream be used to scan any file, most probably one which isn't "supported", to scan for headers of audio files?

Like scanning a huge resource file for e.g. MP3 files or other sound files. I know, back then Dragon UnPACKer could do such a thing with HyperRipper, though the program hasn't been updated in quite some years.

I know, that this could only work with non-encrypted/scrambled files.

**Comment by NicknineTheEagle** [comment]
vgmstream is an audio decoder. It is not an archive extractor nor does it aim to be one.
