### ISSUE TITLE
[Request] “GIRLS' FRONTLINE 2:EXILIUM” audio files 

### ISSUE THREAD

**Issue by lingmiao1** [vgmstream/vgmstream#1460]
GIRLS' FRONTLINE 2:EXILIUM change the hca.key. Could you please update the key? Thanks

**Comment by lloyddunamis** [comment]
Just in case, for reference again of where to download the app. BiliBili PC doesn't require any (CN) login to download-install & launch.

- Sunborn CN https://gf2.sunborngame.com/index
- TapTap (Shares accounts with Sunborn CN) https://www.taptap.cn/app/190930
- BiliBili Mobile https://www.biligame.com/detail/?id=107267&sourceFrom=320005
- BiliBili PC https://www.biligame.com/detail/?id=107242&sourceFrom=9900000011
