### ISSUE TITLE
[Request] Test Drive: Ferarri Racing Legends FSB Files support

### ISSUE THREAD

**Issue by TBNRassault0030** [vgmstream/vgmstream#1461]
The FSB Files of TDFRL is encrypted and seems the vgmstream doesn't support it, because of FSB Key needed, so here's the FSB Key:

4DxgpNV3pQLPD6GT7g9Gf6eWU7SXutGQ

I found it in a complicated way tbh... So have fun.

![image](https://github.com/vgmstream/vgmstream/assets/86336214/9af86dad-a432-4f0f-a5e4-de2fc5a2bae9)

Edit: Forgot to upload a screenshot for proof.

**Comment by bnnm** [comment]
Added.
