### ISSUE TITLE
[Bug] WEM to WAV for Wwise - missing loop points

### ISSUE THREAD

**Issue by soniquete0** [vgmstream/vgmstream#1463]
While the source WEM file does have LOOP_END and LOOP_START tags, the loop points are missing from the resulting WAV file in both fubar2000 and Wwise.

Am I doing something wrong or is that an expected behavior?

**Comment by bnnm** [comment]
That is the expected behavior.

When converting to `.wav` in foobar2000, it creates a pre-looped file based on player's settings, since people converting to `.wav` usually want to listen to a "complete" file. Plus, I don't think you make foobar to add loop points to a generated `.wav`.

You can create a `.wav` with loop points in the command line using: `vgmstream-cli -L file`.

**Comment by soniquete0** [comment]
From my testing, -L function trims the file, producing almost the same result to -i function. Only header seems to differ slightly, viewing it in an hex editor.
Is that expected?

**Comment by bnnm** [comment]
-L will create a plain wav (same as -i) but add standard .wav loop metadata that programs which understand it can read and loop the file like vgmstream does. Without -L / -i it creates a pre-looped wav that doesn't need loop metadata (since it's already looped...). What behavior are you expecting?

**Comment by soniquete0** [comment]
I expected a full untrimmed/pre-looped file but with the loop metadata to still have the option to play the file in full or play between the loop markers set up by the game developer.

**Comment by bnnm** [comment]
I think what you describe would be confusing for most users.

When using -L vgmstream writes all posible audio data + loop metadata. Without that, it just repeats audio data per loop. Adding loop metadata on top of that "bloated"/repeated .wav that only loops a small region of the wav would be strange (which part was from the original file and which was repeated by vgmstream?). Also note that some files have proper audio after loop points such as song endings, that are kept with -L.

Loop info can only be used by a handful of specialized tools anyway, so I can't think one would want a big bloated .wav with loop metadata if they are just going to loop it in some DAW.

Further, people should keep the original .wem for playing/re-converting anyway. Converting to .wav isn't fully lossless in various cases, so it's always better to keep original files around so when vgmstream is updated you always have the best version of audio.

**Comment by soniquete0** [comment]
Alright, that makes sense. Thank you for your assistance and explanation. I have all the information I need to proceed further with my modding project.

I'll close the issue for now as all the behavior does seem to be as intended.
Once again, thank you kindly for your time.
