### ISSUE TITLE
[Request] EA .sdt subsongs

### ISSUE THREAD

**Issue by applecuckoo** [vgmstream/vgmstream#1464]
Hi there! It seems like the EA .sdt format doesn't seem to support subsongs. I can rename the file extension to .asf for vgmstream to play the first track, but it ignores everything else. Examples are attached [here](https://github.com/vgmstream/vgmstream/files/13782831/sdt.zip).

**Comment by applecuckoo** [comment]
Nope, I might just be seeing chunks of the overall sound file. Deleting some of them seems to wreck the sound file a bit.

**Comment by applecuckoo** [comment]
Yeah, I still think they seem to be hiding subsongs in the file somewhere.

**Comment by bnnm** [comment]
Please post which game is affected.

There are multiple subsongs inside lang .sdt, but offsets would be in another file. There is only 1 song in mainmenu_s.sdt though.

**Comment by applecuckoo** [comment]
Nerf N-Strike for the Wii. Would they be in the .rpk file?

**Comment by bnnm** [comment]
Other EA formats work with "companion", like bgm.mpf (header) + bgm.mus (data), so this case is probably similar.

If you don't see any files around named like the .sdt then its companion file is probably inside that .rpk. That sounds like a generic bigfile though, extracting it would be outside vgmstream's realm, best ask around in ripping communities.

At worst you could use a hex editor to find "SCHl" and split each new one into separate .asf files (tools like vgmtoolbox have options to split by header).
