### ISSUE TITLE
Handling packed files (eg. Wwise Audio Package)

### ISSUE THREAD

**Issue by davispuh** [vgmstream/vgmstream#1470]
Hi,

I've been looking into playing audio from `Genshin Impact` and `Honkai: Star Rail` both developed by miHoYo.
The main issue is that their audio is packed into "Wwise Audio Package" (`.pck`) and there isn't really any "proper" tool to unpack those.
My question is should `vgmstream` support it natively or that should be left to some another tool?

Currently there are many projects that try to do this but it's very fragmented with various tweaked implementations (not a complete list):
* https://github.com/Vextil/Wwise-Unpacker
* https://github.com/emannotava/Wwise-Unpacker
* https://github.com/mortalis13/Wwise-Unpacker
* https://codeberg.org/VIPLightning/Wwise-Unpacker-Revamped
* https://github.com/bnnm/wwiser-utils
* https://github.com/MeguminSama/genshin-audio-extractor
* https://github.com/PseudoResonance/Genshin-Impact-New-Music-Unpacker
* https://github.com/HongyuS/Genshin-Impact-Music-Unpacker
* https://github.com/paimoooon/HoYo-New-Music-Extractor
* https://github.com/yoroshikun/universal-pck-audio-extractor
* https://github.com/JustSomeGuy1234/Fable2Modding (for Fable 2)
* https://github.com/Timo576/Wwise-Unpacker-D4-/tree/Diablo4_audio (for Diablo 4)

Most of them are based on [QuickBMS](https://aluigi.altervista.org/quickbms.htm) script `wavescan.bms` (by AlphaTwentyThree from 2012) that unpacks in separate `.wem` files which then can be played/converted with `vgmstream` 

There is also newer version of [wav_scanner.bms](https://github.com/emannotava/Wwise-Unpacker/blob/master/Tools/wav_scanner.bms) dated 2022 and also completely different script [wwise_pck_extractor.bms](https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms)

So currently you can unpack it with:
```
$ quickbms wav_scanner.bms External0.pck
```
and use  `vgmstream`  to play those files.

But I've noticed that  `vgmstream` is unable to decode some files so I suspect that unpacking logic is wrong for most implementations. Also for some `.pck` files `wwise_pck_extractor.bms` unpacks less files than other scripts. I don't know if that is more correct or not...

PS. `vgmstream`  is amazing!

**Comment by davispuh** [comment]
`.pck` file example
```
00000000  41 4b 50 4b b4 02 00 00  01 00 00 00 14 00 00 00  |AKPK............|
00000010  04 00 00 00 84 02 00 00  04 00 00 00 01 00 00 00  |................|
00000020  0c 00 00 00 00 00 00 00  73 00 66 00 78 00 00 00  |........s.f.x...|
00000030  00 00 00 00 20 00 00 00  bd c2 07 3e 01 00 00 00  |.... ......>....|
00000040  c0 f4 41 00 bc 02 00 00  00 00 00 00 15 08 12 3e  |..A............>|
00000050  01 00 00 00 53 b5 64 00  7c f7 41 00 00 00 00 00  |....S.d.|.A.....|
00000060  f7 9a 20 3e 01 00 00 00  51 fd 2c 00 cf ac a6 00  |.. >....Q.,.....|
00000070  00 00 00 00 cb 01 27 3e  01 00 00 00 2b b5 50 00  |......'>....+.P.|
00000080  20 aa d3 00 00 00 00 00  e5 a2 2a 3e 01 00 00 00  | .........*>....|
00000090  74 07 70 00 4b 5f 24 01  00 00 00 00 0a 10 37 3e  |t.p.K_$.......7>|
[...]
```

**Comment by davispuh** [comment]
Cool, thanks!

Yeah I just noticed that `wavescan.bms` based ones split audio sentence in separate multiple files while with `wwise_pck_extractor.bms` it's all in single file. But there are still some issue, all files come out as `.bnk` extension with `BKHD` header but many of them are not recognized by vgmstream.

```
$ vgmstream-cli 881726317.bnk
failed opening 881726317.bnk

$ hexdump -Cn 320 881726317.bnk
00000000  42 4b 48 44 18 00 00 00  87 00 00 00 6d 13 8e 34  |BKHD........m..4|
00000010  07 1c a8 c9 10 00 00 00  60 20 00 00 00 00 00 00  |........` ......|
00000020  48 49 52 43 72 04 00 00  0e 00 00 00 0e 93 00 00  |HIRCr...........|
00000030  00 97 d1 b9 16 00 00 00  00 01 02 03 ff 04 02 02  |................|
00000040  00 00 00 00 00 00 00 00  00 04 00 00 00 00 00 48  |...............H|
00000050  42 00 00 80 bf 04 00 00  00 00 02 00 00 00 00 00  |B...............|
00000060  00 00 00 00 04 00 00 00  00 00 48 42 00 00 f0 41  |..........HB...A|
00000070  04 00 00 00 00 02 00 00  00 00 00 00 00 00 00 04  |................|
00000080  00 00 00 00 00 48 42 00  00 c8 41 04 00 00 00 00  |.....HB...A.....|
00000090  04 00 00 00 00 00 00 00  c8 42 09 00 00 00 00 00  |.........B......|
000000a0  80 3f 00 00 c8 42 04 00  00 00 00 00 20 41 00 00  |.?...B...... A..|
000000b0  00 00 09 00 00 00 00 00  48 42 00 00 00 00 04 00  |........HB......|
000000c0  00 00 00 00 0e 7b 00 00  00 13 03 53 20 00 00 00  |.....{.....S ...|
000000d0  00 01 ff 02 03 04 02 02  00 00 00 00 00 00 00 00  |................|
000000e0  00 04 00 00 00 00 00 8c  42 00 00 80 bf 04 00 00  |........B.......|
000000f0  00 00 02 00 00 00 00 00  00 00 00 00 04 00 00 00  |................|
00000100  00 00 8c 42 00 00 0c 42  04 00 00 00 00 02 00 00  |...B...B........|
00000110  00 00 00 00 00 48 42 04  00 00 00 00 00 8c 42 00  |.....HB.......B.|
00000120  00 00 00 04 00 00 00 00  02 00 00 00 00 00 00 00  |................|
00000130  a0 42 04 00 00 00 00 00  8c 42 00 00 00 00 04 00  |.B.......B......|
```

**Comment by bnnm** [comment]
`.bnk` may contain audio or just wwise commands (you can use wwiser to see them). When they don't have tracks vgmstream writes "no subsongs" to the [log](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#logged-errors-and-unplayable-supported-files).

Do note many songs in the .bnk are "preloading" audio, truncated versions (few seconds) of some full .wem, marked in vgmstream with a "[pre]" name. Your typical wavescanner will incorrectly extract them as if they were a full file. Also some Wwise platforms/versions don't have proper .wav/wem sizes that wavescanners expect and files will have missing chunks of data.
