### ISSUE TITLE
[Bug] unsupported SCD file

### ISSUE THREAD

**Issue by H41Ri0** [vgmstream/vgmstream#1471]
Many SCD files are supported but some are not.
This occurred with a file from Drag-On Dragoon 3 (PS3).

Samples of some files are [attached](https://mega.nz/file/rLJnnBbS#49_kDMH0kq_BlUuHaQIg3EPbbB2djC4WF7XyznPECQg).

please help me

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/
