### ISSUE TITLE
[Bug] L+R .dsp files from Harvest Moon: Tree of Tranquility don't connect as stereo

### ISSUE THREAD

**Issue by applecuckoo** [vgmstream/vgmstream#1477]
Hi! I have these files that are named `[name]_L.dsp` and `[name]_R.dsp` but for some reason they don't connect up. They seem to match the naming pattern, and I've tested vgmstream-cli, vgmstream123 and the Audacious plugin which all play them in mono. Samples are attached.

[dualstereotest.zip](https://github.com/vgmstream/vgmstream/files/14144680/dualstereotest.zip)

**Comment by bnnm** [comment]
Fixed but note those L/R files are a bit buggy and a few files loop differently (which is why the were getting ignored). Meaning opening the L has different loop points that the R file. On a quick look L loops are correct but not sure if that's true for every track.
