### ISSUE TITLE
[Bug] Error opening ALSA audio device

### ISSUE THREAD

**Issue by PhoenixClank** [vgmstream/vgmstream#1478]
This used to happen occasionally, but since the latest system upgrade it just doesn't work anymore.

alsa-lib is version 1.2.10-2
vgmstream has just been rebuilt via AUR
pipewire-alsa is version 1:1.0.2-1

I can use the pulseaudio driver, but that one doesn't downmix to stereo correctly, so for example with Mario Kart music I hear the base track on the left and the frontrunning beat on the right.

**Comment by bnnm** [comment]
vgmstream doesn't interface with audio devices directly so you may be talking about vgmstream123, which uses `libao` to handle that.

I don't think it's doing anything out of ordinary so you may need to debug your libao, apparently it's possible to enable debug output: https://xiph.org/ao/doc/config.html

Games that use non-standard/layered channel layouts (like Mario Kart I think) are probably best handled via `.txtp`.

**Comment by PhoenixClank** [comment]
Thanks for the context! Yes I was talking about vgmstream123.

I got libao debug output and it tries opening the 'default' ALSA device, and fails with a message "operation not permitted" or something like that.

Anyway one system upgrade later, pipewire-alsa is now at version 1:1.0.3-1 and vgmstream123 is back to working.
