### ISSUE TITLE
[Bug] Valorant .bkl files are not working with vgmstream.

### ISSUE THREAD

**Issue by MayankS-Code** [vgmstream/vgmstream#1481]
When i drag and drop .bnk files like these [BNK files.zip](https://github.com/vgmstream/vgmstream/files/14165750/BNK.files.zip) on vgmstream-cli.exe it does nothing. 

These files are from the game - Valorant. Exported using FModel.

Let me know if you need more to make it compatible.

Thank You

**Comment by NicknineTheEagle** [comment]
These Wwise BNKs do not contain any WEMs so there's nothing to play. Not a vgmstream issue.
You need to extract WEM files used by these BNKs. Also see https://github.com/bnnm/wwiser.

**Comment by IITian-VFX** [comment]
Wait, I just checked. I have the WEM files, too, in a separate folder. But they are named as integers, not strings. I have no clue which ones are which. Would you happen to know any way to extract info related to this? Thanks for letting me know anyway.

**Comment by NicknineTheEagle** [comment]
> Wait, I just checked. I have the WEM files, too, in a separate folder. But they are named as integers, not strings. I have no clue which ones are which. Would you happen to know any way to extract info related to this? Thanks for letting me know anyway.

Like I said, check the repository I linked, the documentation in it talks about what Wwise is and how it works. If you're lucky, the game will ship with .txt files or soundbanksinfo.xml which will have names for WEMs as well as Wwise events, states, switches, etc. If not, tough luck.

**Comment by TheKrisn** [comment]
@IITian-VFX, you can search the sourceId attributes in wwiser dump of a bnk file. The sourceId(s) obtained will match to the integers of wem you are talking about.
But one bnk file contains many-many of such wems, i dont know how to reproduce the exact audio played in game from these wems and bnk
