### ISSUE TITLE
[Request] HCA Key Request 

### ISSUE THREAD

**Issue by INKIA69** [vgmstream/vgmstream#1482]
IDOL FANTASY -アイドルファンタジー- (iOS,Android)(2018) ACB
re_コロキュアル colloquial2 (iOS,Android)(2019) ACB+AWB
おじさまと猫 スーパーミラクルパズル (iOS,Android)(2022) ACB+AWB

samples and lib
https://mega.nz/folder/lqxG0TyC#zYAteVI9bNQJre1adetoDw

Thanks!

**Comment by chokoooreto** [comment]
IDOL FANTASY -アイドルファンタジー- :  4308390175392019587  hex: 3BCA7A09A6063483
re:colloquial : 9863154698521  hex: 000008F871D50919
おじさまと猫 スーパーミラクルパズル : 5783843453453438113  hex: 504456FA0F8F8CA1

**Comment by bnnm** [comment]
Added.
