### ISSUE TITLE
[Request] Decryption key for Argonavis Kimisute (Kimi ga mita stage e)

### ISSUE THREAD

**Issue by chokoooreto** [vgmstream/vgmstream#1483]
Hello, I've been trying to decrypt Kimisute's audio, the problem is there's no key.
The files are in awb/acb format, the voices are in hca while everything else is adx, encrypted with type 9 (that's what foobar2000 tells me)
I've tried looking at the CriwareInitializer, but even with the decompiled Il2cpp it just says:  

"useDecrypter": false,
  "DecrypterConfig": {
    "key": "",

when it supposedly should say "true" and give me the key.
I also found a "guessadx" program, that brute forces a key, but it says that the files don't seem to be encrypted. 
Am I looking in the wrong place? It's a new game, but I hope someone can give me a hand here.

Here are some sample files (both for the adx and hca, as well as a usm video) and the decompiled il2cpp, made with il2cpp dumper: [https://mega.nz/folder/1O100RZI#ahd7sdCBqG9eXIjhIxeMNA](https://mega.nz/folder/1O100RZI#ahd7sdCBqG9eXIjhIxeMNA)

**Comment by bnnm** [comment]
Added
