### ISSUE TITLE
[Bug] EAM audio is dramatically shortened.

### ISSUE THREAD

**Issue by Acts19quiz** [vgmstream/vgmstream#1484]
vgmstream version: Bug starts at [r1690](https://github.com/vgmstream/vgmstream/releases/tag/r1690).
Winamp version: 5.9.1

The issue filed here is specifically for EAM format files. On versions of vgmstream prior to r1690 (including r1667), EAM files play correctly. Beginning with r1690, however, EAM files of moderate length (minutes, ranging from 2 to 9) suddenly only play the first 20 seconds of their run time, often less. Two games in particular are specific rips of the PlayStation versions of Need For Speed II and Need For Speed III.

I use the keyword "specific rips" because the rips came from [https://psf.joshw.info/n/](https://psf.joshw.info/n/). However, those packs were updated at some point around or before 2020 to use different file formats. That may be a factor or a clue as to what's going on. It should be noted that whether or not the PlayStation rips were redone because they were buggy or insufficient, or the EAM format/extension was considered deprecated, prior versions of vgmstream played them perfectly regardless of that.

However, [FORMATS.md](https://github.com/vgmstream/vgmstream/blob/master/doc/FORMATS.md) does declare EAM to be a supported format. vgmstream might be buggy and playing them incorrectly (original ones to test with are hard to come by, as noted above), or it might be deprecated and FORMATS.md doesn't reflect this yet. It should also be noted that r1690 was released on Nov 30, 2021, well after joshw removed hosted instances of the format that I'm aware of.

For a single sample, [here is ZZMENU1.eam](https://github.com/vgmstream/vgmstream/files/14231454/ZZMENU1.zip) as joshw formerly hosted it. ZZMENU1 should be a 1:07 minute track, but recent versions of vgmstream truncate it to 0:24. There are more extreme examples than this. For a full track list, [archive.org](http://web.archive.org/web/20160401000000*/http://psf.joshw.info/n/Need%20for%20Speed%20II%20[Over%20Drivin'%20II]%20(1997-03-31)(EA%20Canada)(Electronic%20Arts).7z) can spot you the EAM versions of NFSII. archive.org failed to backup NFSIII, though I still have the full (unzipped) download at my disposal (that I'll be retaining for all time for obvious reasons).

Formats not impacted include XA, VGM, MP3, SPC... I haven't noticed the issue with any except EAM.

One final note: The Need For Speed tracks are a curious bunch, existing in small segments that are stitched together in-game so that as the situation changes (players get towards the end of the lap, get busted for speeding, start wrecking, etc.), an alternate version of the track can be subbed in on the spot. The EAM versions are "all-in-ones" with all of the segments in a single file, so this is perhaps where vgmstream is getting lost.

https://github.com/vgmstream/vgmstream/pull/339 A possibly-related issue appears to have been discussed here, though it should be noted that the pull request at the end predates the introduction of the bug by a few years.

**Comment by NicknineTheEagle** [comment]
The issue is that you're playing an improperly made rip. Automatic segment merging is an old hack and .eam is a fake extension invented for... some reason. The hack was removed due to being rendered obsolete by TXTP (https://github.com/vgmstream/vgmstream/blob/master/doc/TXTP.md) and fake .eam extension should be gutted at some point, too. You want to get the newer rip with MAP/MUS files and use TXTP to merge the segments in the desired order (note that this game has dynamic music).

**Comment by Acts19quiz** [comment]
Duly noted. Though I should note that I had already observed that the music was dynamic in my report. If this is unplanned, then FORMATS.md should be revised in the future to remove EAM as a supported format since it, well, isn't anymore. I otherwise doubt I'd filed this report if I hadn't found acknowledgment of EAM support in the current FORMATS.md

As it stands, I'll keep the EAM files I have. They're already all-in-one, and I'd have to invest days trying to use the suggested tools to bake new files matching the exact segment order of files (which would require hours of listening back-and-froth) that... I already have. But thank you for the update anyway.

**Comment by NicknineTheEagle** [comment]
Old hack actually just dumbly plays the segments in the order they're stored in the bigfile. So you can do something like that for every file:
```
ZTR04ROK.MAP#1~147
```

**Comment by NicknineTheEagle** [comment]
BTW, in case of Need for Speed II, the new rips on the archive contain pre-made TXTPs that actually provide a good listening order as opposed to the mess that the old auto-merging hack produces.
