### ISSUE TITLE
[Info] Decrypting with vgmstream

### ISSUE THREAD

**Issue by chokoooreto** [vgmstream/vgmstream#1489]
Hi, I'm sorry if this sounds like a stupid question but I have always relied on other software to decrypt hca files. Now that I have some adx files and I don't know what program to use, I want to ask if I could get clearer information on how to decrypt with vgmstream?
I've read the usage post, but forgive me, I am still pretty lost. what kind of file should the .adxkey be? Should it contain only the key in plain format? Should I use the list provided and rename the file extension to .adxkey? How should I specify in the command line that I want to use a decryption key?
Sorry again if it sounds stupid.

**Comment by bnnm** [comment]
For example, if you have an ADX key string *"123456789"*, make a text file named `.adxkey` (notice
it starts with a dot), open it with a text editor and copy that key without quotes nor line endings:
`123456789`. Save it then play the ADX normally. vgmstream will see this key and use it automatically.

Alternatively post the key and it could be added to the global list vgmstream uses.

**Comment by chokoooreto** [comment]
Ah, thank you, now I understand! About the global list, do I have to download it every time it updates and do something or is it automatically updated without ever downloading it? As in, do I have to do any extra steps to use it or is it always inside the software and it automatically attempts to use the keys in the list if i feed it an encrypted file?

**Comment by bnnm** [comment]
The global list is part of vgmstream and is used automatically if no .adxkey/.hcakey/etc file is found. Every time it changes you need to update manually: [vgmstream.org](https://vgmstream.org/)

(foobar component [here](https://www.foobar2000.org/components/view/foo_input_vgmstream) can be updated directly from its menu but is updated less often that the site)

**Comment by chokoooreto** [comment]
Now everything is clear! Thank you so much for the info!
