### ISSUE TITLE
V-Rally 3 PS2 (and probably others) - sequenced bank format

### ISSUE THREAD

**Issue by AlphaTwentyThree** [vgmstream/vgmstream#1490]
Not entirely sure if this is possible but I'm trying my luck here.

[vrally3_bank.zip](https://github.com/vgmstream/vgmstream/files/14318689/vrally3_bank.zip)

Included a QuickBMS script that at least has _some_ data readout but I'm completely lost when it comes to these sequenced formats. 
Those files include soundbank and sequence files. *.iop is just some placeholder, others come with a *.bnk suffix, but have the same structure.
Here's how the menu music probably should sound like: https://www.youtube.com/watch?v=UnKpl8LepFs

**Comment by bnnm** [comment]
That looks like a container of .bd/hd/seq. If the game uses the standard driver you may be able to make .psf2 from those files + game's irxs with vgmtoolbox and related tools, but we can't do much here ([note](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#sequences-and-streams)).
