### ISSUE TITLE
[Request] Love Live! SIF2 .ppart format

### ISSUE THREAD

**Issue by AndnixSH** [vgmstream/vgmstream#1494]
I came across a game that have audio files with .awb, .acb, awb.ppart and acb.ppart format. vgmstream can't play ppart files but plays .awb and .acb perfectly fine. Idk if ppart are splitted but there is no base file of these. 

Example:

07b92a8e1c1dbcb60eecfdbad8e06298_6976d7d79ab3df75d3adb77d8ad64d74.awb.ppart
07b92a8e1c1dbcb60eecfdbad8e06298_fdea1774703738756ef78ebbbaaa1643.acb.ppart

[Sample 1.zip](https://github.com/vgmstream/vgmstream/files/14393674/Sample.1.zip)

7a195f58057c48041518e9d31fc832b1_c152fcc4bb3c073f8ddf76ddcb3f7858.awb.ppart
7a195f58057c48041518e9d31fc832b1_ef824caef0881ef5294b8a991a467218.acb.ppart

[Sample 2.zip](https://github.com/vgmstream/vgmstream/files/14393675/Sample.2.zip)

What I'm looking for is the menu soundtracks that seems to be in ppart files. I looked through all .awb and .acb files, there was no sountracks I'm looking for

Foobar2000 version: v2.1.2
vgmstream version: r1896
Tried online web player as well

**Comment by bnnm** [comment]
Those files look like parts of awb or acb so you'd need to find the rest of the data and join them. Nothing vgmstream can do about it.

**Comment by bnnm** [comment]
No idea sorry, maybe they are inside of other files. This would be an extraction issue (try reshax/xentax discord).

**Comment by AndnixSH** [comment]
Ok

**Comment by Rin-Wood** [comment]
{    "Bgm/song_1126_YumenakiYumehaYumejyanai.acb.ppart":{
        "name":"Bgm/song_1126_YumenakiYumehaYumejyanai.acb.ppart",
        "url":"https://img-sif2.lovelive-sif2.com/Android/EN/de7e47fcded7e75946fcaf532cb45edb/56ce144b99c54ba1b8f8fe8fd2e68b24.acb.ppart",
        "md5":"56ce144b99c54ba1b8f8fe8fd2e68b24"
    },
    "Bgm/song_1126_YumenakiYumehaYumejyanai.acb.spart":{
        "name":"Bgm/song_1126_YumenakiYumehaYumejyanai.acb.spart",
        "url":"https://img-sif2.lovelive-sif2.com/Android/EN/de7e47fcded7e75946fcaf532cb45edb/56ce144b99c54ba1b8f8fe8fd2e68b24.acb.spart",
        "md5":"56ce144b99c54ba1b8f8fe8fd2e68b24"
    },
    "Bgm/song_1126_YumenakiYumehaYumejyanai.awb.ppart":{
        "name":"Bgm/song_1126_YumenakiYumehaYumejyanai.awb.ppart",
        "url":"https://img-sif2.lovelive-sif2.com/Android/EN/de7e47fcded7e75946fcaf532cb45edb/56ce144b99c54ba1b8f8fe8fd2e68b24.awb.ppart",
        "md5":"56ce144b99c54ba1b8f8fe8fd2e68b24"
    },
    "Bgm/song_1126_YumenakiYumehaYumejyanai.awb.spart":{
        "name":"Bgm/song_1126_YumenakiYumehaYumejyanai.awb.spart",
        "url":"https://img-sif2.lovelive-sif2.com/Android/EN/de7e47fcded7e75946fcaf532cb45edb/56ce144b99c54ba1b8f8fe8fd2e68b24.awb.spart",
        "md5":"56ce144b99c54ba1b8f8fe8fd2e68b24"
    }}

**Comment by AndnixSH** [comment]
@Rin-Wood okay. how do you obtain the json data and how to open those files?

**Comment by Rin-Wood** [comment]
> @Rin-Wood okay. how do you obtain the json data and how to open those files?
I am using python and using brute force search to extract md5 values.

```py
import re, json

class rns:
    import numpy as np
    @staticmethod
    def rbin(fp: str, num: int = 0) -> bytes:
        with open(fp, 'rb') as file:
            return file.read() if num == 0 else file.read(num)

    @staticmethod
    def sjson(fp: str, data: dict) -> None:
        with open(fp, 'w', encoding='utf-8') as file:
            json.dump(data, file, indent=4, ensure_ascii=False, separators=(',', ':'))


class xxx:
    def dd(file, f):
        def d(data):
            mcls = [i.start() for i in re.finditer(b'\x20[0-9a-f]{32}', data)]
            a = mcls[0] - 5
            b = mcls[0]
            c = {a:[b + 1]}
            for i in mcls[1:]:
                if (i - b) > 64:
                    a = i - 5
                c.setdefault(a, []).append(i + 1)
                b = i
            for i, j in c.items():
                l = data[data[:i].rfind(b'\x00') + 1]
                n = data[i - l:i].decode('utf-8')
                f[n] = [data[k:k + 32].decode('utf-8') for k in j]
        data = rns.rbin(file)
        d(data)

f = {}
xxx.dd('sound.bin', f)
rns.sjson('0.json', f)
```

**Comment by Rin-Wood** [comment]
> @Rin-Wood okay. how do you obtain the json data and how to open those files?

[](https://img-sif2.lovelive-sif2.com/Android/EN/0de9f85900e910b0b4873dcdd0933aa5/387b0126300c54515911bffb6540982d.unity3d
)
![image](https://github.com/vgmstream/vgmstream/assets/153263099/47195c12-5a5a-4972-926c-65cdef124b2c)
Its resource list file is stored in this unity3d file. Extract 'moive', 'sound' and 'bundle'. These three files are encrypted using aes-cbc, key: b'akmzncej3dfheuds654sg9ad1f3fnfoi', iv: b'lmxcye89bsdfb0a1'

**Comment by AndnixSH** [comment]
doesn't those resource list get extracted to like soundInfo.json in /data partition? I failed to decrypt from extracted resource, so I went after soundInfo.json instead. After decrypting, the format seems to be broken, Idk if it's encoding issue
[soundInfo.json](https://github.com/vgmstream/vgmstream/files/14493361/soundInfo.json)

Now the question is, how to open or join of so called PrimaryPart (ppart) files? Let's say BG_0001

```
   "  Bgm/BG_0001_Home_acbPrimaryPart#   70a36bac78496bcf237fdfb7e868c642$   
b6dff4a7c8e357fc05362cf56846a790      %  Bgm/BG_0001_Home_awbPrimaryPart	#  '   
7a3307736bd1e0d9b82ebc2e3ceab02d      
```

It doesn't seems to have spart, and it does not point to other files other than .acb.ppart and .awb.ppart. I'm mostly after the songs. Voices are not problem since most voices can be opened

acb.ppart have additional header at the bottom that oridinary acb doesn't have

![image](https://github.com/vgmstream/vgmstream/assets/40742924/8a78a0e1-b9d2-4ffd-9568-6738a56b5454)

**Comment by kofing1** [comment]
Based on Wood's hints, I managed to restore the filenames, but I failed to understand the relationship between the 'acb/awb.s/ppar' files within the same directory.
![image](https://github.com/vgmstream/vgmstream/assets/22070324/a8c88723-d1ae-4d36-a790-95780a3b381a)

**Comment by bnnm** [comment]
Since this .ppart/spart scheme is just simple obfuscation made for the game it doesn't have anything to do with CRIWARE/vgmstream and must be merged externally, so this is not the place to ask.

These kind of questions are for xentax/reshax/hcs64 discord, but if you look hard enough there are scripts that handle it.
