### ISSUE TITLE
[Request] List 118 FSB Keys

### ISSUE THREAD

**Issue by Dedopolis** [vgmstream/vgmstream#1496]
Hi there,

I'm having trouble opening these files with vgmstream:

[Samples.zip](https://github.com/vgmstream/vgmstream/files/14406830/Samples.zip)

I belive it need the FSB encyption key to play them, and I've tried extracting it, but haven't been successful.

**Comment by bnnm** [comment]
Those files are encrypted with some complex algorithm (ex. AES o chacha20), and don't look like FSB encrypted files (which have much worse byte distribution).

You should ask instead in modding communities such as the reshax/xentax discord, there isn't much we can do.
