### ISSUE TITLE
[Bug] failed opening sfx_container.bnk (Cyberpunk 2077)

### ISSUE THREAD

**Issue by Zhincore** [vgmstream/vgmstream#1500]
Hello,
I am trying to extract embedded audio / subsongs from Cyberpunk 2077's .bnk files.
For the smaller ones it works perfectly, but for the sfx_container.bnk (and few others) vgmstream just says "failed opening \<path>". The file exists at that path, it is accessible, it works for other bnks in that folder.

Samples:
- [non-working sfx_container.bnk](https://static.zhincore.eu/tmp/sfx_container.bnk)
- [working quadra_turbo_r.bnk which can be extracted just fine](https://static.zhincore.eu/tmp/quadra_turbo_r.bnk)

I can provide more samples of openable and not openable .bnks if needed.

I am using `vgmstream CLI decoder r1896-82-gaa22b1c8 (Feb 25 2024)`.
Thanks.

P.S. According to wwiser, some of the sounds in sfx_container are "PCM" instead of the usual "Crankcase REV Model Player" that is used in most of the other embedded subsongs.

**Comment by bnnm** [comment]
Fixed. But note that to get all subsongs in ADM3 you need to extract the file. inside .bnk vgmstream can only play the first one, but not sure could we handle it since it's a kind of special plugin helper rather than regular audio.
