### ISSUE TITLE
[Request] HCA key for Toaru Majutsu no Index: Imaginary Fest / とある魔術の禁書目録 幻想収束 

### ISSUE THREAD

**Issue by MrShiruba** [vgmstream/vgmstream#1503]
Game : Toaru Imaginary Fest for Android : https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.index_if&hl=en_US
Package name : com.square_enix.android_googleplay.index_if

I've extracted some usm movies files from the game using crid_mod.exe but I need a key to get a playable m2v and adx (or hca it seems), 
 something like this : https://github.com/vgmstream/vgmstream/blob/master/src/meta/hca_keys.h. 

I've managed to get a `dump.cs` thanks to https://github.com/Perfare/Il2CppDumper but I don't know what to do next. Does somebody have a link or documentation that would tell me how to get that key so that I can add the key to the .h file (I've found some links that talk about UnityExplorer but it seems it requires an exe and it is an android game)? I've looked online but I didn't find anything. 

Download link for some usm and dump.cs : https://drive.google.com/file/d/1JRTlGNIQBV_MgzvcGotUcR3yHe2AIjYE/view?usp=sharing

**Comment by bnnm** [comment]
Key is 8612225740870068410

Note that crid_mod can't identify which audio/video format is used.
