### ISSUE TITLE
[Request] Allow users to select which vgmstream_function to use

### ISSUE THREAD

**Issue by hugeBlack** [vgmstream/vgmstream#1507]
Hi, I'm currently working on the training of an Al model out of game audios, which need me to extract thousands of audios of same format from game assets. 

After some dive into the code, I found that each initiation of struct `VGMSTREAM` is done by calling `init_vgmstream_from_STREAMFILE(STREAMFILE* sf)`. This function then calls `init_vgmstream_internal(STREAMFILE* sf)`, which loops through 500+ `vgmstream_function_t` to find the proper format. In my scenario, this will cause thousands of useless loops.

What I suggest is simple, break the `init_vgmstream_internal(STREAMFILE* sf)` into two functions. One loops through the array and find proper `vgmstream_function_t`, then returns both the function and the generated `VGMSTREAM`. Other checks whether the generated `VGMSTREAM` is valid. Also, remove the `static` flag of `init_vgmstream_count` so that we can access the length of `init_vgmstream_functions` from other files.

I can create a pr if you consider this reasonable.

**Comment by bnnm** [comment]
I feel this use-case is a bit too specific and the changes (as you describe them) makes maintenance/tweaking harder, but this only would be used "once". Note that vgmstream's internals aren't really "public" (there is WIP sketch of an API in api.h tho).

Another possible approach is that the `VGMSTREAM` would save a pointer to its init function, which allows (re)opening itself or similar files via a separate/public API (no need to change current model), though still thinking (possibly will need this for further changes on the road).

Maybe it's simpler/faster that you apply a git patch to your built vgmstream that disables all `init_vgmstream_functions` except the format you need.

Though ultimately `init_vgmstream_internal` just should be faster and need less loops.

**Comment by hugeBlack** [comment]
I see your point of view. I'll create a fork and base my project on that.

**Comment by bnnm** [comment]
Once there is an actual public API I can add some way to do this (for example returning a "format_id" what could be used with vgmstream_open_by_id or some such). So still under consideration, just that internals are rather brittle and would rather not use them as "public" API.
