### ISSUE TITLE
[Bug] Distorted audio from Kururin Squash! (GameCube, .ssm files)

### ISSUE THREAD

**Issue by craftersshaft** [vgmstream/vgmstream#1511]
Music works fine, sound effects/voices sound crackly when used with foobar/the standalone cli tool.

This is how it should sound ingame: https://github.com/vgmstream/vgmstream/assets/16724730/e30aca89-42b7-4779-91c7-b632d44014fd

Original file/converted to wav from foobar: [Sample.zip](https://github.com/vgmstream/vgmstream/files/14890363/Sample.zip)

Thanks!

**Comment by bnnm** [comment]
Fixed.
