### ISSUE TITLE
[Bug] Cannot install the latest version of the vgmstream component for foobar2000

### ISSUE THREAD

**Issue by TestNintendo** [vgmstream/vgmstream#1513]
After I installed the vgmstream component, it failed to load it.
I'm using foobar2000 v1.5.11 on Windows XP Pro with SP3.
Can you fix that issue?

**Comment by NicknineTheEagle** [comment]
Windows XP support has been dropped two years ago. You can find the last build  that works on WinXP here: https://github.com/vgmstream/vgmstream/releases/tag/r1745
