### ISSUE TITLE
[Request] James Cameron's Avatar: The Game (PC, PS3, Xbox 360) - another "bao" to deal with

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#1515]
just leaving this out here before i dash off

for various reasons, i'm leaving off all the sound files from the "next-gen" versions of that one Avatar game from 2009.

i could test all of them myself but they're a mess to sort through and i frankly don't have the mental bandwidth to test a thousand baos at any one time so i'm just posting all them samples as-is and will make no guarantees on any of their availability. better safe than sorry.

so, without further ado, here they are.
[[james_camerons_avatar_the_game]ps3_bao.tar](https://qiwi.gg/file/7r429741-jamescameronsavatarthegameps3bao)
[[james_camerons_avatar_the_game]xbox360_bao.tar](https://qiwi.gg/file/8dNS1693-jamescameronsavatarthegamexbox360bao)
files from Vista ver will be posted here as well but no ETA.

included in these files are spk+sbao files, spk files contain actual bao data but are wrapped into metadata containing info on how to load said bao.

spk are by themselves fairly small, only serving as a front-loader for various external sbao that a bao needs, and when sounds are included in a bao from a spk they're all very small sounds (be it foley, footsteps, menus, etc.)

**Comment by modusc896d352** [comment]
here are the vista files as promised
[[james_camerons_avatar_the_game]windowsivsta_bao.tar](https://qiwi.gg/file/oocK2011-jamescameronsavatarthegamewindowsivstabao)

**Comment by modusc896d352** [comment]
issue closed. i'll do it myself. no ETA.

**Comment by bnnm** [comment]
Just fyi bao is a pain to deal with and a huge timesink, and given this variant is used in a single game it doesn't exactly have the highest priority.

Here is something to get you started: https://github.com/vgmstream/vgmstream/blob/master/src/meta/ubi_bao.c#L207

**Comment by modusc896d352** [comment]
i'll see what i can do with it
