### ISSUE TITLE
[Request] HCA key

### ISSUE THREAD

**Issue by aslkdjkalsdjalkdaslkd** [vgmstream/vgmstream#1518]
Game: Sengoku A live (Android)

https://www.mediafire.com/folder/acfarturezgdl/help_me_please_lol

**Comment by Rairyujin** [comment]
Game: Code Geass lost stories

**Comment by aslkdjkalsdjalkdaslkd** [comment]
I noticed is actually possible to hear the audios in foobar2000 adding the .acb extension to the files, maybe there is some way to get the key using that instead of analysing the game files.
my intention with the key is using it for getting the videos of the game

**Comment by bnnm** [comment]
Can't do anything about USM keys.

**Comment by aslkdjkalsdjalkdaslkd** [comment]
don't worry, thanks for your reply anyways. By the way, i managed to get the key, it was just 0
