### ISSUE TITLE
[Request] Mario Strikers Charged (Wii) .nlxwb

### ISSUE THREAD

**Issue by LuckyMage92** [vgmstream/vgmstream#1523]
Please add these extension. Here's the link.
https://mega.nz/file/5GJzDbrR#KyLJ9cJZJJtluXLwwe2ngqyaAxUW3rl9dzUywSngWCI

**Comment by applecuckoo** [comment]
fyi, some of the nlxwb files that contain music are just containers with Next Level .idsp files.

**Comment by LuckyMage92** [comment]
So do you know some tool to extract the nlxwb files?

**Comment by applecuckoo** [comment]
@LuckyMage92 No, not all of them. Some files with the IDSP header (i.e. FE_GEN_Music.nlxwb) are just those files stacked on top of each other (separated by the IDSP header) and can be cut into an .idsp file for vgmstream to play. As far as I know, there's no way to play the SFX or voice lines.

**Comment by bnnm** [comment]
This looks more like a resource file and not an audio format. Better use some tool to extract it:

https://github.com/DKDave/Scripts/blob/master/Python/Mario_Strikers_Charged_(Wii)_RESBUN.py

**Comment by LuckyMage92** [comment]
This is good enough. Many thanks!

Il Dom 21 Lug 2024, 22:32 bnnm ***@***.***> ha scritto:
