### ISSUE TITLE
[Bug]  Broken STHD/STX for Phantom Dust Re-Release

### ISSUE THREAD

**Issue by Torphedo** [vgmstream/vgmstream#1525]
Hello, I've been researching audio in the 2004 Xbox game Phantom Dust recently. It was re-released for PC/Xbox One in 2017, with higher-quality textures/cutscenes/audio.

I found that for the re-release, VGMStream's decoded WAV sounds like static (very similar to what happens when I try to force the 2004 build to play 2017 files, or vice versa). I don't have the 2004 files on-hand, but STX files from a 2003 development build decode perfectly fine. The 2017 files still use an STX file extension & look like the same STHD format, but are a little over 3x larger (I'm guessing there's less compression going on). I haven't worked with audio data before, but I know C and I'm willing to write the fix myself if I can find the problem. As far as I can tell, the revelant code is in [meta/sthd.c](https://github.com/vgmstream/vgmstream/blob/master/src/meta/sthd.c) and [coding/ima_decoder.c](https://github.com/vgmstream/vgmstream/blob/master/src/coding/ima_decoder.c).

I directly uploaded the 2003 files, but the 2017 ones are so large I had to upload them to my university's server:
[2003_stx.zip](https://github.com/vgmstream/vgmstream/files/15281623/2003_stx.zip)
[2017_stx.7z](https://cs.rit.edu/~aeh6923/files/pd_dev_stx/2017_stx.7z)

The decoded audio is [here](https://cs.rit.edu/~aeh6923/files/pd_dev_stx/), and sounds exactly like in-game. The 2017 files will sound slightly different since the decode is from early files, but they should be very similar.

**Comment by bnnm** [comment]
Fixed.

**Comment by Torphedo** [comment]
Awesome, thanks! What does the "channel size" in the comments refer to? Size in bytes per channel?

**Comment by bnnm** [comment]
That's correct. Each block (other than the first/header) has a 0x20 header + channel_size bytes for channel 0 + channel_size bytes for channel 1. Sometimes channel_size changes per block and part of the block is left unused though.
