### ISSUE TITLE
[Bug][Build] ubi_hx -Wincompatible-pointer-types compile error

### ISSUE THREAD

**Issue by KirshD** [vgmstream/vgmstream#1529]
Keep on hitting a pointer incompatibility error when compiling ubi_hx.
Running Fedora 40, got all the libraries, just seems to hang on the Ubisoft stuff. Not sure if I missed some extra library since the fresh install.

Output:
/mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/ubi_hx.c: In function ‘parse_header’:
/mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/ubi_hx.c:386:106: error: passing argument 6 of ‘find_chunk_riff_ve’ from incompatible pointer type [-Wincompatible-pointer-types]
In file included from /mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/ubi_hx.c:5:
/mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/../util/chunks.h:38:127: note: expected ‘size_t *’ {aka ‘long unsigned int *’} but argument is of type ‘uint32_t *’ {aka ‘unsigned int *’}
/mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/ubi_hx.c:396:103: error: passing argument 6 of ‘find_chunk_riff_ve’ from 
/mnt/nvme0n1p6/GitStuff/vgmstream/src/meta/../util/chunks.h:38:127: note: expected ‘size_t *’ {aka ‘long unsigned int *’} but argument is of type ‘uint32_t *’ {aka ‘unsigned int *’}
make[2]: *** [src/CMakeFiles/libvgmstream.dir/build.make:6824: src/CMakeFiles/libvgmstream.dir/meta/ubi_hx.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:342: src/CMakeFiles/libvgmstream.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by modusc896d352** [comment]
you're not

**Comment by KirshD** [comment]
Success, many thanks!
