### ISSUE TITLE
[Bug] Xbox ADPCM (Crimson Skies: High Road to Revenge) music fails to convert

### ISSUE THREAD

**Issue by RevOcelotMGS** [vgmstream/vgmstream#1538]
Regular Xbox ADPCM, I think. No clue why, but it also has a ton of noise when converted using ffmpeg or other software, versus when played through Windows using the Xbox ADPCM codec.

I've attached two sample files. One is .wav and is the original file, the .flac is recorded through loopback on Audacity and is how it is intended to sound.
[flyaround_06.zip](https://github.com/vgmstream/vgmstream/files/15491901/flyaround_06.zip)

**Comment by bnnm** [comment]
Rename to .lwav or change plugin's priority, [info](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#common-and-unknown-extensions).
