### ISSUE TITLE
[Bug] Forza Motorsport 3 .fsb files fail to play using vgmstream

### ISSUE THREAD

**Issue by Birdatoo** [vgmstream/vgmstream#1551]
some .fsb files play completely fine with all files intact, others fail to play properly with some XMA files inside the fsb container presumably failing to be decoded (problem files are namely 10N2_CGT_Exh.fsb, 10N3_E60M5_Exh.fsb, 10N3_E60M5_Int.fsb, 10N3_Gallardo_Exh.fsb etc)

Sample files can be downloaded from: https://www.mediafire.com/file/y47ge0jfb9cvh7f/Soundbanks.zip/file

**Comment by bnnm** [comment]
Fixed
