### ISSUE TITLE
[Bug] Custom DSP music files lost support in r1690

### ISSUE THREAD

**Issue by Acts19quiz** [vgmstream/vgmstream#1570]
**Describe the bug**
Beginning in vgmstream r1690, custom DSP files stopped working. Specifically, these are homemade files not ripped from a game, but using the same technologies the original sound composers and engineers used to make the game files. It may have something to do with, "[Improved DSP validations.](https://github.com/vgmstream/vgmstream/releases/tag/r1690)"

**Build that the bug occurred in**
r1690 - r1917

**To Reproduce**
1. [Download the custom Metroid Prime DSP files](https://mega.nz/file/zjJDiQpQ#Re6zI7UEGKf0EbvPYiYNUtXorGWhoaIRJBeYQp9sQ10) (you can hear them [here](https://www.youtube.com/watch?v=Lwmlr29Q7Xg)).
2. Attempt to play them with vgmstream.

**Expected behavior**
For vgmstream to play DSP files that were working and considered valid before.

**Additional context**
This was tested with Winamp 5.9. The author of the custom Metroid Prime music files anticipates users actually patching game ISOs with them and running then on authentic hardware or emulators, so they are, indeed, working DSP files (that apparently fail whatever validation vgmstream is using... maybe vgmstream is checking to see if they're from actual games?).

The last working version for custom DSP files not ripped from games is r1667.

**Comment by EdnessP** [comment]
Just putting this here for your information, they are failing because the initial offset (stored at 0x18) isn't set to 0x02 which is typically the 'expected' value for DSPs.  Only `over-stonehenge` meets that criteria from your samples and is one that still loads.  I suppose a temporary fix would be to just overwrite that value for all the other files which will then make it work.

**Comment by Acts19quiz** [comment]
Interesting. Easy and straightforward if you know your way around a hex editor. Thanks for the heads up.

From the programming standpoint, I still wonder why the rest of the files went from working to failing. Obviously the headers are a factor, but I'm more interested in the vgmstream side and if there's a way to work around different headers while still maintaining compatibility with existing files.

**Comment by EdnessP** [comment]
Mostly because the standard variant of DSP has very little uniquely identifiable elements in its header, so stricter checks were put in place on the header data itself making sure it seems 'correct' to weed out any false positives.

**Comment by bnnm** [comment]
Fixed.

As for those files failing, somebody shared non-dsp files (renamed to .dsp) that were being incorrectly identified as .dsp, so we added some extra validations. The files you posted are a bit odd and those extra validations didn't like them, but if they work in hardware I guess it's fine. I'd be nice if modders just made standard .dsp though.
