### ISSUE TITLE
[Bug] FSB Clicking noise at the beginning of sounds in Halo 3

### ISSUE THREAD

**Issue by AlexisJonsson** [vgmstream/vgmstream#1575]
There's an audible click at the start of louder sounds. It's very clearly audible in the Halo 3 sfx.fsb for the sounds: #7485, #7486, #7487, #7505 #7506 #7507.

We've verified that those clicks don't appear in the editing kit or the retail game. It has also been tested on several machines with the same outcome.

**Comment by bnnm** [comment]
You'd need to post that file so we can test it.

**Comment by bnnm** [comment]
On a quick glance the songs you posted sound normal enough. Which OS/component are you using? (self compiled?).

Example of what I get: [wav.zip](https://github.com/user-attachments/files/16638910/wav.zip), maybe your version is creating something slightly different?

**Comment by bnnm** [comment]
No further comments so closing.
