### ISSUE TITLE
[Request] Opus - .rvw format (Half-Minute Hero [PC/Steam])

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1578]
Format Specifications:

Format is basically RIFF .wav file but it starts with "fmt". Loop info is at the end of the file and at the very end is the first bytes of a RIFF WAVE header.

Codec: Microsoft ADPCM

Samples: coming soon.

Ideas:

Because .txth cannot handle grabbing info from the end of the file. I got an idea to extract the smpl data and convert the loops to .txtp.

**Comment by bnnm** [comment]
Please, don't just post "samples coming" with no files. Next time I'll just close the issue. It's really annoying when people ask for bug fixes with no sample files, but even more so when they pretend they'll post them then don't.

Just this time: TXTH can read from end of the file using `base_offset`
```
codec = MSADPCM
channels = @0x0A$2
sample_rate = @0x0c
frame_size = @0x14$2
base_offset = data_size - 0x50
loop_flag = @0x24
loop_start = @0x34
loop_end = @0x38

data_size = data_size - 0x50
start_offset = 0x42
num_samples = data_size
```

**Comment by Sukotto-1999** [comment]
There you go. I'll post an updated rip and okay fine. I'll post samples next time!
