### ISSUE TITLE
[Bug] Fire Emblem Warriors 3 Hopes Switch (KOEI Tecmo) inconsistent *.SRSA playback

### ISSUE THREAD

**Issue by Xehanort88** [vgmstream/vgmstream#1579]
I can see there is a difference in the headers but, I'm gonna be honest, I can't tell what is different exactly. I also have the entire rom dump, so would be interested to provide a sample of every file to see if there are more undiscovered audio formats.

[working SRSA.zip](https://github.com/user-attachments/files/16694908/working.SRSA.zip)
[non-working SRSA.zip](https://github.com/user-attachments/files/16694909/non-working.SRSA.zip)

Tried using the below script as well (from the 3 hopes audio rip) to see if it led to different results, but nothing came out of it.
[rdb.zip](https://github.com/user-attachments/files/16694976/rdb.zip)

**Comment by bnnm** [comment]
srsa need to be paired with srst: https://github.com/bnnm/vgm-tools/blob/master/py/archives/ktsl-srsa-srst-matcher.py

Sometimes srsa they use variations that aren't supported, check the log: https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#logged-errors-and-unplayable-supported-files

Also please either ask in discord or github but not both.
