### ISSUE TITLE
[Bug] Are minipsf2 files supported?

### ISSUE THREAD

**Issue by Wedge009** [vgmstream/vgmstream#1581]
Since migrating to Linux several years ago I primarily use vgmstream as an Audacious plug-in - regarding support for PSF, does that include `*.minipsf2` files? Previously, I used the 'Highly Experimental' PSF plug-in for Winamp - in contrast with that experience I find I cannot play the original (PS2) Final Fantasy X soundtrack, though I can play PS1 and PS2 stand-alone PSFs okay (albeit with occasional glitches in some tracks).

FFX: [vgm.hcs64.com](https://psf2.joshw.info/f/Final%20Fantasy%20X%20(2001-07-19)(Square)[PS2].7z)

I've just (re)built vgmstream at r1951 but I've found this to be a problem for quite some time. Currently using Audacious 4.4.

**Comment by Dobby233Liu** [comment]
vgmstream doesn't support the kind of PSF you're thinking of - it's out of scope. Not sure what PSF plugins are out there for Audacious, but vgmstream definitely isn't one of them

**Comment by Wedge009** [comment]
Right, sorry, been a while since I looked at the individual plug-ins - I completely missed there's an 'OpenPSF' plug-in for Audacious.
