### ISSUE TITLE
[Request] Sims Games for Gamecube & PS2

### ISSUE THREAD

**Issue by ghyujkilop** [vgmstream/vgmstream#1583]
Any/All Sims games. The music files are in the .arc format. I'm quite sure that the files are in a similar format to how .xwb works (which I wish I could re-add music to it ugh!) but yes, just thought that'd be neat to place from the .arc files archive. Ty!

GameCube:
https://drive.google.com/file/d/112piKIpCo5OFrQR6tl2e3Np0iwj0n8fI/view?usp=sharing

PS2:
https://drive.google.com/file/d/1iRcOP2L7pPhzRVkGNsH0o_JSigixOvvi/view?usp=sharing

**Comment by ghyujkilop** [comment]
Is there a best/appropriate way to extract .xwb files? Like, do you have this info but in relation to XWB? Just so I can know in case I want to re-add to it etc .

**Comment by bnnm** [comment]
vgmstream should open and play .xwb. while those .arc are just simple generic archives you need to extract with the .bms posted above.

xwb is a full audio format and would be pretty hard to modify if that's what you are asking for, try asking in xentax/reshax/modding communities. That's beyond vgmstream's realm though.
