### ISSUE TITLE
[Bug] Some PSB Files From The Quintessential Quintuplets - Memories of a Quintessential Summer [Switch] Not Playing

### ISSUE THREAD

**Issue by N6661** [vgmstream/vgmstream#1586]
_The Quintessential Quintuplets - Memories of a Quintessential Summer_ uses the PSB container for audio files. Certain files from the Switch version do not play, incurring the error message `Unable to open item for playback (Unsupported format or corrupted file)` in foobar2000 with vgmstream r1951. The issue applies to this game and its two sequels on Switch.

A few observations I've made which may help:
1. Each PSB file contains two audio files; One for the song's intro and one for its loop. Files that do not work has an empty intro file that, as seen in a hex editor, only contains header data and nothing else.
2. All audio files extracted from the PSB files play correctly (albeit lacking looping), including audio files extracted from PSB files that do not play.
3. The PC version of this game does not use the same internal structure, and instead only has one audio file in each PSB. All PSB files from the PC version play correctly.

The contents of the PSB files can be extracted using FreeMoteToolkit's PsbDecompile.exe with the following decryption key: `523aad2de7132`

I've uploaded the full set with this bug report.
[sound.zip](https://github.com/user-attachments/files/16772362/sound.zip)

**Comment by bnnm** [comment]
Fixed in the last PR: https://github.com/vgmstream/vgmstream/pull/1584

See: https://vgmstream.org/
