### ISSUE TITLE
FIFA WORLD CUP 2010-FIFA 11 .sbs .sbr files not playable

### ISSUE THREAD

**Issue by faruk1407** [vgmstream/vgmstream#1587]
Hi!
Interestingly, audio from older ps3 fifa games like fifa 08 or euro 2008 can be played on vgnstream without any issues.

Newer games like FIFA 12 and World cup 2014 also play perfectly but world cup 2010 and fifa 11 files can not be played on vgnstream/foobar. I wonder if i'm doing something wrong.

Thanks in advance

**Comment by modusc896d352** [comment]
you may need to post the files first so others can see what's up

**Comment by faruk1407** [comment]
On paper, the format is exactly the same as the other ps3 era Fifa Games. .sbr and .sbs formats. 

If i extract the files for fifa 12 or world cup 2014 on foobar2000 using vgmstream, they are fully audiable and playable but fifa 10-11 files can't be played eventhough they have the exact same file format (.sbr and .sbs "sound bank" formats)

Its difficult to post files because the file size will be relatively big.

**Comment by NicknineTheEagle** [comment]
We can't fix the the file support without having the files in the first place. If the sample files are too big for GitHub, you can upload them to Google Drive or MEGA.

**Comment by faruk1407** [comment]
https://www.mediafire.com/file/uqq31t5u72eliqp/FIFA_WORLD_CUP_2010_.SBS-.SBR_SOUND_BANK_FILES.rar/file

Here are the files. 
Thanks for all your effort

**Comment by bnnm** [comment]
The `.sbr` you posted doesn't seem correctly decompressed (presumably extracted from `.big` or similar bigfile).

Make sure you are using a proper extractor that supports compressed files, ex. https://aluigi.altervista.org/bms/ea_big4.bms

`.sbs` looks correct but probably wasn't compressed to begin with.

**Comment by faruk1407** [comment]
Yes, the files are extracted from typical .big files of ea games and when you extract the same .sbr/.sbs files for fifa 14 world cup or fifa 12, all of the audio files are automatically loaded and played without any issue. 

From what i understand, i may be missing a different file which is also related to sbr/sbs files for fifa world cup 2010.

Because ea uses multiple file formats/methods to store sound files. I remember asking here about uefa 06-07 on xbox360 and i was told that i need a .sth file in addition to the usual .hdr, .dat files and my issue was resolved.

**Comment by EdnessP** [comment]
The SBR in this case is RefPack compressed - a custom EA compression algorithm used by many of their games, easily identifiable by them starting with \x10\xFB.  (Well, the 1st byte can vary since it contains bitflags, but this is the most common config, and the 2nd byte should always be \xFB)

You can decompress them with a simple QuickBMS script such as this one:
```
comtype refpack
get ZSIZE asize
get FNAME basename
get EXT extension
string NAME P "%FNAME%.dec.%EXT%"
clog NAME 0 ZSIZE 1
```

**Comment by faruk1407** [comment]
I have no clue on coding, i extract the commentary lines and compile them/map them accordingly for an other football game, Pro Evolution Soccer. 

In other words, i have no clue on coding/decoding, unfortunately.

**Comment by NicknineTheEagle** [comment]
It's a script for QuickBMS, you don't need to compile it or anything.
https://aluigi.altervista.org/quickbms.htm
Just save the script into a text file and open it with QuickBMS, then open the target file.

**Comment by faruk1407** [comment]
Thank you so much for your help and detailed explaination! Problem solved!
