### ISSUE TITLE
[Bug] Issue playing these .wav songs in Foobar2000 (but I can play & open them normally in FL Studio)

### ISSUE THREAD

**Issue by ghyujkilop** [vgmstream/vgmstream#1588]
So these are samples taken directly from an Xbox game converted to .wav:
https://drive.google.com/file/d/1fb4-MKUGfuK8sMNOgeJapr4mf-oMOeuU/view?usp=sharing

The one is specifcally converted using the tool [Xbox ADPCM Converter](https://github.com/Sergeanur/XboxADPCM/tree/v1.2) and includes the original & converted:
https://drive.google.com/file/d/1hAr3xOUJvcx8Uup2cYJVvYk3aHWiQSV4/view?usp=sharing

Song more examples: https://drive.google.com/file/d/1OHridfoyuBtpgEpIZecvD9Mrg-lhYfzm/view?usp=sharing
-ogmusic_24_stage_succ1.wav - song stripped directly from the .xwb and converted to .wav which is playable & normal in foobar & fl studio.
-music_24_stage_succ1_pcm.wav - same as the above, only put through the XboxADPCM software. Playable in Foobar & FL Studio.
-fl studio ogmusic_24_stage_succ1.wav - takes ogmusic_24_stage_succ, but just converted it to a 44.1khz .wav using FL Studio. Plays fine in Foobar as well.
-fl studio music_24_stage_succ1 adpcm.wav - Takes fl studio ogmusic_24_stage_succ1 and puts in through XboxADPCM. Won't play in Foobar, plays fine in FL Studio.

**Comment by NicknineTheEagle** [comment]
postadpcmmusic_48_title_track_adpcm.wav plays fine in vgmstream on my end. Is your vgmstream up-to-date? You should always get the latest build from https://vgmstream.org.

**Comment by NicknineTheEagle** [comment]
I don't think I understand your question. What exactly are the files you are trying to play? vgmstream is intended to play original game files not conversions. If the game audio is stored in XWB banks then that's what you should open in vgmstream.

**Comment by ghyujkilop** [comment]
> I don't think I understand your question. What exactly are the files you are trying to play? vgmstream is intended to play original game files not conversions. If the game audio is stored in XWB banks then that's what you should open in vgmstream.

So, I've taken some .wav files from an archive called "samples.arc" these files are playing normally inputted into fl studio, but not foobar. this would likely mean that something would need to be changed in the codec to account for these game files (the samples zip i've attached). The second zip shows the original, and the converted. But that conversion, plays in game and fl studio but not foobar, so something is missing there. the third example (seperate from the samples example) gives more insight. As the same converter used allwos for the pcm from the original 24khz song to be played in foobar, but when exporitng the original as 44.1khz from fl studio, that plays normally, but then reconverting to adpcm (instead of standard pcm, as that's what the conversion software does) shows us that this version wont play in foobar, but it plays in the modified .xwb file and in fl studio. So there's missing things from the vgmstream codec, that can be added to play these extra songs that are designed (or come directly from) the game archives. both .arc & .xwb.

**Comment by NicknineTheEagle** [comment]
All files from the first zip and both files from the second zip play fine in vgmstream on my end. Is your vgmstream up-to-date? You should always get the latest build from https://vgmstream.org.

**Comment by NicknineTheEagle** [comment]
Also, if you're using foobar2000, be sure to either tick "Enable common exts" in vgmstream plugin settings or rename the files to .lwav.

**Comment by ghyujkilop** [comment]
Yeah I just installed the latest component from this github.
![image](https://github.com/user-attachments/assets/c3980425-637f-44e9-849b-222e8dde3d4b)
![image](https://github.com/user-attachments/assets/34e7a6e3-f913-49d0-84be-1ef77da50eff)
Where do I find this Enable common exts?

**Comment by NicknineTheEagle** [comment]
![image](https://github.com/user-attachments/assets/dffc8134-9019-459a-b582-e521f0ea5cef)

**Comment by NicknineTheEagle** [comment]
Get vgmstream from the official website not Github. Github releases are made at arbitrary points, vgmstream doesn't have "stable" builds. The official website always has the latest nightly build.

**Comment by ghyujkilop** [comment]
Oh my gosh, that fixed my issue, thank you! What would enable unknown exts be for?

**Comment by NicknineTheEagle** [comment]
It makes vgmstream accept extensions that aren't in its extensions list. It's disabled by default mainly to avoid interfering with other plugins or the player itself.

**Comment by ghyujkilop** [comment]
So is it better to leave that specific one disabled?

**Comment by NicknineTheEagle** [comment]
Yeah, I don't enable this unless I have to. If you run into a new extension for an otherwise supported format, you should report it so it can be added.

**Comment by ghyujkilop** [comment]
No worries. Thanks for your help! I'll close this.

**Comment by ghyujkilop** [comment]
My apologies, I do have to re-open this. I can't seem to open this .wav: https://drive.google.com/file/d/1wdA2JzMj8ACTH6sYPh9LpLrzuy3LGMR-/view?usp=sharing

and I know for a fact it works, because it works in game.

**Comment by NicknineTheEagle** [comment]
Works on my end. Double check your settings. You might need to move vgmstream to the top of decoders in foobar decoder list.

**Comment by ghyujkilop** [comment]
> Works on my end. Double check your settings. You might need to move vgmstream to the top of foobar decoder list.

yeah, I don't think I can move it higher, is there something I'm missing? I've tried with eneable unknown exts off & on to no avail, redownloaded the vgmstream.org component

**Comment by NicknineTheEagle** [comment]
Not here, on Decoding page.

**Comment by ghyujkilop** [comment]
Sweet, pulled vgmstream to the top, still no fix.
![image](https://github.com/user-attachments/assets/bc39361c-d8e0-4172-8074-f09276290301)

**Comment by bnnm** [comment]
Also works here but try renaming the extension to `.lwav` as that would force the file to be played by vgmstream

**Comment by ghyujkilop** [comment]
Is there no way to play just the .wav as is? contonuiously renaming these as .lwav will become tedious

**Comment by bnnm** [comment]
Putting vgmstream on top of other decoders **and** checking *Enable common exts* works here, so check you did all that and saved foobar's options.

You could rename via command line all files in the dir (`ren *.wav *.lwav` for example) or use CLI to drag + drop files.

**Comment by ghyujkilop** [comment]
"You could rename via command line all files in the dir (ren *.wav *.lwav for example) or use CLI to drag + drop files."

How do I do this? All of this is new to me. As long as all this means I can play these .wavs normally in Foobar, that's all I want lol

**Comment by Maxkatsur** [comment]
Same thing with _CoD: Black Ops_ (2010, PC Steam)

**Comment by NicknineTheEagle** [comment]
> Same thing with _CoD: Black Ops_ (2010, PC Steam)

This is unrelated to the OP. If you're having a problem, open your own issue.
