### ISSUE TITLE
BTSND improvements

### ISSUE THREAD

**Issue by Sukotto-1999** [vgmstream/vgmstream#1597]
I came across an issue, most .BTSNDs loop likely, but certain ones don't. An example of this was on Splatoon, the .BTSND loops as normal on hardware, but it is not looping on vgmstream.

It turns out, certain BTSNDs don't start with this hex: 00 00 00 02 rather than 00 00 00 00. My new idea is this, if the BTSND starts with a hexadecimal 00 00 00 00, then check at offset 0x04 as a loop flag. If it is anything other than hexadecimal 00 00 00 00, then looping is enabled.

Here is a comparison when i applied a txth:

[btsnd_COMPARISON.zip](https://github.com/user-attachments/files/17005747/btsnd_COMPARISON.zip)

bootSound,wav was exported from bootSound.btsnd with a TXTH

bootSoundWOTXTH.wav was exported from bootSound.btsnd without a TXTH.

**Comment by bnnm** [comment]
Fixed.
