### ISSUE TITLE
[Request] AirRider FSB file support

### ISSUE THREAD

**Issue by VigilanteOL** [vgmstream/vgmstream#1604]
The AirRider FSB files are encrypted, when I try to use vgmstream to open, it doesn't work, so seems the vgmstream doesn't support them. Here's the FSB Key:

dpdjeoqkr

Sample files: https://drive.google.com/file/d/1GyEQX-eKySEHMrJ0Lum89j3NQviHawOr/view?usp=sharing
Screenshot:
![AirRider Key](https://github.com/user-attachments/assets/6e8a3fb6-806e-4496-aaa7-67acc8f4d074)

**Comment by bnnm** [comment]
Thanks, added.
