### ISSUE TITLE
[Bug] Missing sounds on Like a Dragon: Infinite Wealth Criware ACB/AWB

### ISSUE THREAD

**Issue by Fronkln** [vgmstream/vgmstream#1608]
If you open the fighter sounds of a character in Like a Dragon: Infinite Wealth (2024) with the foobar2000 plugin, many sounds will be missing, which was not the case for the previous game, Yakuza: Like a Dragon (2020)

For example, revive_s, revive_l and state_ sound categories will be missing.

Like a Dragon:Infinite Wealth version
[gv_fighter_saeko.zip](https://github.com/user-attachments/files/17171684/gv_fighter_saeko.zip)
Yakuza: Like a Dragon version
[gv_fighter_saeko.zip](https://github.com/user-attachments/files/17171679/gv_fighter_saeko.zip)

**Comment by bnnm** [comment]
Names from .awb come from .acb. 

The .acb from Infinite Wealth you posted doesn't look correctly ripped and has excess data. If you trim it vgmstream will show subsongs names (ex. "revive" subsongs are 25-27). The correct size is at offset 0x04 plus 0x08 bytes, (or maybe check the extraction tool).

As for "missing" audio vgmstream shows all audio that there is in the file, but note that those .acb are playable (once size if fixed)

**Comment by Fronkln** [comment]
Hello, checking the ACB and the header reports 910264 bytes, adding 8 to it, and it matches the total file size of 910272 for the Infinite Wealth file.
Worth mentioning that Infinite Wealth has different voicelines even if they have much of the same sound categories, its not meant to be identical to the Yakuza: Like a Dragon one

**Comment by Fronkln** [comment]
Hello, after double checking the files and ensuring the sizes are consistent, all sounds are present again, however there seems to be a catch.

If i open the .ACB file first with foobar2000, some sounds will be missing again. If i open the .AWB file first, all sounds will be present with their names, but they will be out of order (it doesnt start with attack and damage sounds for instance.)

It's worth mentioning that only the ACB was extracted. The AWB file didnt need to be extracted and was copied from the game as is, i also verified game integrity through Steam right now so i can ensure the "integrity" of the files

I updated the files below.
[gv_fighter_saeko.zip](https://github.com/user-attachments/files/17174689/gv_fighter_saeko.zip)

**Comment by bnnm** [comment]
I'm not sure why do you say they are missing.

One .awb has 235 subsongs and the other 172 (file is smaller). That's it. Header only has that number of subsongs, plus you can check it yourself by counting the HCAs inside. If the character has more sounds probably they'll be in other files.

**Comment by Fronkln** [comment]
I meant "missing" in the context of foobar2000 not picking up on them.
I ended up looking more into this and the problem was mainly due to me confusing the behavior of this plugin to other tools that view/modify this format. I was assuming foobar2000 would automatically load the AWB along with the ACB when opening (very common for criware modding tools like [Sonic Audio Tools](https://github.com/blueskythlikesclouds/SonicAudioTools) and thought the plugin itself was broken because it didnt do that, after opening the ACB and loading the AWB on top of it as well manually, everything was fine, sorry to take your time. I will update the issue for anybody that may run into this in the future

**Comment by bnnm** [comment]
That's correct, vgmstream just plays the internal waves from each acb/awb rather than fully simulating how acb+awb works, on purpose.

More info: https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#cue-formats
