### ISSUE TITLE
[Request] TMNT Mutant Melee

### ISSUE THREAD

**Issue by leop2p** [vgmstream/vgmstream#1612]
Hi there!!!

Could you please add support to "Music.mcp" archive, contains music tracks from the game.

I will provide you the archives to PS2 and to PC game version. Please make a preference to a PC version, because there's more filesize than PS2. Maybe in PC version packed quality is better.

https://mega.nz/folder/SkV0yIRI#nfiSmoycqNrSYn1ba6uR6g

Thanks!!!

**Comment by leop2p** [comment]
Ojj thank you very much!!! Thank you!!!

**Comment by leop2p** [comment]
Could you please tell me, is there same sample rate (32 KHz) for XBox version?

https://mega.nz/file/7osCQLKD#qDk5piyKXWevcdEw8ivz2vO7S2EOBEeG0ei1M7yCPp4

**Comment by NicknineTheEagle** [comment]
```
codec = XBOX
sample_rate = 44100
channels = 2
num_samples = data_size
```

**Comment by leop2p** [comment]
Thank you
