### ISSUE TITLE
Project IGI wav files

### ISSUE THREAD

**Issue by AntonZab** [vgmstream/vgmstream#1616]
Hello. How about support Project IGI wav files (Inner Loop Sound File)?

https://drive.google.com/file/d/13T3jH2S6neDIEcRo1H3t9YsZf9DkO1Qf/view?usp=drive_link

**Comment by bnnm** [comment]
Should work if you unzip this file into the music folder and open each music file: [txth.zip](https://github.com/user-attachments/files/17533410/txth.zip)

You may need to rename .wav to .lwav, or change player's priority so vgmstream plays .wav first ([>>](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#common-and-unknown-extensions))
