### ISSUE TITLE
[Request] Support for Red Dead Redemption (PC) .AWC

### ISSUE THREAD

**Issue by Puterboy1** [vgmstream/vgmstream#1626]
I can't play them in Foobar.
[weather.zip](https://github.com/user-attachments/files/17612486/weather.zip)

**Comment by leop2p** [comment]
Hi!

I'm not from support of VGMStream, but I was able to play *.awc in VGMStream, only for XBox 360 version. It plays correctly. Format is **XBox Media Audio 2**, 32 KHz (for music).

Maybe this helps.

I think VGMStream Team will add support for AWC for the PC-version of the game.

Good luck!

**Comment by bnnm** [comment]
added
