### ISSUE TITLE
[Request] Medal of Honor: Frontline (XBox)

### ISSUE THREAD

**Issue by leop2p** [vgmstream/vgmstream#1629]
Hi there!!!

I think, the music is stored in **...StrBnk.ast**. But I'm not sure. There are several folders inside **DATA** named **1**, **2**, **3**, etc. Inside, for example, folder **1** there are subfolders **1_1**, **1_2** etc. Inside each that folder almost the same filenames. And, for example, inside folder **1_1** there are file named **11StrBnk.ast**. It structure starts with **SCHl**. It's in every file **...StrBnk.ast**. Maybe the name is "Stream Bank". I think, the music is stored inside the files with that name.

I have provided full directory **DATA\1** with the subfolders. Please pay attention on the file I provided. Or maybe I wrong and the music is stored inside an other file.

https://mega.nz/file/PtsknSAJ#V-TG37CIfIlSzmdL5fzc6sdWVkVAZjesXoNlD5PjTuo

Could you help me to listen the music through VGMSTREAM?

Thanks!!!

**Comment by bnnm** [comment]
Link does not work.

For .ast you typically need to open .abk of the same name, so post some of those .abk if they don't work.

**Comment by leop2p** [comment]
Yes, I figured out that the mus is stored inside *.mus files. I have extracted them with ADPCM Player then extracted *.SNG load to vgmstream. Everything is fine. Thank you!
