### ISSUE TITLE
[Request] Just Cause 4 (FMOD)

### ISSUE THREAD

**Issue by leop2p** [vgmstream/vgmstream#1633]
Hi there!!!

There's a bank file **streaming_music_score_global.bank**, if rename it to **streaming_music_score_global.bank**, it plays with vgmstream, but there's no correct filenames. Could you please help me, how to play it in vgmstream with the correct filenames?

I provided an original **streaming_music_score_global.fmod_bankc** and extracted ***.fsb** file.

https://mega.nz/folder/P49k0ZIT#Swz3bkmnnhSi5cw6ITUslw

Thanks!!!

**Comment by bnnm** [comment]
When I play the file in foobar or winamp I see various names:
```
 streaming_music_score_global.fmod_bankc#1 (mus_exp_grassland_flying_ruin_layer_03)  
 streaming_music_score_global.fmod_bankc#2 (Combat07_Main_Intense_01_FinalMix)  
 streaming_music_score_global.fmod_bankc#3 (SB02_CombatG02_Intense01_PM)  
 ...
```
And so on.

Not sure what do you mean by "there's not correct filenames". These are the only names in the .fsb, in that order.

**Comment by leop2p** [comment]
Yes, the filenames are correct.
