### ISSUE TITLE
[Request] Atract 9 from Days Gone not reading

### ISSUE THREAD

**Issue by leop2p** [vgmstream/vgmstream#1635]
Hi!!!

There's several at9 files, but they not playing through vgmstream. Rest of at9 files are playable. What could be wrong?

Thanks!!!
[at9.zip](https://github.com/user-attachments/files/17892417/at9.zip)

**Comment by EdnessP** [comment]
It appears the `data` chunk size is bad for all of these (which in turn also makes the `RIFF` chunk size bad.)  The main concern is that the amount of bytes it's off from the real value is not consistent - 0xE9 for 01a, 0x159 for 02a, 0x184 for 03a, you get the point.  (Also seems like `data` size here is always aligned to 0x80?)
If it were off by a constant amount, that fix could probably be [added to vgmstream itself](https://github.com/vgmstream/vgmstream/blob/f1483e22bb395e2824e3231983085a9e9bb24f71/src/meta/riff.c#L411).  (I suppose one could check for a size range instead)

**Comment by bnnm** [comment]
afaik Days Gone uses .xvag w/ interleaved at9 so they should work if those .xvag were properly extracted.

It would be nice if people explained what they did to get files instead of posting them without context though.

**Comment by leop2p** [comment]
I extracted .pak with BMS script. If you need one, I could attach it. Then in **Audio\Music\Stream_Data** all ***.at9** and ***.xvag** plays perfectly in vgmstream except 9 ***.at9** files. There's message on them, says **"Missing ACM Codec"**. There's no corresponding ***.xvag** with the same name of that 9 files. What information I can give you to help me fix the issue? Thanks!!!

**Comment by bnnm** [comment]
Post the .pak and the bms, to check if the bms didn't extract correctly.

**Comment by leop2p** [comment]
[unreal_tournament_4_0.4.25e.zip](https://github.com/user-attachments/files/17969425/unreal_tournament_4_0.4.25e.zip)
https://mega.nz/file/6kcVXYzL#sGEBACoWi2uoSi5_yolve8Oa050UHq_6fhgl82ANa7o

**Comment by bnnm** [comment]
The files look correctly extracted from Unreal Engine packages. They can be found as-is raw in `.pak`. On further inspection they seem corrupted with random extra bytes that mis-align ATRAC9 frames and aren't actually valid .at9. 

However every file has a similar name one is playable though (`mx_451_sys_camper_hi_outro_01a.at9` > `mx_451_sys_camper_hi_outro_01.at9`). Given all other .at9 seemingly work probably the corrupted files (`(name)_XXa.at9`) where included by mistake.

Surely those can't actually play in game. Sony's original AT9 tools also reject them as invalid and can't decode them, so I don't think we can (or should) fix them either.
