### ISSUE TITLE
About the application on muv luv dimensions

### ISSUE THREAD

**Issue by shibasoraya** [vgmstream/vgmstream#1645]
I'm trying to parse a file called muv luv dimensions.
It's a game and it uses .acb and .awb format files.
But when I try to read them using vgmstream, the sound released is very sharp and unintelligible
And the file size became very large, the original file was about 1.74GB, but after using vgmstream it was 12GB

Here are some of the game files, hope this helps
https://mega.nz/folder/S3I0kAaC#ws7mVFraOGNRFZrX_x7ttA

**Comment by bnnm** [comment]
Added key. Not sure what "file size became very large" means, try using foobar2000 to listen to files instead.

**Comment by shibasoraya** [comment]
> Added key. Not sure what "file size became very large" means, try using foobar2000 to listen to files instead.

Thanks a lot , it works.
