### ISSUE TITLE
Koei Tecmo ATSL4 Support

### ISSUE THREAD

**Issue by bxaimc** [vgmstream/vgmstream#199]
@bnnm paging doc bnnm, you've got a familiar patient all grown up.
from Nobunaga's Ambition: Sphere of Influence (PS4)

[KT-ATSL4.zip](https://github.com/kode54/vgmstream/files/1761109/KT-ATSL4.zip)

Plus some container for SFX (I think)
[res_snd.zip](https://github.com/kode54/vgmstream/files/1761118/res_snd.zip)

**Comment by bnnm** [comment]
ATSL4 should work now.

res_bin is a "LINK" bigfile which is similar to G1L. Contains .wbd ("_DBW") and .wbh (_HBW) that look like sfx packs with subsongs. Also used in other games like Bladestorm, I'll add to the research pile.
