### ISSUE TITLE
Relying on extensions too much?

### ISSUE THREAD

**Issue by NicknineTheEagle** [vgmstream/vgmstream#218]
I've noticed that there's a lot of assumptions in the code based purely on file extension which is not exactly a good practice since extensions by themselves rarely mean much.

https://github.com/kode54/vgmstream/blob/master/src/meta/ps2_mib.c#L279
Here's a pretty nasty example, the code automatically assumes sampling rate and channel count from extension; this is especially bad for "vb" since, AFAIK, VB a common extension used for PS1 sound banks which can contain several SFX with different parameters.

**Comment by bnnm** [comment]
I don't think that's a good example, since that's an ancient parser that hackily tries to support completely headerless PS2 files, purely for convenience.
A check that the file is indeed PS2 sound data should be added (so it would ignore PS1 .vb), but as you can see that parser's code isn't the easiest to tweak.

In other, more modern parsers I think there are adequate validations in place, but sometimes the extension is the easiest (and maybe only) thing to tell similar formats appart.

**Comment by NicknineTheEagle** [comment]
Yeah, that parser is indeed a mess. It should definitely be refactored at some point since it appears to be used as a universal scapegoat for headerless files.

Speaking of which, I don't think trying to support headerless files is a good idea since there's no way they can be validated and there's no way to get parameters (codec, sampling rate, ...) for them other than making hardcoded assumptions which is also unsafe.

It seems especially unnecessary with the recent introduction of TXTH and TXTP generic headers which are less bothersome to set up than GENH.

**Comment by AnonBaiter** [comment]
i think it's better to recode how extensions are handled so headerless extensions like .mib/.cvs/.vb and etcetera can be considered "reserved" for TXTH/TXTP.

although TXTP was only built for playlist building, which means that its features won't get you much in the way of anything.

**Comment by bnnm** [comment]
I've cleaned mib a bit so it rejects non PS-ADPCM files.

While I agree it's no good I don't want to outright remove it as it'd break a bunch of existing rips with no real benefit. Also note that this parser finds loop points automatically by checking data flags, something that isn't replicable with GENH/TXTH ATM.

**Comment by NicknineTheEagle** [comment]
Is re-uploading existing rips such a no-no? Otherwise you can update them with TXTH header.

**Comment by kode54** [comment]
Re-uploads are welcome, so long as they're targeting newer VGMStream. I think.

**Comment by AnonBaiter** [comment]
well i'm just re-ripping the original singstar game with all the filenames and extensions intact(.mih+.mib for example) so...

**Comment by bnnm** [comment]
Well there would be a lot of sets to re-rip...

**Comment by bnnm** [comment]
I've changed it so MIB+MIH are handled separatedly, and headerless PS-ADPCM is autodetected *last*, so TXTH has a chance to work first (it couldn't before). Also added "loop_flag = auto" in TXTH to do the same loop autodetection. 

Now it goes last it's mostly harmless (if butt-ugly), as you can simply add a quick TXTH to any offending sets, so I don't think there is much else to be done here.

(I'll also mention TXTH/vgmstream work with extensionless files too, in case your bigfile of choice doesn't have an extension in sight, or one could use .vgmstream).

**Comment by NicknineTheEagle** [comment]
Excellent, this is a much cleaner setup.
