### ISSUE TITLE
[Request] Support sound files for Cyberflix games

### ISSUE THREAD

**Issue by Puterboy1** [vgmstream/vgmstream#295]
Including Titanic: Adventure Out of Time. Here are the files and see what you can do with the ones labeled “.trk” and “.sfx”: 
https://drive.google.com/open?id=1a1FEG442cVNe8madItRr6K08QOvKTJmA

**Comment by bnnm** [comment]
All files seem to use a generic container. You should ask in zenhax/xentax if somebody would be able to extract them.

**Comment by Puterboy1** [comment]
Here: 
http://forum.xentax.com/viewtopic.php?f=10&t=17905&hilit=Titanic
