### ISSUE TITLE
Metal Gear Solid 3 (PS2) - *.psq

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#374]
[psq_samples.7z](https://www.sendspace.com/file/uztrke)
i used no compression algorithm for packing psq files into a 7z archive file, and quite frankly i'd rather not.
if you need/want more samples for this format, let me know.

**Comment by AnonBaiter** [comment]
link is offline now, i could re-upload it but i'm not in the mood to actually do so right now

**Comment by AnonBaiter** [comment]
okay,here's a new link.
[metal_gear_solid_3_psq](https://1drv.ms/u/s!Asofkpy7aqyKqz9LLXNq2GLuq9de?e=As5yHk)

forgive me if there are inconsistencies between the sendspace link and this link for those who downloded the sendspace one, but i wanted to have a fresh link of sample files out of this issue and to compensate for that i started to document some stuff regarding the .psq format that MGS3 uses.
