### ISSUE TITLE
Ubisoft's early PS2 games - unsupported sound files(bnm-ish format)

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#404]
here goes nothing

---

F1 Racing Championship (PS2)
---

[[f1_racing_championship_ps2]sound.7z](https://drive.google.com/open?id=1RRvdomRSYrCUyHqkrWOmFhKtmacDvowf)
well, i just had to upload the entire sound directory of the PS2 version of this game
compared to the others the size here is relatively light which makes for some WYSIWYG stuff here

Disney's Dinosaur (PS2)
---
[[disneys_dinosaur_ps2]sound.7z](https://drive.google.com/file/d/1skbEX8b7K5dKQ9GspYz7ZKbEu3OPO6ax)
also this
in fact i was just about to upload the whole sound directory of this Dinosaur PS2 game when i realized that posting the full(900MB) version here meant waiting for 4-5 hours until the file would be actually 100% uploaded at all so i selected only a single folder, a few files here and nothing else

Rayman Revolution (PS2)
---
[[rayman_revolution_ps2]sound.7z](https://drive.google.com/open?id=1fq697k6BFfxc-zcKp_JSUxI6X2DU1kJ7)
the sound directory for this PS2 version of that one Rayman 2 game contained nothing but .DSC/.BF archive files that could only be extracted using aluigi's [hype_time_quest.bms](http://aluigi.altervista.org/bms/hype_time_quest.bms) script through the quickbms app, then i had to organize them into the structure you're seeing now
the full size of this directory weighs at about 2.58GB, which is way bigger than what Dinosaur has so i just choose to select a few files here and there

Hype The Time Quest (PS2)
---
[[hype_the_time_quest_ps2]sound.7z](https://drive.google.com/file/d/1qsbIgjEMdgMu6Otski0ARGw0Mlhdq-TD)
the sound directory for this PS2 version of this game had nothing but three .BF files(that's right, not .DSC/.BF files, actual stand-alone .BF files) and four folders containing VSC files in just about every corner
i had to write a script for the .BF files which you can find [right here](https://github.com/AnonBaiter/le_quickbms_script_compendium/blob/master/hype_the_time_quest_ps2_sound.bms)

---

well that was pretty much _it_

**Comment by AnonBaiter** [comment]
first post updated with full sound directory of Hype The Time Quest (PS2) now available.

**Comment by AnonBaiter** [comment]
okay, so the focus of this issue will be changing.

what will this be instead is supposed to be a sample repository containing numerous sound files from various Ubisoft games that i've personally picked over the days. this repository aims to help further development in vgmstream when it comes to these files, although i might not include files using formats that vgmstream already supports(Ubisoft's WAVE mod for Jade engine, Ubisoft HXSound in its entirety, etc.).

**Comment by AnonBaiter** [comment]
fine, here it is.
[ubisoft_sounds](https://1drv.ms/u/s!Asofkpy7aqyKpxa5bAB64mzIvurL?e=CezDcv)

i'll be documenting cranium kabookii format soon enough.

**Comment by AnonBaiter** [comment]
okay, deleted all of the files contained there *except* the text file after lurking through this repo's recent commits. i'll bring up new files whenever i can.

**Comment by AnonBaiter** [comment]
okay, i deleted everything now. i'll contribute something else from their games when i feel like it.

**Comment by AnonBaiter** [comment]
(non-language) sound files from the Xbox version of **Tom Clancy's Ghost Recon Advanced Warfighter** are now up.

**Comment by AnonBaiter** [comment]
all (English) sound files from the Windows version of **Walt Disney's The Jungle Book: Groove Party** are here for about one week.

**Comment by RetingencyPlan** [comment]
right, i lied about the "one week" thing.
Jungle Book files have been taken out, no further files will be brought into the onedrive link at this time.

**Comment by bnnm** [comment]
Note that PS2 .bnm works now (a few tracks should be fixed soon).

**Comment by RetingencyPlan** [comment]
glad to hear.

**Comment by RetingencyPlan** [comment]
the sound files from the GameCube version of **Surf's Up** are now here.

**Comment by RetingencyPlan** [comment]
i'm currently updating the onedrive link with new stuff.

**Comment by RetingencyPlan** [comment]
now i would like to report one bug.
so i was playing some Rayman 2 (Dreamcast) music when i found out foobar2000 (for anyone caring about "latest versions" or whatever i'm using version 1.6.2 beta 1) doesn't like BNK_63.DAT at all.
literally every subsong i've tried to play out of that file through foobar2000 i was greeted with this.
```
Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 1

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 2

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 3

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 4

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 5

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 6

Unable to open item for playback (Object not found):
"H:\Sega - Dreamcast\RAYMAN_2_THE_GREAT_ESCAPE [Recovered File System]\DCDATA\SOUND\vgm_hcs64\BNK_63.DAT" / index: 7
```
this happens to literally every subsong vgmstream can handle out of that file.

here are the relevant sample files for this just in case.
[BNK63_foobar2000bug](https://1drv.ms/u/s!Asofkpy7aqyKvkLcR_Zj7lWfzgk0?e=cagWYJ)

BNK_63.DAT works fine with test.exe, no issues with it so far.

**Comment by NicknineTheEagle** [comment]
Fixed here: https://github.com/losnoco/vgmstream/pull/719
Note that some entries in Rayman 2 banks reference non-existent external files (e.g. JINGL7.WAV), they'll show up as failed subsongs, nothing I can do about that.

**Comment by RetingencyPlan** [comment]
OK, sorry about the silence. here's what i brought to the table:
the bao files from the PS3 and Xbox 360 versions of that one Beowulf game
and all the sound files from Naruto: Rise of a Ninja

that's it.

**Comment by RetingencyPlan** [comment]
ubisoft_sounds has been updated with the following items
**_[microsoft_windows]largo_winch_empire_under_threat_** - an entire folder containing hxd files from the Windows version of that Largo Winch game from 2002
under vgmstream, they are treated as MP3 files and literally nothing else.
and i managed to decompress a bunch of files from the Xbox 360 version of Assassin's Creed.
the result is in **_ac1_xbox360_bao_samples.7z_**

**Comment by bnnm** [comment]
I think all of the above is covered and is hard to notice updates, so closing for now. Probably best to open a new issue if more of those surface.
