### ISSUE TITLE
help: PPEF/PPHD/PPPG header, it seems like hd3_bd3 structure

### ISSUE THREAD

**Issue by EmirioBomb** [vgmstream/vgmstream#433]
Here is a file
10.pck: [https://www.dropbox.com/s/tc454qk8wkrzp7v/10.pck?dl=0](url)
I just can confirm the relationship of the address
![5](https://user-images.githubusercontent.com/27725119/60381355-41b22580-9a86-11e9-82c1-9241d8ef419a.jpg)

**I think 10.pck looks like hd3_bd3 format, so I cut 10.pck as two files.**
**1. 10.hd - PPEF Header**
-> cut from 0x30 to 0x59800, file size = 597D0(light green color, marked as above figure)
**2. 10.bd -> Main Data block**
-> cut 0x59800 to the end

I have no idea about audio format, so would anyone like to tell me how to do this?
I think **10.hd&10.bd played as like hd3_bd3 format**, but I don't know how to vgmstream.
Or, is it possible add to vgmstream?

Any help will be greatly appreciated!!!! Thank you guys

**Comment by bnnm** [comment]
To be able to add it to vgmstream you need to post many samples (preferably original files if they were extracted from some bigger file) and the name of the name, at least.

**Comment by EmirioBomb** [comment]
> To be able to add it to vgmstream you need to post many samples (preferably original files if they were extracted from some bigger file) and the name of the name, at least.


Thank you for your prompt reply.
It's a good news for me, thank you, bnnm!!!
Here is the all the samples.
[https://www.dropbox.com/s/71h9c8ooxou6s6y/voice.rar?dl=0](url)
All of them are extracted from
PSV tales of innocence R, l7ca script
You guys really do a great job!!
