### ISSUE TITLE
(Linux) "vgmstream123" Does absolutely nothing beyond print help or respond to the -h switch.

### ISSUE THREAD

**Issue by KynikossDragonn** [vgmstream/vgmstream#455]
I have absolutely no idea what I'm doing wrong either. Everything seems to have compiled just fine, ldd shows it can find all it's shared libraries... but no matter what I try to do it just instantly returns with no message, no output, nothing.

What exactly am I doing wrong?

**Comment by bnnm** [comment]
Should be fixed.

**Comment by KynikossDragonn** [comment]
It's now properly entering playback but if it ends for any reason the process freezes with 100% CPU usage and will only respond to SIGTERM or SIGKILL at this point.

**Comment by bnnm** [comment]
Works fine on Windows but I can't test on Linux easily. Try going to cli/vgmstream123.c and comment lines 702 throgh 713, could help (those are recent additions I'm not sure of).

**Comment by froggestspirit** [comment]
not sure if this is the same issue, but playing target.hps (super smash bros melee) with -r for infinite looping, the song still fades to silence after 2 loops, but doesnt free the terminal (maybe its looping infinitely silently?)

**Comment by bnnm** [comment]
It seems -r just repeats (or should, if it was working) after song fades+ends. I can't add infinite looping nor fix this at the moment (possibly later after plugin code is more unified), you could use a big number of loops to get pseudo-infinite loops for now.

**Comment by bnnm** [comment]
I've added a proper -p to play forever and I think I've fixed -r and all parsing problems (getopt behaving differently in various Linux flavors, gee thanks).
