### ISSUE TITLE
[Request] Support for .wavloop extension

### ISSUE THREAD

**Issue by dokutoku** [vgmstream/vgmstream#482]
[Request] Support for .wavloop extension

I would like to support music files in the .wavloop format supported by foo_input_wave_loop.
This extension reads the loop information stored in the wav file with the following priority.

1.Loop information stored in smpl chunk
2."LOOPSTART" and "LOOPLENGTH" stored in ID3 tag

foo_input_wave_loop
https://slemanique.com/software/foo_input_wave_loop.html

**Comment by bnnm** [comment]
We would need some file examples (and the name of games using them).

Note that vgmstream already plays .wav files with "smpl" if renamed to .lwav, and also .ogg renamed as .logg with LOOPSTART/LOOPLENGTH tags. I haven't see ID3 tags with LOOPSTART/LOOPLENGTH though.

**Comment by dokutoku** [comment]
This format is only for foo_input_wave_loop, and no game is adopted.

I converted RPG Maker and other loop music to .wavloop to play loop music.
I requested that I want to play the file as it is.
