### ISSUE TITLE
[Filetype question (Wii)] Monster 4x4 World Circuit GSB/GWB/GWD files 

### ISSUE THREAD

**Issue by Mtik333** [vgmstream/vgmstream#582]
Hello,

I've tried to investigate files found in WBFS file of Monster 4x4 World Circuit. After using NKit, I managed to get some files from the image. In the path that contains a bunch of audio files I believe, every background music file seems to be split into three files: GSB, GWB, GWD.

I'm not sure if I should ask here, because the only work that I did here was to extract that, and I have no knowledge regarding identifying what type of audio this really is. Maybe someone here might have time to look at this. I can provide other files if required (I guess main.dol might be useful)

Obviously it cannot be played in fooplayer with the plugin, but I don't think there's any software capable of streaming this file.

[extrabgm.zip](https://github.com/losnoco/vgmstream/files/4362906/extrabgm.zip)

**Comment by bnnm** [comment]
Works now.
