### ISSUE TITLE
.sbr/.sbs - some files are not decoded/extracted

### ISSUE THREAD

**Issue by vergol** [vgmstream/vgmstream#592]
I found some files in FIFA 20 (Switch) which can't be decoded/extracted with vgmstream (I'm checking with Winamp plugin).

.DUR section - **resolved**
https://mega.nz/file/jkcnxIID#0hOsDc9EH581xfg-HGygnYMufmnUrAXEknbxNpjjRMw

easpeex codec - **needs EASpeex decoder**
https://mega.nz/file/blF3hQAQ#TpcnCxmFMZ48KEspHUmD_BslhiSuhAr-hIeDh3fxzWE
https://mega.nz/file/7lUl3IYJ#fJRb4tRB6b-DO2i3_yEhR-4ISdku8nGbpAphtHv-tw8

EAOpus, not decoded/extracted (without .DUR)  - **resolved**
https://mega.nz/file/XtsGXQRa#nmz3uk-55uJnjEDmE4eYPCoLSIjyGuXvebqKZyWAhyA
https://mega.nz/file/O11QnIzA#YqxcKzQJBPhonYFTOY_AnDcReBnQbO4cM98RWWICOLY

**Comment by NicknineTheEagle** [comment]
Let me guess, is this EASpeex? It's not implemented at the moment. @bnnm had it on the backburner for a file.

**Comment by vergol** [comment]
The first file (with .DUR section) is eaopus.
Next 2 use easpeex.
Fourth is also eaopus.

**Comment by NicknineTheEagle** [comment]
Tried the fourth archive in foobar, they just play silence. Possibly a decoder bug?

**Comment by vergol** [comment]
You're right, sorry. The fourth file was a silence.

**Comment by NicknineTheEagle** [comment]
The first file plays after I added code to skip .DUR section.

**Comment by vergol** [comment]
Ok, great.
I found some other files, added to the first message:
eaopus, but without .DUR section.

**Comment by NicknineTheEagle** [comment]
Alright, I think I got these solved, watch for my next PR.

**Comment by NicknineTheEagle** [comment]
https://github.com/losnoco/vgmstream/pull/593
Try AppVeyor build from here, this should work with everything sans EASpeex files.

**Comment by vergol** [comment]
I checked on some other files, and everything works now.
For EASpeex, I saw that some people made a tool for it and they used some library, probably obtained from game files.
Fortunatelly, those files with EASpeex were not very important for me.
Thank you.

**Comment by NicknineTheEagle** [comment]
Keeping it open for now due to EASpeex support being wanted.

**Comment by vergol** [comment]
In case if more EASpeex examples needed, here are some files from FIFA 14 (PC)
https://mega.nz/file/jpFj1QIJ#vB07z9Z9owtP-tS-ZqcOlvu705MtLgReTLVZ9QYDtrU

**Comment by bnnm** [comment]
EASpeex is now supported: https://vgmstream.org/downloads
