### ISSUE TITLE
Guitar Hero III (360) FSB Artefacts

### ISSUE THREAD

**Issue by ACheapLemon** [vgmstream/vgmstream#639]
When converting the fsb.xen files found in the MUSIC directory of the 360 versions of Guitar Hero III and Guitar Hero Aerosmith, as well as the GH3 DLC, occasional sounds similar to that of a muted strum effect appear that are not in the original audio, usually audible during silent parts of the tracks in songs like Through the Fire and Flames, seemingly exclusive to the right channel.

Another example can be heard in We Three Kings just before the first note of the song, among many other songs like Cliffs of Dover, Barracuda, etc.

**Comment by bnnm** [comment]
You'd need to post some samples so we can check.

Something that specific may mean the files are like that, just that it isn't very noticeable in-game.

**Comment by ACheapLemon** [comment]
Here are some example .fsb.xen files for Cliffs of Dover, We Three Kings (DLC36) and Through the Fire and Flames. https://drive.google.com/file/d/1VNMalg6ih1YMSjeRUqXyCfD6dkvfgirT/view?usp=sharing

The .xen extension is applied to all files in the game and is just used to determine what platform the files are from. The PC version also has .xen, Wii has .ngc, PS3 has .PS3, etc.

For TTFAF in particular, the sounds appear regularly throughout the audio. Here's a comparison of the 360 conversion of the first track (top) which was encoded as an .xma file, and the PC version (bottom) which was encoded as .mp3. https://i.imgur.com/LApdtGK.png
Normally we'd just use the PC versions to work around this, despite being lower quality, but the DLC was only released on PS3 and 360, with the Halo Theme DLC in particular being 360 exclusive.

**Comment by bnnm** [comment]
I've checked it's a bug in the decoder we are using (FFmpeg). The glitches don't happen with Microsoft's decoder.
Unfortunately this can't be easily fixed at the moment.

**Comment by bnnm** [comment]
This seems fixed now.
