### ISSUE TITLE
(Request) Support for .l1g and .xws files

### ISSUE THREAD

**Issue by Mysticus92** [vgmstream/vgmstream#658]
Please, add these .l1g and .xws extension for vgmstream from Team Ninja games like Dead or Alive 5 Last Round.

[CHAR_VOICE_000_EN.zip](https://github.com/losnoco/vgmstream/files/4865426/CHAR_VOICE_000_EN.zip)
[SOUND_001_EN.zip](https://github.com/losnoco/vgmstream/files/4865430/SOUND_001_EN.zip)

**Comment by bnnm** [comment]
.l1g/g1l is a too simple bigfile container, (and contains files that contains subsongs) so probably can't be added. I suggest finding some extraction .bms

As for xws, you'd need to post multiple samples (not one) and the game/platform of origin.

**Comment by Mysticus92** [comment]
Here's more xws files.
They're from the game called Dead or Alive 5 Last Round (Steam).
[Dead or Alive 5 LR rips.zip](https://github.com/losnoco/vgmstream/files/4897061/Dead.or.Alive.5.LR.rips.zip)
While for l1g files I successfully extracet and they are in .kov files that unfortunately are not playable yet for Foobar2000.
Do you plan to add the .kov extension?
[CHAR_VOICE_000_EN.zip](https://github.com/losnoco/vgmstream/files/4896170/CHAR_VOICE_000_EN.zip)

**Comment by bnnm** [comment]
You need to rename .kov to .kvs.

**Comment by bnnm** [comment]
I would need many more .xws from more games.

**Comment by Mysticus92** [comment]
Dead or Alive 5 Last Round (Steam)
https://drive.google.com/file/d/1uD-awQh5-GDENVG_vXOJ0JFTmYKHOR22
Ninja Gaiden 3 Razor's Edge (PS3)
https://drive.google.com/file/d/1bc5_xWhoqVdBLIg-cIkjvEj6jcxEq-Y3

**Comment by Mysticus92** [comment]
Ninja Gaiden Sigma 2 (PS3)
https://drive.google.com/file/d/1jL1pw-KAS7cOaE1uXZU4mITw-KmocZ10

**Comment by Mysticus92** [comment]
Thanks for adding the .xws file support.
But it still doesn't work for some reason.

**Comment by bnnm** [comment]
Still working on it, there are multiple, different .xws.

**Comment by bnnm** [comment]
All should work now: https://vgmstream.org/downloads

**Comment by Mysticus92** [comment]
Bless you bnnm!
Thank you very much!
