### ISSUE TITLE
.CWAV (CompressWav) Format?

### ISSUE THREAD

**Issue by Tenome** [vgmstream/vgmstream#666]
Would it be possible to implement support for the CWAV format? It seems to be a compressed WAV branch that was implemented in some Japanese games in the 90's-00's. The author apparently stopped working on it around 2007. On one hand, it seems to be fairly uncommon, so it's not at all a priority. But hey, maybe it's an easy implementation. Just thought I'd mention it since I'm not the first to need to convert this format.

JP Wiki:
https://ja.wikipedia.org/wiki/Cwav
Library + Player:
http://kota.dokkoisho.com/#cw
Conversion program (seems to have the source code included) + sample CWAV songs:
https://mega.nz/file/Bh5nXYwD#CSQiXhT-OIr_md1hyyP7BMI5tyUROj8IwWHmYh2-A9s

**Comment by bnnm** [comment]
I think it's possible, and has the source (in Pascal, of all things). It's a bit complex though.

However you need to post the name of the game(s) using this, as the links are sparse in details.

**Comment by Tenome** [comment]
Ah, sorry, didn't think it mattered. The game is an old doujinshi shoot 'em up, RADIO ZONDE.

**Comment by bnnm** [comment]
Usually, the more a format is used the better chance it has to be added (more games benefit).

Conversely, if I can't verify an actual game uses the format it has almost no chance, vgmstream only handling game music and all.

**Comment by Tenome** [comment]
Understandable. Personally I've only encountered it in Radio Zonde so far, but I also haven't played many Japanese PC games from the 90's-00's like the Wiki suggests exists. Here's a screenshot of the game folder.

https://puu.sh/G6Tij/001ec7d863.png

**Comment by bnnm** [comment]
.cwav works now: https://vgmstream.org/downloads
