### ISSUE TITLE
Fantasy Earth Zero (PC/.wav)

### ISSUE THREAD

**Issue by alittlered** [vgmstream/vgmstream#747]
update1:
[https://mega.nz/file/7X4GWKqB#QRkT2J0Zj3NLAM5MlMLDr9zcn9rcQWMtXsS6p0JVVmo](https://mega.nz/file/7X4GWKqB#QRkT2J0Zj3NLAM5MlMLDr9zcn9rcQWMtXsS6p0JVVmo)
site(JP) [http://www.fantasy-earth.com/](http://www.fantasy-earth.com/)

**Comment by bnnm** [comment]
Post many more example files.

**Comment by alittlered** [comment]
> Post many more example files.

updated

**Comment by bnnm** [comment]
All the files seem to use some complex encryption.

There is not much to do here, that's better suited for xentax/zenhax.
