### ISSUE TITLE
FatalFrame5(WiiU/.sed .whd)

### ISSUE THREAD

**Issue by alittlered** [vgmstream/vgmstream#748]
[ff5vo_up1](https://mega.nz/file/SKxADCjT#XWfp1wH9xogB3HsocO86vPB5s8sw5iif0eOF9KMUHpE)
similar thread [https://forum.xentax.com/viewtopic.php?f=17&t=22893](https://forum.xentax.com/viewtopic.php?f=17&t=22893)

**Comment by bnnm** [comment]
Post many more example files.

**Comment by alittlered** [comment]
> Post many more example files.

updated
I didn't change the filename this time, the original extension is ".sed"

**Comment by bnnm** [comment]
.sed should play now: https://vgmstream-builds.losno.co/

.vcpk must be extracted first and files named .dsp to play.

**Comment by alittlered** [comment]
Thanks.
