### ISSUE TITLE
[Request] Tom Clancy's Rainbow Six Siege (PTADPCM?)

### ISSUE THREAD

**Issue by FatalBulletHit** [vgmstream/vgmstream#752]
I'm trying to convert wave files extracted from Tom Clancy's Rainbow Six Siege ".pck" files. They used to be extracted as ".lwav" files (wwise adpcm) but since an update are extracted as ".wav_unknown" and not convertible anymore.

I tried different tools and using https://github.com/MRWITEK/wwise-adpcm-to-wave-adpcm I ended up getting this error: "File doesn't seem to be (Wwise) IMA ADPCM wave. It has format ID 0x8311 and bit depth 4.".

Searching for "0x8311" lead me here but vgmstream fails to open the files.

I'm not sure if the files are Wwise PTADPCM so here are a few samples; https://mega.nz/file/AhZSgZaK#y3VVwgWe1tN4NfVgP-H1iX5RmhZ2D7SU4lkJ-yZsYLU

**Comment by bnnm** [comment]
They play if renamed to .wem (correct extension).

Also try a better .pck extractor, for example: https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms

**Comment by FatalBulletHit** [comment]
Thank you very much!
