### ISSUE TITLE
[Request] Support fusers .uexp file format

### ISSUE THREAD

**Issue by Crafty-The-Fox** [vgmstream/vgmstream#755]
From the looks of it, Fusers audio files are encrypted .mogg files (like rock band 3) inside of a .euxp file, and the .euxp files are inside of a .pak file. im assuming you already have a sample of it, if not i can send one.

**Comment by bnnm** [comment]
.uexp/uasset are generic Unreal Engine 4 container and not an audio file that can be added, use something like umodel or some UE4 .bms to handle.

Encrypted .mogg can't really be added unless decryption is known.

**Comment by Crafty-The-Fox** [comment]
> .uexp/uasset are generic Unreal Engine 4 container and not an audio file that can be added, use something like umodel or some UE4 .bms to handle.
> 
> 
> 
> Encrypted .mogg can't really be added unless decryption is known.
> 
> 

i know it's a container. I can't extract it because it's an encrypted .mogg file.

**Comment by bnnm** [comment]
This topic asks for "Support fusers .uexp file format". .uexp is a standard (non-audio) container, so it can't be added.

.uexp files are simple and it should be easy to extract data inside with some program/bms/hex editor (see xentax/zenhax).

Then with the extracted .mogg, data is encrypted. Unless somebody figures out the encryption nothing can be done. So there is nothing much to do here.

**Comment by Crafty-The-Fox** [comment]
> This topic asks for "Support fusers .uexp file format". .uexp is a standard (non-audio) container, so it can't be added.
> 
> .uexp files are simple and it should be easy to extract data inside with some program/bms/hex editor (see xentax/zenhax).
> 
> Then with the extracted .mogg, data is encrypted. Unless somebody figures out the encryption nothing can be done. So there is nothing much to do here.

yeah, fair enough. ive already done that with the files, but its not playable in stuff like audacity.

**Comment by SCOTT0852** [comment]
> Then with the extracted .mogg, data is encrypted. Unless somebody figures out the encryption nothing can be done. So there is nothing much to do here.

Stumbled across this issue while searching for something else, the encryption has been cracked now. It's all documented at https://github.com/DarkRTA/themethod3. It can handle all known MOGG formats from v11 (Rock Band 1 on-disc) to v17, which I believe includes Fuser's game-specific variant (although admittedly I haven't checked as I'm not familiar with Unreal file ripping). I'd like to see all encrypted MOGG types supported, Fuser would make an alright starting point.
