### ISSUE TITLE
[Question] How can I find hca subkey and decrypt with subkey?

### ISSUE THREAD

**Issue by Pokko653** [vgmstream/vgmstream#757]
I have some .hca files of _D4DJ Groovy mix_, which is a game from Bushiroad, and They may have been encrypted. I also found their base key(not sure it is real key) and I tried to decrypt them with .hcakey file which includes their base key and test.exe. But they made not musics but noises. So, I guessed that they have some subkey, but I have no idea about how to find subkey and decrypt with subkey. 

How can I find subkey and if I find their subkey, How can I decrypt them with their subkey?
Thanks and Sorry for my poor English and Coding knowledge.

**Comment by bnnm** [comment]
The game uses 2 keys. base files (bgm_*.acb) use 393410674916959300 (0x575ACECA945A444), other files (music_*.acb) use other unknown key.

If you play the .acb with vgmstream and you have the correct hcakey, it will use the subkey automatically.

Subkey is only needed if you extract to .hca inside .acb, It's a value 0x0E bytes from "AFS2" inside the .acb. But I recommend you just play .acb directly.

**Comment by Pokko653** [comment]
Thank you for comment! I'll try it!

**Comment by Nikolayio** [comment]
Hello, did you get any results on decrypting the .HCA music files?
