### ISSUE TITLE
PS4 Audio File Format

### ISSUE THREAD

**Issue by DavidAshta** [vgmstream/vgmstream#760]
hey guys this file is from Dragon Quest Builders 2 PS4, actually it doesnt work on VGMStream of Foobar2000

![54235](https://user-images.githubusercontent.com/23743522/99211251-ac145480-27a6-11eb-9c0c-608c1eb83853.png)

[BGM001.g1l.ps4.zip](https://github.com/vgmstream/vgmstream/files/5544021/BGM001.g1l.ps4.zip)

**Comment by DavidAshta** [comment]
[SOLVED] - I've extract that with a (.BMS File) and it comes WAV but i rename it to .AT9 and works perfectly! ;D

**Comment by DavidAshta** [comment]
there's file called .ATS , i don't know what to do with this one but it's just one of the files, the others are working well

**Comment by bnnm** [comment]
Try renaming to .ATSL, or post the file.

**Comment by DavidAshta** [comment]
> Try renaming to .ATSL, or post the file.

it works! i've renamed it to "ATSL" the put the file on Foobar2000 and automatically it splits on two files, thanks man!
