### ISSUE TITLE
Audiokinetic Wwise file with "failed opening" message

### ISSUE THREAD

**Issue by mortalis13** [vgmstream/vgmstream#762]
I tried to decode a **WEM** audio file with the latest version of `test.exe` tool on **Windows** (release `r1050-3312-g70d20924`):

```
> test sounds_sfx_music_1.wem
failed opening sounds_sfx_music_1.wem
```

The same output with the `-m` (metadata) option.

Another file from the same PCK (sound effects from *Assassin's Creed Valhalla*) decodes fine.
Here are the sounds: [sounds.zip](https://github.com/vgmstream/vgmstream/files/5573192/sounds.zip).

Could you check the **"_1.wem"** file and tell what could be wrong with it?
Thanks.

**Comment by NicknineTheEagle** [comment]
_1 is Wwise Opus which is not implemented. Upload more samples. A lot more samples.

**Comment by bnnm** [comment]
Also add some .bnk that should be in the pck or related sound folders.

**Comment by Karimmusa** [comment]
these are the files in the sound folder
![unnamed](https://user-images.githubusercontent.com/74689376/99830255-1d1c8900-2b66-11eb-978b-b3e063b00025.png)

**Comment by NicknineTheEagle** [comment]
AC games store everything in PCKs so BNKs should be there, too.

**Comment by Karimmusa** [comment]
Well this is the pck file itself that I'm trying to extract and I can't seem to find any bnk files at all
https://bit.ly/3kQnNQd
if anyone can check the pck itself that would be great

**Comment by NicknineTheEagle** [comment]
Use this script to extract PCKs instead of whatever you're using now: https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms

**Comment by Karimmusa** [comment]
Well. I'm super amateur with these things, so I assumes you mean to use the script using quickbms yea?
okay so when I do that using the script you linked to extract the pck, I get this error

Error: invalid endian value guess
- c_structs: "xmath" "SUM" "SEC1_SIZE + SEC2_SIZE + SEC3_SIZE + 0x10"

Error: invalid command "xmath" or arguments -1 at line 29

Am I doing something wrong? or I should use something else and not quick bms?
Also thank you so much for your help

**Comment by NicknineTheEagle** [comment]
Are you using up-to-date version of QuickBMS? The latest version is 0.10.1: https://aluigi.altervista.org/quickbms.htm

**Comment by Karimmusa** [comment]
Okay there is progress, I got 5 .bnk files and  I was able to extract all the files into .wem , but I'm still not able to convert them into playable files. only 122 files get converted to OGG files. the rest of the files I get these errors 

Parse error: expected 0x42 fmt if vorb Messing
or
parse error: unknown chunk type

I also tried using wwise_ima_adpcm tool and it's not working as well 
here are some samples 

I've also uploaded the bnk files if that's any help

[BNK.zip](https://github.com/vgmstream/vgmstream/files/5575785/BNK.zip)


[Samples.zip](https://github.com/vgmstream/vgmstream/files/5575772/Samples.zip)

More samples here :
https://drive.google.com/file/d/1e4ZbdeL7wID0jTtHJi0MIMAsVEOMrwu9/view?usp=sharing

**Comment by NicknineTheEagle** [comment]
More Wwise Opus. And don't use ww2ogg, vgmstream covers WEM format (almost) fully.

**Comment by Karimmusa** [comment]
So Wwise Opus basically means I cannot play them at the moment by any means?

**Comment by NicknineTheEagle** [comment]
Until it's implemented, no.

**Comment by Karimmusa** [comment]
Well damn! 
But thank you so so so much you've been a great help. Cheers man.

**Comment by bnnm** [comment]
Should be playable now: https://vgmstream-builds.losno.co/

Use the .bms posted above, extracts with proper sizes and extensions.

**Comment by Karimmusa** [comment]
Oh my god. I cannot thank you enough! this worked like a charm everthing is working ! 
THank you so so so much man.

**Comment by mortalis13** [comment]
Awesome.
Thanks for your time.
Now I'll try to update the [Wwise-Unpacker](https://github.com/Vextil/Wwise-Unpacker) project (the **BMS** script and the **vgmstream** executable, in particular), where the original issue appeared.
