### ISSUE TITLE
(Request) Please, add support for Gears 4's .wem files

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#765]
Could you please add support for .wem audio files from Gears of War 4?
Gears 4's .wem files look like modifications of original .wem, used for certain audio files type (voicelines).
Here some sample of the files:

https://drive.google.com/file/d/1wc2Ehust7B42ow95pEkMDFceV441Rqtb/view?usp=sharing

https://drive.google.com/file/d/1JP2m4VZC3_redurOFZGdqzfigzCvud-r/view?usp=sharing

I sincerely thank you!

**Comment by bnnm** [comment]
Should work now: https://vgmstream-builds.losno.co/

**Comment by Simo311** [comment]
I can't belive it! It works! I've wasted an entire week trying to make it work!
I can never thank you enough for that!
