### ISSUE TITLE
TVDJ (PS2) - IMA ADPCM variant

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#767]
alright.

so i've found an IMA ADPCM variant that TVDJ (an obscure PS2 rhythm game) uses. whole thing uses standard DVI IMA ADPCM coding scheme _except_ you have hist and step size index values pasted before actual IMA data every 516 bytes.

the game uses two sound formats for such an variant - the headerless format (extension is "INA") and an "sound pack" of sorts (with "SPK" as its extension).

tried to make do with a txth, and although you can _kinda_ hear some stuff through there the results are generally messy.

**.lwav.txth**
```
codec = DVI_IMA
interleave = 0x204
channels = 2
sample_rate = 48000
start_offset = 0
num_samples = data_size
```
yes, the "lwav" extension is there. for testing reasons.
samples are [here](https://www.sendspace.com/file/8w2uwh).
do note though that the spk files are not included there. i wanted to focus on the lwav files only.

**Comment by bnnm** [comment]
First update to latest vgmstream (https://vgmstream-builds.losno.co/)

Then this makes them playable (not 100% accurate not very noticeable):
```
codec = DVI_IMA
interleave = 0x200
channels = 2
sample_rate = 48000
start_offset = 0

chunk_number      = 1
chunk_count       = 1
chunk_start       = 0x00
chunk_header_size = 0x04
chunk_data_size   = 0x200
chunk_size        = 0x204

num_samples = data_size
```
The ce545044** file is mono and looks like some sfx collection, maybe not correctly extracted.

**Comment by RetingencyPlan** [comment]
got it.
i'll close the issue for now.
