### ISSUE TITLE
[Request/Question] Regarding .nsopus files

### ISSUE THREAD

**Issue by cucholix** [vgmstream/vgmstream#768]
Hi, it's already possible convert .opus files to .nsopus?
I ask because I wanted to replace the compressed audio voices in Sakuna Switch version with the PC version, currently it's possible extract/import arc files in Sakuna, the only problem are the .nsopus files.

![image](https://user-images.githubusercontent.com/16081693/100394359-a8d95e00-301b-11eb-9c48-f89664c1c99e.png)
I have installed the last release of vgstreams component into fubar2000, but it fails to open .nsopus "Unable to open item for playback (Unsupported file format):"

Thanks for your contribution, cheers!

**Comment by kode54** [comment]
VGMStream is for playing game audio, not for replacing game audio.

**Comment by kode54** [comment]
Wait, my bad. If you upload a .nsopus file for example, someone may be able to identify it. But this project won't be able to encode them from other sources, sorry. Maybe VGAudio or some other project would be helpful.

**Comment by cucholix** [comment]
[05000601_1.zip](https://github.com/vgmstream/vgmstream/files/5605241/05000601_1.zip)

**Comment by kode54** [comment]
@bnnm

**Comment by bnnm** [comment]
.nsopus are supported in the latest vgmstream: https://vgmstream-builds.losno.co/

They are regular Nintendo .opus with a simple header pasted before it, should be easy to hex edit.

**Comment by cucholix** [comment]
@bnnm sorry to ask again, I know it's not the place, but where could ask for help to create a opus -> nsopus converter? 
I'm willing to pay for the work and time involved.
