### ISSUE TITLE
New wwise .wem variant - Cyberpunk 2077

### ISSUE THREAD

**Issue by namidairo** [vgmstream/vgmstream#778]
I've stumbled upon a new wwise/wem variant which appears to just be the typical wwise RIFF header and then what appears to be a fully formed Opus ogg, albeit with incorrect total sample counts. (?, didn't look too hard into it)

Carving out the file does appear to work, however the new format appears to share the codec value with the Wwise Authoring Tool PCM (0xFFFE), which obviously ends up in garbled output for anyone attempting to decode it current vgmstream builds.

This appears to be restricted to just audio effects, all the other audio appears to be already seen and usable wwise vorbis.

Example:

![image](https://user-images.githubusercontent.com/1764089/101487983-12aa1e00-39b3-11eb-8f71-7ceb112a8c6f.png)

Samples:
[Samples.zip](https://github.com/vgmstream/vgmstream/files/5659628/Samples.zip)

**Comment by namidairo** [comment]
Apologies on the late reply.

> How where those extracted/stored?

In the game's .archive files. 

> Normally Wwise doesn't use regular names

I was making assumptions on file extensions since the file paths weren't known at the time (they were stored as FNVA64 hashes). _It appears these particular files are stored as .opuspak, not .wem as I had presumed by the header._ I already had the .bnk file names figured out from their headers, but I thought it would be better to wait for file names of some of the sample files as well.

[Samples2.zip](https://github.com/vgmstream/vgmstream/files/5684070/Samples2.zip)

**Comment by bnnm** [comment]
Thanks, those details are important for research. Works now (extracted as .wem): https://vgmstream.org/downloads

**Comment by RetingencyPlan** [comment]
there's also sfx_container.opusinfo though i don't have the game to give you such a file.

**Comment by yurmad** [comment]
I have a few questions,
1. Does "extracted as .wem" mean simply renaming the .opuspak to .wem or continuing to extract the .wem files from the .opuspak files or something else? I see there are both .ogg and .wem files and sometimes only .ogg or .wem files in the .opuspak files. The .ogg files play just fine, but .wem files are always just white noises. But if I just rename .opuspak to .wem then the audio just gets cut short and I think only the very first audio gets played.

Here are some samples:
.opuspak files that only contain .oggs:
[ogg only.zip](https://github.com/vgmstream/vgmstream/files/5722376/ogg.only.zip)
.opuspak files that contain .wems (and .oggs):
[wem.zip](https://github.com/vgmstream/vgmstream/files/5722396/wem.zip)

2. There are also .bnk files that are not currently supported. They are always paired with another 32 bytes .bnk file, though.

Some samples:
[bnk.zip](https://github.com/vgmstream/vgmstream/files/5722426/bnk.zip)

**Comment by bnnm** [comment]
.opuspak is a container of multiple .wem, but info/offsets must be in another file (.opusinfo?) so isn't directly playable. If you extract those .wem manually (one file per "RIFF") they'll be playable. Each .wem then contains one standard .opus file, but that's normal and playable without extraction (some .wem do this). Zips you posted look the same to me, multiple .wem.

Those .bnk's data in some kind of custom format ("ADM3"), not sure what. The small .bnk are empty.

Btw, I made a tool to show .bnk internal info/scripting: https://github.com/bnnm/wwiser
Output kind of chokes if you try to print sfx_container.bnk since they put 100000+ objects in there tho.

**Comment by yurmad** [comment]
Okay, thank you.

**Comment by shmerl** [comment]
Sorry for side question, but is there some tool that extracts or gives information about that .opusinfo file to be able to access files in opuspaks?
