### ISSUE TITLE
[Request] Guilty Party (Wii) - *.smp format

### ISSUE THREAD

**Issue by ataylor-design** [vgmstream/vgmstream#783]
[gp_samples.zip](https://github.com/vgmstream/vgmstream/files/5675471/gp_samples.zip)

Hello! I extracted the audio files from Guilty Party; they are formatted as *.smp with a *.snb soundbank file. However, vgmstream returns failed upon trying to open/convert the files. I have tried different audio files, all to no avail.

Let me know if you need additional samples.

**Comment by bnnm** [comment]
Should be fixed: https://vgmstream.org/downloads

**Comment by ataylor-design** [comment]
Works perfectly! Thank you very much.
