### ISSUE TITLE
vgmstream_get_title dereferences cfg without checking NULL

### ISSUE THREAD

**Issue by jchv** [vgmstream/vgmstream#790]
Since 01eaab1f01d24bb50d3e608b503bfd2c142ce113, passing NULL as `cfg` into `vgmstream_get_title` now causes a NULL dereference, due to this addition:

```cpp
    /* name without extension */
    if (cfg->remove_extension) {
        pos2 = strrchr(buf, '.');
        if (pos2 && strlen(pos2) < 15) /* too big extension = file name probably has a dot in the middle */
            pos2[0] = '\0';
    }
```

It may very well be that passing `NULL` for `cfg` is not intended, however it is currently being done by the Audacious plugin. Therefore, I'm filing this issue instead of making a PR because it is unclear which option is best. None of the other plugins currently seem to pass `NULL` for `cfg`.

**Comment by bnnm** [comment]
Was supposed to accept NULL, should be fixed now.

**Comment by jchv** [comment]
Thanks for the prompt fix.
