### ISSUE TITLE
awc.c, coding_FFmpeg undeclared

### ISSUE THREAD

**Issue by Daniel-z-Kaplan** [vgmstream/vgmstream#792]
`awc.c: In function ‘init_vgmstream_awc’:
awc.c:165:42: error: ‘coding_FFmpeg’ undeclared (first use in this function)
  165 |                 vgmstream->coding_type = coding_FFmpeg;
      |                                          ^~~~~~~~~~~~~
`

I'm running on Fedora 32, and ffmpeg-devel is installed. How do I fix this/what other information should I provide?

**Comment by Daniel-z-Kaplan** [comment]
So I "fixed" this by changing the line in question, which was in awc.c, 159.
#ifdef VGM_USE_VORBIS
became
#if defined(VGM_USE_VORBIS) && defined(VGM_USE_FFMPEG)

I don't know if this actually fixes the issue, but it compiled and I was able to play the file I wanted, so..

**Comment by bnnm** [comment]
awc.c should be fixed now
