### ISSUE TITLE
Some MIB files play too fast or are corrupt when converted

### ISSUE THREAD

**Issue by zacchi4k** [vgmstream/vgmstream#794]
I'm trying to convert some audio files from a lesser known PS2 game, but almost all MIB files I convert have some issues. Some of them play at exactly 2x the speed they're supposed to, others have desynced audio channels and/or are corrupt (skipping some parts), even others seem to have both issues at the same time, while very few don't have either. Tested both with the latest GitHub release and with the latest autobuild.
Note that there also are some VAG files in the game disc, but all of them seem to convert fine

Note that while I'm not sure if the fast audio is actually an issue with vgmstream, I don't see any other explaination for the ones that get corrupted

Here are a few of the audio files, both original MIB files and converted WAVs, along with the output on the cmd: https://mega.nz/file/YV1HVCiI#M5a1SrKYbf7WydEmXBDF9uQgAjgfkN1zGRb9Yb93NF0

**Comment by NicknineTheEagle** [comment]
MIB files should always come with MIH, standalone MIB playback is legacy behavior which will be removed eventually. If can't see any MIH in the same folder, they must be stored someplace else.

**Comment by zacchi4k** [comment]
> MIB files should always come with MIH, standalone MIB playback is legacy behavior which will be removed eventually. If you can't see any MIH files in the same folder, they must be stored someplace else.

There are no MIB files in the whole disk, unless they're stored inside BNK files

**Comment by NicknineTheEagle** [comment]
They're stored inside some archive then. I know one game that does that.
