### ISSUE TITLE
[Request] Please, add support for .res files from BF: Bad Company

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#795]
Hi, could you please add support for .res audio files, extracted from Battlefield: Bad Company 1 (Xbox 360 version)
Apparently there's no other software capable of converting those .res files into a playable audio format!
Here some samples of the aforementioned files -> https://drive.google.com/file/d/1lrYcw9J1ElQwpM5V6B0tfa8Iqgnb9bYW/view?usp=sharing

One little note, i was able to successfully convert .res file included in Battlefield: Bad Company 2 using Ealayer.exe ( https://bitbucket.org/Zenchreal/ealayer3/downloads/ ) those .res files seem to be extacly the same as the ones included on it's predecessor (BF:BC1) nonetheless Ealayer.exe only works with .res files from BF:BC2...
Here some samples of BFBC2 .res file, maybe you can spot the difference between the two -> https://drive.google.com/file/d/1ekzCJI_Zvn68HBG8le3xfEnnjC2xX5p6/view?usp=sharing

Thank you so much!

**Comment by NicknineTheEagle** [comment]
Frostbite .res files are not an audio format. They can contain .sps files which is standard EA sound format but extracting them is outside the scope of this project.

**Comment by Simo311** [comment]
> Frostbite .res files are not an audio format. They can contain .sps files which is standard EA audio format but extracting them is outside the scope of this project.

Sorry, but i won't be so sure. The .res files i've managed to successfully convert were indeed an audio format! 
Someone in the past even actually managed to convert .res file into .wav (as you can clearly read from this old thread -> http://old.zenhax.com/battlefield-bad-company-extract-audio-from-res-t1231.html ) 
Sadly though, the scripts they've used are no longer avaiable...
That's why i'm asking your help!

**Comment by NicknineTheEagle** [comment]
I am sure, Frostbite Engine uses .res to store its assets so it can contain pretty much anything. It is not specifically an audio format so this doesn't fall under vgmstream's coverage.

**Comment by Damolx** [comment]
Check this tool : https://mega.nz/file/Dxki2JKJ#jpViNj4B78xu6PNE5HNrCL74I8V-Mk7z30ewrbwSSyo

**Comment by Simo311** [comment]
Wow, that's awesome! You saved me!
I immensely thank you!
One question, did you create that tool just for me?

**Comment by Damolx** [comment]
No i did it for myself some weeks ago.
I only created the procedure, the tools are here : [BFEditor.org](http://www.bfeditor.org/forums/index.php?/topic/14539-extracting-sound-and-music-files-from-bfbc2/)

**Comment by Damolx** [comment]
No i did it for myself some weeks ago.
I only created the procedure.

**Comment by ratsphere** [comment]
> Check this tool : https://mega.nz/file/Dxki2JKJ#jpViNj4B78xu6PNE5HNrCL74I8V-Mk7z30ewrbwSSyo

Necroposting but is this tool still available? I too am looking to extract the sound files from bad company 2

**Comment by neyxs** [comment]
Here it is : https://mega.nz/file/fpUUiJRZ#9llvExW6ReVY7IvH9iZ5AVVDhspQvfoHMCADhfg4yhw
