### ISSUE TITLE
(Request) Sakura Wars (2019) .awb & .acb support

### ISSUE THREAD

**Issue by Mysticus92** [vgmstream/vgmstream#797]
Please, add these .awb & .acb files for vgmstream from the game called Sakura Wars (2019).

[se_ev_00_btl.zip](https://github.com/vgmstream/vgmstream/files/5791329/se_ev_00_btl.zip)
[vo_btl_sakura.zip](https://github.com/vgmstream/vgmstream/files/5791330/vo_btl_sakura.zip)

**Comment by bnnm** [comment]
.awb plays for me and .acb is not an .acb and has garbage data, maybe incorrectly extracted.

**Comment by Mysticus92** [comment]
So, any solution?
Is there something to correctly extract the cpk files from that game?

**Comment by bnnm** [comment]
Try asking on xentax/zenhax since they deal with extraction and stuff and that's outside vgmstream's realm.
