### ISSUE TITLE
Assassin's Creed 1 ubi_bao decoding doesn't work

### ISSUE THREAD

**Issue by withmorten** [vgmstream/vgmstream#801]
Hi, I'm trying to decode AC1 sound files using test.exe - I compiled it myself so only ever `init_vgmstream_ubi_bao_atomic` gets checked, and every file returns `failed opening common\Common_BAO_0x5926ad44`.

The file I'm testing is the above mentioned file, I know it contains audio, since it has `vorbis` strings inside of it and I have decoded long ago with DecUbiSnd.

When debugging, it seems to get as far as `init_vgmstream_ubi_bao_header` and then fails because `total_subsgongs` is 0.

The relevant part is probably in `parse_bao`, where it returns 1 early and doesn't increase the total_subsongs if this is true:

`if (bao_class != 0x20000000) /* ignore non-header classes */`

The bao_class this file has is `0x50000000` when I debug it. I don't know enough about the format to debug further.

The type of the file is also TYPE_NONE, while it should probably be TYPE_AUDIO.

I've uploaded the file to wetransfer, where it will be available for 4 weeks: https://we.tl/t-YT3XCBnw3l

**Comment by bnnm** [comment]
The file you posted is a "streamed BAO". vgmstream needs "header BAOs" , b/c streamed alone isn't enough to play all BAOs correctly (DecUbiSnd just does some guesswork while vgmstream aims for proper support, simulating what the BAO engine does).

Extracting header BAOs is a bit involved but here is a guide and tools: [ac1.zip](https://github.com/vgmstream/vgmstream/files/5845302/ac1.zip)

**Comment by withmorten** [comment]
Ah I see. I did stumble on that archive as well. I'll test again tomorrow and report back!

**Comment by withmorten** [comment]
Yes indeed, that complicated process worked out. Thanks very much for the hint!
