### ISSUE TITLE
GTA San Andreas [PS2] - Streams format

### ISSUE THREAD

**Issue by BloodRaynare** [vgmstream/vgmstream#802]
[Track_001.zip](https://github.com/vgmstream/vgmstream/files/5853023/Track_001.zip) 
(From one of the radio commercials inside ADVERTS.PAK)
[Track_008.zip](https://github.com/vgmstream/vgmstream/files/5853051/Track_008.zip) 
(From one of the "Mission Passed" audio clip inside BEATS.PAK)

(Note: The actual extensions might not be .VAG)
Tried to write a TXTH file for this format, but for some reason I'm unable to make it work properly. Either it comes out as a clicky noises (Due to the offset where the data starts is starting at 0x04 instead of 0x00) or the padding chunks aren't being skipped.

Quick rundown of the info for this format:
0x00 = Commands for rhythm minigames. Values set to single 0xFFFF if's it for regular audio streams.
Depending on the format types:
0x1F40 & 0x1F48 or 0x1F50 & 0x1F58 = Actual size of the audio data per channel (not including padding)
0x1F44 & 0x1F4C or 0x1F54 & 0x1F5C = Sample rate
0x1F80 = Number of the occurences of the info above?
0x1F84 = Start of the audio data. Again, depending of the audio format type, the padding could be starting at the 0x00 of the audio data or at the next of interleave x channels. Size of the padding data is 0x1000 and can be garbage audio data or zeroes.

**Comment by bnnm** [comment]
I've pushed some txth updates to handle this kind of stuff, see [here](https://github.com/vgmstream/vgmstream/blob/master/doc/TXTH.md#grand-theft-auto-san-andreas-vgmstreamtxth).

**Comment by BloodRaynare** [comment]
Thanks so much, now it's played correctly :)

**Comment by bnnm** [comment]
Forgot to remove file's end padding in the example, see link again (`padding_size = auto`).
