### ISSUE TITLE
[Request] Please, add support for .fsb and .pck files from Halo games.

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#806]
Hi, could you please add support for .fsb and .pck audio files from Halo games? (Halo: The Master Chief collection)

Halo 3/Halo 3 ODST uses .fbs container to storage audio (like voicelines), there's already a software that could open those files, although it works pretty bad as it's only able to play them, not extract! (the aforementioned software -> https://www.nexusmods.com/darksouls/mods/1193 )
Sample of the file -> https://drive.google.com/file/d/1naNMA68mMfYWEZQEJ6BL3B_ccoeHc_7i/view?usp=sharing

Halo 4 uses .pck container to storage audio (like voicelines) could you please add support for this type of file?
Sample of the file -> https://drive.google.com/file/d/1ucCFi_sJZhMIZLKkaaC-f22c4wQ5xjgf/view?usp=sharing

Thank you immensely!

**Comment by bnnm** [comment]
That .fsb works fine here, try latest vgmstream: https://vgmstream.org/downloads

For .pck you need to unpack files first with [quickbms](https://aluigi.altervista.org/quickbms.htm) and [this bms script](https://github.com/bnnm/wwiser-utils/blob/master/scripts/wwise_pck_extractor.bms), resulting files should be playable with vgmstream.

**Comment by Simo311** [comment]
Thank you for helping me!

I tried the latest version of vmgstream on that .fsb file and it works! But due to my lack of knowledge regarding command-line softwares, i've managed to extract just one single file out of it, i'm sure there're thounsands of file packed in there, could you please teach me how to do extract all of them?

For .pck file, i've tried using the script you suggested me, it works seamlessly! Thank you so much!
Just one little note, is there a way to order the extracted files? Because all the files are randomly named and it's impossible for me to recognize them.

**Comment by bnnm** [comment]
Easiest would be installing foobar2000 player + vgmstream plugin, drag file to playlist and it'll "unpack" all, then right click > convert to wav. Otherwise try in command line:
```
for /L %A in (0,1,32984) do test.exe -s %A -o file_%A.wav file.fsb
```

There generally is no way to order .pck (Wwise) files, as names are just those numbers. A few games may include a SoundInfoBank.xml file with number<>original name info though.

**Comment by Simo311** [comment]
I couldn't find SoundInfoBank.xml anywhere, so i guess i have to order them out manually... it's going to take an huge amount of time, but at least i've got the files!

I am really thankful for all your support!
