### ISSUE TITLE
Please, help me to unpack the audio from Need For Speed

### ISSUE THREAD

**Issue by Simo311** [vgmstream/vgmstream#809]
It's been years since i'm trying to unpack the voicelines from Need For Speed: Most Wanted 2012.
I've already posted this request in many other forum, but no one helped me since then.

The file i'm talking about is this -> https://drive.google.com/file/d/1X0jfHoU29j9HhGrzkaXzXOhz93FEJq0K/view
I've managed to extract one single file out of thousands of them using a software called ealayer3 ( -> https://bitbucket.org/Zenchreal/ealayer3/downloads/ ) but sadly that's all it can do.
So i need someone that could help me to extract all the remaining audio files.
Vgmstream does not seem to work.

Among game files, there's also another file that could be related to the voicelines -> https://drive.google.com/file/d/1XS940mvo9eKOMbWHgaL-YAGNdqI5_0nk/view?usp=sharing
It likely contain information on where and when the actual voicelines are being used while gaming...

I sincerely thanks whoever will take the time to look at it!!

**Comment by bnnm** [comment]
Since that's a generic EA archive thing that's outside vgmstream's realm. I suggest you ask in xentax.com/zenhax.com for help.

It looks like .bndl has offsets and is used to extract audio from the .swc0, extracted files should be playable in vgmstream (use .sps extension).

**Comment by Simo311** [comment]
Sadly, l've already asked this on xentax / zenhax forums almost 4 years ago, no one has ever replied.

Yeah, I knew that the .bndl had something to do with files offsets, unfortunately I have no idea how to make it works using vgmstream.
I guess I'll never be able to rip those voicelines...  :(

**Comment by modusc896d352** [comment]
here. this is the needed script to extract bndl files.
[nfsmw2012_windows_bms.zip](https://github.com/vgmstream/vgmstream/files/7959716/nfsmw2012_windows_bms.zip)
and here is the needed script to extract some swc0 file.
[nsfmw2012_wct[bms].zip](https://github.com/vgmstream/vgmstream/files/7959783/nsfmw2012_wct.bms.zip)

some wct file must be alongside that swc0 file because i did a rush job out of it.

**Comment by Simo311** [comment]
Thank you a lot!!
