### ISSUE TITLE
GI USM Extraction Question

### ISSUE THREAD

**Issue by Eleiyas** [vgmstream/vgmstream#813]
Hi Bnnm.
I posted on your lengthy comment thread on hcs64, but the last comment was a few months ago now, so I thought I'd post here.

I'm trying to extract the .USM files from Genshin Impact. Now, I know you focus on audio with VGM Stream, but that's not where my issues lie, it's in the video.
Opening the USMs in hex, reveals one .avi file, one avi.ivf file and 4 .wav.hca files, each relating to a different language the game's audio can be played in.

VGM Toolbox can extract the files, which end up being one .m2v video and the 4 .hca files. Now, with a quick conversion from .hca to .wav, the audio files play fine, but the video is just black and stays at 00:00, while refusing to play.

This says to me (at least), that the video is encrypted, despite the audio not being so.

I tried using your modified CRID(USM) tool on hcs64 but couldn't find the keys used to decrypt the video in the USM.

Was hoping you could help out, cheers.

**Comment by bnnm** [comment]
See hcs64, this place is for vgmstream issues.

**Comment by BAHAA-THE-KING** [comment]
I have the same problem, no solution yet ?
