### ISSUE TITLE
ios/tvos build failure

### ISSUE THREAD

**Issue by fuzzard** [vgmstream/vgmstream#814]
Kodi builds a vgmstream based addon for their supported platforms.
For ios/tvos we have had build failures reporting

```
 /Users/Shared/jenkins/workspace/TVOS/tools/depends/target/binary-addons/appletvos13.2_arm64-target-release/build/audiodecoder.vgmstream/lib/vgmstream/src/meta/ubi_sb.c:1754:22: error: implicitly declaring library function 'ceil' with type 'double (double)' [-Werror,-Wimplicit-function-declaration]
     return (uint32_t)ceil(sample_rate);
                      ^
```

std::ceil function include from math.h header

A proposed fix for the kodi addon can be seen at https://github.com/fuzzard/audiodecoder.vgmstream/commit/b6ed2756141754750e64fee2223e1cae9d6ffc16

I'm not sure if theres a more appropriate fix (possibly build flags i guess) on the kodi end, but the simple addition of the include math.h has it building on all kodi platforms now.

Happy to open a PR if the above fix is an acceptable solution to you, just let me know.

**Comment by bnnm** [comment]
Fix makes sense to me, added to the latest PR while I was fixing other stuff.

**Comment by fuzzard** [comment]
Thanks, appreciated.
