### ISSUE TITLE
Possiblity to encode wav files back into one of these video game formats? (ie custom music)

### ISSUE THREAD

**Issue by FB-Productions** [vgmstream/vgmstream#819]
Currently we have the option to decode these formats to wav files using this command:
`test.exe -o happy.wav happy.adx to decode happy.adx to happy.wav`
Is there a way or a chance of adding support for _encoding_ any wav file back into these formats?
Say if I wanted to have custom music in some of the supported video games.
If that is beyond the scope of this project, I kindly ask (if possible) to refer me to some other projects that might allow this to be done.
Thank you!

**Comment by CyberBotX** [comment]
vgmstream is only a decoder, it is not an encoder at all. I personally do not know of any projects offhand that do encoding from wav to video game formats. I imagine they exist, so perhaps someone else can chime in with answers to that part.

**Comment by bnnm** [comment]
Encoding wav to other formats is complex and needs specialized programs, vgmstream was made only with decoding in mind.

You could try [VGAudio](https://github.com/Thealexbarney/VGAudio/releases), for some common game formats, and [FFmpeg](https://ffmpeg.org/download.html) for more general audio formats. Beyond that you may find tools for certain formats around (ex. [KOEI libs](https://github.com/yretenai/Cethleann)). Some common libraries like Wwise (.wem) or FMOD (.fsb) have official tools/SDKs to encode (may be subject to licenses/limitations and whatnot though).

Other than that your best chance would be asking in modding communities.
