### ISSUE TITLE
[Incomplete format support] Gundam Extreme Vs Maxiboost On (nus3audio)

### ISSUE THREAD

**Issue by rikimtasu** [vgmstream/vgmstream#829]
Some nus3audio file do work,however it either have incomplete index or straight up not able to play in foobar2000.

attached is samples that doesn't work yet.

https://mega.nz/file/1o1DQAwQ#mvqb2nzG9FP90n2ZSXmW1kKr1jVOIib_rhNYyMYIC-c

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/downloads
