### ISSUE TITLE
These Formats are supported by the winamp plugin (in_cube.dll)

### ISSUE THREAD

**Issue by AntonZab** [vgmstream/vgmstream#830]
Hello. I read that vgmstream is the former in_cube for winamp. So, the following formats are supported there in the link, but you do not have

https://drive.google.com/file/d/14cU3AzhEkJL73YANWWYu7jOuLqirShPR/view?usp=sharing

**Comment by bnnm** [comment]
Those files don't seem correct, vgmstream expects properly ripped files with original extensions. For example demo11_02.afc and  stm_bgm_B_colosseum1.ish. Ancient in_cube may have allowed wrong extensions but vgmstream aims for correctness.

Try re-ripping audio from the games first or getting another rip, report those that really don't work (including multiple files and the name of the game).

**Comment by hcs64** [comment]
A few notes from [this post by pooruser](https://hcs64.com/mboard/forum.php?showthread=26929&showpage=408#post_62257) about these files and the needed extensions:

> ‘type_astafc - demo11_02.afc’: Vgmstream wants ‘.ast’ file extension.
> 
> ‘type_gcub - Organ - PA_45.dsp’: vgmstream likes ‘.gcub’.
> 
> ‘type_idsp2 - LIVE_01_.idsp’: couldn’t find a suitable extension for Vgmstream, but Foobar2000 takes it with the help of ‘foo_adpcm.dll’.
> 
> ‘type_ish - stm_bgm_B_colosseum1.dsp’ is paired with ‘type_ish - stm_bgm_B_colosseum1.001’, also in the zip folder. For Vgmstream, the ‘.dsp’ file has to be remed to ‘.ish’, and the ‘.001’ file to ‘.isd’. As usual, both files must be placed in the same folder, Vgmstream must be invoked with the ‘.isd’ file.
> 
> ‘type_whdpcm - Title2V3+K.dsp’: couldn’t find a suitable extension for Vgmstream nor for Foobar2000. For WinAmp and XmPlay ‘in_cube.dll’ still remains. It’s taken from ‘Hitman 2 - Silent Assassin’ for the PS2. On yoshw.info you can get it as ‘.tak’, though I doubt that’s the original format.

Yes, vgmstream is a descendant of in_cube, but it's come a long way.
