### ISSUE TITLE
Broken SABs from Kingdom Hearts 0.2 PC

### ISSUE THREAD

**Issue by JosouKits** [vgmstream/vgmstream#832]
Tried to check the SAB files from Kingdom Hearts 0.2 PC version, but they aren't recognized, seem to be encrypted.

[KH_02_Broken_SAB.zip](https://github.com/vgmstream/vgmstream/files/6249227/KH_02_Broken_SAB.zip)

**Comment by bxaimc** [comment]
Hmm, they seem to work fine on my end. Try updating vgmstream if you haven’t done so already.
![502ACCBA-D3A0-4B2E-887B-D0F712F312C0](https://user-images.githubusercontent.com/9313677/113418943-74dcc380-9394-11eb-9d72-6d6fbcb89e27.jpeg)
