### ISSUE TITLE
Not Work Amagami PS2

### ISSUE THREAD

**Issue by mumriks** [vgmstream/vgmstream#833]
Not work correctly, AHX type 0x08 decrypt (Amagami PS2)
There is noise. Not Clear.

**Comment by bnnm** [comment]
Unzip this file in the .ahx folder:

[key.zip](https://github.com/vgmstream/vgmstream/files/6252691/key.zip)

**Comment by mumriks** [comment]
Thanks. Better than that. But noise little, yet.

**Comment by bnnm** [comment]
My example files sound ok: [sample.zip](https://github.com/vgmstream/vgmstream/files/6255011/sample.zip)

You need to post .ahx that play with noise.

**Comment by mumriks** [comment]
Your sample is clear!
I execute on Windows10 + WSL2. 
ASF archive file -> AHX by ASFExplorer.
[mysample.zip](https://github.com/vgmstream/vgmstream/files/6255502/mysample.zip)

**Comment by mumriks** [comment]
Now, I rebuild vgmstream_cli , and execute again, it is clear!
Thanks so much!
