### ISSUE TITLE
Shadow of the Colossus PS3 .int_cp3 PS ADPCM

### ISSUE THREAD

**Issue by sephirothkefka** [vgmstream/vgmstream#835]
I'm trying to play these files from Shadow of the Colossus on PS3 and I would assume ICO uses similar files as well. I've managed to get them play but i cant seem to find a loop pointer. They appear to be 48khz in stereo with a 0x10 interleave. Any help would be greatly appreciated!
[test_adpcm.zip](https://github.com/vgmstream/vgmstream/files/6253306/test_adpcm.zip)

**Comment by bnnm** [comment]
Files are raw PSX ADPCM and lack loop points. Header/loop info would be in another file, in the PS2 version header was in a .sts file and data in .int, probably similar here.

**Comment by sephirothkefka** [comment]
[test_adpcm2.zip](https://github.com/vgmstream/vgmstream/files/6255239/test_adpcm2.zip)
Indeed there was a seperate STS directory in the game (though with the games janky file system it was a bit hard to find at first.) It seems like the paired files should work after removing the "_cp3" part but it looks a bit different than normal. Is this a unknown version that Bluepoint/japan studio used here? I have attatched 2 int/sts combos here.

**Comment by bnnm** [comment]
Looks like a PS3 variation of STS+INT. m12p_00.int_cp3 and m12p_00b.int_cp3 don't seem to match up, did you post the correct pair? Post a few more pairs for loop testing, and some small-ish files that don't loop (value at 0x0c is 0).

**Comment by sephirothkefka** [comment]
Oddly I couldn't seem to find any files that had 0x0C as "00" all the ones i found were "01". And i just realized the mistake earlier! Super sorry about that! Anyway i have some more files here including ones that i believe are non-looping (b_info which is the files of dormin explaining the location of the colossus)
[test_adpcm3.zip](https://github.com/vgmstream/vgmstream/files/6265084/test_adpcm3.zip)
