### ISSUE TITLE
I can play only 210 songs about D4DJ Groovy Mix.

### ISSUE THREAD

**Issue by kjhmagic** [vgmstream/vgmstream#836]
I tried to play the acb files about "D4DJ Groovy Mix" using foobar2000 component from commit b5d5d6d62b4989d3a385cbb7609205393cd9ca17.

D4DJ have total 288 of music acb files and vgmstream have total 220 of subkey in hca_keys.h file.
But I could play only 210 acb files from foobar2000. Others are still noisy sound.

I think some subkeys are not working.

Thanks in advance.

**Comment by bnnm** [comment]
If you are sure vgmstream isn't picking the correct key for `(file).acb`, you can force it by creating a file named `(file).hcakey` with the 8-byte key inside. 

If it plays correctly with the `.hcakey`, could be that vgmstream isn't detecting all keys correctly, you'd need to post samples + key of those cases (though the current key detector should be very accurate).

If it doesn't, wrong key. I don't know how to get keys from that game so you are better off asking the person who posted them [here](https://github.com/vgmstream/vgmstream/issues/825).
