### ISSUE TITLE
Use vgmstream to convert wav to scd?

### ISSUE THREAD

**Issue by Noxalus** [vgmstream/vgmstream#837]
Hello everyone,

I saw that vgmstream can read SCD files and can convert from SCD to WAV. As SCD format is handled, I was wondering if it's possible to do the opposite, start with a WAV file and convert it into a SCD file, choosing the codec as option?

Thanks in advance for your answer!

**Comment by bnnm** [comment]
Sorry, vgmstream can only convert to WAV and can't do the opposite (would need a whole new program as it's very a different thing).

**Comment by Noxalus** [comment]
Thank you for the answer, do you know any tool to do what I would like? 🤔

**Comment by bnnm** [comment]
There are programs like [VGAudio](https://github.com/Thealexbarney/VGAudio) or FFmpeg that can convert WAV to some common game formats but not SCD.

Your best bet would be asking around modding communities I think (try for other games using SCD too).
