### ISSUE TITLE
these XVAG are unplayable for some reason (Days Gone [PS4])

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#845]
so i came across three unplayable XVAG files while datamining the PS4 version of days gone.
to elaborate, three of them are "multilayer test" files. i had no idea what caused vgmstream to reject them all of a sudden.

here is a 7z file containing said files plus an extra playable xvag file. just in case an playable XVAG is needed for a potential fix to happen.
[days_gone_ps4_xvag_samples.7z](https://www.sendspace.com/file/5l45w3)

**Comment by bnnm** [comment]
Should work now.

**Comment by RetingencyPlan** [comment]
nice! these files are actually playable now.
thanks for the fix.
