### ISSUE TITLE
[Request] MushokuTensei Mobage audio file

### ISSUE THREAD

**Issue by lloyddunamis** [vgmstream/vgmstream#847]
VGMStream (r1050-3682) and VGMToolbox (r1040) seems to be able to extract the music, but both tools produce **audio files that are a squeaky mess**.
Main concern is the BGM (and the BGMs the game will download) but I included the sound effects and what seems to be the title screen voice sample for further tests.

Game: [Mushoku Tensei: Game ni Nattemo Honki Dasu](https://apps.qoo-app.com/en/app/15433)
Sample: https://mega.nz/file/aAEjGIIC#7WYcu-cknSTxaGXvCQo4s1H3XREDfXVMiRb5O7q6Alg (pass: Roxify)

Seeing that the case for UmaMusume was somehow resolved for the most part, I hope this is alright. Let me know if it isn't though.

**Comment by bnnm** [comment]
Should work now: https://vgmstream.org/downloads

**Comment by lloyddunamis** [comment]
Confirmed working! So it turns out it just needed the correct key...
Thank you so much!

_(sample removed as it's served its purpose)_
