### ISSUE TITLE
[Request] Accept array of input files

### ISSUE THREAD

**Issue by FatalBulletHit** [vgmstream/vgmstream#859]
Currently, mass converting files requires a call for each file and I've noticed that calling a program thousands of times will trigger the `Antimalware Service Executable` on Windows 10.
This will decrease performance significantly and while this can be partially counteracted by adding `test.exe` to Exclusions, running multiple instances parallel in order to increase performance will see the `Antimalware Service Executable` take away a good chunk of our processing power again.

Having `test.exe` accept an array of input files could counteract this even more and increase ease of use if applied to drag and drop operations.

**Comment by bnnm** [comment]
You can pass or drag and drop multiple files now: https://vgmstream.org/downloads

There is an OS limit in the command line length though, so maybe it can't handle thousand files, but try and see.

**Comment by FatalBulletHit** [comment]
That was quick! Thanks a lot! 👍
And it made it quicker, too - by nearly 5 times:

![Screenshot 2021-05-10 135843](https://user-images.githubusercontent.com/37146617/117655833-dfed9700-b197-11eb-97d8-a3bb0f2468e2.png)

_I included a test with the variant I used beforehand for both the latest release and the latest build to see if there's a performance difference between them (`vgmstream.exe` is `test.exe` from the latest release)._

And you're correct, passing 1500 files (may differ depending on the length of the full path to each file) caused an error:
`Program 'test.exe' failed to run: The filename or extension is too long.`

To avoid the command line length limitation, I'd suggest to allow `INFILE` to be a path to a directory, probably in combination with a wildcard, e.g. `C:\some\path\*.wem`, so `vgmstream` can get the collection of files itself rather than have it passed to it.

Hope this isn't too much to ask for. 😁

**Comment by bnnm** [comment]
There aren't simple/portable ways to read folders in C, and I'd rather avoid maintaining per-OS code or adding extra libs, so no wildcards planned ATM.

Besides, I think converting +1000 files to wav isn't something one does all the time, shouldn't be too hard to make workarounds when calling vgmstream, plus one can (should?) play those directly with foobar/winamp+plugin then pick choice files.

"test" was renamed to vgmstream-cli for other OSs not too long ago, but I kept it as test.exe on Windows since I figured people were used to that name (used in forums and stuff for like ~10 years).

**Comment by FatalBulletHit** [comment]
Fair enough,  the command line length limit is 32767, coming up with a workaround wasn't too hard.

I created a an array of strings that are shorter than the limit (taking into account the length of the path to the program and the spaces and quotation marks surrounding the paths to the files) and loop through it.

That is still a lot faster although it varies depending on the length of the paths for each file - either way, thanks! :)
