### ISSUE TITLE
one isb file not working (music_bank.isb)

### ISSUE THREAD

**Issue by RetingencyPlan** [vgmstream/vgmstream#862]
so this file seems to be the only isb file that doesn't work with vgmstream.
[[mass_effect_xbox360]music_bank[unsupported_isb_file].7z](https://www.sendspace.com/file/yk8dg7)
not even CLI version of vgmstream works with it.

i also have another file with the same name and vgmstream cannot play it either.
[[mass_effect_legendary_edition_windows7]music_bank[unsupported_isb_file].7z](https://www.sendspace.com/file/oie77r)
sorry for the leak.

**Comment by bnnm** [comment]
Should work now.

**Comment by RetingencyPlan** [comment]
nice work!

**Comment by RetingencyPlan** [comment]
wait, i have a question to ask.
so, as it turns out that enigmatic music_bank.isb file contains dozens of "fldr" chunks. and following a "fldr" chunk there's a "titl" chunk. said chunk is also present as a successor bank to "smpl", and the names of those "smpl" chunks are read there unlike with "fldr" chunks which can have dozens of subsongs.

the point is, is there any way you can possibly build up a "subsong name" of sorts for subsongs that managed to be in those "fldr" chunks? like this:
```
music_bank#60 (ucw/mus_galaxy_map_loop.wav)
```

**Comment by bnnm** [comment]
I'll add later
