### ISSUE TITLE
Audio tracks exported from Gameloft vxn files do not contain the full information

### ISSUE THREAD

**Issue by antoniu200** [vgmstream/vgmstream#868]
Hello!

I have tried extracting the sounds from Asphalt 8 and 9, but all tracks extracted from vxn files have a small part from the end cut off.

Below I have attached both the vxn and a comparison wav file between what is ripped using Foobar2000 and this plugin and what the game plays back. The rip is made from the latest version of Asphalt 9 currently available (2.8.4a). However, the situation is the same for the oldest verison of Asphalt 9 available (0.4.6c).

It is also possible the extracted files have some silence that is not present while the game plays the files, but I'm not sure it's from the plugin.

The issues don't seem to appear in Asphalt 8.

Please analyze the files and let me know what your conclusions are.

[Desktop.zip](https://github.com/vgmstream/vgmstream/files/6566904/Desktop.zip)

**Comment by bnnm** [comment]
Should sound better now: https://vgmstream.org/downloads

**Comment by antoniu200** [comment]
Fixed. Thank you!
