### ISSUE TITLE
[Request] Project Sekai Colorful Stage feat. Hatsune Miku

### ISSUE THREAD

**Issue by streamerunit** [vgmstream/vgmstream#870]
Please support this game.

Name:
Project Sekai Colorful Stage feat Hatsune Miku

Android Application Link:
https://play.google.com/store/apps/details?id=com.sega.pjsekai

iOS/iPadOS Application Link:
https://apps.apple.com/jp/app/%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%BB%E3%82%AB%E3%82%A4-%E3%82%AB%E3%83%A9%E3%83%95%E3%83%AB%E3%82%B9%E3%83%86%E3%83%BC%E3%82%B8-feat-%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF/id1489932710

**Comment by kotori2** [comment]
HCA key = 0x22CE

**Comment by xfl03** [comment]
HCA is not encrypted, so HCA key = None .

**Comment by bnnm** [comment]
@streamerunit base awb files in the apk work fine (no encryption), post files that don't play.
Make sure you have latest version: https://vgmstream.org/downloads

Maybe the game downloads audio that is encrypted, but the key posted above was already included.

**Comment by streamerunit** [comment]
Thank you for researching.
