### ISSUE TITLE
EA Sports Madden 08 ASF file corrupted with multiple audio clips in one

### ISSUE THREAD

**Issue by ApexJohn** [vgmstream/vgmstream#874]
Used QuickBMS to export audio files from Madden 08 on PC, and found that almost all ASF files have multiple clips embedded in one file, and that vgmstream plays these corrupted.

Here's a few example of the ASF files.
[spchdata.zip](https://github.com/vgmstream/vgmstream/files/6652796/spchdata.zip)

**Comment by NicknineTheEagle** [comment]
These appear to be DAT files from HDR/DAT format. You need to find a way to extract the files with names, otherwise you're out of luck.

**Comment by ApexJohn** [comment]
> These appear to be DAT files from HDR/DAT format. You need to find a way to extract the files with names so you can get matching HDRs, otherwise you're out of luck.

Just tried another tool specifically for extracting .DAT files from Madden 08 (DAT File Replacer 5.0), Didn't work, and it can't open the said files I posted as DAT files to extract them further. Not familiar with what HDR is.

Can't vgmstream just read where multiple file headers are in the file? I managed to split them by using Notepad++ and saving all data between mentions of "SCHl" and that worked well enough to get un-corrupted data out, but doing that for over 15,000 files is a problem.

**Comment by NicknineTheEagle** [comment]
> Just tried another tool specifically for extracting .DAT files from Madden 08 (DAT File Replacer 5.0), Didn't work, and it can't open the said files I posted as DAT files to extract them further. Not familiar with what HDR is.

HDR is the actual header format that is supposed to be coupled with DAT.

> Can't vgmstream just read where multiple file headers are in the file? I managed to split them by using Notepad++ and saving all data between mentions of "SCHl" and that worked well enough to get un-corrupted data out, but doing that for over 15,000 files is a problem.

No. vgmstream is an audio decoder not a data extractor.

**Comment by NicknineTheEagle** [comment]
If finding matching HDR files is impossible you can try using this BMS script to split those DAT files: https://pastebin.com/0MW9M7cD

**Comment by ApexJohn** [comment]
> If finding matching HDR files is impossible you can try using this BMS script to split those DAT files: https://pastebin.com/0MW9M7cD

That worked! Thanks.
