### ISSUE TITLE
[Request] Love Live! School idol festival ~after school ACTIVITY~ (Arcade)

### ISSUE THREAD

**Issue by Mysticus92** [vgmstream/vgmstream#875]
A certain user somewhere in Discord gave me .acb files since this game have .awb files only.
But they don't show subsongs from .awb files even if the .acb is equipped. Could you please add support of them?
https://drive.google.com/file/d/1DtwkvC38JwOuZBAwp4D8wwwRme9_kO-z

**Comment by bnnm** [comment]
acb look incorrectly extracted, must be re-ripped
They have empty data at the beginning end missing data at the end.
