### ISSUE TITLE
Request Modding Gal Gun 2 (Switch) Audio

### ISSUE THREAD

**Issue by Pokemon1995** [vgmstream/vgmstream#878]
This is more a question than an issue. But it is possible to convert .wav sound files to the same audio format which Gal Gun 2 (Switch) used? 

https://github.com/vgmstream/vgmstream/pull/220/commits/d2925316548cc95fa86873f7b88db2c5487cf31b

I´m not am programmer but i really want to mod the music in Gal Gun 2 (Switch) but i can not recreate the sound files.

**Comment by kode54** [comment]
This library is for playing game resources, not modding or replacing them. Maybe investigate VGAudio instead.
