### ISSUE TITLE
[Request] Sengoku Basara 4 (PS3\PS4) - sspr and cfsm

### ISSUE THREAD

**Issue by MikoMMM** [vgmstream/vgmstream#883]
sspr is used for story voices and music, seems to be bundled in audio archives sometimes
cfsm is used for sound effects and character battle grunts and voices, seems to be singular audio clips

Samples link for sspr: https://mega.nz/file/4GAl1SDA#7MNzmig8ezudY2bXHt4tCVCDBGqSwYo8v-QKiIwaZ9w
Samples link for cfsm: https://mega.nz/file/hDBh0aqJ#Agmj3w3xVpxCy9BmoXFmMlGRcYi1R8OUfDauU002Vnc

**Comment by MikoMMM** [comment]
Oh, looks like cfsm files can be played by simply renaming their extension to .wav

**Comment by MikoMMM** [comment]
And looks like the mysterious sspr files can be played with PotPlayer https://potplayer.daum.net/ **but only some of them** (the ones from the gallery folder can't be played at all) **and they can't be saved or converted with PotPlayer either**

**Comment by bnnm** [comment]
.sspr play directly now: https://vgmstream.org/downloads

Or you could extract the internal files first: https://raw.githubusercontent.com/bnnm/vgm-tools/master/bms/capcom_sspr_extractor.bms

cfsm proper extension is .msf
