### ISSUE TITLE
[Request] Dragon Quest Tact (Android/iOS) .awb / .acb support 

### ISSUE THREAD

**Issue by fulanodetalo** [vgmstream/vgmstream#884]
Hello, I know this is a long shot since the game isn't popular but hope you guys can add support for acb and awb files of the game Dragon Quest Tact.

Asking around people tell me to write a request here since the file are using cipher key and without it is an unplayable mess of sound.

I uploaded the files unpacked
[Google Drive - acb/awb File](https://drive.google.com/file/d/1F6hO9M0fq98t68vR0Zt73NcyF1j977B-/view?usp=sharing)

Thanks to who can help

**Comment by NicknineTheEagle** [comment]
AWB is not a sound bank format so it won't be added. It's a general container format used by CRI middleware and it holds ADX or HCA files. You can extract them using this script: https://aluigi.altervista.org/bms/awb_afs2.bms
ADX and HCA are indeed often encrypted, if that's the case, decryption key would need to be found. Post the game executable.

**Comment by bnnm** [comment]
There is .awb support, it's just missing the key. 3234477171400153310, will add later

**Comment by fulanodetalo** [comment]
> 
> 
> AWB is not a sound bank format so it won't be added. It's a general container format used by CRI middleware and it holds ADX or HCA sound files. You can extract them using this script: https://aluigi.altervista.org/bms/awb_afs2.bms
> ADX and HCA are indeed often encrypted, if that's the case, decryption key would need to be found and added to the code. Post the game executable.

this is a mobile game, with executable you mean the whole .apk file?

**Comment by fulanodetalo** [comment]
> 
> 
> There is .awb support, it's just missing the key. 3234477171400153310, will add later

hey thanks you for the help, i'm noob with this but is that the cipher key?

**Comment by bnnm** [comment]
Works now: https://vgmstream.org/downloads

**Comment by fulanodetalo** [comment]
> 
> 
> Works now: https://vgmstream.org/downloads

thanks a lot!!!!
