### ISSUE TITLE
SimCity 3000 Unlimited not supported

### ISSUE THREAD

**Issue by efdeveloper** [vgmstream/vgmstream#885]
[3KSE1.XA.zip](https://github.com/vgmstream/vgmstream/files/6779189/3KSE1.XA.zip)

This track for example from this game is not being recognized by the plugin. 

Could you please verify why?

**Comment by NicknineTheEagle** [comment]
Update your vgmstream.

**Comment by efdeveloper** [comment]
I updated to the latest version as you told me to do and it worked. Thanks.
