### ISSUE TITLE
[Request] Output loop points to file

### ISSUE THREAD

**Issue by IngwiePhoenix** [vgmstream/vgmstream#890]
Hello there!

I want to build a custom sound pack for Persona 4 Golden on PC for me and my friends to fool around with. It'd be great if I could re-use some existing loops. But, not being the greatest Audacity user, I am not really good in precisely picking loop start and end points. However, some of the games that I am looking at to pick songs from might actually have those very points predefined in their BGM container (i.e. Drakengard for PS2).

Is there a way to extract songs from a container and also obtain their respective loop points so that I can write them to a file? If this feature does not exist yet, I would like to request that. But from looking at the CLI, I found nothing of the like.

Thank you in advance!

Kind regards,
Ingwie

**Comment by bnnm** [comment]
There is the `-x` that prints a command for adxenc.exe with loop points, that should be easy to write to txt and modify for your needs (using "replace" in text editors).

Assuming Windows, example for all files in a dir (in some `vgmstream.bat`): 
`for %%x in (*.*) do test.exe -x "%%x" >> commands.txt`.

Other probably-useful functions are `-b` (text in different format) and `-L` (creates a .wav with standard loop points, don't think Audacious supports them but maybe other tools do).
