### ISSUE TITLE
[Bug] vgmstream123 - crash/segfault when playing TXTP with top-level "layer" group directly (Linux)

### ISSUE THREAD

**Issue by apocalyptech** [vgmstream/vgmstream#901]
Hello!  I've got a TXTP file which looks like this:

     ../../373941567.wem #i #b 28.8 #r 3.2
     ../../457494411.wem #i #b 28.8 #r 3.2
     ../../491627536.wem #i #b 28.8 #r 3.2 #v -2.0dB ##fade
    group = -L3 #v 1.0dB #@layer-v

That plays just fine using the Audacious vgmstream plugin, and can dump to wav using `vgmstream_cli` without problems, but it crashes `vgmstream123` when attempting to play it.  I get the crash even when outputting to a wav file (with `-d wav -f out.wav`).  The full output when run as-is:

    Playing stream: 2.txtp
    Audio device: WAV file output
    Comment: Sends output to a .wav file
    
    Segmentation fault (core dumped)

When looking at a backtrace on a debug build, I get:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff62ada08 in fwrite () from /usr/lib/libc.so.6
    (gdb) bt
    #0  0x00007ffff62ada08 in fwrite () at /usr/lib/libc.so.6
    #1  0x00007ffff7f6c7bb in  () at /usr/lib/libao.so.4
    #2  0x000055555556c79d in play_vgmstream (filename=0x7fffffffe5a9 "2.txtp", cfg=0x7fffffffe090) at /home/pez/git/b2patching/vgmstream/cli/vgmstream123.c:417
    #3  0x000055555556d340 in play_file (filename=0x7fffffffe5a9 "2.txtp", par=0x7fffffffe090) at /home/pez/git/b2patching/vgmstream/cli/vgmstream123.c:633
    #4  0x000055555556d5ac in main (argc=6, argv=0x7fffffffe208) at /home/pez/git/b2patching/vgmstream/cli/vgmstream123.c:685

If I alter the TXTP so that the "top-level" group isn't a layer based, though, vgmstream123 plays it just fine.  For instance, this file will play perfectly;

      ../../373941567.wem #i #b 28.8 #r 3.2
      ../../457494411.wem #i #b 28.8 #r 3.2
      ../../491627536.wem #i #b 28.8 #r 3.2 #v -2.0dB ##fade
     group = -L3 #v 1.0dB #@layer-v
    group = -S1

Links to the `.wem` files in question:
https://apocalyptech.com/scratchpad/vgmstream/373941567.wem
https://apocalyptech.com/scratchpad/vgmstream/457494411.wem
https://apocalyptech.com/scratchpad/vgmstream/491627536.wem

Not a huge deal, really, since both Audacious and vgmstream_cli seem to work fine, but perhaps something to look into?  Let me know if I can provide any extra detail here.  Thanks!

**Comment by kode54** [comment]
Looks like the libao driver is crashing. Maybe a channel configuration it doesn't handle properly? Hmm...

**Comment by bnnm** [comment]
Should be fixed in last PR

**Comment by apocalyptech** [comment]
> Should be fixed in last PR

Aha, indeed!  Working great now.  Thanks a bunch!
