### ISSUE TITLE
[Request] Alchemy Stars acb/awb Audio File Support

### ISSUE THREAD

**Issue by lloyddunamis** [vgmstream/vgmstream#903]
Tools used for extraction attempt:
- VGMStream plugin for foobar2000 (r1050-3827)
- VGMToolbox (r1040)

Able to extract the music & read the names for them, but produce **squeaky audio files**.
Probably needs the correct hca key. _I know, it's a copypasta at this point, but hope it helps in the investigation anyway._

For reference when looking up the in-game files:
- Requires 64-bit device
- obb files are disk image files instead of the common zip files. May need something like [ImDisk](https://sourceforge.net/projects/imdisk-toolkit/) to be able to mount it as like a disk drive.
- No folder structure; just all the files in one directory (or two in the Main obb). From a bit of inspection, BGM files may be the ones that have `@m#_` in .acb/.awb filenames.

Game: [US](https://play.google.com/store/apps/details?id=com.proximabeta.baiyeus) | [Global](https://play.google.com/store/apps/details?id=com.tencent.baiyeint) (around 1.9GB download) _(the two regions reportedly have no difference. In this case, I have upped sample files from Global)_
Sample: [AlchemyStars acbawb.rar](https://mega.nz/file/vJ1i1aJL#UzPoEXG5bSLGA1FB72270lfAfTyCpEZnKdEPoJAH1sA) (rar5 pass: `ViceWeiss`)

Thanks in advance!

**Comment by bnnm** [comment]
Should work now.

**Comment by lloyddunamis** [comment]
Confirmed working. Thank you!
_Concerned linked files have been removed._

_(following are etc. and just reference stuffs)_
For anyone else maybe looking into AS's files, the BGM files are apparently ones with junei, juwai, and juqing; which by CN translation means inside, outside, and plot (story), respectively. Yes, they are categorized, even in the in-game music player.
Quite unfortunate that the BGMs are mono though...
