### ISSUE TITLE
[Bug] Cannot build anymore if VGM_USE_MPEG is not defined but VGM_USE_FFMPEG is

### ISSUE THREAD

**Issue by PieroV** [vgmstream/vgmstream#913]
Hi, from commit 039541f88158a691f0fdc471fe6d6ecdd2ba0481, in msf.c the number of samples for MPEG with FFMPEG is computed with the function mpeg_get_samples_clean.
This function is implemented in mpeg_custom_utils.c under VGM_USE_MPEG, but defined outside this ifdef in conding.h.
For this reason, I encounter a linking problem...

**Comment by bnnm** [comment]
Should work now.

**Comment by PieroV** [comment]
Thanks, but it does not compile, yet.
`mpeg_frame_info` and `mpeg_get_frame_info` (on `mpeg_decoder.h`) should be outside `#ifdef VGM_USE_MPEG` as well.
In this way it compiles correctly

**Comment by bnnm** [comment]
last minute oops, try now

**Comment by PieroV** [comment]
Now it works, thanks! :+1:
