### ISSUE TITLE
[Request] Spider-Man (Xbox) - .XSH+.XSD

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#920]
ummm, hey.

so, i took a quick list at this bug list [right here](https://github.com/bnnm/vgmstream/wiki/Bug-list) and noticed that out of all the things that were listed there, the sound bank format used in that spider-man game from 2002 was the one that caught the most attention from me. so i thought i could help.

anyhow, how i'm going to explain this... okay, the Xbox version of the game uses a sound bank format designed specifically for that version. said format requires at least two files with the same name but with different extensions. the "XSH" file is the header file for the "XSD" file which is the entire sound data itself.

i did find out though that the "XSH" file may need "xss" files which are the usual RIFF WAVE files with XBOX ADPCM audio data in it as most Xbox games. and... well, that's it from me.

with that being said, here are some files from the game itself.
[[spiderman_2002][xbox][english]xsh+xsd.7z](https://www.sendspace.com/file/6rt8jw)
i did not include the xss files in this 7z pack as i wasn't sure that would be a good idea given that vgmstream already supports these files.

**Comment by NicknineTheEagle** [comment]
I actually wrote a BMS script to extract this a long time ago1. XSH files contain RIFF fmt chunks for sounds in XSD files. I'm not sure this format can be added to vgmstream, it's hard to identify.

**Comment by modusc896d352** [comment]
oh, right. can you give me some pointers as to where i can find the script?

speaking of "identifying the format" i spotted the format in the Xbox version of **Kelly Slater's Pro Surfer**, where it seems said format has been updated with a... new number at the start of the file (0x100 instead of 0x9d) and a similar structure for the rest of the file. well, aside from a new change where you see a big STREAMS.XSS file without so much as a single RIFF WAVE header in it. in fact, it's all raw XBOX ADPCM data.

should you want me to upload these XSH+XSD files from that game, let me know.

**Comment by bnnm** [comment]
Yeah please upload those too.

**Comment by modusc896d352** [comment]
OK.

**Comment by NicknineTheEagle** [comment]
```
# Spider-Man (Xbox) - .xsd

include func_header_GENH.bms

set ADD_GENH long 1

open FDDE "XSD"
open FDDE "XSH" 1

goto 0x8 1
get FILES long 1
for i = 0 < FILES
    getdstring NAME 0x20 1
	get TYPE long 1
	get OFFSET long 1
	get SIZE long 1
	goto 0x20 1 SEEK_CUR # bunch of zeroes followed by some junk, probably hash?
	
	# Mini RIFF-like header
	get FORMAT short 1 # 0x69 for XBOX IMA ADPCM
	get CH short 1
	get FREQ long 1
	get AVGBYTES long 1
	get BLOCKALIGN short 1
	get BITS short 1
	get EXTRA_DAT_SIZE short 1 
	goto EXTRA_DAT_SIZE 1 SEEK_CUR
	
	if SIZE == 0 # some of these are XSS file references, ignore those
		continue
	endif
	
	if ADD_GENH == 1
		set CODEC long 0x01
		set LOOP_START long -1
		callfunction BYTESTOSAMPLES 1
		callfunction TOGENH 1
	else
		string NAME + ".vgmstream"
		log NAME OFFSET SIZE
	endif
next i
```
Here, ignore that GENH thing, it's an old script, just use it as a reference for the structure. You should be able to use TXTH to load it in vgmstream, it's not terribly complex.

**Comment by modusc896d352** [comment]
alright. thanks for the script.

**Comment by bnnm** [comment]
Should work now, needs xsh/xsd/xss together.

**Comment by modusc896d352** [comment]
OK, i'm on my way of testing this new update.

**Comment by modusc896d352** [comment]
OK.
tested all the xsh files i have with the new update and it works without issue with those files.
time to close the issue i guess.
