### ISSUE TITLE
[Request] m HOLD'EM (エムホールデム)

### ISSUE THREAD

**Issue by kokoropaint** [vgmstream/vgmstream#923]
vgmstream recognizes the files and the filenames within the acb, but doesn't play them properly. probably just missing a key of some kind (HCA?)? I'm not super familiar with these things but it'd be nice if support could get added.
[Game link](https://mpj-portal.jp/game/)
[Example files (MEGA)](https://mega.nz/folder/LIw31IwL#7DbWIY-MoVNFTYg_PvDH5A)
I ripped the above files with AssetStudio so there's a possibility something got messed up along the way but I'm pretty sure they're fine.

**Comment by bnnm** [comment]
Added key.
