### ISSUE TITLE
[Bug] MP3 playback glitches with some files from the PS3 ports of Just Dance 3, 4 and Michael Jackson: The Experience

### ISSUE THREAD

**Issue by mbc07** [vgmstream/vgmstream#924]
Just Dance 4 on PS3 uses MP3 codec (stored inside Ubiosft LyN RIFF container) and vgmstream decodes nearly all tracks normally, but the menu tracks glitches out during playback: it plays in mono instead of stereo and the sound keep skipping every two or three seconds.

The glitch is more pronounced when using the input plugin (tested with `in_vgmstream` on Winamp and XMPlayer), if you use `vgmstream-cli` to decode the problematic tracks, it'll throw some warnings but produce a nearly flawless file, in stereo as it should be, however the left and right channels get desynced nearly the track end.

The other ports of the game, which uses the same Ubisoft LyN RIFF container but with different codecs (Nintendo ADPCM on Wii/Wii U and Microsoft XMA2 on Xbox 360), plays normally, the issue is exclusive to the PS3 port of Just Dance 4 and happens only with the menu tracks.

-----

vgmstream-cli output:
```
decoding JD4Score.lwav
sample rate: 44100 Hz
channels: 2
looping: disabled
loop start: 0 samples (0:00.000 seconds)
loop end: 1954945 samples (0:44.330 seconds)
stream total samples: 1954945 (0:44.330 seconds)
encoding: MPEG Layer III Audio (MP3)
layout: flat
metadata from: Ubisoft LyN RIFF header
bitrate: 192 kbps
play duration: 1954945 samples (0:44.330 seconds)
Note: Illegal Audio-MPEG-Header 0x996020dc at offset 491520.
Note: Trying to resync...
Note: Skipped 147 bytes in input.
Note: Illegal Audio-MPEG-Header 0xa601ad17 at offset 524435.
Note: Trying to resync...
Note: Skipped 147 bytes in input.
Note: Illegal Audio-MPEG-Header 0xf0cf715b at offset 524582.
Note: Trying to resync...
Note: Skipped 17 bytes in input.

Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
Note: Illegal Audio-MPEG-Header 0x67cff0c9 at offset 525752.
Note: Trying to resync...
Note: Skipped 250 bytes in input.
```
[Decoded output sample](https://github.com/vgmstream/vgmstream/files/7024836/Output.Sample.zip)
[Original files with the glitch](https://github.com/vgmstream/vgmstream/files/7024840/Original.Files.zip)

**Comment by mbc07** [comment]
So, this also happens with all menu-related tracks from the PS3 version of Just Dance 3. Same Ubisoft LyN RIFF container with MP3 codec as on Just Dance 4...

[JD3 Glitched Files (set 1)](https://github.com/vgmstream/vgmstream/files/7025007/JD3.Glitched.Files.set.1.zip)
[JD3 Glitched Files (set 2)](https://github.com/vgmstream/vgmstream/files/7025008/JD3.Glitched.Files.set.2.zip)

**Comment by mbc07** [comment]
Checked the PS3 version of Michael Jackson: The Experience and it's affected too (same container and codec as the others, same glitches, only on menu and UI-related tracks). This confirms the glitch happens with all LyN-based Just Dance games for the PS3.

[MJ:E Glitched Files](https://github.com/vgmstream/vgmstream/files/7025042/MJE.Glitched.Files.zip)

**Comment by bnnm** [comment]
Should work now. If XMP/Winamp isn't playing it ok may be other plugin hijacking it, check the info dialog box and also [see this](https://github.com/vgmstream/vgmstream#xmp-vgmstream-xmplay-plugin).

**Comment by mbc07** [comment]
Tested the last vgmstream build and the MP3 tracks of all affected games work properly now. Thanks
