### ISSUE TITLE
[Bug] broken sounds in some subsongs of PSP Ubisoft games

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#935]
so, i managed to play some sounds from a PSP came called **Chessmaster: The Art of Learning**, which is apparently a version of that one **Chessmaster: Grandmaster Edition** game from 2007.

some short sounds play fine, but longer sounds have this unwieldy "pop"-ish sound that's honestly rather calming to listen to. kinda like rain except not sounding like such. then i looked at an hex editor and... well, now i know why.

here are the sound files from that PSP game.
[[psp][chessmaster_the_art_of_learning]sp5+sm5+ss5.7z](https://1drv.ms/u/s!Asofkpy7aqyKxHqEhixKX2VPGxAp?e=U5KjqS)

**Comment by modusc896d352** [comment]
OK, i don't want to sound spammy here. i really don't. but some things just don't sound right.

the sound files from the PSP version of **Michael Jackson: The Experience** have the same issue i tried to describe earlier when passed through foobar2000 with the vgmstream component installed - broken subsongs that sound like reality-bending rain if it was made digital.

a new link will be made available later.

**Comment by NicknineTheEagle** [comment]
Sounds like bad offsets. I'll look into it.

**Comment by NicknineTheEagle** [comment]
Oh, it looks it's AT3 that gets misidentified as PSX ADPCM.

**Comment by modusc896d352** [comment]
glad you looked into it. i was about to post another 7z file here.

**Comment by modusc896d352** [comment]
same issue here with the petz game about dogs from PSP
[[petz_dogz_family][psp]sp5+sb5+ss5.7z](https://1drv.ms/u/s!Asofkpy7aqyKxHxwzNtqQz_vS0QU?e=7D0iTj)
apparently that game was sold under two different names: in the USA the name of the game is **Petz: Dogz Family** while in Europe it's **Petz: My Puppy Family**.

**Comment by NicknineTheEagle** [comment]
Check the build in PR.

**Comment by modusc896d352** [comment]
checked it. everything's fine now.
