### ISSUE TITLE
[Bug] Sonic Colors: Ultimate ADX keycode missing

### ISSUE THREAD

**Issue by ActualMandM** [vgmstream/vgmstream#945]
Several ACB files in Sonic Colors: Ultimate fail to open, giving the error of `ADX: decryption keycode not found` in test.

[SCU-ACB.zip](https://github.com/vgmstream/vgmstream/files/7158843/SCU-ACB.zip)

**Comment by ActualMandM** [comment]
Fixed with #946

**Comment by bnnm** [comment]
[Errors](https://github.com/vgmstream/vgmstream/blob/master/doc/USAGE.md#logged-errors-and-unplayable-supported-files) are shown in foobar too btw
