### ISSUE TITLE
[Bug]  *.ACM sound effects from Fallout (1997) play at double speed

### ISSUE THREAD

**Issue by Sduibek** [vgmstream/vgmstream#949]
This affects all sfx audio files from the first Fallout game (1997) which are in ACM. What's odd is the music in .ACM from this game sounds fine.

I think your code might be treating all ACM files as stereo, thus playing mono files back at double speed.

Issue can be reproduced with any of these: https://www.dropbox.com/sh/fpw5q59uf76x9h9/AABK6-rhO9OGcM3qMm2zljSqa?dl=0

I'm using vgmstream plugin r1640-49-g0dd8bdd7 (Sep 15 2021) and Foobar 1.6.7

**Comment by bnnm** [comment]
There is no way (AFAIK) to detect stereo or mono ACM in Fallout 1, so they play as stereo by default. You can force them to mono by renaming then to .wavc though.

Also see https://github.com/vgmstream/vgmstream/issues/22#issuecomment-419918566

**Comment by Sduibek** [comment]
Thanks very much!
