### ISSUE TITLE
[Request] More 5 codec identifiers for Ogg Vorbis ACM codec in RIFF WAVE format

### ISSUE THREAD

**Issue by grj1234** [vgmstream/vgmstream#951]
According to source code `/src/meta/riff.c`, vgmstream can recognize codec identifier 0x6771 (Ogg Vorbis mode 3+).
On the other hand, Ogg Vorbis ACM codec not only uses 0x6771 but more 5 identifiers: 0x674f (mode 1), 0x676f (mode 1+), 0x6750 (mode 2), 0x6770 (mode 2+), and 0x6751 (mode 3).
I think that mode 1/2/3 is normal vorbis codec.
According to [this blog](https://ameblo.jp/true-shootingstar/entry-11009237346.html), "+" in mode number seems that mean pseudo-CBR mode.

Sample files are in:
- `Only One 2 - Meshimase Megumi no Sweet Apron (2005-01-28)(Globe)[PC][rr].7z` (Codec identifier 0x676f, already uploaded to joshw but not published yet)
- [this archive](https://www86.zippyshare.com/v/saFXwIGa/file.html) (Sample files created with vorbis.acm 0.0.3.6 and AviUtl 1.00)

**Comment by bnnm** [comment]
Fixed Only One 2 / Kirara Kirara NTR 

vorbis.acm samples weren't added since we generally only support files from actual games, and those samples are kind of buggy/not simple to add.

**Comment by grj1234** [comment]
Tested the latest build and it works properly now. Thank you!
