### ISSUE TITLE
[Request] Gameboy Advance's .MINIGSF

### ISSUE THREAD

**Issue by FelipeLema** [vgmstream/vgmstream#960]
Reference: [foobar2000 plugin for playing .MINIGSF](https://www.foobar2000.org/components/view/foo_input_gsf)

This plugin itself uses [libmgba](https://mgba.io/) (a gba emulator itself)

**Comment by FelipeLema** [comment]
I'm willing to work on this (if accepted as a valid request)

Can libmgba be included as a third party dependence?

**Comment by bnnm** [comment]
vgmstream only plays, well, streams, and isn't really suited to handle sequenced formats like minigsf.

That effort would make more sense in projects that already handle sequenced audio.
