### ISSUE TITLE
[Request] sound files from the Xbox version of XIII

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#963]
uhh, i found an HXAudio game that doesn't work with vgmstream.
apparently, vgmstream code does support hxx files (src/meta/ubi_hx.c) yet when i punch even a single hsx file into foobar2000 with the vgmstream component installed (already at **r1640-77-ga79768c9**) it does nothing useful with it.

here are the sound files.
[[xiii][xbox]hsx+hxx.7z](https://1drv.ms/u/s!Asofkpy7aqyKxH34lY1ewJZeAKsB?e=VKoaxk)
apologies for the highly-compressed 7z package.

**Comment by bnnm** [comment]
Should work now.

**Comment by modusc896d352** [comment]
alright. closing this now.
