### ISSUE TITLE
[Bug] some wem/bnk files don't play (Tales of Arise Demo [Windows])

### ISSUE THREAD

**Issue by modusc896d352** [vgmstream/vgmstream#964]
so, i came across a recent UE4 game (Tales of Arise) using Wwise.
thing is, some wem files are literally unplayable. and at least one bnk file cannot be played at all.

here are the files.
[[tales_of_arise_demo][windows]unplayable_bnk.7z](https://www.sendspace.com/file/prf4pz)
[[tales_of_arise_demo][windows]unplayable_wem.7z](https://www.sendspace.com/file/5cz1zr)

**Comment by bnnm** [comment]
Should work now.

**Comment by modusc896d352** [comment]
alright. closing this now.
