### ISSUE TITLE
[Request] Cyberworks encrypted OGG audio (.J0 / .K0 / .U0 extension)

### ISSUE THREAD

**Issue by grj1234** [vgmstream/vgmstream#978]
I extracted some music from the game developed by TinkerBell (one of the game brand of Cyberworks), but vgmstream doesn't support yet.

Sample files are in:
- Yumekoi Tensei (2008-10-10)(TinkerBell Nanigashigumi)(TinkerBell)[PC][unplayable].7z
- Zettai Maji Love! Amaicha Happening! - Shimai x Shimai de Doki Ero Seikatsu! Kyun Melopower o Shuushuu Seyo! (2013-07-26)(TinkerBell)[PC][unplayable].7z

(Already uploaded to joshw but not published yet)

This link might be useful: [Decoder implementation from GARbro (developed by morkt, released under the MIT license)](https://github.com/morkt/GARbro/blob/master/ArcFormats/Cyberworks/AudioTINK.cs)

**Comment by bnnm** [comment]
Added u0

**Comment by grj1234** [comment]
Thanks!
