### ISSUE TITLE
Namco encrypted HCA Audio

### ISSUE THREAD

**Issue by User9013** [vgmstream/vgmstream#999]
I would like to extract the BGM from "Super Robot Wars 30" that I purchased on STEAM, but the HCA file seems to be encrypted and I am having a hard time decoding it correctly.
Please tell me how to get the key to decrypt the HCA.

These are the HCA files that are encrypted and the files that seem to be related to them.
https://mega.nz/file/vaRkiLqa#BJ_f3tTRU3vxnf5AeUP6PIchbGgegkMaRcCpKxy7cBI

Thank you.

**Comment by bnnm** [comment]
Added
